### ISSUE TITLE
Mainline mode exception

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#1021]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitVersion.VersionCalculation.NextVersionCalculator.<>c__DisplayClass7_0.<GetMainlineTip>b__4(Branch b)
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at GitVersion.VersionCalculation.NextVersionCalculator.GetMainlineTip(GitVersionContext context)
   at GitVersion.VersionCalculation.NextVersionCalculator.FindMainlineModeVersion(BaseVersion baseVersion, GitVersionContext context)
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion(GitVersionContext context)
   at GitVersion.GitVersionFinder.FindVersion(GitVersionContext context)
   at GitVersion.ExecuteCore.<>c__DisplayClass6_0.<ExecuteInternal>b__0(IRepository repo)
   at GitVersion.GitPreparer.WithRepository[TResult](Func`2 action)
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig)
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
```

**Comment by JakeGinnivan** [comment]
Fixed by #1027
