### ISSUE TITLE
Installation into projects using nCrunch

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitVersion#11]
Add `AND $(nCrunch) ==''` to the condition of importing the targets file

**Comment by mkoertgen** [comment]
Currently, GitVersion fails to find the `.git` directory during standard NCrunch builds:

    WARNING - WARN [03/19/16 9:36:36:33] Could not determine assembly version:
    System.NullReferenceException: Object reference not set to an instance of an object.
       at GitVersion.GitPreparer.GetDotGitDirectory()
       at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId)
       at GitVersion.ExecuteCore.TryGetVersion(String directory, VersionVariables& versionVariables, Boolean noFetch, Authentication authentication)

This is plausible because by default, NCrunch shadow copies the projects (without `.git` of course). 

Certainly not a show stopper as you can just disable GitVersion `UpdateAssemblyInfo` and `GetVersion` when `$(NCrunch) == 1`
