### ISSUE TITLE
Gitversion on Appveyor cannot find git directory

### ISSUE THREAD

**Issue by promontis** [GitTools/GitVersion#1140]
Hi guys,

I generated an appveyor.yml file using gitversion init, however I get the following error in AppVeyor:

```
System.IO.DirectoryNotFoundException: Can't find the .git directory in C:\projects\eneco-beheer
   at GitVersion.GitPreparer.GetDotGitDirectory()
   at GitVersion.GitPreparer.GetProjectRootDirectory()
   at GitVersion.ConfigurationProvider.Verify(GitPreparer gitPreparer, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
```

It seems the current directory is not a valid git directory. I'm not really sure why this is the case. This is the full log. It is fetching repository commits, whereas the repository is a git repository. So I would expect the folder to be a git repository.

```
Build started
Fetching repository commit (4c882fb)...OK
Total: 55.6 MB in 959 files
Restoring build cache
Cache 'src/packages' - Restored
Running Install scripts
choco install gitversion.portable -pre -y
Chocolatey v0.10.3
Installing the following packages:
gitversion.portable
By installing you accept licenses for the packages.
GitVersion.Portable v4.0.0-beta0009 [Approved]
gitversion.portable package files install completed. Performing other installation steps.
Added C:\ProgramData\chocolatey\bin\gfv.exe shim pointed to '..\lib\gitversion.portable\tools\gitversion.exe'.
 ShimGen has successfully created a shim for GitVersion.exe
 The install of gitversion.portable was successful.
  Software install location not explicitly set, could be in package or 
  default install location if installer.
Chocolatey installed 1/1 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
nuget sources add -Name tamtamprivate -Source https://www.myget.org/F/tamtamprivate/auth/ffa378d1-1a73-4f55-b40f-10808938f7fc/
Package Source with Name: tamtamprivate added successfully.
gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH
INFO [01/18/17 14:27:30:86] Working directory: C:\projects\eneco-beheer
INFO [01/18/17 14:27:30:88] IsDynamicGitRepository: False
ERROR [01/18/17 14:27:30:93] An unexpected error occurred:
System.IO.DirectoryNotFoundException: Can't find the .git directory in C:\projects\eneco-beheer
   at GitVersion.GitPreparer.GetDotGitDirectory()
   at GitVersion.GitPreparer.GetProjectRootDirectory()
   at GitVersion.ConfigurationProvider.Verify(GitPreparer gitPreparer, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
INFO [01/18/17 14:27:30:93] 
INFO [01/18/17 14:27:30:93] Attempting to show the current git graph (please include in issue): 
INFO [01/18/17 14:27:30:93] Showing max of 100 commits
INFO [01/18/17 14:27:31:08] ERROR: fatal: Not a git repository (or any of the parent directories): .git
INFO [01/18/17 14:27:30:86] Working directory: C:\projects\eneco-beheer
INFO [01/18/17 14:27:30:88] IsDynamicGitRepository: False
ERROR [01/18/17 14:27:30:93] An unexpected error occurred:
System.IO.DirectoryNotFoundException: Can't find the .git directory in C:\projects\eneco-beheer
   at GitVersion.GitPreparer.GetDotGitDirectory()
   at GitVersion.GitPreparer.GetProjectRootDirectory()
   at GitVersion.ConfigurationProvider.Verify(GitPreparer gitPreparer, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
INFO [01/18/17 14:27:30:93] 
INFO [01/18/17 14:27:30:93] Attempting to show the current git graph (please include in issue): 
INFO [01/18/17 14:27:30:93] Showing max of 100 commits
INFO [01/18/17 14:27:31:08] ERROR: fatal: Not a git repository (or any of the parent directories): .git
Command exited with code 1
```

**Comment by JakeGinnivan** [comment]
Honestly no idea what is going on here. Can you open an issue with AppVeyor support? There should be a git repo.. We have similar setup for our CI with no issues =/

If you find out any more info and we can help post and we can reopen this issue

**Comment by johncrim** [comment]
I'm having the same issue. @promontis , Did you ever determine the cause?

@JakeGinnivan Are there existing public AppVeyor builds that use GitVersion that someone can look at for reference?

**Comment by promontis** [comment]
Yeah there was this checkbox that you shouldn't copy from sources or something. Can't really remember, but that fixed it!

**Comment by johncrim** [comment]
OK - thank you.

FYI, I was able to resolve this by moving my gitversion invocation from the `init:` block to the `before_build:` block.

This didn't work (gave me the error documented in this issue):

```
install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

init:
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - ps: Update-AppveyorBuild -Version "$env:GitVersion_NuGetVersion"

before_build:
  - ps: nuget restore

```

This worked:

```
install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

init:

before_build:
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - ps: Update-AppveyorBuild -Version "$env:GitVersion_NuGetVersion"
  - ps: nuget restore

```
