### ISSUE TITLE
nofetch not respected for PR builds

### ISSUE THREAD

**Issue by Trass3r** [GitTools/GitVersion#1199]
```
One remote found (origin -> ...
Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
HEAD is detached and points at commit '1df...'.
Local Refs: refs/pull/1/merge (1df...)
No local branch pointing at the commit '1df...'. Fake branch needs to be created.
Fetching remote refs to see if there is a pull request ref
End: Normalizing git directory for branch '' (Took: 629.06ms)
An unexpected error occurred:
LibGit2Sharp.LibGit2SharpException: this remote has never connected
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Core\Ensure.cs:line 154
   at LibGit2Sharp.Core.Proxy.git_remote_ls(Repository repository, RemoteHandle remote) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Core\Proxy.cs:line 2313
   at LibGit2Sharp.Network.ListReferencesInternal(String url, CredentialsHandler credentialsProvider) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Network.cs:line 130
   at GitTools.Git.GitRepositoryHelper.GetRemoteTipsForAnonymousUser(Repository repo, Remote remote)
   at GitTools.Git.GitRepositoryHelper.CreateFakeBranchPointingAtThePullRequestTip(Repository repo, AuthenticationInfo authentication)
   at GitTools.Git.GitRepositoryHelper.NormalizeGitDirectory(String gitDirectory, AuthenticationInfo authentication, Boolean noFetch, String currentBranch)
   at GitVersion.GitPreparer.Initialise(Boolean normaliseGitDirectory, String currentBranch)
   at GitVersion.ExecuteCore.ExecuteGitVersion
```

**Comment by asbjornu** [comment]
1. Which version of GitVersion are you using?
2. Are you using GitVersionTask, `gitversion.exe` or something else?
3. What build server is this?
4. How have you configured or passed `nofetch` to GitVersion?
5. Is your build server doing a sparse checkout? Can you try to do `git fetch --unshallow` as a step before executing GitVersion to ensure that the entire repository is available to GitVersion?

**Comment by Trass3r** [comment]
# `4.0.0-beta.11+1258.Branch.master.Sha.cc28b2dbff86`
# `Executing: packages/Tools/GitVersion.CommandLine/tools/GitVersion.exe" -updateassemblyinfo "src/GlobalAssemblyInfo.cs" -nofetch`
# TeamCity agent checkout. git.exe could only fetch with the access token. I'd like gitversion to work "offline" without another fetch, after all it seems to have a "name" for the build: `Local Refs: refs/pull/1/merge`.
# cmdline
# no

**Comment by asbjornu** [comment]
@Trass3r: Thanks for the information. Have you tried `it fetch --unshallow`?

**Comment by Trass3r** [comment]
Maybe it's related to TC's use mirrors setting: "When this option is enabled, TeamCity clones the repository under the agent's system\git directory and uses the mirror as an alternate repository when updating the checkout directory for the build. As a result, this speeds-up clean checkout (because only the working directory is cleaned), and saves disk space (as there is only one clone of the given git repository on an agent)."

But still, it does find the local ref but doesn't use it:
```
HEAD is detached and points at commit '8fb46da'.
Local Refs:
refs/pull/1/merge (8fb46da)
No local branch pointing at the commit '8fb46da'. Fake branch needs to be created.
Fetching remote refs to see if there is a pull request ref
```

**Comment by Trass3r** [comment]
Though there is a .git folder and `fatal: fetch --unshallow on a complete repository does not make sense`

**Comment by asbjornu** [comment]
Can you please take a look at https://github.com/GitTools/GitVersion/issues/912#issuecomment-314443855 and see if setting `teamcity.git.fetchAllHeads` to `true` fixes your problem? Please reopen the issue if the problem persists.

**Comment by xero-jackieweng** [comment]
I'm getting this exact problem, and `teamcity.git.fetchAllHeads` doesn't not actually help.

Setup:
- TC: 2020.2.2
- Repo: GitHub enterprise (brand new)
- GitVersion image: `gittools/gitversion:5.6.9-alpine.3.12-x64-5.0`

```
INFO [04/08/21 22:59:32:75] Begin: Normalizing git directory for branch ''
  INFO [04/08/21 22:59:32:78] One remote found (origin -> 'https://github.dev.xero.com/Xero/teamcity-dsl-test').
  INFO [04/08/21 22:59:32:78] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
  INFO [04/08/21 22:59:32:79] Skipping update of 'refs/remotes/origin/master' as it already matches the remote ref.
  INFO [04/08/21 22:59:32:80] HEAD is detached and points at commit '73813e3ce36b7e835b1897bf629913bc5159167d'.
  INFO [04/08/21 22:59:32:80] Local Refs:
refs/heads/master (52a0ddb55b89b47987be13569c9ec32fe792b6b8)
refs/pull/1/head (73813e3ce36b7e835b1897bf629913bc5159167d)
refs/remotes/origin/master (52a0ddb55b89b47987be13569c9ec32fe792b6b8)
  INFO [04/08/21 22:59:32:80] No local branch pointing at the commit '73813e3ce36b7e835b1897bf629913bc5159167d'. Fake branch needs to be created.
  INFO [04/08/21 22:59:32:80] Fetching remote refs to see if there is a pull request ref
  INFO [04/08/21 22:59:33:01] End: Normalizing git directory for branch '' (Took: 261.15ms)
  ERROR [04/08/21 22:59:33:03] An unexpected error occurred:
LibGit2Sharp.LibGit2SharpException: this remote has never connected
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_ls(Repository repository, RemoteHandle remote)
   at LibGit2Sharp.Network.ListReferencesInternal(String url, CredentialsHandler credentialsProvider)
   at LibGit2Sharp.Network.ListReferences(Remote remote)
   at GitVersion.GitRepository.<>c__DisplayClass30_0.<CreateBranchForPullRequestBranch>b__0() in D:\a\1\s\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 107
   at GitVersion.RepositoryExtensions.RunSafe(Action operation) in D:\a\1\s\src\GitVersion.LibGit2Sharp\RepositoryExtensions.cs:line 16
   at GitVersion.GitRepository.CreateBranchForPullRequestBranch(AuthenticationInfo auth) in D:\a\1\s\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 100
   at GitVersion.GitPreparer.<>c__DisplayClass17_0.<NormalizeGitDirectory>b__3() in D:\a\1\s\src\GitVersion.Core\Core\GitPreparer.cs:line 260
   at GitVersion.Helpers.RetryAction`1.<>c__DisplayClass1_0.<Execute>b__0() in D:\a\1\s\src\GitVersion.Core\Helpers\RetryAction.cs:line 20
   at Polly.Policy`1.<>c__DisplayClass11_0.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy`1.Implementation(Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy`1.Execute(Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy`1.Execute(Func`1 action)
   at GitVersion.Helpers.RetryAction`2.Execute(Func`1 operation) in D:\a\1\s\src\GitVersion.Core\Helpers\RetryAction.cs:line 42
   at GitVersion.Helpers.RetryAction`1.Execute(Action operation) in D:\a\1\s\src\GitVersion.Core\Helpers\RetryAction.cs:line 18
   at GitVersion.GitPreparer.NormalizeGitDirectory(Boolean noFetch, String currentBranchName, Boolean isDynamicRepository) in D:\a\1\s\src\GitVersion.Core\Core\GitPreparer.cs:line 260
   at GitVersion.GitPreparer.NormalizeGitDirectory(String targetBranch, Boolean isDynamicRepository) in D:\a\1\s\src\GitVersion.Core\Core\GitPreparer.cs:line 147
   at GitVersion.GitPreparer.PrepareInternal(Boolean normalizeGitDirectory, String currentBranch, Boolean shouldCleanUpRemotes) in D:\a\1\s\src\GitVersion.Core\Core\GitPreparer.cs:line 77
   at GitVersion.GitPreparer.Prepare() in D:\a\1\s\src\GitVersion.Core\Core\GitPreparer.cs:line 59
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\1\s\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 43
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\1\s\src\GitVersion.App\GitVersionExecutor.cs:line 61
  INFO [04/08/21 22:59:33:03] Attempting to show the current git graph (please include in issue): 
  INFO [04/08/21 22:59:33:03] Showing max of 100 commits
  INFO [04/08/21 22:59:33:04] * 73813e3 2 minutes ago  (HEAD, refs/pull/1/head)
* 5bf0e66 14 minutes ago 
* 52a0ddb 14 minutes ago  (origin/master, master)
* 83ae817 56 minutes ago 
* 56496d0 56 minutes ago 
* 01ea255 2 hours ago 
* aeadf63 2 hours ago 
* 8ecbef0 2 hours ago 
```

**Comment by xero-jackieweng** [comment]
Fixed by supplying username and password to GitVersion command, i.e.

```
/tools/dotnet-gitversion /output buildserver /nofetch /u %github.user% /p %github.token%
```
