### ISSUE TITLE
nullref in GitRepoMetadataProvider.FindMergeBase

### ISSUE THREAD

**Issue by SimonCropp** [GitTools/GitVersion#1230]
this is with current the current master as at https://github.com/GitTools/GitVersion/commit/30f413aacda93cd0abb4b342cb421641bb8377eb

Still trying to grok why. but here is the debug state to start with. seems `Repository.ObjectDatabase.FindMergeBase` returned null

![image](https://user-images.githubusercontent.com/122666/26905015-3466def6-4c28-11e7-93f7-3ec8a6c77655.png)

and here is the trace

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		WARN [06/08/17 8:03:16:07] Could not determine assembly version: System.NullReferenceException: Object reference not set to an instance of an object.
   at GitVersion.GitRepoMetadataProvider.FindMergeBase(Branch branch, Branch otherBranch)
   at GitVersion.GitRepoMetadataProvider.<>c__DisplayClass13_0.<GetMergeCommitsForBranch>b__0(Branch otherBranch)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitVersion.GitRepoMetadataProvider.GetMergeCommitsForBranch(Branch branch)
   at GitVersion.GitRepoMetadataProvider.FindCommitBranchWasBranchedFrom(Branch branch, Branch[] excludedBranches)
   at GitVersion.BranchConfigurationCalculator.InheritBranchConfiguration(GitVersionContext context, Branch targetBranch, BranchConfig branchConfiguration, IList`1 excludedInheritBranches)
   at GitVersion.BranchConfigurationCalculator.GetBranchConfiguration(GitVersionContext context, Branch targetBranch, IList`1 excludedInheritBranches)
   at GitVersion.GitVersionContext.CalculateEffectiveConfiguration()
   at GitVersion.GitVersionContext..ctor(IRepository repository, Branch currentBranch, Config configuration, Boolean onlyEvaluateTrackedBranches, String commitId)
   at GitVersion.ExecuteCore.<>c__DisplayClass6_0.<ExecuteInternal>b__0(IRepository repo)
   at GitVersion.GitPreparer.WithRepository[TResult](Func`2 action)
   at GitVersion.ExecuteCore.ExecuteInternal(String targetBranch, String commitId, GitPreparer gitPreparer, IBuildServer buildServer, Config overrideConfig)
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache)
   at GitVersion.ExecuteCore.TryGetVersion(String directory, VersionVariables& versionVariables, Boolean noFetch, Authentication authentication)	NServiceBus.Log4Net		1	

```

**Comment by SimonCropp** [comment]
so seems adding

```
if (mergeBase != null)
{
     Logger.WriteDebug("New Merge base " + mergeBase.Sha);
}
```
and letting the loop fall out results in the correct version number.

do u want a PR for that?

**Comment by asbjornu** [comment]
@SimonCropp: Yes, that would be nice. A warning that no merge base was found should also probably be written, no?

**Comment by SimonCropp** [comment]
@JakeGinnivan polite request for a release ;)

**Comment by SimonCropp** [comment]
@asbjornu @gep13 @pascalberger can we get a release of this?

Also as an aside any eta on the next stable release?

**Comment by tpluscode** [comment]
Has this been released? I've been seeing this too.

Also, weirdly, I get this locally but not on AppVeyor 🤔

**Comment by asbjornu** [comment]
Yes, as a99f256a3d8ced260ef4affc7327c37b4e64e2f6 shows, this should be in `v4.0.0-beta.13`.

**Comment by bording** [comment]
@asbjornu The latest release on nuget.org is [4.0.0-beta0012](https://www.nuget.org/packages/GitVersionTask/4.0.0-beta0012). Beta 13 was never released.

**Comment by asbjornu** [comment]
@bording: Aha. We need to get a move on #1338. Any help with making the release process 99% automated is highly appreciated.

**Comment by bording** [comment]
@asbjornu Is the mean time, would it be possible to manually release a new package? In fact, I'd like to see a beta 14 released that incorporates the latest changes. Beta 13 was tagged before a lot of important changes.

**Comment by asbjornu** [comment]
@bording: I would love to, I just don't understand how. If I did, I would have made many releases already.
