### ISSUE TITLE
Issue with getting version number.

### ISSUE THREAD

**Issue by robertkolskiboa** [GitTools/GitVersion#1285]
The server is not able to connect to BitBucket.

INFO [08/31/17 11:14:35:36] Running on Windows.
INFO [08/31/17 11:14:35:36] Applicable build agent found: 'Jenkins'.
INFO [08/31/17 11:14:35:36] Branch from build environment: 
ERROR [08/31/17 11:14:35:76] An unexpected error occurred:
LibGit2Sharp.LibGit2SharpException: this remote has never connected
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in c:\Git\LibGit2Sharp\LibGit2Sharp\Core\Ensure.cs:line 154
   at LibGit2Sharp.Core.Proxy.git_remote_ls(Repository repository, RemoteHandle remote) in c:\Git\LibGit2Sharp\LibGit2Sharp\Core\Proxy.cs:line 2213
   at LibGit2Sharp.Network.ListReferencesInternal(String url, CredentialsHandler credentialsProvider) in c:\Git\LibGit2Sharp\LibGit2Sharp\Network.cs:line 129
   at GitTools.Git.GitRepositoryHelper.GetRemoteTipsForAnonymousUser(Repository repo, Remote remote)
   at GitTools.Git.GitRepositoryHelper.CreateFakeBranchPointingAtThePullRequestTip(Repository repo, AuthenticationInfo authentication)
   at GitTools.Git.GitRepositoryHelper.NormalizeGitDirectory(String gitDirectory, AuthenticationInfo authentication, Boolean noFetch, String currentBranch)
   at GitVersion.GitPreparer.Initialise(Boolean normaliseGitDirectory, String currentBranch)
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig)
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
INFO [08/31/17 11:14:35:76] 
INFO [08/31/17 11:14:35:76] Attempting to show the current git graph (please include in issue): 
INFO [08/31/17 11:14:35:76] Showing max of 100 commits
INFO [08/31/17 11:14:35:82] * c9b321b 4 minutes ago  (HEAD)
| *   2cd3010 24 hours ago  (origin/master, master)
| |\  
| |/  
|/|   
* |   9930d43 2 days ago  (origin/feature/MDTCICD-37, origin/develop, feature/MDTCICD-37, develop)
|\ \  
| * \   e3198c3 2 days ago 
| |\ \  
| |/ /  
|/| |   
* | | cd77758 2 days ago 
* | |   d63afe4 2 days ago 
|\ \ \  
| * | | 6bc23f9 2 days ago 
|/ / /  
| * | 63e7932 2 days ago 
| * | 9d46070 2 days ago 
| * | 7ba146c 2 days ago 
|/ /  
* |   09eecdc 10 days ago 
|\ \  
| * | 2b10786 13 days ago 
| * | 2235f00 13 days ago 
| * | 7f1407a 13 days ago 
| * | f863d7c 13 days ago 
| * | 4b9a2ff 13 days ago 
| * | 8bf4acb 2 weeks ago 
| * | 327d0e0 2 weeks ago 
| * | 757f47d 2 weeks ago 
| * | 3c736a2 2 weeks ago 
| * | 0d58df1 2 weeks ago 
| * | b0f479a 2 weeks ago 
| * | 58623c2 2 weeks ago 
| * | df67ed9 2 weeks ago 
|/ /  
| *   9a948b8 2 weeks ago  (origin/feature/MDTCICD-4-Kumar, feature/MDTCICD-4-Kumar)
| |\  
| |/  
|/|   
* |   e152fa9 2 weeks ago 
|\ \  
| * | c5e557e 2 weeks ago 
* | |   5606825 2 weeks ago 
|\ \ \  
| |/ /  
| * | d205bb3 2 weeks ago 
| * | 838ab85 2 weeks ago 
| * | 89e1b43 2 weeks ago 
| * | 9b49928 2 weeks ago 
| * | 1b03940 2 weeks ago 
| * | 5a9d993 2 weeks ago 
| * | b80a116 2 weeks ago 
| * | dcae1f8 2 weeks ago 
| * | 000b63b 2 weeks ago 
| * | b61bed6 2 weeks ago 
| |/  
| *   587d841 3 weeks ago 
| |\  
| |/  
|/|   
* |   7ca04e2 3 weeks ago 
|\ \  
| * | 6731802 3 weeks ago 
|/ /  
* | 0c3abb9 3 weeks ago 
* | 9e67d85 3 weeks ago 
|/  
* e9ec7d1 3 weeks ago

**Comment by asbjornu** [comment]
@robertkolskiboa: Have you tried to set the environment variables `GITVERSION_REMOTE_USERNAME` and `GITVERSION_REMOTE_PASSWORD` [as explained in the documentation](http://gitversion.readthedocs.io/en/latest/usage/msbuild-task/#my-git-repository-requires-authentication-what-should-i-do)?

**Comment by asbjornu** [comment]
Closing due to inactivity.
