### ISSUE TITLE
Trying to add assembly-file-versioning-scheme to GitVersion.yml file

### ISSUE THREAD

**Issue by psandhu79** [GitTools/GitVersion#1299]
Hi 

I have been struggling to add the assembly-file-versioning-scheme to the GitVersion.yml file. It gives me an error saying it's not recognized. So for a test i took the file below from the source area

GitVersion/src/GitVersionCore.Tests/ConfigProviderTests.CanWriteOutEffectiveConfiguration.approved.txt

Renamed it to GitVersion.yml then ran GitVersion.exe and got the following stacktrace

:\GIT\myassembly.Basics>gitversion
INFO [09/28/17 15:12:10:52] Working directory: D:\GIT\myassembly.Basics
INFO [09/28/17 15:12:10:52] IsDynamicGitRepository: False
INFO [09/28/17 15:12:10:53] Returning Project Root from DotGitDirectory: D:\GIT\myassembly.Basics\.git - D:\GIT\myassembly.Basics
INFO [09/28/17 15:12:10:54] Running on Windows.
INFO [09/28/17 15:12:10:54] IsDynamicGitRepository: False
INFO [09/28/17 15:12:10:54] Returning Project Root from DotGitDirectory: D:\GIT\myassembly.Basics\.git - D:\GIT\myassembly.Basics
INFO [09/28/17 15:12:10:54] Project root is: D:\GIT\myassembly.Basics
INFO [09/28/17 15:12:10:54] DotGit directory is: D:\GIT\myassembly.Basics\.git
INFO [09/28/17 15:12:10:54] IsDynamicGitRepository: False
INFO [09/28/17 15:12:10:54] Returning Project Root from DotGitDirectory: D:\GIT\myassembly.Basics\.git - D:\GIT\myassembly.Basics
INFO [09/28/17 15:12:10:58] Begin: Loading version variables from disk cache
  INFO [09/28/17 15:12:10:58] Cache file D:\GIT\myassembly.Basics\.git\gitversion_cache\5725BA67ED38485E0AFA86778D40760E3E84016B.yml not found.
INFO [09/28/17 15:12:10:58] End: Loading version variables from disk cache (Took: 1.00ms)
INFO [09/28/17 15:12:10:58] IsDynamicGitRepository: False
INFO [09/28/17 15:12:10:58] Returning Project Root from DotGitDirectory: D:\GIT\myassembly.Basics\.git - D:\GIT\myassembly.Basics
ERROR [09/28/17 15:12:10:65] An unexpected error occurred:
YamlDotNet.Core.YamlException: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): Exception during deserialization ---> System.Runtime.Serialization.SerializationException: Property 'assembly-file-versioning-scheme' not found on type 'GitVersion.Config'.
   at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(EventReader reader, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at GitVersion.ConfigSerialiser.Read(TextReader reader)
   at GitVersion.ConfigurationProvider.Provide(String workingDirectory, IFileSystem fileSystem, Boolean applyDefaults, Config overrideConfig)
   at GitVersion.ExecuteCore.ExecuteInternal(String targetBranch, String commitId, GitPreparer gitPreparer, IBuildServer buildServer, Config overrideConfig)
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig)
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
INFO [09/28/17 15:12:10:65]
INFO [09/28/17 15:12:10:65] Attempting to show the current git graph (please include in issue):
INFO [09/28/17 15:12:10:65] Showing max of 100 commits
INFO [09/28/17 15:12:10:70] * baa9a55 25 minutes ago  (HEAD -> GitVersionTest, origin/GitVersionTest)

**Comment by asbjornu** [comment]
Which version of GitVersion are you using?

**Comment by psandhu79** [comment]
@asbjornu 3.6.4.0

**Comment by asbjornu** [comment]
@psandhu79: Can you please upgrade to v4 beta and see if it understands the property?

**Comment by psandhu79** [comment]
@asbjornu v4 Beta works, thanks.

**Comment by asbjornu** [comment]
Awesome!
