### ISSUE TITLE
An unexpected error occurred: System.InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by pshrosbree** [GitTools/GitVersion#1316]
GitVersion faults when attempting to calculate the version.

GitVersion.yml:

```yaml
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
mode: Mainline
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
commit-message-incrementing: Enabled
branches:
  master:
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: develop$
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
  develop:
    mode: ContinuousDeployment
    tag: alpha
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    regex: develop.+
    tracks-release-branches: true
    is-release-branch: false
    is-mainline: false
ignore:
  sha: []
  commits-before: 2017-10-22T10:23:00
```
Running gitversion I get:

```console
λ gitversion
INFO [10/27/17 12:03:52:24] Working directory: G:\mc\EventHubs
INFO [10/27/17 12:03:52:25] IsDynamicGitRepository: False
INFO [10/27/17 12:03:52:26] Returning Project Root from DotGitDirectory: G:\mc\EventHubs\.git - G:\mc\EventHubs
INFO [10/27/17 12:03:52:27] Running on Windows.
INFO [10/27/17 12:03:52:27] IsDynamicGitRepository: False
INFO [10/27/17 12:03:52:27] Returning Project Root from DotGitDirectory: G:\mc\EventHubs\.git - G:\mc\EventHubs
INFO [10/27/17 12:03:52:27] Project root is: G:\mc\EventHubs
INFO [10/27/17 12:03:52:27] DotGit directory is: G:\mc\EventHubs\.git
INFO [10/27/17 12:03:52:28] IsDynamicGitRepository: False
INFO [10/27/17 12:03:52:28] Returning Project Root from DotGitDirectory: G:\mc\EventHubs\.git - G:\mc\EventHubs
INFO [10/27/17 12:03:52:31] Begin: Loading version variables from disk cache
  INFO [10/27/17 12:03:52:31] Cache file G:\mc\EventHubs\.git\gitversion_cache\30910D2AEEB1FB9403A69E58685FDBAA429BB45B.yml not found.
INFO [10/27/17 12:03:52:31] End: Loading version variables from disk cache (Took: 1.00ms)
INFO [10/27/17 12:03:52:31] IsDynamicGitRepository: False
INFO [10/27/17 12:03:52:31] Returning Project Root from DotGitDirectory: G:\mc\EventHubs\.git - G:\mc\EventHubs
INFO [10/27/17 12:03:52:40] Using latest commit on specified branch
INFO [10/27/17 12:03:52:41] Begin: Attempting to inherit branch configuration from parent branch
  INFO [10/27/17 12:03:52:42] Begin: Finding branch source of 'feature/merge-liblog'
    INFO [10/27/17 12:03:52:43] Begin: Finding merge base between 'feature/merge-liblog' and 'develop'.
      INFO [10/27/17 12:03:52:44] Found merge base of 83d23c3118f5cf3ca8a62aad9f2f8ba478f8f4f7
      INFO [10/27/17 12:03:52:44] Merge base of feature/merge-liblog' and 'develop is 83d23c3118f5cf3ca8a62aad9f2f8ba478f8f4f7
    INFO [10/27/17 12:03:52:44] End: Finding merge base between 'feature/merge-liblog' and 'develop'. (Took: 13.48ms)
    INFO [10/27/17 12:03:52:44] Begin: Finding merge base between 'feature/merge-liblog' and 'feature/gitversion'.
      INFO [10/27/17 12:03:52:44] Found merge base of 83d23c3118f5cf3ca8a62aad9f2f8ba478f8f4f7
      INFO [10/27/17 12:03:52:44] Merge base of feature/merge-liblog' and 'feature/gitversion is 83d23c3118f5cf3ca8a62aad9f2f8ba478f8f4f7
    INFO [10/27/17 12:03:52:44] End: Finding merge base between 'feature/merge-liblog' and 'feature/gitversion'. (Took: 0.00ms)
    INFO [10/27/17 12:03:52:44] Begin: Finding merge base between 'feature/merge-liblog' and 'feature/merge-liblog'.
      INFO [10/27/17 12:03:52:44] Found merge base of 2ea5dc43db93a626099d2c1d8eef08ebeb2913ac
      INFO [10/27/17 12:03:52:44] Merge base of feature/merge-liblog' and 'feature/merge-liblog is 2ea5dc43db93a626099d2c1d8eef08ebeb2913ac
    INFO [10/27/17 12:03:52:44] End: Finding merge base between 'feature/merge-liblog' and 'feature/merge-liblog'. (Took: 0.50ms)
    INFO [10/27/17 12:03:52:44] Begin: Finding merge base between 'feature/merge-liblog' and 'feature/use-imetric'.
      INFO [10/27/17 12:03:52:44] Found merge base of 28185d94d6b23857f1eafa565056e0e80dcdff49
      INFO [10/27/17 12:03:52:44] Merge base of feature/merge-liblog' and 'feature/use-imetric is 28185d94d6b23857f1eafa565056e0e80dcdff49
    INFO [10/27/17 12:03:52:44] End: Finding merge base between 'feature/merge-liblog' and 'feature/use-imetric'. (Took: 0.00ms)
    INFO [10/27/17 12:03:52:44] Begin: Finding merge base between 'feature/merge-liblog' and 'merge'.
      INFO [10/27/17 12:03:52:45] Found merge base of 2b399323eeb89e5150eb84c40c9049913ae77226
      INFO [10/27/17 12:03:52:45] Merge base of feature/merge-liblog' and 'merge is 2b399323eeb89e5150eb84c40c9049913ae77226
    INFO [10/27/17 12:03:52:45] End: Finding merge base between 'feature/merge-liblog' and 'merge'. (Took: 2.52ms)
    INFO [10/27/17 12:03:52:45] Begin: Finding merge base between 'feature/merge-liblog' and 'merge-liblog'.
      INFO [10/27/17 12:03:52:45] Found merge base of 2ea5dc43db93a626099d2c1d8eef08ebeb2913ac
      INFO [10/27/17 12:03:52:45] Merge base of feature/merge-liblog' and 'merge-liblog is 2ea5dc43db93a626099d2c1d8eef08ebeb2913ac
    INFO [10/27/17 12:03:52:45] End: Finding merge base between 'feature/merge-liblog' and 'merge-liblog'. (Took: 0.00ms)
    INFO [10/27/17 12:03:52:45] Begin: Finding merge base between 'feature/merge-liblog' and 'online-execute'.
      INFO [10/27/17 12:03:52:45] Found merge base of 136138ae226d5eb22e588d1a6ec349e5004c1bbc
      INFO [10/27/17 12:03:52:45] Merge base of feature/merge-liblog' and 'online-execute is 136138ae226d5eb22e588d1a6ec349e5004c1bbc
    INFO [10/27/17 12:03:52:45] End: Finding merge base between 'feature/merge-liblog' and 'online-execute'. (Took: 1.00ms)
    INFO [10/27/17 12:03:52:45] Begin: Finding merge base between 'feature/merge-liblog' and 'origin/develop'.
      INFO [10/27/17 12:03:52:45] Found merge base of 83d23c3118f5cf3ca8a62aad9f2f8ba478f8f4f7
      INFO [10/27/17 12:03:52:45] Merge base of feature/merge-liblog' and 'origin/develop is 83d23c3118f5cf3ca8a62aad9f2f8ba478f8f4f7
    INFO [10/27/17 12:03:52:45] End: Finding merge base between 'feature/merge-liblog' and 'origin/develop'. (Took: 0.00ms)
    INFO [10/27/17 12:03:52:45] Begin: Finding merge base between 'feature/merge-liblog' and 'origin/feature/gitversion'.
      INFO [10/27/17 12:03:52:45] Found merge base of 83d23c3118f5cf3ca8a62aad9f2f8ba478f8f4f7
      INFO [10/27/17 12:03:52:45] Merge base of feature/merge-liblog' and 'origin/feature/gitversion is 83d23c3118f5cf3ca8a62aad9f2f8ba478f8f4f7
    INFO [10/27/17 12:03:52:45] End: Finding merge base between 'feature/merge-liblog' and 'origin/feature/gitversion'. (Took: 0.00ms)
    INFO [10/27/17 12:03:52:45] Begin: Finding merge base between 'feature/merge-liblog' and 'origin/feature/liblog'.
      INFO [10/27/17 12:03:52:45] Found merge base of 985a4c08ddc6a6aa478df7404d71fcf09224310c
      INFO [10/27/17 12:03:52:45] Merge base of feature/merge-liblog' and 'origin/feature/liblog is 985a4c08ddc6a6aa478df7404d71fcf09224310c
    INFO [10/27/17 12:03:52:45] End: Finding merge base between 'feature/merge-liblog' and 'origin/feature/liblog'. (Took: 0.50ms)
    INFO [10/27/17 12:03:52:45] Begin: Finding merge base between 'feature/merge-liblog' and 'origin/feature/msbuild-templates'.
      INFO [10/27/17 12:03:52:45] Found merge base of fc2a524056f0bbe891f978962c863422520fef71
      INFO [10/27/17 12:03:52:45] Merge base of feature/merge-liblog' and 'origin/feature/msbuild-templates is fc2a524056f0bbe891f978962c863422520fef71
    INFO [10/27/17 12:03:52:45] End: Finding merge base between 'feature/merge-liblog' and 'origin/feature/msbuild-templates'. (Took: 0.50ms)
    INFO [10/27/17 12:03:52:45] Begin: Finding merge base between 'feature/merge-liblog' and 'origin/feature/use-imetric'.
      INFO [10/27/17 12:03:52:45] Found merge base of 28185d94d6b23857f1eafa565056e0e80dcdff49
      INFO [10/27/17 12:03:52:45] Merge base of feature/merge-liblog' and 'origin/feature/use-imetric is 28185d94d6b23857f1eafa565056e0e80dcdff49
    INFO [10/27/17 12:03:52:45] End: Finding merge base between 'feature/merge-liblog' and 'origin/feature/use-imetric'. (Took: 0.00ms)
    INFO [10/27/17 12:03:52:45] Begin: Finding merge base between 'feature/merge-liblog' and 'origin/HEAD'.
      INFO [10/27/17 12:03:52:45] Found merge base of 83d23c3118f5cf3ca8a62aad9f2f8ba478f8f4f7
      INFO [10/27/17 12:03:52:45] Merge base of feature/merge-liblog' and 'origin/HEAD is 83d23c3118f5cf3ca8a62aad9f2f8ba478f8f4f7
    INFO [10/27/17 12:03:52:45] End: Finding merge base between 'feature/merge-liblog' and 'origin/HEAD'. (Took: 0.48ms)
    INFO [10/27/17 12:03:52:45] Begin: Finding merge base between 'feature/merge-liblog' and 'origin/online-execute'.
      INFO [10/27/17 12:03:52:45] Found merge base of 136138ae226d5eb22e588d1a6ec349e5004c1bbc
      INFO [10/27/17 12:03:52:45] Merge base of feature/merge-liblog' and 'origin/online-execute is 136138ae226d5eb22e588d1a6ec349e5004c1bbc
    INFO [10/27/17 12:03:52:45] End: Finding merge base between 'feature/merge-liblog' and 'origin/online-execute'. (Took: 1.50ms)
    INFO [10/27/17 12:03:52:45] Begin: Finding merge base between 'feature/merge-liblog' and 'origin/optional-cursor'.
      INFO [10/27/17 12:03:52:45] Found merge base of a6f932f73d3af316ccdc4e0ba82019d63f90d125
      INFO [10/27/17 12:03:52:45] Merge base of feature/merge-liblog' and 'origin/optional-cursor is a6f932f73d3af316ccdc4e0ba82019d63f90d125
    INFO [10/27/17 12:03:52:45] End: Finding merge base between 'feature/merge-liblog' and 'origin/optional-cursor'. (Took: 0.50ms)
    INFO [10/27/17 12:03:52:45] Begin: Finding merge base between 'feature/merge-liblog' and 'upstream/develop'.
      INFO [10/27/17 12:03:52:45] Found merge base of 8967544fac03162fb35820b775a9d5bf2d7d7d6d
      INFO [10/27/17 12:03:52:45] Merge base of feature/merge-liblog' and 'upstream/develop is 8967544fac03162fb35820b775a9d5bf2d7d7d6d
    INFO [10/27/17 12:03:52:45] End: Finding merge base between 'feature/merge-liblog' and 'upstream/develop'. (Took: 0.50ms)
    INFO [10/27/17 12:03:52:45] Begin: Finding merge base between 'feature/merge-liblog' and 'upstream/petshr/cake'.
      INFO [10/27/17 12:03:52:45] Found merge base of d078cc65af683c558518169bf8e77e5631378be7
      INFO [10/27/17 12:03:52:45] Merge base of feature/merge-liblog' and 'upstream/petshr/cake is d078cc65af683c558518169bf8e77e5631378be7
    INFO [10/27/17 12:03:52:45] End: Finding merge base between 'feature/merge-liblog' and 'upstream/petshr/cake'. (Took: 1.00ms)
    INFO [10/27/17 12:03:52:45] Begin: Finding merge base between 'feature/merge-liblog' and 'upstream/petshr/language-ext'.
      INFO [10/27/17 12:03:52:45] Found merge base of 11e0d7e9e9a9e3ca9233b16630638a70f097206a
      INFO [10/27/17 12:03:52:45] Merge base of feature/merge-liblog' and 'upstream/petshr/language-ext is 11e0d7e9e9a9e3ca9233b16630638a70f097206a
    INFO [10/27/17 12:03:52:45] End: Finding merge base between 'feature/merge-liblog' and 'upstream/petshr/language-ext'. (Took: 0.50ms)
    INFO [10/27/17 12:03:52:45] Begin: Finding merge base between 'feature/merge-liblog' and 'upstream/petshr/paket'.
      INFO [10/27/17 12:03:52:45] Found merge base of d078cc65af683c558518169bf8e77e5631378be7
      INFO [10/27/17 12:03:52:45] Merge base of feature/merge-liblog' and 'upstream/petshr/paket is d078cc65af683c558518169bf8e77e5631378be7
    INFO [10/27/17 12:03:52:45] End: Finding merge base between 'feature/merge-liblog' and 'upstream/petshr/paket'. (Took: 0.50ms)
    INFO [10/27/17 12:03:52:45] Begin: Finding merge base between 'feature/merge-liblog' and 'upstream/remove-secrets'.
      INFO [10/27/17 12:03:52:45] Found merge base of 0d53b8c6eacefd07f393e9b0c2f72ec7f911d309
      INFO [10/27/17 12:03:52:45] Merge base of feature/merge-liblog' and 'upstream/remove-secrets is 0d53b8c6eacefd07f393e9b0c2f72ec7f911d309
    INFO [10/27/17 12:03:52:45] End: Finding merge base between 'feature/merge-liblog' and 'upstream/remove-secrets'. (Took: 0.52ms)
  INFO [10/27/17 12:03:52:46] End: Finding branch source of 'feature/merge-liblog' (Took: 43.02ms)
  INFO [10/27/17 12:03:52:46] Begin: Getting branches containing the commit '2ea5dc43db93a626099d2c1d8eef08ebeb2913ac'.
    INFO [10/27/17 12:03:52:46] Trying to find direct branches.
    INFO [10/27/17 12:03:52:46] No direct branches found, searching through tracked branches.
  INFO [10/27/17 12:03:52:47] End: Getting branches containing the commit '2ea5dc43db93a626099d2c1d8eef08ebeb2913ac'. (Took: 2.99ms)
  INFO [10/27/17 12:03:52:47] Found possible parent branches:
  WARN [10/27/17 12:03:52:47] Failed to inherit Increment branch configuration, no branches found.

Falling back to develop branch config
INFO [10/27/17 12:03:52:47] End: Attempting to inherit branch configuration from parent branch (Took: 62.48ms)
INFO [10/27/17 12:03:52:47] Running against branch: feature/merge-liblog (2ea5dc43db93a626099d2c1d8eef08ebeb2913ac)
INFO [10/27/17 12:03:52:48] Begin: Calculating base versions
  INFO [10/27/17 12:03:52:48] Fallback base version: 0.1.0 with commit count source 6c44bdb217c8f67efdf8471b030a7358c96359c2 (Incremented: None)
  INFO [10/27/17 12:03:52:48] Source was ignored due to commit date being outside of configured range
INFO [10/27/17 12:03:52:51] End: Calculating base versions (Took: 30.00ms)
ERROR [10/27/17 12:03:52:51] An unexpected error occurred:
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersion(GitVersionContext context)
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion(GitVersionContext context)
   at GitVersion.GitVersionFinder.FindVersion(GitVersionContext context)
   at GitVersion.ExecuteCore.<>c__DisplayClass6_0.<ExecuteInternal>b__0(IRepository repo)
   at GitVersion.GitPreparer.WithRepository[TResult](Func`2 action)
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache)
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
INFO [10/27/17 12:03:52:51]
INFO [10/27/17 12:03:52:51] Attempting to show the current git graph (please include in issue):
INFO [10/27/17 12:03:52:51] Showing max of 100 commits
INFO [10/27/17 12:03:52:56] * 2ea5dc4 4 minutes ago  (HEAD -> feature/merge-liblog, merge-liblog)
*   a9a9c1f 2 hours ago
|\
| * 985a4c0 2 hours ago  (origin/feature/liblog)
| * 22a85e0 4 days ago
* | 28185d9 2 hours ago  (origin/feature/use-imetric, feature/use-imetric)
|/
* 83d23c3 5 days ago  (origin/feature/gitversion, origin/develop, origin/HEAD, feature/gitversion, develop)
* fc2a524 5 days ago  (origin/feature/msbuild-templates)
*   4c34876 5 days ago
|\
| *   13cf407 6 days ago
| |\
| | *   8967544 2 weeks ago  (upstream/develop)
| | |\
| | | * 0d53b8c 2 weeks ago  (upstream/remove-secrets)
| | |/
* | | 8952034 6 days ago
* | | 15b1ca8 6 days ago
* | | c64557d 6 days ago
* | | 049300d 6 days ago
* | | afe4905 6 days ago
* | | 543add9 6 days ago
* | | a6f932f 2 weeks ago  (origin/optional-cursor)
* | | 9797bfa 2 weeks ago
* | | 75ed844 3 weeks ago
* | | 18d02e0 3 weeks ago
* | | 1c93ce1 3 weeks ago
* | | 775a1a4 3 weeks ago
|/ /
* | 7588949 3 weeks ago
* | 72a09eb 3 weeks ago
* | ff68e67 3 weeks ago
* | fce27b0 3 weeks ago
* | e31dbc5 3 weeks ago
| | *   3f5188e 3 weeks ago  (refs/stash)
| | |\
| |/ /
|/| |
| | * 5811dd1 3 weeks ago
| |/
|/|
* | 2b39932 3 weeks ago  (merge)
* | ac94cab 3 weeks ago
* | a94c1d6 3 weeks ago
* | 90ea4b9 4 weeks ago
* |   091f8a9 4 weeks ago
|\ \
* | | 2402437 4 weeks ago
* | | 81088d7 4 weeks ago
* | | d9f4eeb 4 weeks ago
| | | * 879ba32 4 weeks ago  (origin/online-execute)
| | | * 2909320 5 weeks ago
| | |/
| |/|
| * | 136138a 5 weeks ago  (online-execute)
| * | 945d765 5 weeks ago
| * | d84f73c 5 weeks ago
| * | dbf3899 5 weeks ago
| * | ec8ee6f 5 weeks ago
| * | 6c3c655 5 weeks ago
| * | 439df5a 5 weeks ago
| * | 0c23a16 5 weeks ago
| * | 4782c38 5 weeks ago
| * | 093a5aa 5 weeks ago
|/ /
* | 5e83361 6 weeks ago
|/
* 11e0d7e 6 weeks ago  (upstream/petshr/language-ext)
* a3e296a 6 weeks ago
* e0045c3 7 weeks ago
* 18eb68d 7 weeks ago
* 41e7e97 7 weeks ago
* 374eefa 7 weeks ago
| * ae443cf 8 weeks ago  (upstream/petshr/cake)
| * 2ef9bb2 8 weeks ago
| | * e250e65 8 weeks ago  (upstream/petshr/paket)
| | * dcaf220 8 weeks ago
| |/
| * ee39bd4 8 weeks ago
|/
* d078cc6 8 weeks ago
* 0f46036 8 weeks ago
* a79a45b 8 weeks ago
* 1c52579 8 weeks ago
* 5c0b201 8 weeks ago
* c62ad94 8 weeks ago
* 5c00067 8 weeks ago
* cfcfde4 8 weeks ago
* 629e7c2 8 weeks ago
* dbbb331 8 weeks ago
* dc1ead3 8 weeks ago
* 80b61a8 8 weeks ago
* 2f75d65 8 weeks ago
* 2bdad52 8 weeks ago
* 7b78637 8 weeks ago
* 3b7d0df 8 weeks ago
* 54e374f 8 weeks ago
* a118e10 8 weeks ago
* 251f086 8 weeks ago
* 119af20 8 weeks ago
* af599b6 8 weeks ago
* 0ec9fe6 8 weeks ago
* c9ae476 8 weeks ago
* 54c21a4 9 weeks ago
* a0aec93 9 weeks ago
* 2d110bd 9 weeks ago
* 82e79ff 9 weeks ago
* 00bd899 9 weeks ago
* 7a3daa9 9 weeks ago
* 5a0f4bb 9 weeks ago
* af4a64b 9 weeks ago
* 20528ef 9 weeks ago
* 12061a4 9 weeks ago
* fdf8200 9 weeks ago
* 2468dcd 9 weeks ago
* da62b28 9 weeks ago
* a761274 9 weeks ago
* 24e2c7f 9 weeks ago
```

Is this a bug? Or am I doing something wrong?

**Comment by pshrosbree** [comment]
Changing GitVersion.yml the following results in the same error.

`GitVersion 4.0.0-beta.12+1315.Branch.master.Sha.9c70946f68973b3b31b2861913c247fbe6c3f0ec`

```yaml
next-version: 1.0.0
commit-message-incrementing: Disabled
ignore:
  sha: []
  commits-before: 2017-10-22T10:23:00
```

**Comment by asbjornu** [comment]
How about deleting `GitVersion.yml`, what happens then?

**Comment by timdeboer** [comment]
Hi @asbjornu -  I'm having the same problem. I suspect it's because every potential version source is being ignored. When I added a tag outside the "exclusion zone" GitVersion succeeded. I've included the output from the two runs for you to compare... The first without the additional tag (which failed) and the second with it.

[LogForFailedRun.txt](https://github.com/GitTools/GitVersion/files/1963101/LogForFailedRun.txt)
[LogForPassingRun.txt](https://github.com/GitTools/GitVersion/files/1963102/LogForPassingRun.txt)

**Comment by asbjornu** [comment]
@timdeboer: Great, I'll look into the logs ASAP. Is the failing repository available somewhere publicly or can you reproduce it somehow in a public repository?

**Comment by timdeboer** [comment]
Hi @asbjornu - Sorry missed your email as got tucked away in gmail's forum tag which I visit irregularly. How'd you go with this? It would take a little time but I could reproduce a repo that would create the error but I suspect the logs will be enough. If not let me know. The repo this happened on is not available publicly so can't provide that.

**Comment by asbjornu** [comment]
@timdeboer: It looks like you're using version `3.6.5` of GitVerison. Can you please upgrade to v4 beta 12 and see if it behaves better?

**Comment by icurto** [comment]
I'm facing the same issue, I've tried also with v4.0.1-beta1-47. It seems to happen only when I ignore all commits before a date and no version is found, but if I ignore all these commits specifying the sha it works correctly.

**Comment by asbjornu** [comment]
@icurto: How does the log look like? Do you get a stack trace so we can pinpoint where in GitVersion this is occurring?

**Comment by icurto** [comment]
This is the log: [log.txt](https://github.com/GitTools/GitVersion/files/2610495/log.txt)
And my GitVersion.yml:
```
assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDelivery
next-version: 1.0.1
commit-message-incrementing: Enabled
ignore:
  sha: []
  commits-before: 2018-11-22T12:00:00
```
But it works correctly if I change the yml like this:
```
assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDelivery
next-version: 1.0.1
commit-message-incrementing: Enabled
ignore:
  sha:
    - d392375ea44525b303888a40d046acd9115b36d3
    - 2dbb79e089956b9d1fcaceb5c3ff571c26e8dd19
    - b0b7e20af44165165ff10653de8f7c609d239f59
    - 8de72ffba4c6c1d396a7a2bc9b7ca07a946a4234
    - d07e673b7343309ef6fb385923daeaedb588609f
    - 3faabe1fdd6b301583f0d6e41bc080c06bb4a443
    - b3f30dcab2181ed2544808cbf11e2c623caf0dc7
    - dbeafbb4b337aeafb4b9b9c6330ede4ab879afad
    - f7b5bf82b731bba1bc83fdb6905d14aff9209469
    - afcaa6134abec9b82df76019ad3bc7adef31f014
    - 4c898d4e4093aaec05584f062b2f0fac2987cbb2
    - 67a902af65f1ae77aca4353de5353443ba693e4b
    - 5b3d428321f92c09199824a20953bc3baa151493
    - 8fd127a03a87ce75a45a4f9de9ca45090586541b
    - 3edbb280f24f9a84718da8f255c2682a8a029bdf
    - 34cc688d0808eb6d1cf545387bdd3933f1bea15a
    - ad534c9d9cc23b7918983f75c0f033d80266b3c3
    - 3b6c16200c423ede7305e81a6b052ffef571c9ec
    - b6857dd4c593d4a5c241aa936a68daf071b42c53
    - 218c454adf38837d506a9d66146e7015b10009e3
    - a1e276ae8751d6a31b6677b357e8b1b23534669f
    - b4e56a73001645579d893852d0ec1b819d077921
    - 0cbc39f7ec0ac4a28c891f01939069d7630e5a19
    - e21dfbd9ef82549ff30f9338d07c41af0ecf2ace
    - 59eda33ebe08a86defc2ea034b596219295002b1
    - 96e3a67323da135166905ce01492938ca94327b4
    - 9bc07baa5f287bf94b44631522516c0140ff41f3
```

**Comment by asbjornu** [comment]
@icurto: Thanks. Based on that stack trace, I think it must be this that is failing:

https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/VersionCalculation/BaseVersionCalculator.cs#L64-L69

I don't have a solution to not finding any base version in that sequence, so please feel free to suggest changes that will fix the problem. Also, a test that provokes this problem would be highly appreciated.
