### ISSUE TITLE
Unable to determine which AssemblyBuilder required to generate GitVersion assembly information

### ISSUE THREAD

**Issue by walter-csharp** [GitTools/GitVersion#1343]
I am creating project which is setting target frameworks to NetStandard2.0 and .net461 using VS2017.
And that project does not have any single class file.It's have only content files.
After added GitVersionTask package to this project and then i build project am getting error like.

Error		
Error occurred: GitTools.WarningException: Unable to determine which AssemblyBuilder required to generate GitVersion assembly information
   at AssemblyInfoBuilder.GetAssemblyInfoBuilder(IEnumerable`1 compileFiles)
   at GitVersionTask.UpdateAssemblyInfo.CreateTempAssemblyInfo(VersionVariables versionVariables)
   at GitVersionTask.UpdateAssemblyInfo.InnerExecute()
   at GitVersionTask.UpdateAssemblyInfo.Execute()	Ashley.Integrations.Standard.Logging		1

**Comment by asbjornu** [comment]
I can only assume this is caused by GitVersion not having .NET Core / Standard support yet. That is being developed in #1269.
