### ISSUE TITLE
"Mainline development mode doesn't yet support pre-release tags on master"

### ISSUE THREAD

**Issue by Kieranties** [GitTools/GitVersion#1356]
## Brief

I'm using the [beta 13 release](https://github.com/GitTools/GitVersion/releases/tag/v4.0.0-beta.13) with `mainline` mode enabled for the repository.
My configuration sets up a `preview` branch which is designed to build as pre-release and is tagged by the build server with pre-release tags. (I know this sounds like the default release branch configuration, but bear with me. I'm having to name things with current internal naming conventions.)

```yaml
mode: Mainline
tag-prefix: 'build\/'
legacy-semver-padding: 5
build-metadata-padding: 5
commits-since-version-source-padding: 5
branches:
  preview:
    mode: ContinuousDeployment
    regex: preview[/-]
    tag: useBranchName
    source-branches: ['master', 'preview', 'release']
```

## Scenario
1. The preview branch has built previously and has been tagged with a pre-release tag
2. A developer creates a feature branch from the tagged commit on the preview branch.
3. A pull request is raised to merge the feature branch back to the preview branch

### Expected

The pull-request is able to be versioned to enable the PR build to execute.

### Actual

An error is thrown:

```
ERROR [01/16/18 16:39:07:53] An unexpected error occurred:
System.NotSupportedException: Mainline development mode doesn't yet support pre-release tags on master
   at GitVersion.VersionCalculation.MainlineVersionCalculator.FindMainlineModeVersion(BaseVersion baseVersion, GitVersionContext context)
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion(GitVersionContext context)
   at GitVersion.GitVersionFinder.FindVersion(GitVersionContext context)
   at GitVersion.ExecuteCore.<>c__DisplayClass6_0.<ExecuteInternal>b__0(IRepository repo)
   at GitVersion.GitPreparer.WithRepository[TResult](Func`2 action)
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch,
Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache)
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
```

## Additonal

I can see that this is an explicit decision in the code base, but I'd like to understand why. 
I had hoped that setting `mode: ContinuousDeployment` for the preview branch would have forced commits into the branch to always increment the pre-release version, but it seems mainline mode still affects the counts  in the branch.

**Comment by asbjornu** [comment]
If overriding `mode` in a branch doesn't work, that sounds like a bug. If you're already poking around in the source code, would you mind submitting a pull request addressing that?

**Comment by asbjornu** [comment]
This also seems to be a duplicate of #1332.
