### ISSUE TITLE
Installing latest vsix throws and InvalidExtensionManifestException `Element 'Identity' has invalid value for attribute 'Version'`

### ISSUE THREAD

**Issue by KrzysFR** [GitTools/GitVersion#1407]
Trying to install the [v4.0.0-beta.13 .vsix](https://github.com/GitTools/GitVersion/releases/tag/v4.0.0-beta.13) fails with the following error (see below for full install log): `Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: Element 'Identity' has invalid value for attribute 'Version' ---> System.FormatException: Input string was not in a correct format
`

Looking at the callstack, I'm wondering if it is failing to parse the `15.7.103+gdea0b20b76` which has a `+` inside it? I reproduce a similar exception message with C# Interactive:
```csharp
> System.Version.Parse("15.7.103+gdea0b20b76")
Input string was not in a correct format.
  + System.Version.VersionResult.SetFailure(System.Version.ParseFailureKind, string)
  + System.Version.TryParseComponent(string, string, ref System.Version.VersionResult, out int)
  + System.Version.TryParseVersion(string, ref System.Version.VersionResult)
  + System.Version.Parse(string)
  + <Initialize>.MoveNext()
> 
```

I have Visual Studio 2017 v15.6.7 installed.

VSIX install log:
```
04/05/2018 14:52:34 - Microsoft VSIX Installer
04/05/2018 14:52:34 - -------------------------------------------
04/05/2018 14:52:34 - vsixinstaller.exe version:
04/05/2018 14:52:34 - 15.7.103+gdea0b20b76
04/05/2018 14:52:34 - -------------------------------------------
04/05/2018 14:52:34 - Command line parameters:
04/05/2018 14:52:34 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\chevalier\Downloads\gittools.gitversion-4.0.0-beta0013.vsix
04/05/2018 14:52:34 - -------------------------------------------
04/05/2018 14:52:34 - Microsoft VSIX Installer
04/05/2018 14:52:34 - -------------------------------------------
04/05/2018 14:52:36 - Initializing Install...
04/05/2018 14:52:37 - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: Element 'Identity' has invalid value for attribute 'Version' ---> System.FormatException: Input string was not in a correct format.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.<>c.<ExtractManifestData>b__64_1(String s)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ExtractManifestData(PackageManifest manifest)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadPackageManifest(XmlReader reader)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadManifest(Stream manifestStream)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath)
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by Skleni** [comment]
I just encountered the same problem and found this issue by googling the error message. If anyone else does the same and also lands here: The problem seems to be that when you double-click the .vsix file, it tries to install the extension to Visual Studio, not Visual Studio Code. Installing by clicking `.../Install` from VSIX in VS Code (or dragging the file in the extension area) works just fine.
