### ISSUE TITLE
VSTS Task does not support agents with spaces in file path.

### ISSUE THREAD

**Issue by dalee-bis** [GitTools/GitVersion#1440]
I have a build in VSTS which I have enabled the GitVersion task on. Unfortunately, the build agent is configured to use "D:\VSTS Agent" which causes the following error:

```
2018-07-04T14:46:12.7459316Z D:\VSTS Agent\_work\_tasks\GitVersion_e5983830-3f75-11e5-82ed-81492570a08e\3.6.5\GitVersion.exe D:\VSTS Agent\_work\24\s /output buildserver /nofetch
2018-07-04T14:46:12.7459316Z WARN [07/04/18 15:46:12:44] The working directory 'D:\VSTS' does not exist.
2018-07-04T14:46:12.7459316Z INFO [07/04/18 15:46:12:44] IsDynamicGitRepository: False
2018-07-04T14:46:12.7459316Z ERROR [07/04/18 15:46:12:48] An unexpected error occurred:
2018-07-04T14:46:12.7459316Z System.IO.DirectoryNotFoundException: Can't find the .git directory in D:\VSTS
2018-07-04T14:46:12.7459316Z    at GitVersion.GitPreparer.GetDotGitDirectory()
2018-07-04T14:46:12.7459316Z    at GitVersion.GitPreparer.GetProjectRootDirectory()
2018-07-04T14:46:12.7459316Z    at GitVersion.ConfigurationProvider.Verify(GitPreparer gitPreparer, IFileSystem fileSystem)
2018-07-04T14:46:12.7459316Z    at GitVersion.Program.VerifyArgumentsAndRun()
```

Version details:
```
2018-07-04T14:46:10.5271778Z ==============================================================================
2018-07-04T14:46:10.5271778Z Task         : GitVersion Task
2018-07-04T14:46:10.5271778Z Description  : Easy Semantic Versioning (http://semver.org) for projects using Git
2018-07-04T14:46:10.5271778Z Version      : 3.6.5
2018-07-04T14:46:10.5271778Z Author       : GitVersion Contributors
2018-07-04T14:46:10.5271778Z Help         : See the [documentation](http://gitversion.readthedocs.org/en/latest/) for help
2018-07-04T14:46:10.5271778Z ==============================================================================
```

I'm not familiar with the code but I believe the issue is in the `vsts-task-lib` library as the following lines seem valid to me:
https://github.com/GitTools/GitVersion/blob/06b131e476b205cbacf4497caf550576b617a70e/src/GitVersionTfsTask/GitVersion.ts#L49-L54

**Comment by dalee-bis** [comment]
Commenting to remove stale label...

**Comment by arturcic** [comment]
@dalee-bis can you give a try to this one? https://marketplace.visualstudio.com/items?itemName=GitVersion.gitversion-preview

**Comment by dalee-bis** [comment]
Unfortunately I don't have a way to test this at the moment but if you think it's fixed in that version I'm happy for this to be closed.

**Comment by arturcic** [comment]
Ok then, closing it. In case it's still reproduceable, please open it again
