### ISSUE TITLE
.NET Core GitVersion -showvariable exception

### ISSUE THREAD

**Issue by snovak7** [GitTools/GitVersion#1469]
Hello, I have installed nuget package for netstandard: <PackageReference Include="GitVersion.CommandLine.DotNetCore" Version="4.0.0-pullrequest1269-1541"> This version has an error when I want to make -showvariable, any showvariable, it returns:

```
System.NotImplementedException: The method or operation is not implemented.
   at GitVersion.VersionVariables.ContainsKey(String variable) in C:\projects\gitversion\src\GitVersionCore\OutputVariables\VersionVariables.cs:line 196
   at GitVersion.VersionVariables.TryGetValue(String variable, String& variableValue) in C:\projects\gitversion\src\GitVersionCore\OutputVariables\VersionVariables.cs:line 181
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
```

Without options, I get a valid JSON output.

**Comment by dazinator** [comment]
Yup the .NET Core implementation of this command was omitted in #1269 
It just needs implementing really. I'll mark this as up for grabs.

**Comment by snovak7** [comment]
Well I just used whats in the NETDESKTOP and it worked. You should add NETSTANDARD option there aswell. And here's the patch.
[patch_1469.txt](https://github.com/GitTools/GitVersion/files/2475591/patch_1469.txt)

**Comment by snovak7** [comment]
@dazinator or should I prepare PR?

**Comment by arturcic** [comment]
it's up for grabs, feel free to prepare a PR

**Comment by dazinator** [comment]
Nice one @snovak7
