### ISSUE TITLE
[BuildServer: Jenkins] ref 'refs/remotes/origin/*' doesn't match the destination

### ISSUE THREAD

**Issue by hienng** [GitTools/GitVersion#1490]
When finishing a feature and merging it back to develop. GitVersion always creates the local branch from remote-tracking as part of normalizing the git directory. After that the destination doesn't match with develop anymore. I suspect that, when creating the local branch it also gets checked out.

GitVersion is integrated in my Cake script (v3.6.5). Also have tried 4.0.0-beta0014.

Using GitVersion from CLI and manually executing the Cake script in Powershell doesn't have issues. 

Setup:
Jenkins ver. 2.138.1 
Bitbucket Branch Source Plugin
Setup with Bitbucket Project/Team Pipeline and Bitbucket Server 

![image](https://user-images.githubusercontent.com/7728095/46793899-01b7e080-cd47-11e8-9635-6385e2ffe2cf.png)

E.g. feature9 is being finished and merged back to develop. Jenkins starts the the build job and fails.

```
INFO [10/10/18 15:27:34:36] Begin: Normalizing git directory for branch 'develop'
  INFO [10/10/18 15:27:34:47] One remote found (origin -> 'http://somegit.git').
  INFO [10/10/18 15:27:34:47] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
  INFO [10/10/18 15:27:34:49] Updating local branch refs/heads/develop to match ref develop
  INFO [10/10/18 15:27:34:54] Skipping update of 'refs/remotes/origin/feature/enableNugetPush' as it already matches the remote ref.
  INFO [10/10/18 15:27:34:55] Skipping update of 'refs/remotes/origin/feature/feature4' as it already matches the remote ref.
  INFO [10/10/18 15:27:34:55] Skipping update of 'refs/remotes/origin/feature/feature5' as it already matches the remote ref.
  INFO [10/10/18 15:27:34:55] Skipping update of 'refs/remotes/origin/feature/feature6' as it already matches the remote ref.
  INFO [10/10/18 15:27:34:57] Skipping update of 'refs/remotes/origin/feature/feature7' as it already matches the remote ref.
  INFO [10/10/18 15:27:34:57] Skipping update of 'refs/remotes/origin/feature/feature8' as it already matches the remote ref.
  INFO [10/10/18 15:27:34:57] Creating local branch from remote tracking 'refs/remotes/origin/feature/feature9'.
INFO [10/10/18 15:27:34:60] End: Normalizing git directory for branch 'develop' (Took: 234.37ms)
ERROR [10/10/18 15:27:34:60] An unexpected error occurred:
LibGit2Sharp.LibGit2SharpException: ref 'refs/remotes/origin/feature/feature9' doesn't match the destination
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_refspec_rtransform(IntPtr refSpecPtr, String name)
   at LibGit2Sharp.Remote.FetchSpecTransformToSource(String reference)
   at LibGit2Sharp.BranchUpdater.GetUpstreamInformation(String canonicalName, String& remoteName, String& mergeBranchName)
   at LibGit2Sharp.BranchUpdater.SetUpstream(String upstreamBranchName)
   at LibGit2Sharp.BranchCollection.Update(Branch branch, Action`1[] actions)
   at GitTools.Git.GitRepositoryHelper.CreateOrUpdateLocalBranchesFromRemoteTrackingOnes(Repository repo, String remoteName)
   at GitTools.Git.GitRepositoryHelper.NormalizeGitDirectory(String gitDirectory, AuthenticationInfo authentication, Boolean noFetch, String currentBranch)
   at GitVersion.GitPreparer.Initialise(Boolean normaliseGitDirectory, String currentBranch, Boolean shouldCleanUpRemotes)
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache)
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
```

**Comment by giulianofavro-inpeco** [comment]
We have the same problem. Is not clear why GitVersion work correctly using a standard Jenkins job, but has problem with pipeline job.

**Comment by gitAllender** [comment]
Hi there,
do you know any workaround for this issue?

**Comment by gjonespf** [comment]
YMMV, but my horrible fix for this is to run a prebuild script that does following:
    git fetch origin master
    git fetch origin develop
    git checkout master
    git checkout develop
    git checkout $CurrentBranch

Issue for me is definitely to do with the way Jenkins is doing the fetch and refspec, and this was the only reliable way I found to get gitversion working after fiddling with a lot of Jenkins settings.  I do this in pipeline multibranch jobs as well as normal pipeline jobs, and for good measure also delete .git/gitversion_cache/* before each build (PRs especially bug out with this, using same workspace dir).

**Comment by pniederlag** [comment]
running into same sort of problems with no final solution yet

**Comment by ahmedndm123** [comment]
> YMMV, but my horrible fix for this is to run a prebuild script that does following: git fetch origin master git fetch origin develop git checkout master git checkout develop git checkout $CurrentBranch
> 
> Issue for me is definitely to do with the way Jenkins is doing the fetch and refspec, and this was the only reliable way I found to get gitversion working after fiddling with a lot of Jenkins settings. I do this in pipeline multibranch jobs as well as normal pipeline jobs, and for good measure also delete .git/gitversion_cache/* before each build (PRs especially bug out with this, using same workspace dir).

Hey man I just got into this issue your fix solved my prob thanks a lot man!!!

**Comment by deepgandu** [comment]
/usr/bin/git checkout --progress --force -B master refs/remotes/origin/master

**Comment by deepgandu** [comment]
/usr/bin/git checkout --progress --force -B master refs/remotes/origin/master
