### ISSUE TITLE
GitVersion 4.0.0 fails on VSTS

### ISSUE THREAD

**Issue by jmezach** [GitTools/GitVersion#1496]
Now that the 4.0.0 version of GitVersion has been published to the Marketplace I've been trying to use it in my projects, but unfortunately I'm getting an error when using the 4.0 version of the build task:

```
2018-10-14T17:50:43.3560348Z ##[error]File not found: 'D:\a\_tasks\GitVersion_e5983830-3f75-11e5-82ed-81492570a08e\4.0.0\GitVersion.js'
```

This looks like a packaging issue with the VSTS extension. Looks like the build task is written in TypeScript, so I'm guessing that the TypeScript wasn't transpiled to JavaScript at the time of the release. I believe @arturcic published the 4.0.0 version of the VSTS task as a part of #1445.

**Comment by arturcic** [comment]
Actually the GitVersion.js is there, I guess the task is not looking at the correct location
![image](https://user-images.githubusercontent.com/1760506/46920899-6734f700-cffd-11e8-810f-c88ba236b308.png)

**Comment by jmezach** [comment]
Hmm, looking at the [task.json](https://github.com/GitTools/GitVersion/blob/de31bd5dae0feefaa9b5ed819c1f4208dd38a342/src/GitVersionTfsTask/GitVersionTask/task.json#L71) it's looking for the GitVersion.js in the root, but looking at the screenshot it is inside of a scripts folder. So I guess the task.json should be modified to match the actual path of the GitVersion.js.

**Comment by yohanb** [comment]
Same error on an Ubuntu VSTS build agent.
![screen shot 2018-10-14 at 4 34 40 pm](https://user-images.githubusercontent.com/812993/46921888-160e0e80-cfcf-11e8-9ffa-86efb7eb6cdd.png)
It's a private agent so I was able to look into the task folder's content:
![image](https://user-images.githubusercontent.com/812993/46921936-e6abd180-cfcf-11e8-865a-da2535200000.png)
no scripts folder, no transpiled `GitVersion.js`.

**Comment by jmezach** [comment]
@arturcic I just tried it, but I'm still getting the same error. Since the error also contains the version number, which is still 4.0.0, I'm wondering if the version number on the task has been updated. If not I believe that VSTS will still use the old version (due to caching).

**Comment by arturcic** [comment]
Ok then, I'll update that as well

**Comment by arturcic** [comment]
@jmezach Updated, moved the files to the same location as task.json, can you try the new  version?

**Comment by jmezach** [comment]
Okay, it picked up the new version of the task now, but now I'm getting a different error:

```
2018-10-15T07:02:45.7987690Z ##[section]Starting: GitVersion
2018-10-15T07:02:45.7991420Z ==============================================================================
2018-10-15T07:02:45.7991620Z Task         : GitVersion Task
2018-10-15T07:02:45.7991730Z Description  : Easy Semantic Versioning (http://semver.org) for projects using Git
2018-10-15T07:02:45.7991850Z Version      : 4.0.1
2018-10-15T07:02:45.7992010Z Author       : GitVersion Contributors
2018-10-15T07:02:45.7992190Z Help         : See the [documentation](http://gitversion.readthedocs.org/en/latest/) for help
2018-10-15T07:02:45.7992310Z ==============================================================================
2018-10-15T07:02:46.3209380Z module.js:471
2018-10-15T07:02:46.3218320Z     throw err;
2018-10-15T07:02:46.3218580Z     ^
2018-10-15T07:02:46.3218700Z 
2018-10-15T07:02:46.3219900Z Error: Cannot find module 'vsts-task-lib/task'
2018-10-15T07:02:46.3220270Z     at Function.Module._resolveFilename (module.js:469:15)
2018-10-15T07:02:46.3220560Z     at Function.Module._load (module.js:417:25)
2018-10-15T07:02:46.3220900Z     at Module.require (module.js:497:17)
2018-10-15T07:02:46.3221060Z     at require (internal/module.js:20:19)
2018-10-15T07:02:46.3221860Z     at Object.<anonymous> (/Users/vsts/agent/2.140.2/work/_tasks/GitVersion_e5983830-3f75-11e5-82ed-81492570a08e/4.0.1/GitVersion.js:11:12)
2018-10-15T07:02:46.3222470Z     at Module._compile (module.js:570:32)
2018-10-15T07:02:46.3222700Z     at Object.Module._extensions..js (module.js:579:10)
2018-10-15T07:02:46.3222860Z     at Module.load (module.js:487:32)
2018-10-15T07:02:46.3223090Z     at tryModuleLoad (module.js:446:12)
2018-10-15T07:02:46.3224580Z     at Function.Module._load (module.js:438:3)
2018-10-15T07:02:46.3889420Z ##[error]Exit code 1 returned from process: file name '/Users/vsts/agent/2.140.2/externals/node/bin/node', arguments '"/Users/vsts/agent/2.140.2/work/_tasks/GitVersion_e5983830-3f75-11e5-82ed-81492570a08e/4.0.1/GitVersion.js"'.
2018-10-15T07:02:46.3926680Z ##[section]Finishing: GitVersion
```

Are the node_modules part of the VSIX?

**Comment by arturcic** [comment]
looks like we need to include the node_modules as well

**Comment by arturcic** [comment]
For unix you need mono installed

**Comment by arturcic** [comment]
I'll create a PR for this issue with the changes I've done so far, and I'll close the issue.

**Comment by jmezach** [comment]
Sounds good. I'll file another issue for the macOS and Linux failures.

**Comment by arturcic** [comment]
@yohanb , can you check the new version on your agent, I guess you have mono installed there.

**Comment by yohanb** [comment]
@arturcic why is mono required if it's compiled as .NET Core?

**Comment by arturcic** [comment]
The version that is used in the VSTS package is a .NET Framework package - il-merged. That was the way it was packaged before v.4.0.0, and I did not changed that, so it's still running with mono. Probably we might consider using the .NET core version, but that will add a dependency on .net core to be installed, now it's on mono

**Comment by claudiuconstantin** [comment]
When will this be released?

**Comment by arturcic** [comment]
a PR for this change is welcomed.

**Comment by jmezach** [comment]
Perhaps this is also the reason for #1497. I guess taking a dependency on .NET Core isn't that weird, since the hosted agents on VSTS (including Windows, macOS and Linux) all have .NET Core SDK's installed.

**Comment by yohanb** [comment]
FYI https://github.com/GitTools/GitVersion/pull/1499
