### ISSUE TITLE
Programmatic GitVersion

### ISSUE THREAD

**Issue by LordMike** [GitTools/GitVersion#1567]
I'm trying to programmatically invoke GitVersion to get the versioning information. I've copied out the `GitVersion.Tool` source, and made it work independently in a separate solution using the Nuget packages for `GitTools.Core` and `GitVersionCore` (also: there are some unresolved dependencies in the [betas of GitVersionCore](https://www.nuget.org/packages/GitVersionCore/4.0.1-beta1-58) ...).

Once I import the code into another project, I start getting the error below. I find this extremely odd, as I'm unable to locate the part in GitVersion where this specific constructor is called.. I can't even find the constructor in the YamlDotNet project.

I removed parts of my other project, and suddenly the code worked.. Then, while reproducing this working setup, it didn't work again ... This smells a lot like a set of libraries have to be in just the right versions, and somehow that's being done .. sometimes ... 

Are there any ideas, packages I can locate (f.ex. a `4.x` version of `GitTools.Core`, which is currently at most `1.3.1`)... ?

```
Unhandled Exception: System.MissingMethodException: Method not found: 'Void YamlDotNet.Serialization.Deserializer..ctor(YamlDotNet.Serialization.IObjectFactory, YamlDotNet.Serialization.INamingConvention, Boolean, YamlDotNet.Serialization.YamlAttributeOverrides)'.
   at GitVersion.LegacyConfigNotifier.Notify(StringReader reader)
   at GitVersion.ConfigurationProvider.ReadConfig(String workingDirectory, IFileSystem fileSystem)
   at GitVersion.ConfigurationProvider.Provide(String workingDirectory, IFileSystem fileSystem, Boolean applyDefaults, Config overrideConfig)
   at GitVersion.ExecuteCore.ExecuteInternal(String targetBranch, String commitId, GitPreparer gitPreparer, IBuildServer buildServer, Config overrideConfig)
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache)
 ...
```

**Comment by arturcic** [comment]
Can you try using the latest version of GitVersionCore as there is no more a dependency on GitTools.Core

**Comment by LordMike** [comment]
`GitVersionCore` version `5.0.0-beta2-4` seems to work as intended. My previous test program just spat out the JSON I wanted (what I get from the Tools project). Great! 👍
