### ISSUE TITLE
Not working for branches other than default branch (develop)

### ISSUE THREAD

**Issue by dudedev** [GitTools/GitVersion#1715]
I am using **gittools/gitversion:5.0.0-linux-debian-9-netcoreapp2.2** to version my **angular** project on **GitLab**. It is able to version the commits only on the default branch. If I push to any other branch, it is unable to version those.

Below is the snippet of the error log.
   ```
INFO [06/25/19 9:24:03:19] Begin: Getting branches containing the commit '089ce576dc2ef7f96794a36b1ddc46a93dc21a87'.
      INFO [06/25/19 9:24:03:19] Trying to find direct branches.
      INFO [06/25/19 9:24:03:19] No direct branches found, searching through tracked branches.
    INFO [06/25/19 9:24:03:19] End: Getting branches containing the commit '089ce576dc2ef7f96794a36b1ddc46a93dc21a87'. (Took: 0.14ms)
    INFO [06/25/19 9:24:03:19] Found possible parent branches: 
  INFO [06/25/19 9:24:03:19] End: Attempting to inherit branch configuration from parent branch (Took: 25.57ms)
  ERROR [06/25/19 9:24:03:22] An unexpected error occurred:
System.InvalidOperationException: Could not find a 'develop' or 'master' branch, neither locally nor remotely.
   at GitVersion.BranchConfigurationCalculator.InheritBranchConfiguration(GitVersionContext context, Branch targetBranch, BranchConfig branchConfiguration, IList`1 excludedInheritBranches)
   at GitVersion.BranchConfigurationCalculator.GetBranchConfiguration(GitVersionContext context, Branch targetBranch, IList`1 excludedInheritBranches) in /home/vsts/work/1/s/src/GitVersionCore/BranchConfigurationCalculator.cs:line 32
   at GitVersion.GitVersionContext.CalculateEffectiveConfiguration() in /home/vsts/work/1/s/src/GitVersionCore/GitVersionContext.cs:line 86
   at GitVersion.GitVersionContext..ctor(IRepository repository, Branch currentBranch, Config configuration, Boolean onlyEvaluateTrackedBranches, String commitId) in /home/vsts/work/1/s/src/GitVersionCore/GitVersionContext.cs:line 59
   at GitVersion.ExecuteCore.<>c__DisplayClass6_0.<ExecuteInternal>b__0(IRepository repo) in /home/vsts/work/1/s/src/GitVersionCore/ExecuteCore.cs:line 111
   at GitVersion.GitPreparer.WithRepository[TResult](Func`2 action) in /home/vsts/work/1/s/src/GitVersionCore/GitPreparer.cs:line 102
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache) in /home/vsts/work/1/s/src/GitVersionCore/ExecuteCore.cs:line 55
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem) in /home/vsts/work/1/s/src/GitVersionExe/SpecifiedArgumentRunner.cs:line 28
   at GitVersion.Program.VerifyArgumentsAndRun() in /home/vsts/work/1/s/src/GitVersionExe/Program.cs:line 113
  INFO [06/25/19 9:24:03:22] 
  INFO [06/25/19 9:24:03:22] Attempting to show the current git graph (please include in issue): 
  INFO [06/25/19 9:24:03:22] Showing max of 100 commits
```
It complains that it does not find any direct branch neither 'develop' nor 'master'. What could be the issue?

**Comment by asbjornu** [comment]
We might have a regression here where GitVersion expects `develop` and `master` to exist as a local branch and not just as a remote (named `origin/develop` and `origin/master`). To fix this, ensure that you have an unshallow clone and that you have a local branch called `master`:

```bash
git fetch --unshallow
git branch master origin/master
```

Please let me know if that helps.

**Comment by asbjornu** [comment]
Just FYI, on Travis, I had to do the following massage of the cloned repository in order to get GitVersion to work:

```bash
git fetch --unshallow || true # Travis might do a shallow clone, but GitVersion needs the full history including branches and tags
git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git fetch origin
git branch master origin/master || true # GitVersion seems to require a local "master" branch these days. That's a bug, but oh well.
if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then git checkout -b "$TRAVIS_PULL_REQUEST_BRANCH-pr"; fi # Create an explicit branch on pull requests as I'm unable to pass Git_Branch into the Docker container
```

**Comment by dudedev** [comment]
I changed the "shallow clone" property of my project on GitLab. It works. Thanks.

**Comment by asbjornu** [comment]
I’m glad that helped, @dudedev!

**Comment by arturcic** [comment]
@asbjornu can you have a look on gitter? sent you a message
