### ISSUE TITLE
Sequence contains more than one matching element

### ISSUE THREAD

**Issue by wooderz** [GitTools/GitVersion#1735]
On AppVeyor, new build, on master branch. I receive the following errors:

INFO [07/04/19 11:19:50:58] Begin: Loading version variables from disk cache
    INFO [07/04/19 11:19:50:58] Cache file /home/appveyor/projects/service-resolution/.git/gitversion_cache/02529924CC6772A35EEC8B94196C5B56AD3B3F35.yml not found.
  INFO [07/04/19 11:19:50:58] End: Loading version variables from disk cache (Took: 1.43ms)
  INFO [07/04/19 11:19:50:58] IsDynamicGitRepository: False
  INFO [07/04/19 11:19:50:58] Returning Project Root from DotGitDirectory: /home/appveyor/projects/service-resolution/.git - /home/appveyor/projects/service-resolution
  ERROR [07/04/19 11:19:50:80] An unexpected error occurred:
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at GitVersion.GitVersionContext.GetTargetBranch(IRepository repository, String targetBranch) in D:\a\1\s\src\GitVersionCore\GitVersionContext.cs:line 169
   at GitVersion.ExecuteCore.<>c__DisplayClass6_0.<ExecuteInternal>b__0(IRepository repo) in D:\a\1\s\src\GitVersionCore\ExecuteCore.cs:line 110
   at GitVersion.GitPreparer.WithRepository[TResult](Func`2 action) in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 102
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache) in D:\a\1\s\src\GitVersionCore\ExecuteCore.cs:line 55
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem) in D:\a\1\s\src\GitVersionExe\SpecifiedArgumentRunner.cs:line 28
   at GitVersion.Program.VerifyArgumentsAndRun() in D:\a\1\s\src\GitVersionExe\Program.cs:line 113
  INFO [07/04/19 11:19:50:80] 
  INFO [07/04/19 11:19:50:80] Attempting to show the current git graph (please include in issue): 
  INFO [07/04/19 11:19:50:80] Showing max of 100 commits
Command exited with code 1
Build failed

This then borks my build. Any ideas what I'm getting wrong?

**Comment by wooderz** [comment]
Tried again using the Ubuntu image and the dotnet tool

`dotnet tool install --global GitVersion.Tool --version 5.0.0-beta5.6`

Same error:
```
  INFO [07/05/19 10:20:41:92] Begin: Loading version variables from disk cache
    INFO [07/05/19 10:20:41:93] Cache file /home/appveyor/projects/service-resolution/.git/gitversion_cache/71F356B287A5EFECB165A98F56D5D5086AC02403.yml not found.
  INFO [07/05/19 10:20:41:93] End: Loading version variables from disk cache (Took: 1.18ms)
  INFO [07/05/19 10:20:41:93] IsDynamicGitRepository: False
  INFO [07/05/19 10:20:41:93] Returning Project Root from DotGitDirectory: /home/appveyor/projects/service-resolution/.git - /home/appveyor/projects/service-resolution
  ERROR [07/05/19 10:20:42:15] An unexpected error occurred:
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at GitVersion.GitVersionContext.GetTargetBranch(IRepository repository, String targetBranch) in D:\a\1\s\src\GitVersionCore\GitVersionContext.cs:line 169
   at GitVersion.ExecuteCore.<>c__DisplayClass7_0.<ExecuteInternal>b__0(IRepository repo) in D:\a\1\s\src\GitVersionCore\ExecuteCore.cs:line 110
   at GitVersion.GitPreparer.WithRepository[TResult](Func`2 action) in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 102
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache) in D:\a\1\s\src\GitVersionCore\ExecuteCore.cs:line 55
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem) in D:\a\1\s\src\GitVersionExe\SpecifiedArgumentRunner.cs:line 28
   at GitVersion.Program.VerifyArgumentsAndRun() in D:\a\1\s\src\GitVersionExe\Program.cs:line 113
  INFO [07/05/19 10:20:42:15] 
  INFO [07/05/19 10:20:42:15] Attempting to show the current git graph (please include in issue): 
  INFO [07/05/19 10:20:42:15] Showing max of 100 commits
Command exited with code 1
Build failed
```

**Comment by wooderz** [comment]
If I make AppVeyor use a windows image and use chocolatey to install, it seems to work
