### ISSUE TITLE
LibGit2Sharp.CommitLog.QueryBy has null argument

### ISSUE THREAD

**Issue by ramondeklein** [GitTools/GitVersion#1753]
I'm using the latest v5 beta version which runs fine on my local machine, but on our build server it generates the following stacktrace:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: filter.IncludeReachableFrom
   at LibGit2Sharp.CommitLog.QueryBy(CommitFilter filter)
   at GitVersion.VersionCalculation.FallbackBaseVersionStrategy.GetVersions(GitVersionContext context)+MoveNext() in D:\a\1\s\src\GitVersionCore\VersionCalculation\FallbackBaseVersionStrategy.cs:line 22
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersion(GitVersionContext context)
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion(GitVersionContext context) in D:\a\1\s\src\GitVersionCore\VersionCalculation\NextVersionCalculator.cs:line 42
   at GitVersion.GitVersionFinder.FindVersion(GitVersionContext context) in D:\a\1\s\src\GitVersionCore\GitVersionFinder.cs:line 27
   at GitVersion.ExecuteCore.<>c__DisplayClass7_0.<ExecuteInternal>b__0(IRepository repo) in D:\a\1\s\src\GitVersionCore\ExecuteCore.cs:line 111
   at GitVersion.GitPreparer.WithRepository[TResult](Func`2 action) in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 102
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache) in D:\a\1\s\src\GitVersionCore\ExecuteCore.cs:line 55
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem) in D:\a\1\s\src\GitVersionExe\SpecifiedArgumentRunner.cs:line 28
   at GitVersion.Program.VerifyArgumentsAndRun() in D:\a\1\s\src\GitVersionExe\Program.cs:line 113
```
It seems there is a difference between how TeamCity clones the GIT repository and when I clone it by hand (ordinary `git clone repo`). On the build-server GitVersion work fine on my manually cloned repository, but it doesn't work on the TeamCity cloned version.

I have noticed two significant differences with my GIT repos:

- The TeamCity repo contains `sparseCheckout = true`. It also has a file `.git/info/sparse-checkout` containing the text `/*' (so I guess it checks out everything). I have ran `git config sparseCheckout false`, but it doesn't help.
- The TeamCIty repo contains an `[lfs]` section that is moved outside this directory. I don't use any large files.

I also ran ``git fetch --unshallow``, but GIT reports that it makes no sense, because it's a complete repository. Unfortunately, I cannot test with older versions of GitVersion because I can't get these to run on Linux. GIT repositories, checkout by TeamCity, on Windows with GitVersion v4 have no issues.

**Comment by ramondeklein** [comment]
It seems that `CurrentBranch.Tip` from the `GitVersionContext` is set to `null`. For some reason GIT cannot determine the current branch. When I run `git branch` it shows the develop branch (selected) and master branch. Also `git log` shows all the required commits.

**Comment by ramondeklein** [comment]
I have clone `GitVersion` myself and ran it on the failing repository. It fails because TeamCity uses [GIT alternates](https://stackoverflow.com/a/36123844/956435), when GIT mirroring is used (enabled by default). The [documentation](https://www.jetbrains.com/help/teamcity/git.html#dda649c4) states the following:

> When enabled (default), TeamCity clones the repository under the agent's system\git directory and uses the mirror as an alternate repository when updating the checkout directory for the build. As a result, this speeds-up clean checkout (because only the working directory is cleaned), and saves disk space (as there is only one clone of the given Git repository on an agent).

When GitVersion is running inside its own container, only the check-out directory will be mapped. The system directory isn't, so GIT cannot find the actual repository and fails. The easiest solution is to disable GIT mirroring or making sure the location of the actual repository is also mapped inside the container.

GIT alternates is a supported scenario, but when GitVersion is run inside a container, then it would be great to have a proper error that it cannot find the actual source repository.
