### ISSUE TITLE
"GitVersion has a bug, your HEAD has moved after repo normalisation." reported

### ISSUE THREAD

**Issue by ramondeklein** [GitTools/GitVersion#1754]
When I run GitVersion I receive the following error log:
```
[17:29:19]  INFO [07/22/19 15:23:28:67] End: Normalizing git directory for branch 'develop' (Took: 162.47ms)
[17:29:19]  INFO [07/22/19 15:23:28:67] End: Creating dynamic repository at '/tmp/xpac-framework' (Took: 620.96ms)
[17:29:19]  ERROR [07/22/19 15:23:28:69] An unexpected error occurred:
[17:29:19]GitVersion.BugException: GitVersion has a bug, your HEAD has moved after repo normalisation.
[17:29:19]
[17:29:19]To disable this error set an environmental variable called IGNORE_NORMALISATION_GIT_HEAD_MOVE to 1
[17:29:19]
[17:29:19]Please run `git log --graph --format="%h %cr %d" --decorate --date=relative --all --remotes=* -n 100` and submit it along with your build log (with personal info removed) in a new issue at https://github.com/GitTools/GitVersion
[17:29:19]   at GitVersion.GitRepositoryHelper.NormalizeGitDirectory(String gitDirectory, AuthenticationInfo authentication, Boolean noFetch, String currentBranch)
[17:29:19]   at GitVersion.GitPreparer.CreateDynamicRepository(String targetPath, AuthenticationInfo authentication, String repositoryUrl, String targetBranch, Boolean noFetch) in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 204
[17:29:19]   at GitVersion.GitPreparer.Initialise(Boolean normaliseGitDirectory, String currentBranch, Boolean shouldCleanUpRemotes) in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 71
[17:29:19]   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache) in D:\a\1\s\src\GitVersionCore\ExecuteCore.cs:line 30
[17:29:19]   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem) in D:\a\1\s\src\GitVersionExe\SpecifiedArgumentRunner.cs:line 28
[17:29:19]   at GitVersion.Program.VerifyArgumentsAndRun() in D:\a\1\s\src\GitVersionExe\Program.cs:line 113
[17:29:19]  INFO [07/22/19 15:23:28:69] 
[17:29:19]  INFO [07/22/19 15:23:28:69] Attempting to show the current git graph (please include in issue): 
[17:29:19]  INFO [07/22/19 15:23:28:69] Showing max of 100 commits
```
The output of `git log` looks like this:
```
* 89edfad 6 hours ago  (HEAD -> develop, origin/develop)
* 3ed243d 8 hours ago  (origin/master, master)
* a92d065 6 days ago 
* 20b318f 6 days ago 
* 53d179f 6 days ago 
* abfbdca 7 days ago 
* dc285c9 7 days ago 
* 2d06335 7 days ago 
* 8716e2f 7 days ago 
| * 9eae176 3 weeks ago  (origin/feature/Integrate_generated_general_message_group)
| * b3889d5 3 weeks ago 
| * e8cfdff 3 weeks ago 
|/  
* e961115 3 weeks ago 
* 736ca2d 4 weeks ago 
* 447a75a 7 weeks ago 
* 54b6ad0 7 weeks ago 
* 1306f89 7 weeks ago 
* b8b28cf 7 weeks ago 
* c46e322 7 weeks ago 
* 5a429d5 7 weeks ago 
* dde8684 7 weeks ago 
* d6fd7d9 7 weeks ago 
* 7309f79 7 weeks ago 
| * 57bceab 4 weeks ago  (origin/stone, stone)
| * e6f7964 4 weeks ago 
| * 9b2a5bc 4 weeks ago 
| * 6daf9eb 6 weeks ago 
| * e58e143 6 weeks ago 
| * 61215c3 6 weeks ago 
| * 86486ab 6 weeks ago 
| * be3e7f1 7 weeks ago 
| * 7accc2a 7 weeks ago 
|/  
* de3edb0 7 weeks ago 
* b46b8f1 7 weeks ago 
* 3151260 7 weeks ago 
* 3f3f10c 2 months ago 
* b42f7db 3 months ago 
* cccd161 3 months ago 
* 5f8ee0e 3 months ago 
* f8af077 3 months ago 
* 9c0b206 3 months ago 
* 49348e9 3 months ago 
* 61f0471 3 months ago 
* b6d1f64 3 months ago 
* 9cb95fb 3 months ago 
* 605841a 3 months ago 
* 121f813 3 months ago 
* 5103234 3 months ago 
* 05bb5b0 3 months ago 
* a19cde5 3 months ago 
* fe912cd 3 months ago 
* 36f9952 3 months ago 
* 2181883 3 months ago 
* 8d7c627 3 months ago 
* fa5c16b 3 months ago 
* f2b7532 3 months ago 
* e5fb650 3 months ago 
* 9e9a285 3 months ago 
* 8cf810d 3 months ago 
* 59fb4c0 3 months ago 
* ebe8e3c 3 months ago 
* 89919bf 3 months ago 
* 9824bc0 3 months ago 
* 7e7c01e 3 months ago 
* f059f66 3 months ago 
* e0b2ff2 3 months ago 
* dc61a74 3 months ago 
* 80e0a6b 3 months ago 
* d49f7e2 4 months ago 
* 6b24fab 4 months ago 
* 92a0171 5 months ago 
* ba231d3 5 months ago 
* 4bb226a 5 months ago 
* 3f2fcd1 5 months ago 
* 31435c2 5 months ago 
* 0cb8716 5 months ago 
* d0f3b38 5 months ago 
* 2dccd43 5 months ago 
* 1f298f5 5 months ago 
* 121ffd8 5 months ago 
* 31eea06 5 months ago 
```
I am trying to run GitVersion on the develop branch. Because of issue #1753 I fetch the repository directly from my GIT server using `/url`, `/b` and `/c`.

**Comment by chasewallis** [comment]
I got the same issue on 5.0.0-beta.5+9.Branch.master.Sha.e284e47ecb5de0cf289bf6cb3b4e93fa31d612de

**Comment by GeertvanHorrik** [comment]
@ramondeklein does this happen on dynamic repositories?

**Comment by GeertvanHorrik** [comment]
So to clear this up (with the Catel repo as an example):

1. Run for the first time with these parameters:

```
/url https://github.com/Catel/Catel.git /b master /c f5de8964c35180a5f8607f5954007d5828aa849f /output buildserver /nocache
```

This checks out the code, but since the *default branch* is *develop*, it will throw this exception because "head has moved" between the default clone and the switch to the correct branch.

2. Whenever this is ran against the default branch (or the local cached dynamic repo has already switched to the branch to check against, this error does not occur because it doesn't have to switch branches before doing the version checks (so the head doesn't move).

The solution is to re-evaluate the expected sha *after switching to the correct branch* in case this is a dynamic repository (noFetch == false).
