### ISSUE TITLE
Version 4 bugs out on latest VS2017 hosted pool.

### ISSUE THREAD

**Issue by jessehouwing** [GitTools/GitVersion#1757]
All default settings

```
  | Starting: GitVersion |  
  | ============================================================================== |  
  | Task         : GitVersion Task |  
  | Description  : Easy Semantic Versioning (http://semver.org) for projects using Git |  
  | Version      : 4.0.1 |  
  | Author       : GitVersion Contributors |  
  | Help         : See the [documentation](http://gitversion.readthedocs.org/en/latest/) for help |  
  | ============================================================================== |  
  | module.js:471 |  
  | throw err; |  
  | ^ |  
  |   |  
  | Error: Cannot find module 'vsts-task-lib/task' |  
  | at Function.Module._resolveFilename (module.js:469:15) |  
  | at Function.Module._load (module.js:417:25) |  
  | at Module.require (module.js:497:17) |  
  | at require (internal/module.js:20:19) |  
  | at Object.<anonymous> (d:\a\_tasks\GitVersion_e5983830-3f75-11e5-82ed-81492570a08e\4.0.1\GitVersion.js:11:12) |  
  | at Module._compile (module.js:570:32) |  
  | at Object.Module._extensions..js (module.js:579:10) |  
  | at Module.load (module.js:487:32) |  
  | at tryModuleLoad (module.js:446:12) |  
  | at Function.Module._load (module.js:438:3) |  
  | ##[error]Exit code 1 returned from process: file name 'C:\agents\2.154.3\externals\node\bin\node.exe', arguments '"d:\a\_tasks\GitVersion_e5983830-3f75-11e5-82ed-81492570a08e\4.0.1\GitVersion.js"'. |  
  | Finishing: GitVersion
```

**Comment by jessehouwing** [comment]
Probably related: 

marketplace page jumbled up.

![image](https://user-images.githubusercontent.com/4173387/61960140-3e4a8500-afc5-11e9-87db-804e9e8dcd2c.png)

Tried version v5-preview, but that comes up with unexpected version numbers.
