### ISSUE TITLE
[5.0.0] mainline fails when a single commit

### ISSUE THREAD

**Issue by JonCubed** [GitTools/GitVersion#1768]
I've come across this problem quite often for new repos and finally looked into it. When I run GitVersion on a new repo where it uses mainline calculation, GitVersion will crash with an exception

```
 ERROR [08/08/19 6:09:47:47] An unexpected error occurred:
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at GitVersion.VersionCalculation.MainlineVersionCalculator.FindMergeBaseBeforeForwardMerge(GitVersionContext context, Commit baseVersionSource, Branch mainline, Commit& mainlineTip) in D:\a\1\s\src\GitVersionCore\VersionCalculation\MainlineVersionCalculator.cs:line 218   at GitVersion.VersionCalculation.MainlineVersionCalculator.FindMainlineModeVersion(BaseVersion baseVersion, GitVersionContext context) in D:\a\1\s\src\GitVersionCore\VersionCalculation\MainlineVersionCalculator.cs:line 38
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion(GitVersionContext context) in D:\a\1\s\src\GitVersionCore\VersionCalculation\NextVersionCalculator.cs:line 47
   at GitVersion.GitVersionFinder.FindVersion(GitVersionContext context) in D:\a\1\s\src\GitVersionCore\GitVersionFinder.cs:line 24
   at GitVersion.ExecuteCore.<>c__DisplayClass7_0.<ExecuteInternal>b__0(IRepository repo) in D:\a\1\s\src\GitVersionCore\ExecuteCore.cs:line 111
   at GitVersion.GitPreparer.WithRepository[TResult](Func`2 action) in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 93
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache) in D:\a\1\s\src\GitVersionCore\ExecuteCore.cs:line 55
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem) in D:\a\1\s\src\GitVersionExe\SpecifiedArgumentRunner.cs:line 46
   at GitVersion.Program.VerifyArgumentsAndRun() in D:\a\1\s\src\GitVersionExe\Program.cs:line 111
```

I've trace this back to the following if block with ln223 being the culprit. `mergeBase` is the current commit and `mainlineCommitLog` is an empty list but it expects that there are parents commits however it is the first so there are not.

https://github.com/GitTools/GitVersion/blob/11ee72a0a483c61835161afcbe3da0f59182e40a/src/GitVersionCore/VersionCalculation/MainlineVersionCalculator.cs#L220-L231

This can be fixed if the `if` statement is adjusted to the following 

```csharp
if (mergeBase == context.CurrentCommit && !mainlineCommitLog.Contains(mergeBase) && mainlineTip.Parents.Any())
```

I am uncertain if this is an acceptable fix, but if it is I am happy to make a pr for it

**Comment by asbjornu** [comment]
Hi, @JonCubed and sorry for the lack of response leading to your issue being closed by stalebot. We would love a PR that fixes this problem, alongside a `RepositoryFixture` test that ensures the problem is fixed. 👍

**Comment by asbjornu** [comment]
Is this still a problem in 5.2.4?

**Comment by asbjornu** [comment]
#2318 may help alleviate the exception here and give you the fallback strategy.
