### ISSUE TITLE
[5.0.1] ERROR: Property 'merge-message-formats' not found on type 'GitVersion.Config'

### ISSUE THREAD

**Issue by wwuck** [GitTools/GitVersion#1780]
I installed GitVersion.CommandLine 5.0.1 and ran `GitVersion.exe init`, selecting the Continuous Deployment options which resulted in this YAML file:

```yaml
mode: ContinuousDeployment
branches: {}
ignore:
  sha: []
merge-message-formats: {}

```

I then tried to build this project on AppVeyor by using the `GitVersion.exe init` output for appveyor.yml.

```yaml
install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - nuget restore
  - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH

build:
  project: Project.sln

after_build:
  - cmd: ECHO nuget pack Project\Project.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack Project\Project.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Project.%GitVersion_NuGetVersion%.nupkg"
```
AppVeyor installed GitVersion.Portable 5.0.1 from chocolatey.

The build then failed with the following error in the logs:
```
ERROR [08/15/19 3:03:45:18] An unexpected error occurred:
YamlDotNet.Core.YamlException: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): Exception during deserialization ---> System.Runtime.Serialization.SerializationException: Property 'merge-message-formats' not found on type 'GitVersion.Config'.
   at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at GitVersion.ConfigSerialiser.Read(TextReader reader)
   at GitVersion.ConfigurationProvider.Provide(String workingDirectory, IFileSystem fileSystem, Boolean applyDefaults, Config overrideConfig)
   at GitVersion.ExecuteCore.ExecuteInternal(String targetBranch, String commitId, GitPreparer gitPreparer, IBuildServer buildServer, Config overrideConfig)
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache)
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
```

Looking at the commits, I thought `merge-message-formats` was included in the GitVersion 5.0.0 release?

**Comment by asbjornu** [comment]
Yes, #1488 was included in `5.0.0`. @Kieranties, can you explain why this isn't working?

**Comment by Kieranties** [comment]
I've just ran a quick test locally:
```
> mkdir gitversion
> cd .\gitversion\
> choco install gitversion.portable -pre -y
Installing the following packages:
gitversion.portable
By installing you accept licenses for the packages.
Progress: Downloading GitVersion.Portable 5.1.3-beta1-6... 100%

> git init
> GitVersion.exe init
> cat .\GitVersion.yml
mode: ContinuousDelivery
branches: {}
ignore:
  sha: []
merge-message-formats: {}

> git commit -m test --allow-empty
> GitVersion.exe
{
  "Major":0,
  "Minor":1,
  "Patch":0,
  "PreReleaseTag":"",
  "PreReleaseTagWithDash":"",
  "PreReleaseNumber":"",
   //...
}
```

Which would give me the impression that things work on the `5.1.3-beta1-6` version.
I've also tested directly with 5.0.1 as well and get the same.

Looking at the chocoaltey conversation, there is one user having this issue on AppVeyor too: http://disq.us/p/23pbn24

@asbjornu Is there some alternate processing when the configuration is loaded in AppVeyor?
@wwuck If you remove the merge-message-formats from the config, do you still have the same issue?

**Comment by asbjornu** [comment]
I'm not aware of any variance on the handling of the configuration depending on where GitVersion is being executed. To make GitVersion believe it runs under a specific CI, you just need to declare the environment variable GitVersion is looking for. For AppVeyor it's simply called `APPVEYOR`:

https://github.com/GitTools/GitVersion/blob/fd0d71c7704a3ece6c25ed22b519f307c44891ff/src/GitVersionCore/BuildServers/AppVeyor.cs#L14

**Comment by Kieranties** [comment]
After specifying the `APPVEYOR` environment variable and running with `/diag`
```
INFO [11/20/19 12:06:25:08] Running on Windows.
INFO [11/20/19 12:06:25:09] Applicable build agent found: 'AppVeyor'.
INFO [11/20/19 12:06:25:09] Branch from build environment:
INFO [11/20/19 12:06:25:09] Begin: Normalizing git directory for branch ''
...
```
And I still get successful version output 🤷‍♂️

**Comment by asbjornu** [comment]
I don't quite understand what's going on here, tbh.

**Comment by Kieranties** [comment]
Without any input from @wwuck I'm at a loss on what to test - I've not seen this issue reported elsewhere.

**Comment by wwuck** [comment]
Apologies for the delay in getting back to this, but I've tested it again now.  The build downloaded the newer `GitVersion.Portable 5.1.3` and all seemed to run without error this time.

I guess this can be closed if no-one else has the problem still occurring?
