### ISSUE TITLE
Adding to existing monorepo throws

### ISSUE THREAD

**Issue by daniel-white** [GitTools/GitVersion#1806]
I have a large existing mono repo. I'm trying to add `GitVersion.yml` to each of the top level deployments with ignoring commits before today:

```yaml
next-version: 0.14
ignore:
  commits-before: 2019-09-09
  sha: []
```

I'm running into that the 5.0.1 gitversion tool is finding commits and ignoring them (as expected) to calculate the base version.

```
 ERROR [09/09/19 13:03:13:23] An unexpected error occurred:
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersion(GitVersionContext context) in D:\a\1\s\src\GitVersionCore\VersionCalculation\BaseVersionCalculator.cs:line 64
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion(GitVersionContext context) in D:\a\1\s\src\GitVersionCore\VersionCalculation\NextVersionCalculator.cs:line 42
   at GitVersion.GitVersionFinder.FindVersion(GitVersionContext context) in D:\a\1\s\src\GitVersionCore\GitVersionFinder.cs:line 24
   at GitVersion.ExecuteCore.<>c__DisplayClass7_0.<ExecuteInternal>b__0(IRepository repo) in D:\a\1\s\src\GitVersionCore\ExecuteCore.cs:line 111
   at GitVersion.GitPreparer.WithRepository[TResult](Func`2 action) in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 92
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache) in D:\a\1\s\src\GitVersionCore\ExecuteCore.cs:line 55
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem) in D:\a\1\s\src\GitVersionExe\SpecifiedArgumentRunner.cs:line 46
   at GitVersion.Program.VerifyArgumentsAndRun() in D:\a\1\s\src\GitVersionExe\Program.cs:line 111
  INFO [09/09/19 13:03:13:23] 
  INFO [09/09/19 13:03:13:23] Attempting to show the current git graph (please include in issue): 
  INFO [09/09/19 13:03:13:23] Showing max of 100 commits
```

Shouldn't the tool respect `next-version` in this case?

**Comment by asbjornu** [comment]
I agree that `next-version` should shortcut the version calculation. Is `GitVersion.yml` picked up in each of the deployment builds?
