### ISSUE TITLE
GitVersion throws KeyNotFoundException using git branch 'release/IntX.IntY'

### ISSUE THREAD

**Issue by henrikgjeriksson** [GitTools/GitVersion#1815]
Went from:
cakebuild 0.33.0
ReportUnit&version=1.5.0-beta1
GitVersion.CommandLine&version=4.0.1-beta1-58

To:
cakebuild 0.34.1
GitVersion.CommandLine&version=5.0.1
ReportUnit&version=1.2.1

In "to" state, `release/X.Y` branches  makes gitVersion throw exception according

```
2019-09-18 15:26:00		    INFO [09/18/19 15:26:00:61] Begin: Finding branch source of 'release/6.1'
2019-09-18 15:26:00		    INFO [09/18/19 15:26:00:64] End: Finding branch source of 'release/6.1' (Took: 37.90ms)
2019-09-18 15:26:00		  INFO [09/18/19 15:26:00:65] End: Calculating base versions (Took: 3,925.10ms)
2019-09-18 15:26:00		  ERROR [09/18/19 15:26:00:68] An unexpected error occurred:
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at GitVersion.GitRepoMetadataProvider.<>c__DisplayClass15_0.<GetMergeCommitsForBranch>b__0(String sb)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitVersion.GitRepoMetadataProvider.GetMergeCommitsForBranch(Branch branch, Branch[] excludedBranches)
   at GitVersion.GitRepoMetadataProvider.FindCommitBranchWasBranchedFrom(Branch branch, Branch[] excludedBranches)
   at GitVersion.VersionCalculation.BaseVersionCalculators.VersionInBranchNameBaseVersionStrategy.<GetVersions>d__1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersion(GitVersionContext context)
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion(GitVersionContext context)
   at GitVersion.GitVersionFinder.FindVersion(GitVersionContext context)
   at GitVersion.ExecuteCore.<>c__DisplayClass7_0.<ExecuteInternal>b__0(IRepository repo)
   at GitVersion.GitPreparer.WithRepository[TResult](Func`2 action)
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache)
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
2019-09-18 15:26:00		  INFO [09/18/19 15:26:00:68] 
2019-09-18 15:26:00		  INFO [09/18/19 15:26:00:68] Attempting to show the current git graph (please include in issue): 
2019-09-18 15:26:00		  INFO [09/18/19 15:26:00:69] Showing max of 100 commits
2019-09-18 15:26:01		  INFO [09/18/19 15:26:01:06] * dcbcfda08 2 days ago  (origin/feature/PD-7900-version-management-for-ebmcontrol, feature/PD-7900-version-management-for-ebmcontrol)
* ea7121133 2 days ago  (HEAD -> release/6.1, tag: v6.1.65, origin/development_x64, origin/bugfix/EC-5682-log-write-out-the-full-power-density-curve-for-p1d-part-of-the-heat-equation, origin/HEAD, development_x64)
* 7fd56c756 2 days ago  (tag: v6.1.64)
| * 482bc34dc 2 days ago  (origin/feature/...)
| | * e557dfb07 2 days ago  (origin/feature/PD-8988-upgrade-to-vs2019-build-tools-and-build-scripts_backport5.5)
| | | * 7be86b13e 2 days ago  (origin/feature/PD-8988-upgrade-to-vs2019-build-tools-and-build-scripts_backport6.0)
| | | * f30b03f80 2 days ago  (tag: 6.0.4, origin/release/6.0)
| | | * 6dee3cf4b 5 days ago 
| | | * fd8e52343 5 days ago 

```

Using another branch name makes it works fine.
releases(s) is identified in the GitVersion.yml as
```
branches:
  release:
    regex: release(s)?[/-]
    mode: ContinuousDeployment
    tag: useBranchName
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: true
    source-branches: ['development_x64']
```

**Comment by henrikgjeriksson** [comment]
Has the "...KeyNotFoundException" a correlation with the branch settings mentioned above?
Perhaps there is a change in the attribute settings in newer gitversion

**Comment by henrikgjeriksson** [comment]
We noticed that setting
'is-release-branch' to false, then the exception is no longer thrown.

What can the root cause be? Is there any new issue related to this in latest version of gitVersion?

**Comment by henrikgjeriksson** [comment]
Note, we are note using GitFlow.
The documentation states that "is-release-branch" feature is for GitFlow!?
https://gitversion.readthedocs.io/en/latest/configuration/

**Comment by asbjornu** [comment]
Are you able to reproduce the `KeyNotFoundException` in a `RepositoryFixture` test? If so, it would be a good way to figure out what's going on within GitVersion's internals here.

**Comment by henrikgjeriksson** [comment]
What information would we gain from this?
I never experienced using 

> RepositoryFixture
So I'm not sure how to proceed in this  case

**Comment by asbjornu** [comment]
Please have a look at the following test to get an idea of how you can write yours:

https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore.Tests/IntegrationTests/MasterScenarios.cs#L58-L71
