### ISSUE TITLE
AppVeyor configuration errors exception

### ISSUE THREAD

**Issue by dazinator** [GitTools/GitVersion#1869]
I'm building using AppVeyor and using 5.0.1 and seeing the same error that someone else has reported here: https://help.appveyor.com/discussions/problems/24758-gitversion-5-not-working-on-visual-studio-2019-build

Here is my build output:

```
Build started
git clone -q --branch=develop https://github.com/dazinator/Dazinator.Extensions.WritableOptions.git C:\projects\dazinator-extensions-writableoptions
git checkout -qf 5f9d1c5b8d539974635c9af39ad845db7124d61b
Running Install scripts
choco install gitversion.portable --version 5.0.1 -y
Chocolatey v0.10.15
Installing the following packages:
gitversion.portable
By installing you accept licenses for the packages.
Progress: Downloading GitVersion.Portable 5.0.1... 100%
GitVersion.Portable v5.0.1 [Approved]
gitversion.portable package files install completed. Performing other installation steps.
Added C:\ProgramData\chocolatey\bin\gv.exe shim pointed to '..\lib\gitversion.portable\tools\gitversion.exe'.
 ShimGen has successfully created a shim for GitVersion.exe
 The install of gitversion.portable was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.
Chocolatey installed 1/1 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Enjoy using Chocolatey? Explore more amazing features to take your
experience to the next level at
 https://chocolatey.org/compare
gitversion /l console /output buildserver
INFO [10/25/19 12:39:31:03] Working directory: C:\projects\dazinator-extensions-writableoptions
INFO [10/25/19 12:39:31:03] IsDynamicGitRepository: False
INFO [10/25/19 12:39:31:06] Returning Project Root from DotGitDirectory: C:\projects\dazinator-extensions-writableoptions\.git - C:\projects\dazinator-extensions-writableoptions
INFO [10/25/19 12:39:31:06] Running on Windows.
INFO [10/25/19 12:39:31:06] Applicable build agent found: 'AppVeyor'.
INFO [10/25/19 12:39:31:07] Branch from build environment: 
INFO [10/25/19 12:39:31:07] Begin: Normalizing git directory for branch ''
  INFO [10/25/19 12:39:31:14] One remote found (origin -> 'https://github.com/dazinator/Dazinator.Extensions.WritableOptions.git').
  INFO [10/25/19 12:39:31:15] Fetching from remote 'origin' using the following refspecs: +refs/heads/*:refs/remotes/origin/*.
  INFO [10/25/19 12:39:31:41] Skipping update of 'refs/remotes/origin/develop' as it already matches the remote ref.
  INFO [10/25/19 12:39:31:41] Creating local branch from remote tracking 'refs/remotes/origin/master'.
  INFO [10/25/19 12:39:31:44] HEAD is detached and points at commit '5f9d1c5b8d539974635c9af39ad845db7124d61b'.
  INFO [10/25/19 12:39:31:44] Local Refs:
refs/heads/develop (5f9d1c5b8d539974635c9af39ad845db7124d61b)
refs/heads/master (b5843eb1ec4c7c87a91d14c61ab2bbd2d5cd2fdb)
refs/remotes/origin/HEAD (refs/remotes/origin/master)
refs/remotes/origin/develop (5f9d1c5b8d539974635c9af39ad845db7124d61b)
refs/remotes/origin/master (b5843eb1ec4c7c87a91d14c61ab2bbd2d5cd2fdb)
refs/tags/2.0.0 (b47c86398c7e1e67e1ea7d439fbbdc1bb2281a7e)
  INFO [10/25/19 12:39:31:44] Checking out local branch 'refs/heads/develop'.
  INFO [10/25/19 12:39:31:47] End: Normalizing git directory for branch '' (Took: 393.37ms)
  INFO [10/25/19 12:39:31:47] IsDynamicGitRepository: False
  INFO [10/25/19 12:39:31:47] Returning Project Root from DotGitDirectory: C:\projects\dazinator-extensions-writableoptions\.git - C:\projects\dazinator-extensions-writableoptions
  INFO [10/25/19 12:39:31:47] Project root is: C:\projects\dazinator-extensions-writableoptions
  INFO [10/25/19 12:39:31:47] DotGit directory is: C:\projects\dazinator-extensions-writableoptions\.git
  INFO [10/25/19 12:39:31:47] IsDynamicGitRepository: False
  INFO [10/25/19 12:39:31:47] Returning Project Root from DotGitDirectory: C:\projects\dazinator-extensions-writableoptions\.git - C:\projects\dazinator-extensions-writableoptions
  INFO [10/25/19 12:39:31:48] Begin: Loading version variables from disk cache
    INFO [10/25/19 12:39:31:48] Cache file C:\projects\dazinator-extensions-writableoptions\.git\gitversion_cache\5B9FA80B8E40D3FFE71FFDE243A389D33D092D18.yml not found.
  INFO [10/25/19 12:39:31:48] End: Loading version variables from disk cache (Took: 0.00ms)
  INFO [10/25/19 12:39:31:51] IsDynamicGitRepository: False
  INFO [10/25/19 12:39:31:51] Returning Project Root from DotGitDirectory: C:\projects\dazinator-extensions-writableoptions\.git - C:\projects\dazinator-extensions-writableoptions
  INFO [10/25/19 12:39:31:75] Using latest commit on specified branch
  INFO [10/25/19 12:39:31:75] Running against branch: develop (5f9d1c5b8d539974635c9af39ad845db7124d61b)
  INFO [10/25/19 12:39:31:77] Begin: Calculating base versions
    INFO [10/25/19 12:39:31:80] Fallback base version: 0.1.0 with commit count source 0c71b65a1daa25d5207046407524e3f78610df7b (Incremented: None)
    INFO [10/25/19 12:39:31:87] Git tag '2.0.0': 2.0.0 with commit count source b47c86398c7e1e67e1ea7d439fbbdc1bb2281a7e (Incremented: 2.1.0)
    INFO [10/25/19 12:39:31:92] Found multiple base versions which will produce the same SemVer (2.1.0), taking oldest source for commit counting (Git tag '2.0.0')
    INFO [10/25/19 12:39:31:94] Base version used: Git tag '2.0.0': 2.0.0 with commit count source b47c86398c7e1e67e1ea7d439fbbdc1bb2281a7e (Incremented: 2.1.0)
  INFO [10/25/19 12:39:31:94] End: Calculating base versions (Took: 171.85ms)
  INFO [10/25/19 12:39:31:94] 5 commits found between b47c86398c7e1e67e1ea7d439fbbdc1bb2281a7e and 5f9d1c5b8d539974635c9af39ad845db7124d61b
  INFO [10/25/19 12:39:31:95] Begin: Getting version tags from branch 'refs/heads/develop'.
  INFO [10/25/19 12:39:31:95] End: Getting version tags from branch 'refs/heads/develop'. (Took: 0.00ms)
  INFO [10/25/19 12:39:31:97] Begin: Creating dictionary
  INFO [10/25/19 12:39:31:97] End: Creating dictionary (Took: 0.00ms)
  INFO [10/25/19 12:39:31:98] Begin: Storing version variables to cache file C:\projects\dazinator-extensions-writableoptions\.git\gitversion_cache\5B9FA80B8E40D3FFE71FFDE243A389D33D092D18.yml
  INFO [10/25/19 12:39:32:05] End: Storing version variables to cache file C:\projects\dazinator-extensions-writableoptions\.git\gitversion_cache\5B9FA80B8E40D3FFE71FFDE243A389D33D092D18.yml (Took: 62.51ms)
  INFO [10/25/19 12:39:32:05] Applicable build agent found: 'AppVeyor'.
Executing GenerateSetVersionMessage for 'AppVeyor'.
  ERROR [10/25/19 12:39:32:17] An unexpected error occurred:
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section dllmap. (C:\ProgramData\chocolatey\lib\GitVersion.Portable\tools\GitVersion.exe.Config line 6)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
   at System.Diagnostics.DiagnosticsConfiguration.GetConfigSection()
   at System.Diagnostics.DiagnosticsConfiguration.Initialize()
   at System.Diagnostics.DiagnosticsConfiguration.get_Sources()
   at System.Diagnostics.TraceSource.Initialize()
   at System.Net.Logging.InitializeLogging()
   at System.Net.Logging.get_On()
   at System.Net.WebRequest.Create(Uri requestUri, Boolean useUriBase)
   at GitVersion.AppVeyor.GenerateSetVersionMessage(VersionVariables variables)
   at GitVersion.BuildServerBase.WriteIntegration(Action`1 writer, VersionVariables variables)
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
  INFO [10/25/19 12:39:32:17] 
  INFO [10/25/19 12:39:32:17] Attempting to show the current git graph (please include in issue): 
  INFO [10/25/19 12:39:32:17] Showing max of 100 commits
  INFO [10/25/19 12:39:32:24] * 5f9d1c5 3 minutes ago  (HEAD -> develop, origin/develop)
* 8846231 4 minutes ago 
* bd71cd6 8 minutes ago 
* 86664e5 21 minutes ago 
*   594c88a 26 minutes ago 
|\  
| * b47c863 27 minutes ago  (tag: 2.0.0)
| * 9ec9a82 23 hours ago 
| * bfd9516 35 hours ago 
|/  
* b5843eb 3 months ago  (origin/master, origin/HEAD, master)
* f6d32af 3 months ago 
* 62b9ea0 3 months ago 
* 29cabd5 3 months ago 
* 9cef1c4 3 months ago 
* f53966c 3 months ago 
* 0c71b65 3 months ago 
INFO [10/25/19 12:39:31:03] Working directory: C:\projects\dazinator-extensions-writableoptions
INFO [10/25/19 12:39:31:03] IsDynamicGitRepository: False
INFO [10/25/19 12:39:31:06] Returning Project Root from DotGitDirectory: C:\projects\dazinator-extensions-writableoptions\.git - C:\projects\dazinator-extensions-writableoptions
INFO [10/25/19 12:39:31:06] Running on Windows.
INFO [10/25/19 12:39:31:06] Applicable build agent found: 'AppVeyor'.
INFO [10/25/19 12:39:31:07] Branch from build environment: 
INFO [10/25/19 12:39:31:07] Begin: Normalizing git directory for branch ''
  INFO [10/25/19 12:39:31:14] One remote found (origin -> 'https://github.com/dazinator/Dazinator.Extensions.WritableOptions.git').
  INFO [10/25/19 12:39:31:15] Fetching from remote 'origin' using the following refspecs: +refs/heads/*:refs/remotes/origin/*.
  INFO [10/25/19 12:39:31:41] Skipping update of 'refs/remotes/origin/develop' as it already matches the remote ref.
  INFO [10/25/19 12:39:31:41] Creating local branch from remote tracking 'refs/remotes/origin/master'.
  INFO [10/25/19 12:39:31:44] HEAD is detached and points at commit '5f9d1c5b8d539974635c9af39ad845db7124d61b'.
  INFO [10/25/19 12:39:31:44] Local Refs:
refs/heads/develop (5f9d1c5b8d539974635c9af39ad845db7124d61b)
refs/heads/master (b5843eb1ec4c7c87a91d14c61ab2bbd2d5cd2fdb)
refs/remotes/origin/HEAD (refs/remotes/origin/master)
refs/remotes/origin/develop (5f9d1c5b8d539974635c9af39ad845db7124d61b)
refs/remotes/origin/master (b5843eb1ec4c7c87a91d14c61ab2bbd2d5cd2fdb)
refs/tags/2.0.0 (b47c86398c7e1e67e1ea7d439fbbdc1bb2281a7e)
  INFO [10/25/19 12:39:31:44] Checking out local branch 'refs/heads/develop'.
  INFO [10/25/19 12:39:31:47] End: Normalizing git directory for branch '' (Took: 393.37ms)
  INFO [10/25/19 12:39:31:47] IsDynamicGitRepository: False
  INFO [10/25/19 12:39:31:47] Returning Project Root from DotGitDirectory: C:\projects\dazinator-extensions-writableoptions\.git - C:\projects\dazinator-extensions-writableoptions
  INFO [10/25/19 12:39:31:47] Project root is: C:\projects\dazinator-extensions-writableoptions
  INFO [10/25/19 12:39:31:47] DotGit directory is: C:\projects\dazinator-extensions-writableoptions\.git
  INFO [10/25/19 12:39:31:47] IsDynamicGitRepository: False
  INFO [10/25/19 12:39:31:47] Returning Project Root from DotGitDirectory: C:\projects\dazinator-extensions-writableoptions\.git - C:\projects\dazinator-extensions-writableoptions
  INFO [10/25/19 12:39:31:48] Begin: Loading version variables from disk cache
    INFO [10/25/19 12:39:31:48] Cache file C:\projects\dazinator-extensions-writableoptions\.git\gitversion_cache\5B9FA80B8E40D3FFE71FFDE243A389D33D092D18.yml not found.
  INFO [10/25/19 12:39:31:48] End: Loading version variables from disk cache (Took: 0.00ms)
  INFO [10/25/19 12:39:31:51] IsDynamicGitRepository: False
  INFO [10/25/19 12:39:31:51] Returning Project Root from DotGitDirectory: C:\projects\dazinator-extensions-writableoptions\.git - C:\projects\dazinator-extensions-writableoptions
  INFO [10/25/19 12:39:31:75] Using latest commit on specified branch
  INFO [10/25/19 12:39:31:75] Running against branch: develop (5f9d1c5b8d539974635c9af39ad845db7124d61b)
  INFO [10/25/19 12:39:31:77] Begin: Calculating base versions
    INFO [10/25/19 12:39:31:80] Fallback base version: 0.1.0 with commit count source 0c71b65a1daa25d5207046407524e3f78610df7b (Incremented: None)
    INFO [10/25/19 12:39:31:87] Git tag '2.0.0': 2.0.0 with commit count source b47c86398c7e1e67e1ea7d439fbbdc1bb2281a7e (Incremented: 2.1.0)
    INFO [10/25/19 12:39:31:92] Found multiple base versions which will produce the same SemVer (2.1.0), taking oldest source for commit counting (Git tag '2.0.0')
    INFO [10/25/19 12:39:31:94] Base version used: Git tag '2.0.0': 2.0.0 with commit count source b47c86398c7e1e67e1ea7d439fbbdc1bb2281a7e (Incremented: 2.1.0)
  INFO [10/25/19 12:39:31:94] End: Calculating base versions (Took: 171.85ms)
  INFO [10/25/19 12:39:31:94] 5 commits found between b47c86398c7e1e67e1ea7d439fbbdc1bb2281a7e and 5f9d1c5b8d539974635c9af39ad845db7124d61b
  INFO [10/25/19 12:39:31:95] Begin: Getting version tags from branch 'refs/heads/develop'.
  INFO [10/25/19 12:39:31:95] End: Getting version tags from branch 'refs/heads/develop'. (Took: 0.00ms)
  INFO [10/25/19 12:39:31:97] Begin: Creating dictionary
  INFO [10/25/19 12:39:31:97] End: Creating dictionary (Took: 0.00ms)
  INFO [10/25/19 12:39:31:98] Begin: Storing version variables to cache file C:\projects\dazinator-extensions-writableoptions\.git\gitversion_cache\5B9FA80B8E40D3FFE71FFDE243A389D33D092D18.yml
  INFO [10/25/19 12:39:32:05] End: Storing version variables to cache file C:\projects\dazinator-extensions-writableoptions\.git\gitversion_cache\5B9FA80B8E40D3FFE71FFDE243A389D33D092D18.yml (Took: 62.51ms)
  INFO [10/25/19 12:39:32:05] Applicable build agent found: 'AppVeyor'.
  ERROR [10/25/19 12:39:32:17] An unexpected error occurred:
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section dllmap. (C:\ProgramData\chocolatey\lib\GitVersion.Portable\tools\GitVersion.exe.Config line 6)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
   at System.Diagnostics.DiagnosticsConfiguration.GetConfigSection()
   at System.Diagnostics.DiagnosticsConfiguration.Initialize()
   at System.Diagnostics.DiagnosticsConfiguration.get_Sources()
   at System.Diagnostics.TraceSource.Initialize()
   at System.Net.Logging.InitializeLogging()
   at System.Net.Logging.get_On()
   at System.Net.WebRequest.Create(Uri requestUri, Boolean useUriBase)
   at GitVersion.AppVeyor.GenerateSetVersionMessage(VersionVariables variables)
   at GitVersion.BuildServerBase.WriteIntegration(Action`1 writer, VersionVariables variables)
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
  INFO [10/25/19 12:39:32:17] 
  INFO [10/25/19 12:39:32:17] Attempting to show the current git graph (please include in issue): 
  INFO [10/25/19 12:39:32:17] Showing max of 100 commits
  INFO [10/25/19 12:39:32:24] * 5f9d1c5 3 minutes ago  (HEAD -> develop, origin/develop)
* 8846231 4 minutes ago 
* bd71cd6 8 minutes ago 
* 86664e5 21 minutes ago 
*   594c88a 26 minutes ago 
|\  
| * b47c863 27 minutes ago  (tag: 2.0.0)
| * 9ec9a82 23 hours ago 
| * bfd9516 35 hours ago 
|/  
* b5843eb 3 months ago  (origin/master, origin/HEAD, master)
* f6d32af 3 months ago 
* 62b9ea0 3 months ago 
* 29cabd5 3 months ago 
* 9cef1c4 3 months ago 
* f53966c 3 months ago 
* 0c71b65 3 months ago 
Command exited with code 1

```

Here is my GitVersion.yml in the root of my repo:

```
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
commit-message-incrementing: Enabled
branches:
    feature:
        mode: ContinuousDelivery
        tag: useBranchName
        increment: Inherit
        prevent-increment-of-merged-branch-version: false
        track-merge-target: false
```

**Comment by dazinator** [comment]
Everything works when I downgrade to GitVersion 4.0.0:

```
install:
  - cmd: choco install gitversion.portable --version 4.0.0 -y

```

**Comment by asbjornu** [comment]
Is this reproducible with version 5.1.1 of GitVersion as well?

**Comment by skwasjer** [comment]
I've tested a bit with AppVeyor. 

> Note: I've omitted AspNetCore runtimes

**image: Visual Studio 2017**
```
.NET Core runtimes installed:
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**image: Visual Studio 2019**
```
.NET Core runtimes installed:
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

The issue I believe has to do with the dependency `System.ComponentModel.EventBasedAsync.dll` missing in GitVersion's published package. Thus, the assembly will be resolved from preinstalled runtimes.

The dependency graph is:
```
GitVersionCore -> System.Net.WebClient 4.0.1.0 -> System.ComponentModel.EventBasedAsync.dll 4.1.0.0
```

Version `4.1.0.0` however is only available up until runtime `Microsoft.NETCore.App 2.0.9`. This works on the VS2017 AppVeyor image, because that runtime is installed but it is not on the VS2019 image.

From `Microsoft.NETCore.App 2.1.x` onwards, the `System.ComponentModel.EventBasedAsync.dll` the assembly version is `4.1.1.0`.

**Comment by twopointzero** [comment]
Upon encountering the same issue myself, I was able to narrow the failure to the following version: 4.0.1-beta.1+44.Branch.master.Sha.16c69e62d2a01696728411cb70cfa457551d8bd0

As the version immediately before it does not experience the problem: 4.0.1-beta.1+43.Branch.master.Sha.fc86cb2b6df90b300a5f4a50b1bd113b606c7c99

The changes in 4.0.1-beta.1+44, at least from the perspective of the source tree, seem innocuous. They appear unlikely to cause a problem unless an assembly binding redirect was deleted when it was in actuality required. Perhaps something downstream of the source tree? e.g. build and/or packaging for release?

**Comment by asbjornu** [comment]
I agree 16c69e62d2a01696728411cb70cfa457551d8bd0 looks innocuous. Does the commit in relation to these problems ring a bell, @arturcic?

**Comment by arturcic** [comment]
That is weird
@twopointzero thanks for the investigation, if you revert the change from the 

> I agree [16c69e6](https://github.com/GitTools/GitVersion/commit/16c69e62d2a01696728411cb70cfa457551d8bd0) looks innocuous. Does the commit in relation to these problems ring a bell, @arturcic?

on top of the current head of the master, does it work?
