### ISSUE TITLE
GitVersion 5.1.1 AppVeyor: Input string was not in a correct format.

### ISSUE THREAD

**Issue by casz** [GitTools/GitVersion#1875]
Fails on this https://ci.appveyor.com/project/nmklotas/gitlabapiclient/builds/28479124#L77

https://github.com/nmklotas/GitLabApiClient/blob/082e81db571dd1ce894e79cacb2ff2734f6ef2c9/appveyor.yml

```
dotnet :   ERROR [10/30/19 6:38:07:03] An unexpected error occurred:
At line:1 char:1
+ dotnet gitversion /l console /output buildserver
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (  ERROR [10/30/...error occurred::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, Stri
ng format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at GitVersion.Logging.Log.Write(Verbosity verbosity, LogLevel level, String format, Object[] args) in D:\a\1\s\src\GitVersionCore\Logging\Log.cs:line 45
   at GitVersion.Logging.LogExtensions.Write(ILog log, LogLevel level, String format, Object[] args) in D:\a\1\s\src\GitVersionCore\Logging\LogExtensions.cs:line 100
   at GitVersion.Logging.LogExtensions.Info(ILog log, String format, Object[] args) in D:\a\1\s\src\GitVersionCore\Logging\LogExtensions.cs:line 51
   at GitVersion.Helpers.GitRepositoryHelper.CreateFakeBranchPointingAtThePullRequestTip(ILog log, Repository repo, AuthenticationInfo authentication) in D:\a\1\s\src\GitVersionCore\Helpers\GitRepositoryHelper.cs:line 208
   at GitVersion.Helpers.GitRepositoryHelper.NormalizeGitDirectory(ILog log, IEnvironment environment, String gitDirectory, AuthenticationInfo authentication, Boolean noFetch, String currentBranch, Boolean isDynamicRepository) 
in D:\a\1\s\src\GitVersionCore\Helpers\GitRepositoryHelper.cs:line 111
   at GitVersion.GitPreparer.Prepare(Boolean normalizeGitDirectory, String currentBranch, Boolean shouldCleanUpRemotes) in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 51
   at GitVersion.GitVersionCalculator.CalculateVersionVariables() in D:\a\1\s\src\GitVersionCore\GitVersionCalculator.cs:line 52
   at GitVersion.ExecCommand.Execute() in D:\a\1\s\src\GitVersionExe\ExecCommand.cs:line 40
   at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments) in D:\a\1\s\src\GitVersionExe\GitVersionExecutor.cs:line 117
```

Works fine on this build: https://ci.appveyor.com/project/nmklotas/gitlabapiclient/builds/28473392

**Comment by asbjornu** [comment]
Seems like the problem occurs somewhere in here:

https://github.com/GitTools/GitVersion/blob/a4cb74b2f763d0353d3e20be2e929f99ff46cbee/src/GitVersionCore/Logging/Log.cs#L31-L45

If we wrapped that in a `try` / `catch` and then added the invalid `format` string to the log output or exception message, it would be much easier to debug this issue. Could you do a fork of GitVersion and attempt that to see what may be going on here, @casz?

**Comment by eric-winkler** [comment]
I've successfully repro'd in a debugger, this is occuring when the CanonicalName of a remote tip contains `{}`, for example: `refs/tags/0.0.154.0^{}`.

I'll try and get a PR up to address

**Comment by arturcic** [comment]
@casz can you check that the fix works for you?

**Comment by casz** [comment]
I was blocked by https://github.com/GitTools/GitVersion/issues/1876 so I'll check if this is now fixed :)
