### ISSUE TITLE
Throws System.InvalidOperationException when using ignore commits-before option 

### ISSUE THREAD

**Issue by katrash** [GitTools/GitVersion#1880]
The GitVersion application throws System.InvalidOperationException when using ignore commits-before option in yaml file.

For example, when my YAML file is this:

```yaml
next-version: 3.0.0
ignore:
  commits-before: 2019-10-01T00:00:00
```

I receive the following error:
```
INFO [11/02/19 12:34:30:67] Working directory: C:\Projects\MbsProject
INFO [11/02/19 12:34:30:68] IsDynamicGitRepository: False
INFO [11/02/19 12:34:30:70] Returning Project Root from DotGitDirectory: C:\Projects\MbsProject\.git - C:\Projects\MbsProject
INFO [11/02/19 12:34:30:71] Running on Windows.
INFO [11/02/19 12:34:30:72] IsDynamicGitRepository: False
INFO [11/02/19 12:34:30:72] Returning Project Root from DotGitDirectory: C:\Projects\MbsProject\.git - C:\Projects\MbsProject
INFO [11/02/19 12:34:30:72] Project root is: C:\Projects\MbsProject
INFO [11/02/19 12:34:30:72] DotGit directory is: C:\Projects\MbsProject\.git
INFO [11/02/19 12:34:30:73] IsDynamicGitRepository: False
INFO [11/02/19 12:34:30:73] Returning Project Root from DotGitDirectory: C:\Projects\MbsProject\.git - C:\Projects\MbsProject
INFO [11/02/19 12:34:30:80] Begin: Loading version variables from disk cache
  INFO [11/02/19 12:34:30:80] Cache file C:\Projects\MbsProject\.git\gitversion_cache\3E00B844CAC0058007B17215E9445FF324DA052C.yml not found.
  INFO [11/02/19 12:34:30:80] End: Loading version variables from disk cache (Took: 1.00ms)
  INFO [11/02/19 12:34:30:80] IsDynamicGitRepository: False
  INFO [11/02/19 12:34:30:80] Returning Project Root from DotGitDirectory: C:\Projects\MbsProject\.git - C:\Projects\MbsProject
  INFO [11/02/19 12:34:30:95] Using latest commit on specified branch
  INFO [11/02/19 12:34:30:97] Begin: Attempting to inherit branch configuration from parent branch
    INFO [11/02/19 12:34:30:99] Begin: Finding branch source of 'feature/redesign3.0'
      INFO [11/02/19 12:34:31:02] Begin: Finding merge base between 'feature/redesign3.0' and 'master'.
        INFO [11/02/19 12:34:31:04] Found merge base of ef02f491beb52496c9693d71ccb7991e1a9767b8
        INFO [11/02/19 12:34:31:05] Merge base of feature/redesign3.0' and 'master is ef02f491beb52496c9693d71ccb7991e1a9767b8
      INFO [11/02/19 12:34:31:05] End: Finding merge base between 'feature/redesign3.0' and 'master'. (Took: 27.02ms)
    INFO [11/02/19 12:34:31:06] End: Finding branch source of 'feature/redesign3.0' (Took: 68.11ms)
    INFO [11/02/19 12:34:31:07] Begin: Getting branches containing the commit 'ef02f491beb52496c9693d71ccb7991e1a9767b8'.
      INFO [11/02/19 12:34:31:07] Trying to find direct branches.
      INFO [11/02/19 12:34:31:07] Direct branch found: 'master'.
    INFO [11/02/19 12:34:31:07] End: Getting branches containing the commit 'ef02f491beb52496c9693d71ccb7991e1a9767b8'. (Took: 8.00ms)
    INFO [11/02/19 12:34:31:08] Found possible parent branches: master
  INFO [11/02/19 12:34:31:08] End: Attempting to inherit branch configuration from parent branch (Took: 105.98ms)
  INFO [11/02/19 12:34:31:09] Running against branch: feature/redesign3.0 (81605ccf34e724a2522a21acf0f7f7ea6347df73)
  INFO [11/02/19 12:34:31:10] Begin: Calculating base versions
    INFO [11/02/19 12:34:31:18] Fallback base version: 0.1.0 with commit count source 0efab21e038e5d7b530c6191df69c623f9c54a6b (Incremented: None)
    INFO [11/02/19 12:34:31:18] Source was ignored due to commit date being outside of configured range
    INFO [11/02/19 12:34:31:21] NextVersion in GitVersion configuration file: 3.0.0 with commit count source External Source (Incremented: None)
  INFO [11/02/19 12:34:31:40] End: Calculating base versions (Took: 298.01ms)
  ERROR [11/02/19 12:34:31:42] An unexpected error occurred:
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersion(GitVersionContext context)
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion(GitVersionContext context)
   at GitVersion.GitVersionFinder.FindVersion(GitVersionContext context)
   at GitVersion.ExecuteCore.<>c__DisplayClass7_0.<ExecuteInternal>b__0(IRepository repo)
   at GitVersion.GitPreparer.WithRepository[TResult](Func`2 action)
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache)
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
  INFO [11/02/19 12:34:31:42]
  INFO [11/02/19 12:34:31:42] Attempting to show the current git graph (please include in issue):
  INFO [11/02/19 12:34:31:42] Showing max of 100 commits
  INFO [11/02/19 12:34:31:64] * 81605cc 23 hours ago  (HEAD -> feature/redesign3.0, origin/feature/redesign3.0)
*   12a212b 25 hours ago
|\
| * 374e502 3 weeks ago  (origin/jira/MOB-1039, jira/MOB-1039)
| * 8c8474a 3 weeks ago
| * 5a29acf 3 weeks ago
| * 5b94bb6 6 weeks ago
| * 18be3d1 9 weeks ago
| * 5217cf9 9 weeks ago
* | c44cf61 4 days ago
* | 71cd6d9 4 days ago
* | 8ced0ea 5 days ago  (origin/release/mbs2.5.1, origin/master, origin/HEAD)
* | ef02f49 4 weeks ago  (master)
* | 0363f8d 4 weeks ago
| | * 0a7cd90 4 weeks ago  (origin/release/mbs2.5.0)
| |/
|/|
* | a4198d0 7 weeks ago
|/
* 94f1c96 10 weeks ago
* 08d4bc8 10 weeks ago
* c1ec7b9 10 weeks ago
* f77b639 10 weeks ago
* 18f09f0 2 months ago
* 1fde3a8 3 months ago
* 7a90f3d 3 months ago
* b07d09e 3 months ago
* ec09271 3 months ago
* 61e8f87 3 months ago
* 15595ac 4 months ago
* 9e4c59c 4 months ago
* 69778c5 4 months ago
* 7603d65 4 months ago
* 8a1a50a 4 months ago
* 3905294 4 months ago
* 57f0a56 5 months ago
* 5475589 5 months ago
* 1dc1cbb 5 months ago
* fa8fe3b 5 months ago
* 7c62489 5 months ago
* 586d58f 5 months ago
* 30f38f1 5 months ago
* 4b6ac11 5 months ago
* 703434e 5 months ago
* f875b16 6 months ago
* 2f94d6d 6 months ago
* 7086302 6 months ago
* 6f1532c 6 months ago
* 47b010c 6 months ago
* b80d665 6 months ago
* de20808 7 months ago
* 3c638be 7 months ago
* aa29b1f 7 months ago
* 654f0a3 7 months ago
* 56f9e4a 7 months ago
* 52aad4a 7 months ago
* 848e814 7 months ago
* aa91a3c 7 months ago
* de55bd1 7 months ago
* 9374be2 7 months ago
* 08e4c4b 7 months ago
* c4f8308 7 months ago
* 77f4c00 7 months ago
* 61209af 7 months ago
* 677d8d5 8 months ago
* 44b1a16 8 months ago
* 8674d3e 8 months ago
* 78f72b8 8 months ago
* 6cdfc63 9 months ago
* b32f210 9 months ago
* 495afdc 9 months ago
* 2b2a172 10 months ago
* 18bdc25 10 months ago
* 0752ede 11 months ago  (origin/release/mbs2.4.0)
* 08541bf 11 months ago
* 1e1313c 12 months ago
* 8300dc6 12 months ago
* 5c0a7de 12 months ago
* 847511c 1 year, 1 month ago
* 07b00b2 1 year, 1 month ago
* d7c8a38 1 year, 1 month ago
* d393654 1 year, 2 months ago
* ffec494 1 year, 2 months ago
| * fa54faf 11 months ago  (origin/release/mbs2.2.7)
| | * 39993a4 12 months ago  (origin/release/mbs2.2.8)
| | * ef76ebc 12 months ago
| | * da91208 1 year ago
| | * a4e72da 1 year, 1 month ago
| | * b218df3 1 year, 1 month ago
| | * 2e33342 1 year, 1 month ago
| |/
| * af21124 1 year, 1 month ago
| * bd0617a 1 year, 2 months ago
| | * 3ca5035 1 year, 2 months ago  (origin/release/mbs2.2.6)
| | | * 7ecd327 1 year, 2 months ago  (origin/pooling-httpclients, pooling-httpclients)
| | | * 9c88f41 1 year, 2 months ago
| |_|/
|/| |
* | | a01e63b 1 year, 2 months ago
* | | 283e5f1 1 year, 2 months ago
* | | 1925590 1 year, 3 months ago
* | | f8f9d45 1 year, 3 months ago
* | | bdf3ecc 1 year, 3 months ago
|/ /
* | 2934af2 1 year, 3 months ago
* | 2f6c8d0 1 year, 3 months ago
* | 92a8ccd 1 year, 3 months ago
* | 4b1306b 1 year, 3 months ago
```

**Comment by asbjornu** [comment]
This usually happens if GitVersion can't find any commits after the `commits-before` date you've configured to calculate its version from. If you remove the `ignore` section from `GitVersion.yml`, does it work?

**Comment by katrash** [comment]
@asbjornu, this repository was created over one year ago with 100's of commits. And if you notice, the date I set is a little over a month ago.

When I remove the ignore section, it works properly, but I added it as I need to serve as build number in my case.

**Comment by asbjornu** [comment]
Is it not possible to add a Git tag or `next-version` instead?

**Comment by katrash** [comment]
Yes it is possible, but still the `commits-before` feature still not working as intended. The tag or next-version will help with the `major.minor.patch` values but not with build number value. I though of using number of commits after a specific date to represent the build number, which means that no matter how many times my CICD system (re)builds the solution, I will get the same `major.minor.patch.build#` for the same commit.

**Comment by asbjornu** [comment]
Sorry, I don't think your use-case is compatible with GitVersion. It has no concept of "build number"; that's up to your CI server to provide. GitVersion supports adding environment variables to its version number, but `minor.major.patch.build` is incompatible with SemVer, so I would just use the `major.minor.patch` you get from GitVersion (without `commits-before`) and build a custom version number within the build pipeline.

**Comment by katrash** [comment]
Fine, I will use my CICD system's default build number instead.
But still, I can assume that the `commits-before` isn't working as described or is it broken and it either needs fixing or be removed from the application.

BTW, no need to apologize :) and thanks for this great tool

**Comment by asbjornu** [comment]
`commits-before` works for some use-cases and doesn't for others. What I can say is that it should definitely provide a better error message in the cases it fails, though.
