### ISSUE TITLE
GitVersion 5.1.2 fails on ubuntu 19.10

### ISSUE THREAD

**Issue by MindaugasLaganeckas** [GitTools/GitVersion#1901]
I am using GitVersion 5.1.2 on Ubuntu 19.10 and it fails with:

```
1>/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error : TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error :    at LibGit2Sharp.Core.NativeMethods.git_buf_dispose(GitBuf buf)
/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error :    at LibGit2Sharp.Core.Proxy.git_buf_dispose(GitBuf buf)
/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error :    at LibGit2Sharp.Core.Handles.GitBuf.Dispose()
/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error :    at LibGit2Sharp.Core.Proxy.ConvertPath(Func`2 pathRetriever)
/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error :    at LibGit2Sharp.Core.Proxy.git_repository_discover(FilePath start_path)
/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error :    at LibGit2Sharp.Repository.Discover(String startingPath)
/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error :    at GitVersion.GitPreparer.GetDotGitDirectoryInternal() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 69
/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error :    at GitVersion.GitPreparer.GetDotGitDirectory() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 25
/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error :    at GitVersion.GitVersionCalculator.CalculateVersionVariables() in D:\a\1\s\src\GitVersionCore\GitVersionCalculator.cs:line 54
/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTaskExecutor.WriteVersionInfoToBuildLog(WriteVersionInfoToBuildLog task) in D:\a\1\s\src\GitVersionTask\GitVersionTaskExecutor.cs:line 65
/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTasks.<>c__DisplayClass3_0.<WriteVersionInfoToBuildLog>b__0(IGitVersionTaskExecutor executor) in D:\a\1\s\src\GitVersionTask\GitVersionTasks.cs:line 20
/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.GitVersionTasks.ExecuteGitVersionTask[T](T task, Action`1 action) in D:\a\1\s\src\GitVersionTask\GitVersionTasks.cs:line 31
/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error : DllNotFoundException: Unable to load shared library '/home//.nuget/packages/gitversiontask/5.1.2/build/../tools/netstandard2.0/runtimes/linux-x64/native/libgit2-7ce88e6.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libssl.so.1.0.0: cannot open shared object file: No such file or directory
/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error :    at System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(String unmanagedDllPath)
/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error :    at System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath(String unmanagedDllPath)
/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error :    at GitVersion.MSBuildTask.LibGit2Sharp.GitLoaderContext.LoadUnmanagedDll(String unmanagedDllName) in D:\a\1\s\src\GitVersionTask.MsBuild\LibGit2Sharp\GitLoaderContext.cs:line 54
/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error :    at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext)
/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error :    at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error :    at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary()
/home//.nuget/packages/gitversiontask/5.1.2/build/GitVersionTask.targets(10,9): error :    at LibGit2Sharp.Core.NativeMethods..cctor()
```

Could libssl.so.1.0.0 be a problem? I have /usr/lib/x86_64-linux-gnu/libssl.so.1.1 and cannot downgrade to version 1.0.0.

**Comment by tsebastiani** [comment]
Having exactly the same issue, managed to add libssl1.0.0 but did not solve the problem even if ldd of the library is resolving it:

```	linux-vdso.so.1 (0x00007ffc70abe000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f44e6177000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f44e6154000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f44e5eec000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f44e5aa9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f44e58b8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f44e64c6000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f44e58b2000)
```

**Comment by MindaugasLaganeckas** [comment]
Is there someone, who could provide guidance? It is a really annoying issue :cry:

**Comment by asbjornu** [comment]
Usually, these problems are due to a bug in LibGit2Sharp. Have you investigated whether this is a known issue over there?

**Comment by dnperfors** [comment]
Could this issue be reopened? it is still an issue, currently on Ubuntu 20.04 LTS

**Comment by arturcic** [comment]
@dnperfors there is https://github.com/GitTools/GitVersion/issues/2471
