### ISSUE TITLE
Unable to set `none` flag for verbosity

### ISSUE THREAD

**Issue by DanubeRS** [GitTools/GitVersion#1949]
```
C:\(repository) [(ce4ef6a...) +0 ~1 -0 !]> gitversion . /verbosity none
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'None' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at GitVersion.ArgumentParser.ParseArguments(String[] commandLineArguments)
   at GitVersion.Program.<>c__DisplayClass1_0.<CreateHostBuilder>b__2(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at GitVersion.GitVersionCoreModule.<>c.<RegisterTypes>b__0_0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at GitVersion.Program.Main(String[] args)
   at GitVersion.Program.<Main>(String[] args)
```

also reflected using in the Cake GitVersion tool.

```
Setup(context => {
    version = GitVersion(new GitVersionSettings(){
        Verbosity = GitVersionVerbosity.None
    });
    Information($"Building version {version.InformationalVersion}");
});
```

Docs show usage as;

`/verbosity      Set Verbosity level (debug, info, warn, error, none). Default is info`

**Comment by gep13** [comment]
@DanubeRS looks like the docs, as well as the Cake Alias needs to be updated.  The enum associated with this argument no longer contains the `none` value:

https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/Logging/Verbosity.cs

**Comment by arturcic** [comment]
@gep, in that PR it was also added https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/Logging/LogLevel.cs, so when the cake alias will be adjusted you need to take in consideration that as well.  see the usage https://github.com/GitTools/GitVersion/blob/master/src/GitVersionExe/ArgumentParser.cs#L353

**Comment by gep13** [comment]
@arturcic I think I am a little confused 😄...

Is `none` a valid setting for the logging level?  If so, what is the correct command line usage?

**Comment by arturcic** [comment]
It should be valid, as for the current implementation. Previously there was only a verbosity flag that has the role of the logging level. I made the change by adding a LogLevel enum to control which level of logging you want to target, and verbosity, that controls how much information is shown to the output. There is a dependency between verbosity and log level https://github.com/GitTools/GitVersion/blob/37c67a06d7f364405e1a6fd742ad360234537148/src/GitVersionCore/Logging/LogExtensions.cs#L169. I made possible to specify both loglevel and verbosity as values for the `/verbosity` parameter because I wanted to avoid breaking the consumers, Cake alias for instance. When the new cli for GitVersion will be implemented, at that point I'll make them as separate options, this way breaking the usage. But for now you should be able to consume both values

**Comment by cdonnellytx** [comment]
This still appears to be an issue with GitVersion 5.1.1-5.2.4: if you explicitly specify `None` or `0`, it throws this error.  Specifying any other valid value (e.g. `Error`) appears to work correctly.

None is a valid log level per Cake's docs:

https://cakebuild.net/api/Cake.Common.Tools.GitVersion/GitVersionVerbosity/

I can reproduce it consistently by explicitly using `None`, as well as implicitly on a headless server running TeamCity (probably something to do with how it checks out the files, but I'm not 100% certain).  Works fine if it's explicit, fails if it's implicit or `None`.

**Comment by arturcic** [comment]
@cdonnellytx 
This one will be fixed in 5.3.0 but keep in mind the None flag is only used for compatibility reasons. It will be removed in 6.0.0 The valid values for Verbosity are https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/Logging/Verbosity.cs, but we kept the old values to allow others migrate the usage to the new one.

**Comment by nbarnwell** [comment]
Something is still wrong here because the verbosity setting has no effect on the output for me. No matter what I specify, all I get is the same JSON output. I'm trying to get some sort of verbose information out of it because I can't see why it's generating 0.1.0, for a repo that only has 0.0.0 and 0.0.1 tags.

Here's the output I get:
```
{
  "Major":0,
  "Minor":1,
  "Patch":0,
  "PreReleaseTag":"",
  "PreReleaseTagWithDash":"",
  "PreReleaseLabel":"",
  "PreReleaseNumber":"",
  "WeightedPreReleaseNumber":60000,
  "BuildMetaData":1,
  "BuildMetaDataPadded":"0001",
  "FullBuildMetaData":"1.Branch.master.Sha.c308897f323160f6dce9b455ca23a7602e2377da",
  "MajorMinorPatch":"0.1.0",
  "SemVer":"0.1.0",
  "LegacySemVer":"0.1.0",
  "LegacySemVerPadded":"0.1.0",
  "AssemblySemVer":"0.1.0.0",
  "AssemblySemFileVer":"0.1.0.0",
  "FullSemVer":"0.1.0+1",
  "InformationalVersion":"0.1.0+1.Branch.master.Sha.c308897f323160f6dce9b455ca23a7602e2377da",
  "BranchName":"master",
  "EscapedBranchName":"master",
  "Sha":"c308897f323160f6dce9b455ca23a7602e2377da",
  "ShortSha":"c308897",
  "NuGetVersionV2":"0.1.0",
  "NuGetVersion":"0.1.0",
  "NuGetPreReleaseTagV2":"",
  "NuGetPreReleaseTag":"",
  "VersionSourceSha":"5d3d1fee178b18d9cebaa29c760e3c051cb0e317",
  "CommitsSinceVersionSource":1,
  "CommitsSinceVersionSourcePadded":"0001",
  "CommitDate":"2020-07-06"
}
```

**Comment by asbjornu** [comment]
Try not specifying `/output json`, @nbarnwelll.
