### ISSUE TITLE
GitVersion /showconfig throws an execption in Git Bash on Windows

### ISSUE THREAD

**Issue by dsbut** [GitTools/GitVersion#1972]
Apologies in advance if executing GitVersion in Git Bash on Windows is not a supported scenario. I was unable to find any conclusive information on that. I would naturally assume that GitVersion would work everywhere `git` commands can be sissued, including from Git Bash on Windows. That both `gitversion` and `gitversion init` work within Git Bash on Windows does set an expectation that other GitVersion commands should be fully supported there.

The issue I've encountered is simply that executing `gitversion /showconfig` on my repo from the repository foot produces the following output:
``` console
$ gitversion /showconfig
WARN [12/05/19 10:41:49:60] The working directory 'C:/Program Files/Git/showconfig' does not exist.INFO [12/05/19 10:41:49:61] IsDynamicGitRepository: FalseERROR [12/05/19 10:41:50:09] An unexpected error occurred:
System.IO.DirectoryNotFoundException: Can't find the .git directory in
   at GitVersion.GitPreparer.GetProjectRootDirectoryInternal()
   at GitVersion.GitPreparer.GetProjectRootDirectory()
   at GitVersion.Configuration.ConfigFileLocator.Verify(IGitPreparer gitPreparer)
   at GitVersion.GitVersionExecutor.VerifyConfiguration()
   at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments)INFO [12/05/19 10:41:50:09] INFO [12/05/19 10:41:50:09] Attempting to show the current git graph (please include in issue): INFO [12/05/19 10:41:50:09] Showing max of 100 commitsERROR [12/05/19 10:41:50:38] Couldn't dump the git graph due to the following error: System.ComponentModel.Win32Exception (267): The directory name is invalid.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at GitVersion.Helpers.ProcessHelper.Start(ProcessStartInfo startInfo)
   at GitVersion.Helpers.ProcessHelper.Run(Action`1 output, Action`1 errorOutput, TextReader input, String exe, String args, String workingDirectory, KeyValuePair`2[] environmentalVariables)
   at GitVersion.Extensions.LibGitExtensions.DumpGraph(String workingDirectory, Action`1 writer, Nullable`1 maxCommits)
   at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments)

```

**Comment by asbjornu** [comment]
Sorry, but the command line interface of GitVersion is not the most cross-platform compatible one and also not the best documented part of GitVersion. But all arguments can be passed with dash (`-`) instead of slash (`/`) so it's not interpreted as file paths on POSIX systems. Does `gitversion -showconfig` work?

**Comment by dsbut** [comment]
@asbjornu Ah, yes. It does work in Git Bash on Windows if I specify `gtiversion -showconfig` instead. This is good to know, I'm documenting some guidance for some fellow Developers, and so I'll specify (-) instead of (/) for examples that include arguments.

**Comment by asbjornu** [comment]
I'm glad it works, @dsbut. If you find relevant parts of the documentation to update regarding this, we would love a pull request. 🙏
