### ISSUE TITLE
GitVersion.CommandLine throws exception on appveyor

### ISSUE THREAD

**Issue by soroshsabz** [GitTools/GitVersion#1981]
ITNOA

I have a problem with gitversion on cake in appveyor

first problem is: why gitversion does not load GitVersion.yml on root of my [project](https://github.com/BSVN/Commons)
second problem is: why gitversion throws exception like below

```
INFO [12/10/19 18:53:59:83] Working directory: C:\projects\commons\Build
129
INFO [12/10/19 18:53:59:84] IsDynamicGitRepository: False
130
INFO [12/10/19 18:53:59:88] Returning Project Root from DotGitDirectory: C:\projects\commons\.git\ - C:\projects\commons\
131
INFO [12/10/19 18:53:59:88] Running on Windows.
132
INFO [12/10/19 18:53:59:88] Applicable build agent found: 'AppVeyor'.
133
INFO [12/10/19 18:53:59:88] Branch from build environment: master
134
INFO [12/10/19 18:53:59:88] Begin: Normalizing git directory for branch 'master'
135
  INFO [12/10/19 18:53:59:92] One remote found (origin -> 'https://github.com/BSVN/Commons.git').
136
  INFO [12/10/19 18:53:59:92] Fetching from remote 'origin' using the following refspecs: +refs/heads/*:refs/remotes/origin/*.
137
  INFO [12/10/19 18:54:00:10] Updating local branch refs/heads/master to match ref master
138
  INFO [12/10/19 18:54:00:18] Head has moved from '(no branch) | f82f7c2319304138fb84313a2070d7bff642ad82' => 'refs/heads/master | 7065f14b973a2e1e39c9a6295c15b3fdc9a8c2e9', allowed since this is a dynamic repository
139
  INFO [12/10/19 18:54:00:18] HEAD points at branch 'refs/heads/master'.
140
  INFO [12/10/19 18:54:00:18] End: Normalizing git directory for branch 'master' (Took: 300.20ms)
141
  INFO [12/10/19 18:54:00:18] Project root is: C:\projects\commons\
142
  INFO [12/10/19 18:54:00:18] DotGit directory is: C:\projects\commons\.git
143
  INFO [12/10/19 18:54:00:25] Begin: Loading version variables from disk cache
144
    INFO [12/10/19 18:54:00:25] Cache file C:\projects\commons\.git\gitversion_cache\8552F7DE8B2014FEC1E3D2122A074DFEE2426563.yml not found.
145
  INFO [12/10/19 18:54:00:25] End: Loading version variables from disk cache (Took: 4.36ms)
146
  INFO [12/10/19 18:54:00:27] Using latest commit on specified branch
147
  INFO [12/10/19 18:54:00:33] Running against branch: master (7065f14b973a2e1e39c9a6295c15b3fdc9a8c2e9)
148
  INFO [12/10/19 18:54:00:33] Current commit is tagged with version 1.4.2, version calculation is for metadata only.
149
  INFO [12/10/19 18:54:00:34] 0 commits found between 7065f14b973a2e1e39c9a6295c15b3fdc9a8c2e9 and 7065f14b973a2e1e39c9a6295c15b3fdc9a8c2e9
150
  INFO [12/10/19 18:54:00:34] Begin: Calculating base versions
151
    INFO [12/10/19 18:54:00:35] Fallback base version: 0.1.0 with commit count source 51d0fe43570bdefa4bf687798492cb6acce96700 (Incremented: None)
152
    INFO [12/10/19 18:54:00:40] Git tag '1.4.2': 1.4.2 with commit count source 7065f14b973a2e1e39c9a6295c15b3fdc9a8c2e9 (Incremented: None)
153
    INFO [12/10/19 18:54:00:47] Found multiple base versions which will produce the same SemVer (1.4.2), taking oldest source for commit counting (Git tag '1.4.2')
154
    INFO [12/10/19 18:54:00:47] Base version used: Git tag '1.4.2': 1.4.2 with commit count source 7065f14b973a2e1e39c9a6295c15b3fdc9a8c2e9 (Incremented: None)
155
  INFO [12/10/19 18:54:00:47] End: Calculating base versions (Took: 128.39ms)
156
  INFO [12/10/19 18:54:00:47] Skipping version increment
157
  INFO [12/10/19 18:54:00:47] 0 commits found between 7065f14b973a2e1e39c9a6295c15b3fdc9a8c2e9 and 7065f14b973a2e1e39c9a6295c15b3fdc9a8c2e9
158
  INFO [12/10/19 18:54:00:48] Begin: Creating dictionary
159
  INFO [12/10/19 18:54:00:48] End: Creating dictionary (Took: 5.38ms)
160
  INFO [12/10/19 18:54:00:49] Begin: Storing version variables to cache file C:\projects\commons\.git\gitversion_cache\8552F7DE8B2014FEC1E3D2122A074DFEE2426563.yml
161
  INFO [12/10/19 18:54:00:59] End: Storing version variables to cache file C:\projects\commons\.git\gitversion_cache\8552F7DE8B2014FEC1E3D2122A074DFEE2426563.yml (Took: 107.01ms)
162
  INFO [12/10/19 18:54:00:60] Applicable build agent found: 'AppVeyor'.
163
Executing GenerateSetVersionMessage for 'AppVeyor'.
164
Set AppVeyor build number to '1.4.2'.
165
Executing GenerateBuildLogOutput for 'AppVeyor'.
166
Cake.exe :   ERROR [12/10/19 18:54:01:78] An unexpected error occurred:
167
At C:\projects\commons\Build\build.ps1:241 char:1
168
+ &$CAKE_EXE $cakeArguments
169
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
170
    + CategoryInfo          : NotSpecified: (  ERROR [12/10/...error occurred::String) [], RemoteException
171
    + FullyQualifiedErrorId : NativeCommandError
172
 
173
System.TypeLoadException: Could not load type 'System.ComponentModel.AsyncCompletedEventArgs' from assembly 'System.Net.WebHeaderCollection, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f
174
  INFO [12/10/19 18:54:01:78] 
175
5f7f11d50a3a'.
176
   at GitVersion.BuildServers.AppVeyor.GenerateSetParameterMessage(String name, String value)
177
   at GitVersion.OutputFormatters.BuildOutputFormatter.GenerateBuildLogOutput(IBuildServer buildServer, VersionVariables variables)
178
   at GitVersion.BuildServerBase.WriteIntegration(Action`1 writer, VersionVariables variables)
179
   at GitVersion.ExecCommand.Execute()
180
   at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments)
181
182
  INFO [12/10/19 18:54:01:78] Attempting to show the current git graph (please include in issue): 
183
  INFO [12/10/19 18:54:01:78] Showing max of 100 commits
184
  INFO [12/10/19 18:54:01:91] *   7065f14 33 hours ago  (HEAD -> master, tag: 1.4.2, origin/master, origin/HEAD)
185
|\  
186
| * 00c1289 2 days ago 
187
| * 54dec8e 2 days ago 
188
| * 3f1e15c 2 days ago 
189
| * 12b065a 5 days ago 
190
| * 3a9502d 5 days ago 
191
| * f37b910 5 days ago 
192
| * d9e4a00 5 days ago 
193
| * fbe18ef 5 days ago 
194
| * 37611db 5 days ago 
195
| * c81c709 6 days ago 
196
| * e54c890 6 days ago 
197
| *   c5eb936 7 days ago 
198
| |\  
199
| | * e156da7 13 days ago 
200
| | * c7c8c09 1 year, 1 month ago 
201
| | * bb2544d 1 year, 1 month ago 
202
| | * a321df7 1 year, 1 month ago 
203
| | * 5f4e412 1 year, 1 month ago 
204
| | * da7eef1 1 year, 1 month ago 
205
| * | b13ed99 1 year, 1 month ago 
206
| * | 262048f 1 year, 1 month ago 
207
| * | 3946576 1 year, 1 month ago 
208
| |/  
209
| * 8fb334a 1 year, 1 month ago 
210
| * daf7496 1 year, 1 month ago 
211
| * 36da80b 1 year, 1 month ago 
212
| * 8a8f77b 1 year, 1 month ago 
213
| *   6e4e3b2 1 year, 1 month ago 
214
| |\  
215
| | *   100717d 2 years ago 
216
| | |\  
217
| | | * 2eab07f 2 years ago 
218
| | * | 99cc367 2 years ago 
219
| | * | 544a2e9 2 years ago 
220
| | * | 697e109 2 years ago 
221
| | * | a109663 2 years ago 
222
| | * | 4fa89f5 2 years ago 
223
| | * | 12c82dc 2 years ago 
224
| | * | bee0d4a 2 years ago 
225
| | * | 1e3ad86 2 years ago 
226
| | * | f2373ec 2 years ago 
227
| | * | c292f74 2 years ago 
228
| | * | 527595c 2 years ago 
229
| | |/  
230
| | * e820bc7 2 years, 1 month ago 
231
| | * 72f32ef 2 years, 1 month ago 
232
| | * d9cae0d 2 years, 1 month ago 
233
| | * b42acf5 2 years, 1 month ago 
234
| * 1c59ffe 1 year, 1 month ago 
235
| * 8fa9142 1 year, 1 month ago 
236
| * 45ee611 1 year, 1 month ago 
237
|/  
238
* 51d0fe4 1 year, 1 month ago 
239
240
INFO [12/10/19 18:53:59:82] Applicable build agent found: 'AppVeyor'.INFO [12/10/19 18:53:59:83] Working directory: C:\projects\commons\BuildINFO [12/10/19 18:53:59:84] IsDynamicGitRepository: FalseINFO [12/10/19 18:53:59:88] Returning Project Root from DotGitDirectory: C:\projects\commons\.git\ - C:\projects\commons\INFO [12/10/19 18:53:59:88] Running on Windows.INFO [12/10/19 18:53:59:88] Applicable build agent found: 'AppVeyor'.INFO [12/10/19 18:53:59:88] Branch from build environment: masterINFO [12/10/19 18:53:59:88] Begin: Normalizing git directory for branch 'master'  INFO [12/10/19 18:53:59:92] One remote found (origin -> 'https://github.com/BSVN/Commons.git').  INFO [12/10/19 18:53:59:92] Fetching from remote 'origin' using the following refspecs: +refs/heads/*:refs/remotes/origin/*.  INFO [12/10/19 18:54:00:10] Updating local branch refs/heads/master to match ref master  INFO [12/10/19 18:54:00:18] Head has moved from '(no branch) | f82f7c2319304138fb84313a2070d7bff642ad82' => 'refs/heads/master | 7065f14b973a2e1e39c9a6295c15b3fdc9a8c2e9', allowed since this is a dynamic repository  INFO [12/10/19 18:54:00:18] HEAD points at branch 'refs/heads/master'.  INFO [12/10/19 18:54:00:18] End: Normalizing git directory for branch 'master' (Took: 300.20ms)  INFO [12/10/19 18:54:00:18] Project root is: C:\projects\commons\  INFO [12/10/19 18:54:00:18] DotGit directory is: C:\projects\commons\.git  INFO [12/10/19 18:54:00:25] Begin: Loading version variables from disk cache    INFO [12/10/19 18:54:00:25] Cache file C:\projects\commons\.git\gitversion_cache\8552F7DE8B2014FEC1E3D2122A074DFEE2426563.yml not found.  INFO [12/10/19 18:54:00:25] End: Loading version variables from disk cache (Took: 4.36ms)  INFO [12/10/19 18:54:00:27] Using latest commit on specified branch  INFO [12/10/19 18:54:00:33] Running against branch: master (7065f14b973a2e1e39c9a6295c15b3fdc9a8c2e9)  INFO [12/10/19 18:54:00:33] Current commit is tagged with version 1.4.2, version calculation is for metadata only.  INFO [12/10/19 18:54:00:34] 0 commits found between 7065f14b973a2e1e39c9a6295c15b3fdc9a8c2e9 and 7065f14b973a2e1e39c9a6295c15b3fdc9a8c2e9  INFO [12/10/19 18:54:00:34] Begin: Calculating base versions    INFO [12/10/19 18:54:00:35] Fallback base version: 0.1.0 with commit count source 51d0fe43570bdefa4bf687798492cb6acce96700 (Incremented: None)    INFO [12/10/19 18:54:00:40] Git tag '1.4.2': 1.4.2 with commit count source 7065f14b973a2e1e39c9a6295c15b3fdc9a8c2e9 (Incremented: None)    INFO [12/10/19 18:54:00:47] Found multiple base versions which will produce the same SemVer (1.4.2), taking oldest source for commit counting (Git tag '1.4.2')    INFO [12/10/19 18:54:00:47] Base version used: Git tag '1.4.2': 1.4.2 with commit count source 7065f14b973a2e1e39c9a6295c15b3fdc9a8c2e9 (Incremented: None)  INFO [12/10/19 18:54:00:47] End: Calculating base versions (Took: 128.39ms)  INFO [12/10/19 18:54:00:47] Skipping version increment  INFO [12/10/19 18:54:00:47] 0 commits found between 7065f14b973a2e1e39c9a6295c15b3fdc9a8c2e9 and 7065f14b973a2e1e39c9a6295c15b3fdc9a8c2e9  INFO [12/10/19 18:54:00:48] Begin: Creating dictionary  INFO [12/10/19 18:54:00:48] End: Creating dictionary (Took: 5.38ms)  INFO [12/10/19 18:54:00:49] Begin: Storing version variables to cache file C:\projects\commons\.git\gitversion_cache\8552F7DE8B2014FEC1E3D2122A074DFEE2426563.yml  INFO [12/10/19 18:54:00:59] End: Storing version variables to cache file C:\projects\commons\.git\gitversion_cache\8552F7DE8B2014FEC1E3D2122A074DFEE2426563.yml (Took: 107.01ms)  INFO [12/10/19 18:54:00:60] Applicable build agent found: 'AppVeyor'.  ERROR [12/10/19 18:54:01:78] An unexpected error occurred:
241
System.TypeLoadException: Could not load type 'System.ComponentModel.AsyncCompletedEventArgs' from assembly 'System.Net.WebHeaderCollection, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
242
| | * 5f9bf93 13 days ago 
243
| |/  
244
|/|   
245
| * a269dcc 7 days ago 
246
|/  
247
*   9e71812 1 year, 1 month ago 
248
|\  
249
| * d6d1d0e 1 year, 1 month ago 
250
* |   a6bb84a 1 year, 1 month ago 
251
|\ \  
252
| |/  
253
| * 8c58fa9 1 year, 1 month ago 
254
| * 65d3b02 1 year, 1 month ago 
255
| * df575d2 1 year, 1 month ago 
256
| * c3268a1 1 year, 1 month ago 
257
| * 35e47bd 1 year, 1 month ago 
258
| *   dc02736 1 year, 1 month ago 
259
| |\  
260
| | * e7a9e9d 1 year, 1 month ago 
261
| | * 8fa965e 1 year, 1 month ago 
262
| * | 833cd1b 1 year, 1 month ago 
263
| |/  
264
| * 888bd39 1 year, 1 month ago 
265
| * 2eb0cb0 1 year, 1 month ago 
266
| * 21b4340 1 year, 1 month ago 
267
| * 9b31ee8 1 year, 1 month ago 
268
| *   88909db 1 year, 1 month ago 
269
| |\  
270
| | * 1cd646f 1 year, 1 month ago 
271
| | * 46a6136 1 year, 1 month ago 
272
| | * e8ed587 1 year, 1 month ago 
273
| | * e1acb6e 1 year, 1 month ago 
274
| | * 255d337 1 year, 1 month ago 
275
| | * 1ac448e 1 year, 1 month ago 
276
| | * 9a230f5 1 year, 1 month ago 
277
| | * 7a29faa 1 year, 1 month ago 
278
| | * ead86eb 1 year, 1 month ago 
279
| | * 0467640 1 year, 1 month ago 
280
| | * 6b33658 1 year, 1 month ago 
281
| | * 6f6df3a 1 year, 1 month ago 
282
| | * 25f7c35 1 year, 1 month ago 
283
   at GitVersion.BuildServers.AppVeyor.GenerateSetParameterMessage(String name, String value)
284
   at GitVersion.OutputFormatters.BuildOutputFormatter.GenerateBuildLogOutput(IBuildServer buildServer, VersionVariables variables)
285
   at GitVersion.BuildServerBase.WriteIntegration(Action`1 writer, VersionVariables variables)
286
   at GitVersion.ExecCommand.Execute()
287
   at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments)  INFO [12/10/19 18:54:01:78]   INFO [12/10/19 18:54:01:78] Attempting to show the current git graph (please include in issue):   INFO [12/10/19 18:54:01:78] Showing max of 100 commits  INFO [12/10/19 18:54:01:91] *   7065f14 33 hours ago  (HEAD -> master, tag: 1.4.2, origin/master, origin/HEAD)
288
|\  
289
| * 00c1289 2 days ago 
290
| * 54dec8e 2 days ago 
291
| * 3f1e15c 2 days ago 
292
| * 12b065a 5 days ago 
293
| * 3a9502d 5 days ago 
294
| * f37b910 5 days ago 
295
| * d9e4a00 5 days ago 
296
| * fbe18ef 5 days ago 
297
| * 37611db 5 days ago 
298
| * c81c709 6 days ago 
299
| * e54c890 6 days ago 
300
| *   c5eb936 7 days ago 
301
| |\  
302
| | * e156da7 13 days ago 
303
| | * 5f9bf93 13 days ago 
304
| |/  
305
|/|   
306
| * a269dcc 7 days ago 
307
|/  
308
*   9e71812 1 year, 1 month ago 
309
|\  
310
| * d6d1d0e 1 year, 1 month ago 
311
* |   a6bb84a 1 year, 1 month ago 
312
|\ \  
313
| |/  
314
| * 8c58fa9 1 year, 1 month ago 
315
| * 65d3b02 1 year, 1 month ago 
316
| * df575d2 1 year, 1 month ago 
317
| * c3268a1 1 year, 1 month ago 
318
| * 35e47bd 1 year, 1 month ago 
319
| *   dc02736 1 year, 1 month ago 
320
| |\  
321
| | * e7a9e9d 1 year, 1 month ago 
322
| | * 8fa965e 1 year, 1 month ago 
323
| * | 833cd1b 1 year, 1 month ago 
324
| |/  
325
| * 888bd39 1 year, 1 month ago 
326
| * 2eb0cb0 1 year, 1 month ago 
327
| * 21b4340 1 year, 1 month ago 
328
| * 9b31ee8 1 year, 1 month ago 
329
| *   88909db 1 year, 1 month ago 
330
| |\  
331
| | * 1cd646f 1 year, 1 month ago 
332
| | * 46a6136 1 year, 1 month ago 
333
| | * e8ed587 1 year, 1 month ago 
334
| | * e1acb6e 1 year, 1 month ago 
335
| | * 255d337 1 year, 1 month ago 
336
| | * 1ac448e 1 year, 1 month ago 
337
| | * 9a230f5 1 year, 1 month ago 
338
| | * 7a29faa 1 year, 1 month ago 
339
| | * ead86eb 1 year, 1 month ago 
340
| | * 0467640 1 year, 1 month ago 
341
| | * 6b33658 1 year, 1 month ago 
342
| | * 6f6df3a 1 year, 1 month ago 
343
| | * 25f7c35 1 year, 1 month ago 
344
| | * c7c8c09 1 year, 1 month ago 
345
| | * bb2544d 1 year, 1 month ago 
346
| | * a321df7 1 year, 1 month ago 
347
| | * 5f4e412 1 year, 1 month ago 
348
| | * da7eef1 1 year, 1 month ago 
349
| * | b13ed99 1 year, 1 month ago 
350
| * | 262048f 1 year, 1 month ago 
351
| * | 3946576 1 year, 1 month ago 
352
| |/  
353
| * 8fb334a 1 year, 1 month ago 
354
| * daf7496 1 year, 1 month ago 
355
| * 36da80b 1 year, 1 month ago 
356
| * 8a8f77b 1 year, 1 month ago 
357
| *   6e4e3b2 1 year, 1 month ago 
358
| |\  
359
| | *   100717d 2 years ago 
360
| | |\  
361
| | | * 2eab07f 2 years ago 
362
| | * | 99cc367 2 years ago 
363
| | * | 544a2e9 2 years ago 
364
| | * | 697e109 2 years ago 
365
| | * | a109663 2 years ago 
366
| | * | 4fa89f5 2 years ago 
367
| | * | 12c82dc 2 years ago 
368
| | * | bee0d4a 2 years ago 
369
| | * | 1e3ad86 2 years ago 
370
| | * | f2373ec 2 years ago 
371
| | * | c292f74 2 years ago 
372
| | * | 527595c 2 years ago 
373
| | |/  
374
| | * e820bc7 2 years, 1 month ago 
375
| | * 72f32ef 2 years, 1 month ago 
376
| | * d9cae0d 2 years, 1 month ago 
377
| | * b42acf5 2 years, 1 month ago 
378
| * 1c59ffe 1 year, 1 month ago 
379
| * 8fa9142 1 year, 1 month ago 
380
| * 45ee611 1 year, 1 month ago 
381
|/  
382
* 51d0fe4 1 year, 1 month ago 
383
```

**Comment by soroshsabz** [comment]
#1804

**Comment by soroshsabz** [comment]
Any update for this?

**Comment by soroshsabz** [comment]
I found another issue in this area

```
Cake.exe :   ERROR [01/23/20 13:46:43:99] An unexpected error occurred:
195
At C:\projects\commons\Build\build.ps1:241 char:1
196
+ &$CAKE_EXE $cakeArguments
197
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
198
    + CategoryInfo          : NotSpecified: (  ERROR [01/23/...error occurred::String) [], RemoteException
199
    + FullyQualifiedErrorId : NativeCommandError
200
 
201
LibGit2Sharp.CheckoutConflictException: 14 conflicts prevent checkout
202
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
203
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result)
204
   at Li
205
bGit2Sharp.Core.Proxy.git_checkout_tree(RepositoryHandle repo, ObjectId treeId, GitCheckoutOpts& opts)
206
   at LibGit2Sharp.Repository.CheckoutTree(Tree tree, IList`1 paths, IConvertableToGitCheckoutOpts opts)
207
   at LibGit2Sharp.Repository.Checkout(Tree tree, IEnumerable`1 paths, CheckoutOptions options)
208
   at LibGit2Sharp.Commands.Checkout(IRepository repository, Tree tree, CheckoutOptions checkoutOptions, String refLogHeadSpec)
209
   at LibGit2Sharp.Commands.Checkout(IRepository repository, Branch branch, CheckoutOptions options)
210
   at LibGit2Sharp.Commands.Checkout(IRepository repository, String committishOrBranchSpec, CheckoutOptions options)
211
   at LibGit2Sharp.Commands.Checkout(IRepository repository, String committishOrBranchSpec)
212
   at GitVersion.Helpers.GitRepositoryHelper.EnsureLocalBranchExistsForCurrentBranch(ILog log, Repository repo, Remote remote, String currentBranch)
213
   at GitVersion.Helpers.GitRepositoryHelper.NormalizeGitDirectory(ILog log, IEnvironment environment, String gitDirectory, AuthenticationInfo authentication, Boolean noFetch, String currentBranch, Boolean isDynamicRepository)
214
   at GitVersion.GitPreparer.NormalizeGitDirectory(AuthenticationInfo auth, String targetBranch, String gitDirectory, Boolean isDynamicRepository)
215
   at GitVersion.GitPreparer.Prepare(Boolean normalizeGitDirectory, String currentBranch, Boolean shouldCleanUpRemotes)
216
   at GitVersion.GitVersionCalculator.CalculateVersionVariables()
217
   at GitVersion.ExecCommand.Execute()
218
   at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments)
219
220
  INFO [01/23/20 13:46:43:99] 
```

**Comment by asbjornu** [comment]
Perhaps our resident Cake expert has an idea what may be going on here? @gep13

**Comment by soroshsabz** [comment]
@asbjornu Did you have any idea to how can I debug this error? and where I can start it?

thanks

**Comment by asbjornu** [comment]
You can try to normalize the Git repository before running GitVersion and see if that helps. [Something along these lines](https://github.com/SwedbankPay/swedbank-pay-magento2-checkout/blob/6a6b56f54ee51780d4b018bc81b19b3ea7f2ce0e/.travis.yml#L18-L22):

```yaml
before_install:
- git fetch --unshallow || true # Travis might do a shallow clone, but GitVersion needs the full history including branches and tags
- git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
- git fetch origin
- git branch master origin/master || true # GitVersion seems to require a local "master" branch these days. That's a bug, but oh well.
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then git checkout -b "$TRAVIS_PULL_REQUEST_BRANCH-pr"; fi # Create an explicit branch on pull requests as I'm unable to pass Git_Branch into the Docker container for some
```

**Comment by soroshsabz** [comment]
@asbjornu Thanks for response, but I use AppVeyor, after I try some investigation for problem, I found on bug that if I have detached HEAD, GitVersion does not work. after I do some workaround about that, I have another bug like below ( you can see this human readable at [AppVeyor](https://ci.appveyor.com/project/soroshsabz/commons/builds/30495965) )


```
INFO [01/31/20 20:00:02:43] Working directory: C:\projects\commons\Build
250
INFO [01/31/20 20:00:02:43] IsDynamicGitRepository: False
251
INFO [01/31/20 20:00:02:47] Returning Project Root from DotGitDirectory: C:\projects\commons\.git\ - C:\projects\commons\
252
INFO [01/31/20 20:00:02:47] Running on Windows.
253
INFO [01/31/20 20:00:02:47] Applicable build agent found: 'AppVeyor'.
254
INFO [01/31/20 20:00:02:47] Branch from build environment: master
255
INFO [01/31/20 20:00:02:47] Begin: Normalizing git directory for branch 'master'
256
  INFO [01/31/20 20:00:02:53] One remote found (origin -> 'https://github.com/BSVN/Commons.git').
257
  INFO [01/31/20 20:00:02:53] Fetching from remote 'origin' using the following refspecs: +refs/heads/*:refs/remotes/origin/*.
258
  INFO [01/31/20 20:00:02:83] Updating local branch refs/heads/master to match ref master
259
  INFO [01/31/20 20:00:02:91] HEAD points at branch 'refs/heads/master'.
260
  INFO [01/31/20 20:00:02:91] End: Normalizing git directory for branch 'master' (Took: 434.31ms)
261
Cake.exe :   ERROR [01/31/20 20:00:02:93] An unexpected error occurred:
262
At C:\projects\commons\Build\build.ps1:241 char:1
263
+ &$CAKE_EXE $cakeArguments
264
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
265
    + CategoryInfo          : NotSpecified: (  ERROR [01/31/...error occurred::String) [], RemoteException
266
    + FullyQualifiedErrorId : NativeCommandError
267
 
268
GitVersion.Exceptions.BugException: GitVersion has a bug, your HEAD has moved after repo normalisation.
269
270
To disable this error set an environmental variable called IGNORE_NORMALISATION_GIT_HEA
271
D_MOVE to 1
272
273
Please run `git log --graph --format="%h %cr %d" --decorate --date=relative --all --remotes=* -n 100` and submit it along with your build log (with personal info removed) in a new issue at https://github.com/GitTools/GitVersion
274
   at GitVersion.Helpers.GitRepositoryHelper.NormalizeGitDirectory(ILog log, IEnvironment environment, String gitDirectory, AuthenticationInfo authentication, Boolean noFetch, String currentBranch, Boolean isDynamicRepository)
275
   at GitVersion.GitPreparer.NormalizeGitDirectory(AuthenticationInfo auth, String targetBranch, String gitDirectory, Boolean isDynamicRepository)
276
   at GitVersion.GitPreparer.Prepare(Boolean normalizeGitDirectory, String currentBranch, Boolean shouldCleanUpRemotes)
277
   at GitVersion.GitVersionCalculator.CalculateVersionVariables()
278
   at GitVersion.ExecCommand.Execute()
279
   at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments)
280
281
  INFO [01/31/20 20:00:02:93] 
282
  INFO [01/31/20 20:00:02:93] Attempting to show the current git graph (please include in issue): 
283
  INFO [01/31/20 20:00:02:93] Showing max of 100 commits
284
  INFO [01/31/20 20:00:03:06] *   9ad1d3b 84 seconds ago  (newbranch)
285
|\  
286
| * 30ec779 3 minutes ago 
287
| * ba7cf10 5 minutes ago 
288
| * 4b297e9 10 minutes ago 
289
| * 837066e 21 minutes ago 
290
| * 2d1879c 27 minutes ago 
291
| * 4cc8cb3 35 minutes ago 
292
| * ebd65cd 47 minutes ago 
293
| * 54075cd 52 minutes ago 
294
| * 6aaf63c 55 minutes ago 
295
| * c851a72 2 hours ago 
296
| * 5059364 2 hours ago 
297
| * 8494911 2 hours ago 
298
| * db6c368 7 days ago 
299
| * 04e276c 7 days ago 
300
|/  
301
*   676e24c 7 days ago  (HEAD -> master, origin/master, origin/HEAD)
302
|\  
303
| * 0918d56 7 days ago 
304
| * 22c2f69 7 days ago 
305
| * f70af64 7 days ago 
306
| * ba498af 8 days ago 
307
| * 1bce9af 8 days ago 
308
| * 6703d86 8 days ago 
309
| * 97cb2bb 8 days ago 
310
| * 3accada 8 days ago 
311
| * 2a600fc 8 days ago 
312
| * 9ff5ab1 8 days ago 
313
| * bcaa5ad 8 days ago 
314
| * 628faf7 8 days ago 
315
| * 5b497ed 12 days ago 
316
| * 346f365 12 days ago 
317
| * c069184 12 days ago 
318
| * 8644877 12 days ago 
319
|/  
320
*   149660b 3 weeks ago  (tag: 1.6.1)
321
|\  
322
| * ea9ebab 3 weeks ago 
323
| * 2d65e83 3 weeks ago 
324
| * d797580 3 weeks ago 
325
| * bd783d4 3 weeks ago 
326
| * c03de1a 3 weeks ago 
327
| * 7ebf06c 3 weeks ago 
328
|/  
329
*   637d0d6 7 weeks ago  (tag: 1.6.0)
330
|\  
331
| * 002d026 7 weeks ago 
332
* | 21af707 7 weeks ago 
333
|\| 
334
| * 57ffbdf 7 weeks ago 
335
* | 13946f6 7 weeks ago  (tag: 1.5.0)
336
|\| 
337
| * 7813c43 7 weeks ago 
338
| * 65c29ee 7 weeks ago 
339
| * f488a9b 7 weeks ago 
340
| * 93c4279 7 weeks ago 
341
| * 77a2094 7 weeks ago 
342
| * 0a9507c 7 weeks ago 
343
| * 427ffe0 7 weeks ago 
344
| * f4b7c5a 7 weeks ago 
345
| * 89d900c 7 weeks ago 
346
| * 9821399 7 weeks ago 
347
| * e886146 7 weeks ago 
348
| *   7509056 7 weeks ago 
349
| |\  
350
| |/  
351
|/|   
352
* |   7065f14 8 weeks ago  (tag: 1.4.2)
353
|\ \  
354
| * | 00c1289 8 weeks ago 
355
| * | 54dec8e 8 weeks ago 
356
| * | 3f1e15c 8 weeks ago 
357
| * | 12b065a 8 weeks ago 
358
| * | 3a9502d 8 weeks ago 
359
| * | f37b910 8 weeks ago 
360
| * | d9e4a00 8 weeks ago 
361
| * | fbe18ef 8 weeks ago 
362
| * | 37611db 8 weeks ago 
363
| * | c81c709 8 weeks ago 
364
| * | e54c890 8 weeks ago 
365
| * |   c5eb936 8 weeks ago 
366
| |\ \  
367
| | * | e156da7 9 weeks ago 
368
| | * | 5f9bf93 9 weeks ago 
369
| |/ /  
370
|/| |   
371
| * | a269dcc 8 weeks ago 
372
|/ /  
373
* |   9e71812 1 year, 3 months ago 
374
|\ \  
375
* \ \   a6bb84a 1 year, 3 months ago 
376
|\ \ \  
377
| | | * 4ba8bb1 1 year, 3 months ago 
378
| | | * 924db04 1 year, 3 months ago 
379
| | | * ff0b9a4 1 year, 3 months ago 
380
| | | * 6c40c57 1 year, 3 months ago 
381
| | |/  
382
| | * d6d1d0e 1 year, 3 months ago 
383
| |/  
384
| * 8c58fa9 1 year, 3 months ago 
385
| * 65d3b02 1 year, 3 months ago 
386
| * df575d2 1 year, 3 months ago 
387
| * c3268a1 1 year, 3 months ago 
388
| * 35e47bd 1 year, 3 months ago 
389
| *   dc02736 1 year, 3 months ago 
390
| |\  
391
| | * e7a9e9d 1 year, 3 months ago 
392
| | * 8fa965e 1 year, 3 months ago 
393
| * | 833cd1b 1 year, 3 months ago 
394
| |/  
395
| * 888bd39 1 year, 3 months ago 
396
| * 2eb0cb0 1 year, 3 months ago 
397
| * 21b4340 1 year, 3 months ago 
398
| * 9b31ee8 1 year, 3 months ago 
399
| *   88909db 1 year, 3 months ago 
400
| |\  
401
| | * 1cd646f 1 year, 3 months ago 
402
| | * 46a6136 1 year, 3 months ago 
403
| | * e8ed587 1 year, 3 months ago 
404
| | * e1acb6e 1 year, 3 months ago 
405
| | * 255d337 1 year, 3 months ago 
406
| | * 1ac448e 1 year, 3 months ago 
407
| | * 9a230f5 1 year, 3 months ago 
408
409

```

**Comment by casz** [comment]
May I suggest a simpler version of your gitversion on appveyor:

https://github.com/nmklotas/GitLabApiClient/blob/master/appveyor.yml

Then using https://github.com/nmklotas/GitLabApiClient/blob/a468a5c1b43b1d4024e669e8917a935c3a0959d5/src/GitLabApiClient/GitLabApiClient.csproj#L31-L48

You could optionally depend on GitVersionTask to have properly bump assembly files.
