### ISSUE TITLE
Invalid argument in UseGitVersion VS Task

### ISSUE THREAD

**Issue by bernard-arnaud** [GitTools/GitVersion#1997]
Hi,

We're having issues when using the UseGitVersion task on a dotnetcore 3.1 project.
Here are the logs :

```
Starting: UseGitVersion
==============================================================================
Task         : GitVersion Task
Description  : Easy Semantic Versioning (http://semver.org) for projects using Git
Version      : 5.1.2
Author       : GitVersion Contributors
Help         : See the [documentation](http://gitversion.readthedocs.org/en/latest/) for help
==============================================================================

--------------------------
Installing GitVersion.Tool version 5.1
--------------------------
/opt/hostedtoolcache/dncs/3.1.100/x64/dotnet tool install GitVersion.Tool --tool-path /home/vsts/work/_temp --version 5.1.2
You can invoke the tool using the following command: dotnet-gitversion
Tool 'gitversion.tool' (version '5.1.2') was successfully installed.
Caching tool: GitVersion.Tool 5.1.2 x64
##[error]Error: EINVAL: invalid argument, readlink '/opt/hostedtoolcache/dncs/3.1.100/x64/dotnet'
Finishing: UseGitVersion
```

And here's the yaml part of the task :

```yaml

  - task: UseGitVersion@5
    inputs:
      versionSpec: '5.1'
      updateAssemblyInfo: true
```

**Comment by arturcic** [comment]
Version 5.1.2 targets .net core 3.0, we have not released a version that works on 3.1

**Comment by bernard-arnaud** [comment]
Do you know if 3.1 support is planned in a future release ?

**Comment by arturcic** [comment]
Yes, version 5.1.3 when released

**Comment by neolution-ch** [comment]
Just tried that by using 5.1.3, but the issue persists

```
2020-01-27T10:25:00.6229190Z ##[section]Starting: UseGitVersion
2020-01-27T10:25:00.6232209Z ==============================================================================
2020-01-27T10:25:00.6232282Z Task         : GitVersion Task
2020-01-27T10:25:00.6232318Z Description  : Easy Semantic Versioning (http://semver.org) for projects using Git
2020-01-27T10:25:00.6232417Z Version      : 5.1.2
2020-01-27T10:25:00.6232456Z Author       : GitVersion Contributors
2020-01-27T10:25:00.6232493Z Help         : See the [documentation](http://gitversion.readthedocs.org/en/latest/) for help
2020-01-27T10:25:00.6232569Z ==============================================================================
2020-01-27T10:25:03.5865497Z 
2020-01-27T10:25:03.5866276Z --------------------------
2020-01-27T10:25:03.5866448Z Installing GitVersion.Tool version 5.x
2020-01-27T10:25:03.5866766Z --------------------------
2020-01-27T10:25:04.2829229Z [command]/opt/hostedtoolcache/dotnet/dotnet tool install GitVersion.Tool --tool-path /home/vsts/work/_temp --version 5.1.3
2020-01-27T10:25:09.9043891Z 
2020-01-27T10:25:09.9044799Z Welcome to .NET Core 3.1!
2020-01-27T10:25:09.9046153Z ---------------------
2020-01-27T10:25:09.9046441Z SDK Version: 3.1.101
2020-01-27T10:25:09.9046650Z 
2020-01-27T10:25:09.9046876Z Telemetry
2020-01-27T10:25:09.9047383Z ---------
2020-01-27T10:25:09.9048239Z The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.
2020-01-27T10:25:09.9048443Z 
2020-01-27T10:25:09.9048933Z Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry
2020-01-27T10:25:09.9049126Z 
2020-01-27T10:25:09.9049483Z ----------------
2020-01-27T10:25:09.9049950Z Explore documentation: https://aka.ms/dotnet-docs
2020-01-27T10:25:09.9050162Z Report issues and find source on GitHub: https://github.com/dotnet/core
2020-01-27T10:25:09.9050566Z Find out what's new: https://aka.ms/dotnet-whats-new
2020-01-27T10:25:09.9051069Z Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
2020-01-27T10:25:09.9051514Z Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
2020-01-27T10:25:09.9051929Z Write your first app: https://aka.ms/first-net-core-app
2020-01-27T10:25:09.9052429Z --------------------------------------------------------------------------------------
2020-01-27T10:25:09.9052855Z You can invoke the tool using the following command: dotnet-gitversion
2020-01-27T10:25:09.9053331Z Tool 'gitversion.tool' (version '5.1.3') was successfully installed.
2020-01-27T10:25:09.9100939Z Caching tool: GitVersion.Tool 5.1.3 x64
2020-01-27T10:25:11.1406677Z ##[error]Error: EINVAL: invalid argument, readlink '/opt/hostedtoolcache/dotnet/dotnet'
2020-01-27T10:25:11.3557532Z ##[section]Finishing: UseGitVersion
```

Is there another problem? Haven't had an issue so far on our local Windows buildservers, but the error above occured on a `Ubuntu-16.04` image.

**Comment by nloum** [comment]
I'm getting this issue as well on Ubuntu 18.04 in GitHub Actions, with both .NET Core SDK 3.1.101 and .NET Core SDK 2.2.108.

**Comment by dnperfors** [comment]
I ran the following task using dotnet core sdk 3.1.101:
```
  - task: gittools.usegitversion.gitversion-task.UseGitVersion@5
    displayName: 'Calculate version number'
    inputs:
      versionSpec: 5.x
```
and got the following debug output:
```
--------------------------
Installing GitVersion.Tool version 5.x
--------------------------
##[debug]isExplicit: null
##[debug]explicit? false
##[debug]isExplicit: null
##[debug]explicit? false
##[debug]Agent.Version=2.164.0
##[debug]Agent.ToolsDirectory=/workspace/_tool
##[debug]isExplicit: 5.1.3
##[debug]explicit? true
##[debug]evaluating 1 versions
##[debug]matched: 5.1.3
##[debug]Agent.Version=2.164.0
##[debug]Agent.ToolsDirectory=/workspace/_tool
##[debug]checking cache: /workspace/_tool/GitVersion.Tool/5.1.3/x64
Found tool in cache: GitVersion.Tool 5.1.3 x64
##[debug]toolPath: /workspace/_tool/GitVersion.Tool/5.1.3/x64
##[debug]which 'dotnet'
##[debug]found: '/workspace/_tool/dncs/3.1.101/x64/dotnet'
##[debug]Error: EINVAL: invalid argument, readlink '/workspace/_tool/dncs/3.1.101/x64/dotnet'
    at Error (native)
    at Object.fs.readlinkSync (fs.js:1028:18)
    at ToolInstaller.<anonymous> (/workspace/_tasks/UseGitVersion_bab30d5c-39f3-49b0-a7db-9a5da6676eaa/5.1.2/ToolInstaller.js:54:50)
    at next (native)
    at /workspace/_tasks/UseGitVersion_bab30d5c-39f3-49b0-a7db-9a5da6676eaa/5.1.2/ToolInstaller.js:8:71
    at __awaiter (/workspace/_tasks/UseGitVersion_bab30d5c-39f3-49b0-a7db-9a5da6676eaa/5.1.2/ToolInstaller.js:4:12)
    at ToolInstaller.downloadAndInstall (/workspace/_tasks/UseGitVersion_bab30d5c-39f3-49b0-a7db-9a5da6676eaa/5.1.2/ToolInstaller.js:24:16)
    at GitVersionTask.<anonymous> (/workspace/_tasks/UseGitVersion_bab30d5c-39f3-49b0-a7db-9a5da6676eaa/5.1.2/GitVersion.js:87:66)
    at next (native)
    at /workspace/_tasks/UseGitVersion_bab30d5c-39f3-49b0-a7db-9a5da6676eaa/5.1.2/GitVersion.js:8:71
##[debug]task result: Failed
##[error]Error: EINVAL: invalid argument, readlink '/workspace/_tool/dncs/3.1.101/x64/dotnet'
##[debug]Processed: ##vso[task.issue type=error;]Error: EINVAL: invalid argument, readlink '/workspace/_tool/dncs/3.1.101/x64/dotnet'
##[debug]Processed: ##vso[task.complete result=Failed;done=true;]Error: EINVAL: invalid argument, readlink '/workspace/_tool/dncs/3.1.101/x64/dotnet'
```
Hopefully it helps.

**Comment by arturcic** [comment]
Can you try this new extension https://marketplace.visualstudio.com/items?itemName=gittools.gittools? The UseGitversion will not be updated so any fixes will be done there

**Comment by neolution-ch** [comment]
@arturcic So `GitTools` is now ready for consumption? Because [just a few days ago](https://github.com/GitTools/GitVersion/issues/2050#issuecomment-576340184) `UseGitVersion` was the recommended way to go.

**Comment by arturcic** [comment]
Not yet but o need feedback and you can give it a try

**Comment by dnperfors** [comment]
I did try it with `GitTools` and got the same error when running the setup task:

```
--------------------------
Installing GitVersion.Tool version 5.1.x
--------------------------
##[debug]isExplicit: null
##[debug]explicit? false
##[debug]isExplicit: null
##[debug]explicit? false
##[debug]Agent.Version=2.164.0
##[debug]Agent.ToolsDirectory=/workspace/_tool
##[debug]isExplicit: 5.1.2
##[debug]explicit? true
##[debug]isExplicit: 5.1.3
##[debug]explicit? true
##[debug]evaluating 2 versions
##[debug]matched: 5.1.3
##[debug]Agent.Version=2.164.0
##[debug]Agent.ToolsDirectory=/workspace/_tool
##[debug]checking cache: /workspace/_tool/GitVersion.Tool/5.1.3/x64
Found tool in cache: GitVersion.Tool 5.1.3 x64
##[debug]toolPath: /workspace/_tool/GitVersion.Tool/5.1.3/x64
##[debug]which 'dotnet'
##[debug]found: '/workspace/_tool/dncs/3.1.100/x64/dotnet'
##[debug]task result: Failed
##[error]EINVAL: invalid argument, readlink '/workspace/_tool/dncs/3.1.100/x64/dotnet'
##[debug]Processed: ##vso[task.issue type=error;]EINVAL: invalid argument, readlink '/workspace/_tool/dncs/3.1.100/x64/dotnet'
##[debug]Processed: ##vso[task.complete result=Failed;done=true;]EINVAL: invalid argument, readlink '/workspace/_tool/dncs/3.1.100/x64/dotnet'
```

**Comment by Breederveld** [comment]
Not sure if this helps anyone, but moving the dotnet executable and replacing it with a symlink to the new location solves this issue.
So this can be used as a work-around and also points to the problem: the readlink command returns no value if the original file is referenced and this is somehow not correctly resolved in the tool.

**Comment by dnperfors** [comment]
That is not the best workaround when you install dotnet using the installer task from azure devops, since it requires an ugly script to do that.

**Comment by Breederveld** [comment]
@dnperfors I agree it's not the nicest work-around, but it is currently the best as it is the only one I have seen so far. If you know of a better one, I would really like to hear it as I'm also struggling with the same issue.

**Comment by dnperfors** [comment]
@Breederveld, The workaround I am thinking about now would be to just use a bash scripts instead of these build tasks... Not sure how readable these will be though...
