### ISSUE TITLE
GitVersion 5.1.3 - Sequence contains more than one matching element on PR to master

### ISSUE THREAD

**Issue by jamiemcdade** [GitTools/GitVersion#2007]
Using dotnet tool 5.1.3 with Mainline mode on AppVeyor:

```
INFO [12/23/19 21:17:16:67] Begin: Loading version variables from disk cache

    INFO [12/23/19 21:17:16:67] Cache file C:\projects\myproject\.git\gitversion_cache\36ACD0955BB57396A71A360439FEEF4259779710.yml not found.
  INFO [12/23/19 21:17:16:67] End: Loading version variables from disk cache (Took: 1.12ms)
dotnet-gitversion :   ERROR [12/23/19 21:17:16:95] An unexpected error occurred:
At line:1 char:1
+ dotnet-gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output build ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (  ERROR [12/23/...error occurred::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at GitVersio
n.GitVersionContext.GetTargetBranch(IRepository repository, String targetBranch) in D:\a\1\s\src\GitVersionCore\GitVersionContext.cs:line 177
   at GitVersion.GitVersionCalculator.<>c__DisplayClass14_0.<ExecuteInternal>b__0(IRepository repo) in D:\a\1\s\src\GitVersionCore\GitVersionCalculator.cs:line 111
   at GitVersion.Extensions.LibGitExtensions.WithRepository[TResult](String dotGitDirectory, Func`2 action) in D:\a\1\s\src\GitVersionCore\Extensions\LibGitExtensions.cs:line 17
   at GitVersion.GitVersionCalculator.GetCachedGitVersionInfo(String targetBranch, String commitId, Config overrideConfig, Boolean noCache) in D:\a\1\s\src\GitVersionCore\GitVersionCalculator.cs:line 85
   at GitVersion.GitVersionCalculator.CalculateVersionVariables() in D:\a\1\s\src\GitVersionCore\GitVersionCalculator.cs:line 65
   at GitVersion.ExecCommand.Execute() in D:\a\1\s\src\GitVersionExe\ExecCommand.cs:line 40
   at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments) in D:\a\1\s\src\GitVersionExe\GitVersionExecutor.cs:line 117
```

**Comment by asbjornu** [comment]
Can you please try version 5.2.4? If you are able to reproduce, we'll get a relevant stack trace, if nothing else. :)
