### ISSUE TITLE
5.1.4-linux Docker Image - git executable is missing

### ISSUE THREAD

**Issue by jonstelly** [GitTools/GitVersion#2124]
Trying to run:

`docker run --rm -it -v ${PWD}:/code gittools/gitversion:5.1.4-linux /code`

I accidentally ran this command from a submodule instead of my main repository and there's some error that happens when running it from a submodule.  It seems that the `.git` directory is actually a file and not a directory in a submodule, the file contains a reference to the git module contained in the parent's `.git` directory.

I don't really need that scenario to work, but the real issue seems to be that if gitversion gets an error, it tries to run git directly to get the branch tree and git log and the `git` executable is missing from the docker images, which makes the exception a bit confusing:

```log
System.IO.DirectoryNotFoundException: Can't find the .git directory in 
   at GitVersion.GitPreparer.GetProjectRootDirectoryInternal() in D:\a\GitVersion\GitVersion\src\GitVersionCore\GitPreparer.cs:line 92
   at GitVersion.GitPreparer.GetProjectRootDirectory() in D:\a\GitVersion\GitVersion\src\GitVersionCore\GitPreparer.cs:line 27
   at GitVersion.Configuration.ConfigFileLocator.Verify(IGitPreparer gitPreparer) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Configuration\ConfigFileLocator.cs:line 61
   at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments) in D:\a\GitVersion\GitVersion\src\GitVersionExe\GitVersionExecutor.cs:line 105INFO [02/22/20 18:43:06:81] INFO [02/22/20 18:43:06:81] Attempting to show the current git graph (please include in issue): INFO [02/22/20 18:43:06:81] Showing max of 100 commitsINFO [02/22/20 18:43:06:82] Could not execute 'git log' due to the following error:
System.IO.FileNotFoundException: The executable file 'git' could not be found.
File name: 'git' ---> System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at GitVersion.Helpers.ProcessHelper.Start(ProcessStartInfo startInfo) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Helpers\ProcessHelper.cs:line 20
   at GitVersion.Helpers.ProcessHelper.Start(ProcessStartInfo startInfo) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Helpers\ProcessHelper.cs:line 42
   at GitVersion.Helpers.ProcessHelper.Run(Action`1 output, Action`1 errorOutput, TextReader input, String exe, String args, String workingDirectory, KeyValuePair`2[] environmentalVariables) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Helpers\ProcessHelper.cs:line 120
   at GitVersion.Extensions.LibGitExtensions.DumpGraph(String workingDirectory, Action`1 writer, Nullable`1 maxCommits)

**Comment by arturcic** [comment]
That is because when GitVersion fails it tries to run git log --graph

**Comment by asbjornu** [comment]
I agree GitVersion could behave more gracefully in this circumstance. If you have ideas for a PR that fixes this, please submit one, @jonstelly. As I have no use for running GitVersion in submodules myself, I don't think I'll find time to do it.

**Comment by metalfork** [comment]
I have been dealing with similar issue for a while.
```
  INFO [04/10/20 17:06:52:73] End: Attempting to inherit branch configuration from parent branch (Took: 54.16ms)
  ERROR [04/10/20 17:06:52:75] An unexpected error occurred:
System.InvalidOperationException: Could not find a 'develop' or 'master' branch, neither locally nor remotely.
   at GitVersion.Configuration.BranchConfigurationCalculator.InheritBranchConfiguration(Branch targetBranch, BranchConfig branchConfiguration, IList`1 excludedInheritBranches)
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfiguration(Branch targetBranch, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Configuration\BranchConfigurationCalculator.cs:line 40
   at GitVersion.GitVersionContext.CalculateEffectiveConfiguration() in D:\a\GitVersion\GitVersion\src\GitVersionCore\GitVersionContext.cs:line 86
   at GitVersion.GitVersionContext..ctor(IRepository repository, ILog log, Branch currentBranch, Config configuration, Boolean onlyTrackedBranches, String commitId) in D:\a\GitVersion\GitVersion\src\GitVersionCore\GitVersionContext.cs:line 60
   at GitVersion.GitVersionCalculator.ExecuteInternal(Arguments arguments) in D:\a\GitVersion\GitVersion\src\GitVersionCore\GitVersionCalculator.cs:line 67
   at GitVersion.GitVersionCalculator.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersionCore\GitVersionCalculator.cs:line 45
   at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments) in D:\a\GitVersion\GitVersion\src\GitVersionExe\GitVersionExecutor.cs:line 61
  INFO [04/10/20 17:06:52:75] Attempting to show the current git graph (please include in issue):
  INFO [04/10/20 17:06:52:75] Showing max of 100 commits
  INFO [04/10/20 17:06:52:76] Could not execute 'git log' due to the following error:
System.IO.FileNotFoundException: The executable file 'git' could not be found.
```
