### ISSUE TITLE
GitVersion failure due to stale branch name collision

### ISSUE THREAD

**Issue by tbergstedt** [GitTools/GitVersion#2173]
We have previously pushed a branch `teams/team_1` but deleted it since. Now when we try to use a branch` teams/team_1/feature_1`, i.e. try to expand the branch structure, GitVersion fails with
```
  INFO [03/11/20 9:14:16:16] Creating local branch from remote tracking 'refs/remotes/origin/teams/team_1/feature_1'.
INFO [03/11/20 9:14:16:21] End: Normalizing git directory for branch 'refs/heads/master' (Took: 17,421.17ms)
ERROR [03/11/20 9:14:16:21] An unexpected error occurred:
LibGit2Sharp.LibGit2SharpException: could not remove directory 'C:/agent/_work/1/s/.git/refs/heads/teams/team_1/feature_1': parent is not directory: The system cannot find the path specified.

   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_reference_create(RepositoryHandle repo, String name, ObjectId targetId, Boolean allowOverwrite, String logMessage)
   at LibGit2Sharp.ReferenceCollection.Add(String name, ObjectId targetId, String logMessage, Boolean allowOverwrite)
   at LibGit2Sharp.ReferenceCollection.Add(String name, ObjectId targetId, Boolean allowOverwrite)
   at GitTools.Git.GitRepositoryHelper.CreateOrUpdateLocalBranchesFromRemoteTrackingOnes(Repository repo, String remoteName)
   at GitTools.Git.GitRepositoryHelper.NormalizeGitDirectory(String gitDirectory, AuthenticationInfo authentication, Boolean noFetch, String currentBranch)
   at GitVersion.GitPreparer.Initialise(Boolean normaliseGitDirectory, String currentBranch, Boolean shouldCleanUpRemotes)
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache)
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
```
Not entirely sure if this is actually a GitVersion error (since it is LibGit2Sharp reporting it), but it is only during GitVersion operations we encounter it.

**Comment by asbjornu** [comment]
I doubt there's much we can do in GitVersion when it's LibGit2Sharp that throws this exception. I would suggest creating an issue in their repository to have this fixed there.
