### ISSUE TITLE
[Bug] GitVersion doesn't handle cross-platform path specifications

### ISSUE THREAD

**Issue by fourpastmidnight** [GitTools/GitVersion#2187]
## Description

I tried running `GitVersion /proj` based on the available documentation (currently, only what's provided by `GetVersion /help` and by looking through the source code. There is literally no documentation on using `/proj` and `projArgs`.

After looking at the source code, I also tried `GitVersion /proj GitVersion.props`.

### Update

I was originally running this from a Git for Windows bash shell. Since in the exception log below the paths were displayed with forward soliduses, I decided to try running the same command above in a PowerShell. Upon running this in PowerShell, no exceptions were thrown. So this seems to be a path handling issue in GitVersion.

## Expected Behavior

I expected either an implicit MS Build file to be created (per the ouput from `GitVersion /help`), or the explicitly named file (as shown in my second attempt under the description of this bug).

## Actual Behavior

GitVersion threw an exception:

```log
$ GitVersion /proj GitVersion.props /verbosity debug
WARN [03/17/20 10:34:17:17] The working directory 'C:/Program Files/Git/proj' does not exist.INFO [03/17/20 10:34:17:17] IsDynamicGitRepository: FalseERROR [03/17/20 10:34:17:21] An unexpected error occurred:
System.IO.DirectoryNotFoundException: Can't find the .git directory in
   at GitVersion.GitPreparer.GetProjectRootDirectoryInternal()
   at GitVersion.GitPreparer.GetProjectRootDirectory()
   at GitVersion.Configuration.ConfigFileLocator.Verify(IGitPreparer gitPreparer)
   at GitVersion.GitVersionExecutor.VerifyConfiguration()
   at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments)INFO [03/17/20 10:34:17:21] INFO [03/17/20 10:34:17:21] Attempting to show the current git graph (please include in issue): INFO [03/17/20 10:34:17:21] Showing max of 100 commitsERROR [03/17/20 10:34:17:24] Couldn't dump the git graph due to the following error: System.ComponentModel.Win32Exception (267): The directory name is invalid.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at GitVersion.Helpers.ProcessHelper.Start(ProcessStartInfo startInfo)
   at GitVersion.Helpers.ProcessHelper.Run(Action`1 output, Action`1 errorOutput, TextReader input, String exe, String args, String workingDirectory, KeyValuePair`2[] environmentalVariables)
   at GitVersion.Extensions.LibGitExtensions.DumpGraph(String workingDirectory, Action`1 writer, Nullable`1 maxCommits)
   at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments)
```

## Possible Fix

So that cross-platform builds can be performed on any operating system using GitVersion as a component of the build process, in any shell (i.e. bash, zsh, or PowerShell Core).

## Steps to Reproduce

1. Open a Git for Windows mintty bash terminal
2. Navigate to a git repository configured to use GitVersion
3. Execute: `GitVersion /proj`

## Context

Based on the scant documentation available for the `/proj` switch, I was expecting GitVersion to produce a MS Build project file containing properties of the various version components (as shown in the standard JSON output).

## Your Environment

- Version Used: 5.1.2
- Operating System and version (Windows 10, Ubuntu 18.04): Windows 10 1809
- Link to your project: Unavailable
- Link to your CI build (if appropriate):  Unavailable

**Comment by arturcic** [comment]
Unfortunately the these /proj and /exec will be removed in upcoming minor version, so I'd suggest to not use them, they are marked as obsolete.
