### ISSUE TITLE
gitversion.exe --help crashes

### ISSUE THREAD

**Issue by voltagex** [GitTools/GitVersion#2258]
**Describe the bug**
Running gitversion --help crashes.

## Expected Behavior
gitversion.exe --help to display help or point me to the documentation

## Actual Behavior

```
PS C:\Users\Adam\Downloads> .\gitversion.exe --help
Unhandled exception. GitVersion.WarningException: Could not parse command line parameter '--help'. If it is the target path, make sure it exists.
   at GitVersion.ArgumentParser.ParseTargetPath(Arguments arguments, String name, String[] values, String value, Boolean parseEnded)
   at GitVersion.ArgumentParser.ParseSwitchArguments(Arguments arguments, NameValueCollection switchesAndValues, Int32 i)
   at GitVersion.ArgumentParser.ParseArguments(String[] commandLineArguments)
   at GitVersion.Program.<>c__DisplayClass4_0.<CreateHostBuilder>b__2(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
```

## Steps to Reproduce

Grab the 5.3.2 exe from https://chocolatey.org/packages/GitVersion.Portable, try to run it with a flag

## Context
Just trying to see if there were any command line arguments available

## Your Environment

- Version Used:
- Operating System and version (Windows 10, Ubuntu 18.04): Windows 10
- Link to your project:
- Link to your CI build (if appropriate):

**Comment by svengeance** [comment]
You can use the `/help` instead, if that.. /helps.

**Comment by arturcic** [comment]
@voltagex `/help` or `-help` is currently supported, but we plan to work on new cli in version 6.0.0. For now use the ones I suggested
