### ISSUE TITLE
[Bug] LibGit2Sharp.LibGit2SharpException: remote authentication required but no callback set

### ISSUE THREAD

**Issue by nZeus** [GitTools/GitVersion#2293]
**Describe the bug**
I get `LibGit2Sharp.LibGit2SharpException: remote authentication required but no callback set` error when using GitVersion 5.3.4 on a private repo.

My GitHubAction file:

```yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Calculate version
      run: |
        dotnet tool restore
        dotnet tool run dotnet-gitversion
        NuGetVersionV2=$(dotnet tool run dotnet-gitversion /showvariable NuGetVersionV2)
        ShortSha=$(dotnet tool run dotnet-gitversion /showvariable ShortSha)
        PreReleaseLabel=$(dotnet tool run dotnet-gitversion /showvariable PreReleaseLabel)
        if [ -z "$PreReleaseLabel" ]; then PackageVersion="$NuGetVersionV2"; else PackageVersion="$NuGetVersionV2.$ShortSha"; fi
        echo $PackageVersion
        echo "::set-env name=PackageVersion::$PackageVersion"
```

## Actual Behavior
```
Tool 'gitversion.tool' (version '5.3.4') was restored. Available commands: dotnet-gitversion

Restore was successful.
INFO [05/27/20 21:58:45:41] Applicable build agent found: 'GitHubActions'.
INFO [05/27/20 21:58:45:43] Working directory: /home/runner/work/PV8.Releaser/PV8.Releaser
INFO [05/27/20 21:58:45:46] Branch from build environment: refs/heads/_gitversion
INFO [05/27/20 21:58:45:46] Project root is: /home/runner/work/PV8.Releaser/PV8.Releaser/
INFO [05/27/20 21:58:45:46] DotGit directory is: /home/runner/work/PV8.Releaser/PV8.Releaser/.git
INFO [05/27/20 21:58:45:46] Begin: Normalizing git directory for branch 'refs/heads/_gitversion'
  INFO [05/27/20 21:58:45:49] One remote found (origin -> 'https://github.com/eVisionSoftware/PV8.Releaser').
  INFO [05/27/20 21:58:45:49] Fetching from remote 'origin' using the following refspecs: +refs/heads/*:refs/remotes/origin/*.
  INFO [05/27/20 21:58:45:55] End: Normalizing git directory for branch 'refs/heads/_gitversion' (Took: 95.48ms)
  ERROR [05/27/20 21:58:45:57] An unexpected error occurred:
LibGit2Sharp.LibGit2SharpException: remote authentication required but no callback set
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteHandle remote, IEnumerable`1 refSpecs, GitFetchOptions fetchOptions, String logMessage)
   at LibGit2Sharp.Commands.Fetch(Repository repository, String remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage)
   at GitVersion.GitRepositoryCommands.Fetch(String remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitRepositoryCommands.cs:line 59
   at GitVersion.GitPreparer.NormalizeGitDirectory(String gitDirectory, Boolean noFetch, String currentBranch, Boolean isDynamicRepository) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 226
   at GitVersion.GitPreparer.NormalizeGitDirectory(String targetBranch, String gitDirectory, Boolean isDynamicRepository) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 141
   at GitVersion.GitPreparer.PrepareInternal(Boolean normalizeGitDirectory, String currentBranch, Boolean shouldCleanUpRemotes) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 69
   at GitVersion.GitPreparer.Prepare() in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 48
   at GitVersion.GitVersionTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitVersionTool.cs:line 61
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersionExe\GitVersionExecutor.cs:line 59
  INFO [05/27/20 21:58:45:57] Attempting to show the current git graph (please include in issue): 
  INFO [05/27/20 21:58:45:57] Showing max of 100 commits
  INFO [05/27/20 21:58:45:59] * 1bcf376 35 seconds ago  (grafted, HEAD -> _gitversion, origin/_gitversion)
```

## Your Environment
ubuntu-latest

- Version Used: 5.3.4
- Operating System and version (Windows 10, Ubuntu 18.04): ubuntu-latest
- Link to your project: <<<private>>>
- Link to your CI build (if appropriate): <<<private>>>

**Comment by asbjornu** [comment]
I don't think Ubuntu (Debian 10) is supported by LibGit2Sharp. Are you able to use one of our Docker images instead?

**Comment by nZeus** [comment]
It's a GitHub runner, not a lot to [choose from](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources).

I've tried Ubuntu 16.04.6 LTS, but got exactly the same error :(

**Comment by asbjornu** [comment]
If you're using GitHub Actions, isn't our [official actions](https://github.com/marketplace/actions/use-actions) better to use than to execute GitVersion yourself?

**Comment by nZeus** [comment]
Oh, I wasn't aware of it. Just tried the official action - it works! 
I guess this can be closed then?

**Comment by asbjornu** [comment]
Great!

**Comment by asbjornu** [comment]
Do you have a publicly available reproduction of it, @venkateswarara-tr?

**Comment by venkateswarara-tr** [comment]
sorry, no. tis is confidential one. i cannot do it in publicly.
