### ISSUE TITLE
[Bug] GitVersion ignoring custom credential helper auth when running in Azure Pipelines agent.

### ISSUE THREAD

**Issue by pauldotknopf** [GitTools/GitVersion#2312]
**Describe the bug**
Authentication asked for git repository, even though ```git ls-remote <URL>``` works.

## Expected Behavior
I expected ```gitversion``` to sit entirely on top of ```git``` and it's authentication mechanics. If ```git``` succeeds in pulling from ```origin```, so should ```gitversion```.

## Actual Behavior
The ```gitversion``` command is prompting for credentials.

## Steps to Reproduce

This happens in Azure Pipelines. I manually configure ```git```'s credential helper with a password that is stored via secrets. This works successfully, considering ```git ls-remote``` works properly.

```bash
dotnet tool install GitVersion.Tool --version 5.3.5 --tool-path /usr/bin/
# works
git ls-remote
# fails
dotnet gitversion
```

I am using a self-hosted agent. During debugging, I went into the running container and tried ```dotnet gitversion``` myself in a bash terminal, and it worked!

I figured then that ```gitversion``` was parsing some environment variables during the pipeline, causing the credential helper to fail.

So, I then put a ```printenv``` during the pipeline, and set every environment variable in my local bash prompt, and it failed again.

So, it appears that ```gitversion``` is some how figuring out that it is Azure Pipelines, and ignores any passwords that may be provided via ```git```'s credential helper.

Here is the error during the build:

```
INFO [06/06/20 19:06:42:62] Applicable build agent found: 'AzurePipelines'.
INFO [06/06/20 19:06:42:63] Working directory: /azp/agent/_work/1/s
INFO [06/06/20 19:06:42:64] Branch from build environment: refs/heads/git-version
INFO [06/06/20 19:06:42:64] Project root is: /azp/agent/_work/1/s/
INFO [06/06/20 19:06:42:64] DotGit directory is: /azp/agent/_work/1/s/.git
INFO [06/06/20 19:06:42:64] Begin: Normalizing git directory for branch 'refs/heads/git-version'
  INFO [06/06/20 19:06:42:66] One remote found (origin -> 'https://NDSsi@dev.azure.com/NDSsi/PUREVUE-G2/_git/recipes').
  INFO [06/06/20 19:06:42:66] Fetching from remote 'origin' using the following refspecs: +refs/heads/*:refs/remotes/origin/*.
  INFO [06/06/20 19:06:42:83] End: Normalizing git directory for branch 'refs/heads/git-version' (Took: 187.31ms)
  ERROR [06/06/20 19:06:42:86] An unexpected error occurred:
LibGit2Sharp.LibGit2SharpException: remote authentication required but no callback set
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteHandle remote, IEnumerable`1 refSpecs, GitFetchOptions fetchOptions, String logMessage)
   at LibGit2Sharp.Commands.Fetch(Repository repository, String remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage)
   at GitVersion.GitRepositoryCommands.Fetch(String remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitRepositoryCommands.cs:line 59
   at GitVersion.GitPreparer.NormalizeGitDirectory(String gitDirectory, Boolean noFetch, String currentBranch, Boolean isDynamicRepository) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 226
   at GitVersion.GitPreparer.NormalizeGitDirectory(String targetBranch, String gitDirectory, Boolean isDynamicRepository) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 141
   at GitVersion.GitPreparer.PrepareInternal(Boolean normalizeGitDirectory, String currentBranch, Boolean shouldCleanUpRemotes) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 69
   at GitVersion.GitPreparer.Prepare() in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 48
```

I am using version 5.3.5 on Ubuntu 18.

**Comment by pauldotknopf** [comment]
I verified that ```unset TF_BUILD``` fixes the build.

**Comment by asbjornu** [comment]
I don't think there's anything GitVersion can do about this, as it's LibGit2Sharp that takes care of the network communication. Or do you have an idea of what we can do in GitVersion to resolve this?

**Comment by pauldotknopf** [comment]
Considering that this problem is resolved by ```unset TF_BUILD```, I think component at fault would be the one that is using ```TF_BUILD``` internally, which I don't think ```git``` is, correct?

**Comment by pauldotknopf** [comment]
It looks like in ```GitVersion```, fetch is disabled because the ```TF_BUILD``` exists?

https://github.com/GitTools/GitVersion/blob/5b21b1cd63e49aaa6612d16b6c2b3e19e7cdba26/src/GitVersionCore/BuildAgents/AzurePipelines.cs#L34

Maybe ```GitVersion``` support a ```GIT_VERSION_DEFAULT_GIT=1``` env that prevents any customizations done to the fetching in ```libgit```?

**Comment by asbjornu** [comment]
Aha. Instead of leaving the normalization up to GitVersion, please try to normalize the Git directory yourself before executing GitVersion. Please see #2194 for GitVersion's requirements for successful execution.
