### ISSUE TITLE
[Bug] source-branch configuration is not validated and fails late in a confusing way

### ISSUE THREAD

**Issue by michaelnoonan** [GitTools/GitVersion#2349]
## Expected Behavior
I expected the configuration to be validated early, failing with a clear indication of what was wrong.

## Actual Behavior
GitVersion throws a `System.Collections.Generic.KeyNotFoundException`.

```
    System.Collections.Generic.KeyNotFoundException: The given key 'main' was not present in the dictionary.
13:04:34
       at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
13:04:34
       at GitVersion.RepositoryMetadataProvider.<>c__DisplayClass33_0.<GetMergeCommitsForBranch>b__0(String sb) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\RepositoryMetadataProvider.cs:line 475
13:04:34
       at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
13:04:34
       at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
13:04:34
       at GitVersion.RepositoryMetadataProvider.<>c__DisplayClass33_0.<GetMergeCommitsForBranch>b__1(Branch b) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\RepositoryMetadataProvider.cs:line 480
13:04:34
       at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
13:04:34
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
13:04:34
       at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
13:04:34
       at System.Linq.OrderedEnumerable`1.ToList()
13:04:34
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
13:04:34
       at GitVersion.RepositoryMetadataProvider.GetMergeCommitsForBranch(Branch branch, Config configuration, IEnumerable`1 excludedBranches) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\RepositoryMetadataProvider.cs:line 476
13:04:34
       at GitVersion.RepositoryMetadataProvider.FindCommitBranchWasBranchedFrom(Branch branch, Config configuration, Branch[] excludedBranches) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\RepositoryMetadataProvider.cs:line 333
13:04:34
       at GitVersion.Configuration.BranchConfigurationCalculator.InheritBranchConfiguration(Branch targetBranch, BranchConfig branchConfiguration, Commit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Configuration\BranchConfigurationCalculator.cs:line 80
13:04:34
       at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfiguration(Branch targetBranch, Commit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Configuration\BranchConfigurationCalculator.cs:line 48
```

## Possible Fix
Validate this configuration in the same place the other branch configuration is validated. See the proposed validation in https://github.com/GitTools/GitVersion/pull/2348.

## Steps to Reproduce
See the failing test in https://github.com/GitTools/GitVersion/pull/2348.

**Comment by asbjornu** [comment]
Fixed in #2348.
