### ISSUE TITLE
[Docs] How to install on ubuntu. Why so little documentation on Linux installation?

### ISSUE THREAD

**Issue by sunilshahi** [GitTools/GitVersion#2365]
Apologies in advance. I will admit I am a noob with both gitversion and ubuntu. So maybe I am missing something. 

I am trying to install gitversion command line in Ubuntu 18.04.4 LTS. The documentation [here](https://gitversion.net/docs/usage/command-line) says we need to install` mono-complete` and run  `mono gitversion.exe`. 

How do I get the exe file? downloading and uncompressing the tar.gz file from [here ](https://github.com/GitTools/GitVersion/releases) gave me just a single file named `gitversion`, I do not see any exe file. 

```
wget https://github.com/GitTools/GitVersion/releases/download/5.3.7/gitversion-ubuntu.18.04-x64-5.3.7.tar.gz
tar -xvf gitversion-ubuntu.18.04-x64-5.3.7.tar.gz
```

A little more guideline in docs would be helpful.  

Thanks in advance

**Comment by asbjornu** [comment]
Please see https://github.com/GitTools/GitVersion/issues/2260#issuecomment-625741864. LibGit2Sharp doesn't support Debian 10 based distributions. Can you please explain in which context you want to use GitVersion and why you are installing it so we can better guide you towards the best available package? You can also have a look at #2326 to see which alternatives exist and make a choice for yourself.

**Comment by sunilshahi** [comment]
> why you are installing it so we can better guide you towards the best available package?

Basically, I am trying to setup a CICD Pipeline for one of my project. I have a teamcity server with a ubuntu build agent. I am trying to use semantic version to use it with docker build command so that I can tag the docker image with appropriate version.
Hope that gives you an idea what I am looking for.

**Comment by asbjornu** [comment]
I see. Then I would recommend you use one of our [Docker Images](https://hub.docker.com/r/gittools/gitversion) to execute GitVersion.

**Comment by rhaines-chwy** [comment]
I had the same issue, albeit with MacOS. The information on how to actually _install_ gitverison is buried on https://gitversion.net/docs/usage/command-line . I don't consider installation to be _usage_, it's... installation. Please consider  adding a dedicated tab with installation instructions for each platform. I ended up finding the installation instructions by web searching for them, even though I had already visited the gitversion docs.

**Comment by asbjornu** [comment]
Great idea, @rhaines-chwy. I agree. Would you please submit a PR for that documentation refactoring?

**Comment by johlju** [comment]
I did the following on a Ubuntu (running in WSL). But I need to run it using `sudo gitversion`. I like to avoid that, but not sure how to do that yet, but it is running.

``` 
cd /tmp
wget https://github.com/GitTools/GitVersion/releases/download/5.6.0/gitversion-ubuntu.16.04-x64-5.6.0.tar.gz
cd ~
mkdir gitversion
cd ~/gitversion
sudo tar -xvf /tmp/gitversion-ubuntu.16.04-x64-5.6.0.tar.gz
sudo chmod +x gitversion
sudo ln -sf $(pwd)/gitversion /usr/local/bin/gitversion
sudo gitversion
```

**Comment by arturcic** [comment]
@johlju Glad you are able to use GitVersion. We definitely need the docs to be updated on the installation part as there are so many changes and GitVersion is much easier to install now. For GitVersion you do not need `mono` or `dotnet sdk` to be installed that is because the `tar.gz` file contains the self contained .net core  tool that includes the runtime as well. You just need the minimal requirements you can find [here for your distribution](https://github.com/GitTools/GitVersion/blob/master/src/Docker/linux%20deps.md).

**Comment by cml87** [comment]
@arturcic Thanks for the clarification. The solution posted by @johlju did work for me too. Unfortunately, I didn't find this approach in the [documentation](https://gitversion.net/docs/usage/cli/installation). I was trying instead to use GitVersion by means of the proposed [docker container](https://gitversion.net/docs/usage/cli/installation) in Ubuntu 20.04.  Being in a git project directory, I was doing: 
```shell
 $ docker run --rm -v "$(pwd):/repo" gittools/gitversion:5.6.6 /repo init
```
with no effects. I was getting the same output as without the <code>init</code> argument. Passing <code>-h</code> to see the help gave me an error:
```shell
$ docker run -it  -v "$(pwd):/repo"  gittools/gitversion:5.10.1-ubuntu.20.04-6.0 /repo -h
Unhandled exception. GitVersion.WarningException: Could not parse command line parameter '-h'.
   at GitVersion.ArgumentParser.ParseTargetPath(Arguments arguments, String name, IReadOnlyList`1 values, String value, Boolean parseEnded) in D:\a\GitVersion\GitVersion\src\GitVersion.App\ArgumentParser.cs:line 190
   at GitVersion.ArgumentParser.ParseArguments(String[] commandLineArguments) in D:\a\GitVersion\GitVersion\src\GitVersion.App\ArgumentParser.cs:line 86
   at GitVersion.Program.<>c__DisplayClass4_0.<CreateHostBuilder>b__2(IServiceProvider sp) in D:\a\GitVersion\GitVersion\src\GitVersion.App\Program.cs:line 30
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at GitVersion.Program.Main(String[] args) in D:\a\GitVersion\GitVersion\src\GitVersion.App\Program.cs:line 15
   at GitVersion.Program.<Main>(String[] args)
```

However, argument <code>-showconfig</code> seemed to work in this case. Doing as @johlju suggested above seems to work for me. Now I'm prompted as expected after entering <code>gitversion init</code> in my git project directory:
```shell
$ gitversion init
INFO [04/16/22 17:40:39:62] Working directory: /home/camilo/my_java_projects/restful-web-services_db
GitVersion init will guide you through setting GitVersion up to work for you

Which would you like to change?

0) Save changes and exit
1) Exit without saving

2) Run getting started wizard

3) Set next version number
4) Branch specific configuration
5) Branch Increment mode (per commit/after tag) (Current: )
6) Assembly versioning scheme (Current: )
7) Setup build scripts

> 

```

**Comment by arturcic** [comment]
@johlju or @cml87 you are very welcomed to improve the documentation regarding the linux usage, please fill in a PR to update the docs and then others will be able to use these knowledge
