### ISSUE TITLE
[Bug] GitVersion.Tool seems to require the main branch to be called master?

### ISSUE THREAD

**Issue by DamienDennehy** [GitTools/GitVersion#2368]
**Describe the bug**
GitHub recently [announced](https://github.com/github/renaming) the **master** branch will be called **main** going forward. 
When working on a repo where the main branch is called main and not master running **dotnet gitversion** seems to fail.

## Expected Behavior
When running GitVersion on a repo where there is a main branch it should detect the main branch and continue as normal, or allow you to set it.

## Actual Behavior
An invalid operation is thrown when running GitVersion.

`System.InvalidOperationException: Could not find a 'develop' or 'master' branch, neither locally nor remotely.
   at GitVersion.Configuration.BranchConfigurationCalculator.InheritBranchConfiguration(Branch targetBranch, BranchConfig branchConfiguration, Commit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Configuration\BranchConfigurationCalculator.cs:line 62
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfiguration(Branch targetBranch, Commit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Configuration\BranchConfigurationCalculator.cs:line 48
   at GitVersion.GitVersionContextFactory.Init(Branch currentBranch, String commitId, Boolean onlyTrackedBranches) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitVersionContextFactory.cs:line 46
   at GitVersion.GitVersionContextFactory.Create(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitVersionContextFactory.cs:line 28
   at GitVersion.GitVersionCoreModule.<>c__DisplayClass0_0.<RegisterTypes>b__3() in D:\a\GitVersion\GitVersion\src\GitVersionCore\GitVersionCoreModule.cs:line 61
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at GitVersion.VersionCalculation.NextVersionCalculator.get_context() in D:\a\GitVersion\GitVersion\src\GitVersionCore\VersionCalculation\NextVersionCalculator.cs:line 17
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersionCore\VersionCalculation\NextVersionCalculator.cs:line 32
   at GitVersion.GitVersionTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitVersionTool.cs:line 68
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersionExe\GitVersionExecutor.cs:line 56`

## Steps to Reproduce
1. Install the GitVersion.Tool on your machine.
dotnet tool install --global GitVersion.Tool --version 5.3.7
2. Run GitVersion on a repo where the main branch is called main, both locally and remote.
dotnet gitversion
![image](https://user-images.githubusercontent.com/3924814/88479409-d9629b80-cf46-11ea-8a2b-03609f413a5f.png)

## Context
Unable to rename branch until issue is resolved.

## Your Environment
- Version Used:
- Operating System and version (Windows 10, Ubuntu 18.04): Windows 10
- Link to your project:
- Link to your CI build (if appropriate):

**Comment by DamienDennehy** [comment]
While I didn't find an open issue for this I neglected to check PRs. 
Looks like this will be solved soon by Tim [https://github.com/GitTools/GitVersion/pull/2367](url)
