### ISSUE TITLE
[Bug] NotFoundException: No valid git object identified by 'refs/remotes/origin/HEAD' exists in the repository.

### ISSUE THREAD

**Issue by michalciolek** [GitTools/GitVersion#2380]
**Describe the bug**
After checkout to historical commit build failed with error:
```
NotFoundException: No valid git object identified by 'refs/remotes/origin/HEAD' exists in the repository.
   at LibGit2Sharp.Core.Ensure.GitObjectIsNotNull(GitObject gitObject, String identifier)
   at LibGit2Sharp.RepositoryExtensions.SingleCommittish(Repository repo, Object identifier)
   at LibGit2Sharp.RepositoryExtensions.<Committishes>d__20.MoveNext()
   at LibGit2Sharp.RepositoryExtensions.<Committishes>d__20.MoveNext()
   at System.Linq.Enumerable.<TakeWhileIterator>d__27`1.MoveNext()
   at LibGit2Sharp.CommitLog.CommitEnumerator.InternalHidePush(IList`1 identifier, HidePushSignature hidePush)
   at LibGit2Sharp.CommitLog.CommitEnumerator.Push(IList`1 identifier)
   at LibGit2Sharp.CommitLog.CommitEnumerator..ctor(Repository repo, CommitFilter filter)
   at LibGit2Sharp.CommitLog.GetEnumerator()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at GitVersion.RepositoryMetadataProvider.<GetBranchesContainingCommit>d__20.MoveNext()
   at GitVersion.Extensions.EnumerableExtensions.OnlyOrDefault[T](IEnumerable`1 source) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Extensions\EnumerableExtensions.cs:line 23
   at GitVersion.GitVersionContextFactory.Init(Branch currentBranch, String commitId, Boolean onlyTrackedBranches) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitVersionContextFactory.cs:line 42
   at GitVersion.GitVersionContextFactory.Create(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitVersionContextFactory.cs:line 27
   at GitVersion.GitVersionCoreModule.<>c__DisplayClass0_0.<RegisterTypes>b__3() in D:\a\GitVersion\GitVersion\src\GitVersionCore\GitVersionCoreModule.cs:line 60
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersionCore\VersionCalculation\NextVersionCalculator.cs:line 32
   at GitVersion.GitVersionTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitVersionTool.cs:line 66
   at GitVersion.MSBuildTask.GitVersionTaskExecutor..ctor(IGitVersionTool gitVersionTool, IOptions`1 options) in D:\a\GitVersion\GitVersion\src\GitVersionTask\GitVersionTaskExecutor.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at GitVersion.MSBuildTask.GitVersionTasks.ExecuteGitVersionTask[T](T task, Action`1 action) in D:\a\GitVersion\GitVersion\src\GitVersionTask\GitVersionTasks.cs:line 24
```

## Steps to Reproduce
- Create/open repository with GitVersion.yml
```
assembly-informational-format: '{FullSemVer}-{CommitDate}'
mode: ContinuousDeployment
branches:
        master:
                tag: 'alpha'
ignore:
  sha: []
merge-message-formats: {}

```

- Create some commits on master branch, eg:
```
Commit 0 04.08.2020 11.00 tag v2.2.1
Commit 1 04.08.2020 12.00
Commit 2 04.08.2020 13.00
Commit 3 04.08.2020 14.00 tag v2.2.2
```
- Checkout to `Commit 2` (without creating branch - detached head)
- Build

GitVersion should be v2.2.2-alpha.2 but build failed.

- Version Used: 5.3.7
- Operating System and version: Windows 10

**Comment by asbjornu** [comment]
GitVersion doesn't support detached heads. The exception you got was strange, but this isn't going to work with GitVersion as it needs to know which branch you're on in order to generate a version number.
