### ISSUE TITLE
gitversion/setup on an ubuntu-latest Azure Devops agent fails

### ISSUE THREAD

**Issue by dwfrancis** [GitTools/GitVersion#2459]
Running the `gitversion/setup@0` on the `ubuntu-latest` Azure Devops agent fails with a `System.InvalidOperationException: Sequence contains more than one matching element` exception

## Steps to Reproduce

1. Create a Azure Devops yaml pipeline 
2. Add GitVersion tasks
```
steps:
- task: gitversion/setup@0
  displayName: 'Setup GitVersion'

- task: gitversion/execute@0
  displayName: 'Execute GitVersion'
  inputs:
    useConfigFile: true
    configFilePath: 'GitVersion.yml'
    updateAssemblyInfo: true
```
3. Run the pipeline

## Context
We currently have a azure yaml pipeline running on `ubuntu-latest` using the `GitVersion@5` task. Migrating to the `gitversion/setup` + `gitversion/execute` fails.

Similar migrations have worked without issue on `windows-latest` agents

Version Used:
- GitVersion 5.1.4
- Ubuntu 18.04.5 LTS

### Logs
```
2020-11-19T20:50:30.6749961Z ##[section]Starting: Setup GitVersion
2020-11-19T20:50:30.6757304Z ==============================================================================
2020-11-19T20:50:30.6757589Z Task         : Setup GitVersion Task
2020-11-19T20:50:30.6757896Z Description  : Easy Semantic Versioning (http://semver.org) for projects using Git
2020-11-19T20:50:30.6758284Z Version      : 0.9.6
2020-11-19T20:50:30.6758480Z Author       : GitTools Contributors
2020-11-19T20:50:30.6758784Z Help         : See the [documentation](https://gitversion.net/docs/) for help
2020-11-19T20:50:30.6759100Z ==============================================================================
2020-11-19T20:50:30.8554125Z 
2020-11-19T20:50:30.8555074Z --------------------------
2020-11-19T20:50:30.8556421Z Installing GitVersion.Tool version 5.x
2020-11-19T20:50:30.8556956Z --------------------------
2020-11-19T20:50:31.1389029Z Command: dotnet tool install GitVersion.Tool --tool-path /home/vsts/work/_temp --version 5.5.1
2020-11-19T20:50:31.1426016Z [command]/usr/bin/dotnet tool install GitVersion.Tool --tool-path /home/vsts/work/_temp --version 5.5.1
2020-11-19T20:50:35.8920691Z 
2020-11-19T20:50:35.8921667Z Welcome to .NET Core 3.1!
2020-11-19T20:50:35.8922700Z ---------------------
2020-11-19T20:50:35.8923127Z SDK Version: 3.1.404
2020-11-19T20:50:35.8923442Z 
2020-11-19T20:50:35.8923880Z ----------------
2020-11-19T20:50:35.8924442Z Explore documentation: https://aka.ms/dotnet-docs
2020-11-19T20:50:35.8924926Z Report issues and find source on GitHub: https://github.com/dotnet/core
2020-11-19T20:50:35.8925557Z Find out what's new: https://aka.ms/dotnet-whats-new
2020-11-19T20:50:35.8926251Z Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
2020-11-19T20:50:35.8926990Z Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
2020-11-19T20:50:35.8927665Z Write your first app: https://aka.ms/first-net-core-app
2020-11-19T20:50:35.8928350Z --------------------------------------------------------------------------------------
2020-11-19T20:50:35.8929939Z System.InvalidOperationException: Sequence contains more than one matching element
2020-11-19T20:50:35.8961992Z ##[error]Error installing tool
2020-11-19T20:50:35.8973725Z    at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
2020-11-19T20:50:35.8974083Z    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
2020-11-19T20:50:35.8974475Z    at Microsoft.DotNet.ToolPackage.ToolPackageInstance.FindLibraryInLockFile(LockFile lockFile, PackageId id)
2020-11-19T20:50:35.8974805Z    at Microsoft.DotNet.ToolPackage.ToolPackageInstance.GetCommands()
2020-11-19T20:50:35.8975064Z    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2020-11-19T20:50:35.8975399Z    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
2020-11-19T20:50:35.8975684Z    at System.Lazy`1.CreateValue()
2020-11-19T20:50:35.8975863Z    at System.Lazy`1.get_Value()
2020-11-19T20:50:35.8976113Z    at Microsoft.DotNet.ToolPackage.ToolPackageInstance.get_Commands()
2020-11-19T20:50:35.8976416Z    at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.Execute()
2020-11-19T20:50:35.8976715Z    at Microsoft.DotNet.Tools.Tool.Install.ToolInstallCommand.Execute()
2020-11-19T20:50:35.8977014Z    at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
2020-11-19T20:50:35.8977314Z    at Microsoft.DotNet.Tools.Tool.ToolCommand.Run(String[] args)
2020-11-19T20:50:35.8977611Z    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
2020-11-19T20:50:35.8977896Z    at Microsoft.DotNet.Cli.Program.Main(String[] args)
2020-11-19T20:50:35.8984068Z ##[section]Finishing: Setup GitVersion
```

**Comment by arturcic** [comment]
@dwfrancis I think this is related to dotnet cli failing to install the tool. It's an issue with the dotnet cli, not the gitversion setup task

**Comment by dwfrancis** [comment]
Thanks! The issue was there. 

The tools CLI fails if there is a `runtimeIdentifier` pipeline variable.
https://github.com/dotnet/sdk/issues/3817#issuecomment-613583054
