### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by RwSgxx** [GitTools/GitVersion#2475]
**Describe the bug**
Azure local build on Mac fails with:
EINVAL: invalid argument, readlink '/usr/local/share/dotnet/dotnet'

The same pipeline runs ok on windows.

## Expected Behavior
run ok.

## Actual Behavior
[debug]Error: EINVAL: invalid argument, readlink '/usr/local/share/dotnet/dotnet'
-- trance at the end of the report

## Possible Fix
absolutely no idea 

## Steps to Reproduce
Create an yml Azure pipeline that has this step and run it on a local hosted mac.
steps:
- task: UseGitVersion@5
  displayName: 'Install GitVersion5'
  inputs:
    versionSpec: '5.x'
    additionalArguments: '/output buildserver -config .\GitVersion.yml'

## Context
Run an Azure pipeline on a local Mac Agent. 

## Your Environment

- Version Used:
5.5.1
On: Azure local build agent on Mac OS Big Sur v11.0.1 on intel i9

- Traces:
```
2020-12-10T17:37:50.7364580Z ##[debug]Evaluating condition for step: 'Install GitVersion5'
2020-12-10T17:37:50.7365850Z ##[debug]Evaluating: SucceededNode()
2020-12-10T17:37:50.7366240Z ##[debug]Evaluating SucceededNode:
2020-12-10T17:37:50.7367080Z ##[debug]=> True
2020-12-10T17:37:50.7367600Z ##[debug]Result: True
2020-12-10T17:37:50.7368090Z ##[section]Starting: Install GitVersion5
2020-12-10T17:37:50.7374370Z ==============================================================================
2020-12-10T17:37:50.7374590Z Task         : GitVersion Task
2020-12-10T17:37:50.7374830Z Description  : Easy Semantic Versioning (http://semver.org) for projects using Git
2020-12-10T17:37:50.7375030Z Version      : 5.1.2
2020-12-10T17:37:50.7375190Z Author       : GitVersion Contributors
2020-12-10T17:37:50.7375440Z Help         : See the [documentation](http://gitversion.readthedocs.org/en/latest/) for help
2020-12-10T17:37:50.7375720Z ==============================================================================
2020-12-10T17:37:50.7514870Z ##[debug]Using node path: /Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/externals/node/bin/node
2020-12-10T17:37:50.8396850Z ##[debug]agent.TempDirectory=/Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_temp
2020-12-10T17:37:50.8411460Z ##[debug]loading inputs and endpoints
2020-12-10T17:37:50.8415300Z ##[debug]loading ......xxx.....x.x.x..xx..x.x
2020-12-10T17:37:50.8440460Z ##[debug]loaded 10
2020-12-10T17:37:50.8457210Z ##[debug]Agent.ProxyUrl=undefined
2020-12-10T17:37:50.8457780Z ##[debug]Agent.CAInfo=undefined
2020-12-10T17:37:50.8458900Z ##[debug]Agent.ClientCert=undefined
2020-12-10T17:37:50.8459150Z ##[debug]Agent.SkipCertValidation=undefined
2020-12-10T17:37:50.8591390Z ##[debug]Agent.ProxyUrl=undefined
2020-12-10T17:37:50.8592040Z ##[debug]Agent.CAInfo=undefined
2020-12-10T17:37:50.8592480Z ##[debug]Agent.ClientCert=undefined
2020-12-10T17:37:50.8596360Z ##[debug]check path : /Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_tasks/UseGitVersion_bab30d5c-39f3-49b0-a7db-9a5da6676eaa/5.1.2/node_modules/azure-pipelines-tool-lib/lib.json
2020-12-10T17:37:50.8597070Z ##[debug]adding resource file: /Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_tasks/UseGitVersion_bab30d5c-39f3-49b0-a7db-9a5da6676eaa/5.1.2/node_modules/azure-pipelines-tool-lib/lib.json
2020-12-10T17:37:50.8597630Z ##[debug]system.culture=en-US
2020-12-10T17:37:50.8608700Z ##[debug]versionSpec=5.x
2020-12-10T17:37:50.8611640Z ##[debug]includePrerelease=false
2020-12-10T17:37:50.8612510Z ##[debug]targetPath=null
2020-12-10T17:37:50.8613160Z ##[debug]useConfigFile=false
2020-12-10T17:37:50.8615240Z ##[debug]configFilePath=/Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/1/s
2020-12-10T17:37:50.8616330Z ##[debug]updateAssemblyInfo=false
2020-12-10T17:37:50.8616710Z ##[debug]updateAssemblyInfoFilename=null
2020-12-10T17:37:50.8618280Z ##[debug]additionalArguments=/output buildserver -config .\GitVersion.yml
2020-12-10T17:37:50.8619480Z ##[debug]Build.SourcesDirectory=/Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/1/s
2020-12-10T17:37:50.8628260Z ##[debug]INSTALL_TOOL=undefined
2020-12-10T17:37:50.8641650Z 
2020-12-10T17:37:50.8642920Z --------------------------
2020-12-10T17:37:50.8643070Z Installing GitVersion.Tool version 5.x
2020-12-10T17:37:50.8643370Z --------------------------
2020-12-10T17:37:50.8645870Z ##[debug]isExplicit: null
2020-12-10T17:37:50.8646280Z ##[debug]explicit? false
2020-12-10T17:37:50.8647460Z ##[debug]isExplicit: null
2020-12-10T17:37:50.8648220Z ##[debug]explicit? false
2020-12-10T17:37:50.8649260Z ##[debug]Agent.Version=2.177.1
2020-12-10T17:37:50.8650650Z ##[debug]Agent.ToolsDirectory=/Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_tool
2020-12-10T17:37:50.8651470Z ##[debug]evaluating 0 versions
2020-12-10T17:37:50.8652380Z ##[debug]match not found
2020-12-10T17:37:50.8653140Z ##[debug]isExplicit: null
2020-12-10T17:37:50.8653320Z ##[debug]explicit? false
2020-12-10T17:37:50.8655200Z ##[debug]querying tool versions for GitVersion.Tool@5.x 
2020-12-10T17:37:53.3893710Z ##[debug]got versions: 5.0.0, 5.0.1, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.2.0, 5.2.1, 5.2.2, 5.2.3, 5.2.4, 5.3.0, 5.3.1, 5.3.2, 5.3.3, 5.3.4, 5.3.5, 5.3.6, 5.3.7, 5.5.0, 5.5.1
2020-12-10T17:37:53.3895230Z ##[debug]evaluating 21 versions
2020-12-10T17:37:53.3937280Z ##[debug]matched: 5.5.1
2020-12-10T17:37:53.3938280Z ##[debug]isExplicit: 5.5.1
2020-12-10T17:37:53.3939020Z ##[debug]explicit? true
2020-12-10T17:37:53.3939630Z ##[debug]Agent.Version=2.177.1
2020-12-10T17:37:53.3940880Z ##[debug]Agent.ToolsDirectory=/Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_tool
2020-12-10T17:37:53.3941970Z ##[debug]checking cache: /Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_tool/GitVersion.Tool/5.5.1/x64
2020-12-10T17:37:53.3942700Z ##[debug]not found
2020-12-10T17:37:53.3943990Z ##[debug]which 'dotnet'
2020-12-10T17:37:53.3950230Z ##[debug]found: '/usr/local/share/dotnet/dotnet'
2020-12-10T17:37:53.3951200Z ##[debug]which 'dotnet'
2020-12-10T17:37:53.3964620Z ##[debug]found: '/usr/local/share/dotnet/dotnet'
2020-12-10T17:37:53.3965750Z ##[debug]Agent.TempDirectory=/Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_temp
2020-12-10T17:37:53.3966530Z ##[debug]cleaning: 5.5.1
2020-12-10T17:37:53.3968570Z ##[debug]/usr/local/share/dotnet/dotnet arg: ["tool","install","GitVersion.Tool","--tool-path","/Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_temp","--version","5.5.1"]
2020-12-10T17:37:53.3971460Z ##[debug]exec tool: /usr/local/share/dotnet/dotnet
2020-12-10T17:37:53.3972180Z ##[debug]arguments:
2020-12-10T17:37:53.3972650Z ##[debug]   tool
2020-12-10T17:37:53.3973010Z ##[debug]   install
2020-12-10T17:37:53.3973340Z ##[debug]   GitVersion.Tool
2020-12-10T17:37:53.3973950Z ##[debug]   --tool-path
2020-12-10T17:37:53.3974570Z ##[debug]   /Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_temp
2020-12-10T17:37:53.3975130Z ##[debug]   --version
2020-12-10T17:37:53.3975470Z ##[debug]   5.5.1
2020-12-10T17:37:53.3976780Z [command]/usr/local/share/dotnet/dotnet tool install GitVersion.Tool --tool-path /Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_temp --version 5.5.1
2020-12-10T17:38:13.6834230Z You can invoke the tool using the following command: dotnet-gitversion
2020-12-10T17:38:13.6834910Z Tool 'gitversion.tool' (version '5.5.1') was successfully installed.
2020-12-10T17:38:13.6835590Z ##[debug]tool install result: success 
2020-12-10T17:38:13.6856560Z Caching tool: GitVersion.Tool 5.5.1 x64
2020-12-10T17:38:13.6857300Z ##[debug]source dir: /Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_temp
2020-12-10T17:38:13.6857830Z ##[debug]Agent.Version=2.177.1
2020-12-10T17:38:13.6858450Z ##[debug]Agent.ToolsDirectory=/Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_tool
2020-12-10T17:38:13.6859070Z ##[debug]destination /Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_tool/GitVersion.Tool/5.5.1/x64
2020-12-10T17:38:13.6859730Z ##[debug]rm -rf /Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_tool/GitVersion.Tool/5.5.1/x64
2020-12-10T17:38:13.6860390Z ##[debug]rm -rf /Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_tool/GitVersion.Tool/5.5.1/x64.complete
2020-12-10T17:38:13.6861550Z ##[debug]testing directory '/Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_tool/GitVersion.Tool/5.5.1/x64'
2020-12-10T17:38:13.6862460Z ##[debug]testing directory '/Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_tool/GitVersion.Tool/5.5.1'
2020-12-10T17:38:13.6863090Z ##[debug]testing directory '/Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_tool/GitVersion.Tool'
2020-12-10T17:38:13.6863660Z ##[debug]testing directory '/Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_tool'
2020-12-10T17:38:13.6864210Z ##[debug]mkdir '/Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_tool/GitVersion.Tool'
2020-12-10T17:38:13.6865080Z ##[debug]mkdir '/Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_tool/GitVersion.Tool/5.5.1'
2020-12-10T17:38:13.6865680Z ##[debug]mkdir '/Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_tool/GitVersion.Tool/5.5.1/x64'
2020-12-10T17:38:13.8982910Z ##[debug]Agent.Version=2.177.1
2020-12-10T17:38:13.8984090Z ##[debug]Agent.ToolsDirectory=/Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_tool
2020-12-10T17:38:13.8984550Z ##[debug]finished caching tool
2020-12-10T17:38:13.8986350Z ##[debug]toolPath: /Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_tool/GitVersion.Tool/5.5.1/x64
2020-12-10T17:38:13.8987010Z ##[debug]which 'dotnet'
2020-12-10T17:38:13.8988160Z ##[debug]found: '/usr/local/share/dotnet/dotnet'
2020-12-10T17:38:13.8996420Z ##[debug]Error: EINVAL: invalid argument, readlink '/usr/local/share/dotnet/dotnet'
    at Error (native)
    at Object.fs.readlinkSync (fs.js:1037:18)
    at ToolInstaller.<anonymous> (/Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_tasks/UseGitVersion_bab30d5c-39f3-49b0-a7db-9a5da6676eaa/5.1.2/ToolInstaller.js:54:50)
    at next (native)
    at fulfilled (/Users/userxx/AzBuild/vsts-agent-osx-x64-2.177.1/_work/_tasks/UseGitVersion_bab30d5c-39f3-49b0-a7db-9a5da6676eaa/5.1.2/ToolInstaller.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
2020-12-10T17:38:13.8997570Z ##[debug]task result: Failed
2020-12-10T17:38:13.9022280Z ##[error]Error: EINVAL: invalid argument, readlink '/usr/local/share/dotnet/dotnet'
2020-12-10T17:38:13.9031050Z ##[debug]Processed: ##vso[task.issue type=error;]Error: EINVAL: invalid argument, readlink '/usr/local/share/dotnet/dotnet'
2020-12-10T17:38:13.9040900Z ##[debug]Processed: ##vso[task.complete result=Failed;done=true;]Error: EINVAL: invalid argument, readlink '/usr/local/share/dotnet/dotnet'
2020-12-10T17:38:13.9050750Z ##[section]Finishing: Install GitVersion5
```

**Comment by asbjornu** [comment]
`UseGitVersion` is deprecated. Please use [the GitTools task](https://marketplace.visualstudio.com/items?itemName=gittools.gittools)  isntead.

**Comment by RwSgxx** [comment]
Same happens with GitTools task. I'll close this one and open a new bug.
