### ISSUE TITLE
[Bug] docker tag gittools/gitversion:5.3.5-linux-alpine.3.10-x64-netcoreapp3.1 was deleted from dockerhub

### ISSUE THREAD

**Issue by mabead** [GitTools/GitVersion#2488]
**Describe the bug**
It looks like someone deleted some tags for `gitversion` on dockerhub. We were using `gittools/gitversion:5.3.5-linux-alpine.3.10-x64-netcoreapp3.1`. Starting this morning, all our builds started to break. With many people on vacations in the holidays, this is a big blocker and source of risk for us.

Note that I tried to upgrade to `gittools/gitversion:5.6.1-alpine.3.12-x64-5.0` but it failed like this:

```
[12:00:12]Status: Downloaded newer image for gittools/gitversion:5.6.1-alpine.3.12-x64-5.0
[12:00:13]  ERROR [12/21/20 17:00:07:18] An unexpected error occurred:
[12:00:13]LibGit2Sharp.LibGit2SharpException: No error message has been provided by the native library
[12:00:13]   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
[12:00:13]   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result)
[12:00:13]   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteHandle remote, IEnumerable`1 refSpecs, GitFetchOptions fetchOptions, String logMessage)
[12:00:13]   at LibGit2Sharp.Commands.Fetch(Repository repository, String remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage)
[12:00:13]   at GitVersion.GitRepositoryCommands.Fetch(String remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitRepositoryCommands.cs:line 58
[12:00:13]   at GitVersion.GitPreparer.NormalizeGitDirectory(String gitDirectory, Boolean noFetch, String currentBranch, Boolean isDynamicRepository) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 223
[12:00:13]   at GitVersion.GitPreparer.NormalizeGitDirectory(String targetBranch, String gitDirectory, Boolean isDynamicRepository) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 141
[12:00:13]   at GitVersion.GitPreparer.PrepareInternal(Boolean normalizeGitDirectory, String currentBranch, Boolean shouldCleanUpRemotes) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 66
[12:00:13]   at GitVersion.GitPreparer.Prepare() in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 47
[12:00:13]   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitVersionCalculateTool.cs:line 43
[12:00:13]   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersionExe\GitVersionExecutor.cs:line 59
[12:00:13]Error: System.AggregateException: One or more errors occurred. (Docker: Process returned an error (exit code 1).)
[12:00:13] ---> Cake.Core.CakeException: Docker: Process returned an error (exit code 1).
[12:00:13]   at Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 136
[12:00:13]   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 121
[12:00:13]   at Cake.Docker.GenericDockerRunner`1.RunWithResult[T](String command, TSettings settings, Func`2 processOutput, String[] arguments) in D:\GitProjects\Righthand\Cake\Cake.Docker\src\Cake.Docker\GenericDockerRunner.cs:line 107
[12:00:13]   at Cake.Docker.DockerAliases.DockerRun(ICakeContext context, DockerContainerRunSettings settings, String image, String command, String[] args) in D:\GitProjects\Righthand\Cake\Cake.Docker\src\Cake.Docker\Container\Run\Docker.Aliases.Run.cs:line 59
[12:00:13]   at Submission#0.DockerRun(DockerContainerRunSettings settings, String image, String command, String[] args) in :line 3459
[12:00:13]   at Submission#0.GetDockerGitVersion() in /agent/work/d50858d04622831/src/tools/cake/GitVersion.cake:line 87
[12:00:13]   at Submission#0.GetCurrentGitVersion() in /agent/work/d50858d04622831/src/tools/cake/GitVersion.cake:line 50
[12:00:13]   at Submission#0.<<Initialize>>d__0.MoveNext() in /agent/work/d50858d04622831/src/tools/cake/GitVersion.cake:line 20
[12:00:13]--- End of stack trace from previous location where exception was thrown ---
[12:00:13]   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
[12:00:13]   at Microsoft.CodeAnalysis.Scripting.Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
[12:00:13]   --- End of inner exception stack trace ---
[12:00:13]   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[12:00:13]   at Cake.Scripting.Roslyn.RoslynScriptSession.Execute(Script script) in C:\projects\cake\src\Cake\Scripting\Roslyn\RoslynScriptSession.cs:line 136
[12:00:13]   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 219
[12:00:13]   at Cake.Commands.BuildCommand.Execute(CakeOptions options) in C:\projects\cake\src\Cake\Commands\BuildCommand.cs:line 41
[12:00:13]   at Cake.CakeApplication.Run(CakeOptions options) in C:\projects\cake\src\Cake\CakeApplication.cs:line 45
[12:00:13]   at Cake.Program.Main() in C:\projects\cake\src\Cake\Program.cs:line 81
```

## Expected Behavior
Running `gittools/gitversion:5.3.5-linux-alpine.3.10-x64-netcoreapp3.1` should work as usual.

## Actual Behavior
Image does not exist anymore.

## Possible Fix
Bring back the image in docker hub.

## Steps to Reproduce
See above.

## Context
As said in the introduction, this breaks all our builds that were working correctly last week. It is therefore a pretty big regression.

## Your Environment

- Version Used: see above
- Operating System and version (Windows 10, Ubuntu 18.04): linux
- Link to your project:
- Link to your CI build (if appropriate):

**Comment by mabead** [comment]
I tried `5.5.2-alpine.3.12-x64-3.1` and it also fails:

```
[12:14:01]Status: Downloaded newer image for gittools/gitversion:5.5.2-alpine.3.12-x64-3.1
[12:14:02]  ERROR [12/21/20 17:13:56:30] An unexpected error occurred:
[12:14:02]LibGit2Sharp.LibGit2SharpException: No error message has been provided by the native library
[12:14:02]   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
[12:14:02]   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result)
[12:14:02]   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteHandle remote, IEnumerable`1 refSpecs, GitFetchOptions fetchOptions, String logMessage)
[12:14:02]   at LibGit2Sharp.Commands.Fetch(Repository repository, String remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage)
[12:14:02]   at GitVersion.GitRepositoryCommands.Fetch(String remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitRepositoryCommands.cs:line 59
[12:14:02]   at GitVersion.GitPreparer.NormalizeGitDirectory(String gitDirectory, Boolean noFetch, String currentBranch, Boolean isDynamicRepository) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 226
[12:14:02]   at GitVersion.GitPreparer.NormalizeGitDirectory(String targetBranch, String gitDirectory, Boolean isDynamicRepository) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 141
[12:14:02]   at GitVersion.GitPreparer.PrepareInternal(Boolean normalizeGitDirectory, String currentBranch, Boolean shouldCleanUpRemotes) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 69
[12:14:02]   at GitVersion.GitPreparer.Prepare() in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 48
[12:14:02]   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitVersionCalculateTool.cs:line 45
[12:14:02]   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersionExe\GitVersionExecutor.cs:line 59
[12:14:02]Error: System.AggregateException: One or more errors occurred. (Docker: Process returned an error (exit code 1).)
[12:14:02] ---> Cake.Core.CakeException: Docker: Process returned an error (exit code 1).
[12:14:02]   at Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 136
[12:14:02]   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 121
[12:14:02]   at Cake.Docker.GenericDockerRunner`1.RunWithResult[T](String command, TSettings settings, Func`2 processOutput, String[] arguments) in D:\GitProjects\Righthand\Cake\Cake.Docker\src\Cake.Docker\GenericDockerRunner.cs:line 107
[12:14:02]   at Cake.Docker.DockerAliases.DockerRun(ICakeContext context, DockerContainerRunSettings settings, String image, String command, String[] args) in D:\GitProjects\Righthand\Cake\Cake.Docker\src\Cake.Docker\Container\Run\Docker.Aliases.Run.cs:line 59
[12:14:02]   at Submission#0.DockerRun(DockerContainerRunSettings settings, String image, String command, String[] args) in :line 3459
[12:14:02]   at Submission#0.GetDockerGitVersion() in /agent/work/d50858d04622831/src/tools/cake/GitVersion.cake:line 87
[12:14:02]   at Submission#0.GetCurrentGitVersion() in /agent/work/d50858d04622831/src/tools/cake/GitVersion.cake:line 50
[12:14:02]   at Submission#0.<<Initialize>>d__0.MoveNext() in /agent/work/d50858d04622831/src/tools/cake/GitVersion.cake:line 20
[12:14:02]--- End of stack trace from previous location where exception was thrown ---
[12:14:02]   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
[12:14:02]   at Microsoft.CodeAnalysis.Scripting.Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
[12:14:02]   --- End of inner exception stack trace ---
[12:14:02]   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[12:14:02]   at Cake.Scripting.Roslyn.RoslynScriptSession.Execute(Script script) in C:\projects\cake\src\Cake\Scripting\Roslyn\RoslynScriptSession.cs:line 136
[12:14:02]   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 219
[12:14:02]   at Cake.Commands.BuildCommand.Execute(CakeOptions options) in C:\projects\cake\src\Cake\Commands\BuildCommand.cs:line 41
[12:14:02]   at Cake.CakeApplication.Run(CakeOptions options) in C:\projects\cake\src\Cake\CakeApplication.cs:line 45
[12:14:02]   at Cake.Program.Main() in C:\projects\cake\src\Cake\Program.cs:line 81
```

**Comment by arturcic** [comment]
I noticed that as well, I will need to check why was that. For now can you try a different image ? 
I run locally these 2 command and both got correct results
` docker run --rm -v "$(pwd):/repo" gittools/gitversion:5.6.1-ubuntu.18.04-x64-5.0 /repo`
`docker run --rm -v "$(pwd):/repo" gittools/gitversion:5.6.1-alpine.3.12-x64-5.0 /repo`

**Comment by y0m1g** [comment]
Same thing on our side, we were using tags `5.0.0-linux-netcoreapp2.1` and now those images are just gone, and so our builds are stuck...

I tried upgrading to `5.6.1-alpine.3.12-x64-3.1`, but it fails because of https://github.com/GitTools/GitVersion/issues/2301. 

Also not sure what to do with our Windows builds that were using  `5.1.3-windows-netcoreapp2.1`, but now there's nothing left tagged for Windows  anymore. 😞

**Comment by arturcic** [comment]
> Also not sure what to do with our Windows builds that were using `5.1.3-windows-netcoreapp2.1`, since now there's nothing left tagged for Windows anymore.

I would not recommend to use the docker image for windows, better the GitVersion.Tool or the chocolatey package

**Comment by mabead** [comment]
Also note that the documentation on DockerHub refers to a tag that does not exist anymore:

![image](https://user-images.githubusercontent.com/4930754/102803757-c5508800-4386-11eb-9f5b-5ecc9797faca.png)

**Comment by arturcic** [comment]
The readme on dockerhub is not up to date

**Comment by mabead** [comment]
@arturcic as already said, `gittools/gitversion:5.6.1-alpine.3.12-x64-5.0` does not work for me. I also tried `gittools/gitversion:5.6.1-ubuntu.18.04-x64-5.0` and it also fails with the same error:

```
[12:24:09]Status: Downloaded newer image for gittools/gitversion:5.6.1-ubuntu.18.04-x64-5.0
[12:24:10]  ERROR [12/21/20 17:24:04:29] An unexpected error occurred:
[12:24:10]LibGit2Sharp.LibGit2SharpException: No error message has been provided by the native library
[12:24:10]   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
[12:24:10]   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result)
[12:24:10]   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteHandle remote, IEnumerable`1 refSpecs, GitFetchOptions fetchOptions, String logMessage)
[12:24:10]   at LibGit2Sharp.Commands.Fetch(Repository repository, String remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage)
[12:24:10]   at GitVersion.GitRepositoryCommands.Fetch(String remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitRepositoryCommands.cs:line 58
[12:24:10]   at GitVersion.GitPreparer.NormalizeGitDirectory(String gitDirectory, Boolean noFetch, String currentBranch, Boolean isDynamicRepository) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 223
[12:24:10]   at GitVersion.GitPreparer.NormalizeGitDirectory(String targetBranch, String gitDirectory, Boolean isDynamicRepository) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 141
[12:24:10]   at GitVersion.GitPreparer.PrepareInternal(Boolean normalizeGitDirectory, String currentBranch, Boolean shouldCleanUpRemotes) in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 66
[12:24:10]   at GitVersion.GitPreparer.Prepare() in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitPreparer.cs:line 47
[12:24:10]   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersionCore\Core\GitVersionCalculateTool.cs:line 43
[12:24:10]   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersionExe\GitVersionExecutor.cs:line 59
[12:24:10]Error: System.AggregateException: One or more errors occurred. (Docker: Process returned an error (exit code 1).)
[12:24:10] ---> Cake.Core.CakeException: Docker: Process returned an error (exit code 1).
[12:24:10]   at Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 136
[12:24:10]   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 121
[12:24:10]   at Cake.Docker.GenericDockerRunner`1.RunWithResult[T](String command, TSettings settings, Func`2 processOutput, String[] arguments) in D:\GitProjects\Righthand\Cake\Cake.Docker\src\Cake.Docker\GenericDockerRunner.cs:line 107
[12:24:10]   at Cake.Docker.DockerAliases.DockerRun(ICakeContext context, DockerContainerRunSettings settings, String image, String command, String[] args) in D:\GitProjects\Righthand\Cake\Cake.Docker\src\Cake.Docker\Container\Run\Docker.Aliases.Run.cs:line 59
[12:24:10]   at Submission#0.DockerRun(DockerContainerRunSettings settings, String image, String command, String[] args) in :line 3459
[12:24:10]   at Submission#0.GetDockerGitVersion() in /agent/work/d50858d04622831/src/tools/cake/GitVersion.cake:line 87
[12:24:10]   at Submission#0.GetCurrentGitVersion() in /agent/work/d50858d04622831/src/tools/cake/GitVersion.cake:line 50
[12:24:10]   at Submission#0.<<Initialize>>d__0.MoveNext() in /agent/work/d50858d04622831/src/tools/cake/GitVersion.cake:line 20
[12:24:10]--- End of stack trace from previous location where exception was thrown ---
[12:24:10]   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
[12:24:10]   at Microsoft.CodeAnalysis.Scripting.Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
[12:24:10]   --- End of inner exception stack trace ---
[12:24:10]   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[12:24:10]   at Cake.Scripting.Roslyn.RoslynScriptSession.Execute(Script script) in C:\projects\cake\src\Cake\Scripting\Roslyn\RoslynScriptSession.cs:line 136
[12:24:10]   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 219
[12:24:10]   at Cake.Commands.BuildCommand.Execute(CakeOptions options) in C:\projects\cake\src\Cake\Commands\BuildCommand.cs:line 41
[12:24:10]   at Cake.CakeApplication.Run(CakeOptions options) in C:\projects\cake\src\Cake\CakeApplication.cs:line 45
[12:24:10]   at Cake.Program.Main() in C:\projects\cake\src\Cake\Program.cs:line 81
```

With like 70% of the team in vacations because of the holidays, it is pretty hard for me to find time to investigate and find why this fails. It would therefore be **very** appreciated if you could bring back the old tags.

**Comment by arturcic** [comment]
I will check if I can build older tags. But that might take time

**Comment by arturcic** [comment]
@mabead can you use 
`gittools/gitversion:5.3.8-linux-alpine.3.10-x64-netcoreapp3.1` instead of 
`gittools/gitversion:5.3.5-linux-alpine.3.10-x64-netcoreapp3.1` ?

**Comment by arturcic** [comment]
I was able to build that one, but it was not possible the exact 5.3.5 as there were some build scripts issues

**Comment by mabead** [comment]
@arturcic 
Unfortunately, I was not able to use `gittools/gitversion:5.3.8-linux-alpine.3.10-x64-netcoreapp3.1`. 

Since all our builds were blocked, I had to find the issue that preventing me to use 5.6.1. It ended up being caused by the fact that the environment variable `Git_Branch` was not defined in our TeamCity build. Version 5.3.5 was showing this warning message but `GitVersion` was not failing. 

```
TeamCity doesn't make the current branch available through environmental variables.
Depending on your authentication and transport setup of your git VCS root things may work. In that case, ignore this warning.
In your TeamCity build configuration, add a parameter called `env.Git_Branch` with value %teamcity.build.vcs.branch.<vcsid>%
See https://gitversion.net/docs/build-server-support/build-server/teamcity for more info
```

With 5.6.1, I had the same warning but it caused GitVersion to fail. Once the root cause was found, I had to:

1. Add a TeamCity environment parameter that contains `%teamcity.build.vcs.branch.<vcsid>%`
2. Modify our Cake script to forward that environment variable to `GitVersion`
3. Repeat that for **55** TeamCity build configurations!

So, in the end our code is in a better shape but I must admit that it sent me off my planned tasks for the whole day.

Was there a release note or warning to prevent users that some tags would be deleted from DockerHub? If yes, where can I subscribe to such release notes?

**Comment by dbrougham** [comment]
Hi @arturcic, 

Any chance the `gittools/gitversion:5.2.1-netcoreapp2.1` image can be added back into docker hub?

Also just wondering why this happened? Has someone manually gone in and purged these images? Can imagine this is going to have widespread impact on many teams/orgs CI systems.

Cheers,

**Comment by arturcic** [comment]
@dbrougham  @mabead  @y0m1g I rebuilt the tags, hope they work as original images. I had to build the images in the format -

`gittools/gitversion:$(Tag)-linux-$(Distro)-netcoreapp$(Version)` where `Tag` is the gitversion version tag, `Distro` is the linux distro and `Version` is the .net core version (2.1 or 3.1)

You can have a look here. I was able to build only for version 5.1.3 - 5.5.1 of GitVersion. So please consider targeting one of the tags from the range, or better the 5.6.x tags if possible.

@y0m1g I will try to use the same approach for windows containers, but we won't build windows containers starting v5.6.0 onwards

**Comment by dbrougham** [comment]
Thanks @arturcic, we will look to use the new tag format.

Out of interest, how did this occur? It seems a bit odd to have these images disappear? We now have a large number of repos that will require updates.

**Comment by arturcic** [comment]
@y0m1g I did the same build for [nanoserver ](https://hub.docker.com/repository/docker/gittools/gitversion/tags?page=1&ordering=last_updated&name=nanoserver)

> Out of interest, how did this occur.
I will check that when I can get some spare time. for now closing this issue

I restored the images in this format
`gittools/gitversion:$(Tag)-linux-$(Distro)-netcoreapp$(Version)`
`gittools/gitversion:$(Tag)-windows-$(Distro)-netcoreapp$(Version)`

 where Tag is the gitversion version tag, Distro is the linux distro (or nanoserver for windows) and Version is the .net core version (2.1 or 3.1)
