### ISSUE TITLE
[Bug] Drone Pipeline crash while trying to run GitVersion

### ISSUE THREAD

**Issue by ppodevlab** [GitTools/GitVersion#2705]
**Describe the bug**
Executing docker container on Drone.io pipeline GitVersion crash

## Expected Behavior
Expected output from GitVersion

## Actual Behavior
```
INFO [05/25/21 10:02:15:28] Applicable build agent found: 'Drone'.
--
2 | INFO [05/25/21 10:02:15:30] Working directory: /drone/src
3 | INFO [05/25/21 10:02:15:32] Branch from build environment: feature/drone-ci
4 | INFO [05/25/21 10:02:15:32] Project root is: /drone/src/
5 | INFO [05/25/21 10:02:15:32] DotGit directory is: /drone/src/.git
6 | INFO [05/25/21 10:02:15:32] Begin: Normalizing git directory for branch 'feature/drone-ci'
7 | INFO [05/25/21 10:02:15:36] One remote found (origin -&gt; 'https://bitbucket.voiceworks.com/scm/uc2/sm-web.git').
8 | INFO [05/25/21 10:02:15:36] Fetching from remote 'origin' using the following refspecs: +refs/heads/*:refs/remotes/origin/*.
9 | INFO [05/25/21 10:02:15:59] End: Normalizing git directory for branch 'feature/drone-ci' (Took: 262.49ms)
10 | ERROR [05/25/21 10:02:15:60] An unexpected error occurred:
11 | LibGit2Sharp.LibGit2SharpException: No error message has been provided by the native library
12 | at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
13 | at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result)
14 | at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteHandle remote, IEnumerable`1 refSpecs, GitFetchOptions fetchOptions, String logMessage)
15 | at LibGit2Sharp.Commands.Fetch(Repository repository, String remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage)
16 | at GitVersion.GitRepository.&lt;&gt;c__DisplayClass33_0.&lt;Fetch&gt;b__0() in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 199
17 | at GitVersion.RepositoryExtensions.RunSafe(Action operation) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\RepositoryExtensions.cs:line 16
18 | at GitVersion.GitRepository.Fetch(String remote, IEnumerable`1 refSpecs, AuthenticationInfo auth, String logMessage) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 197
19 | at GitVersion.GitPreparer.&lt;&gt;c__DisplayClass17_1.&lt;NormalizeGitDirectory&gt;b__5() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitPreparer.cs:line 185
20 | at GitVersion.Helpers.RetryAction`1.&lt;&gt;c__DisplayClass1_0.&lt;Execute&gt;b__0() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Helpers\RetryAction.cs:line 20
21 | at Polly.Policy`1.&lt;&gt;c__DisplayClass11_0.&lt;Execute&gt;b__0(Context ctx, CancellationToken ct)
22 | at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
23 | at Polly.Retry.RetryPolicy`1.Implementation(Func`3 action, Context context, CancellationToken cancellationToken)
24 | at Polly.Policy`1.Execute(Func`3 action, Context context, CancellationToken cancellationToken)
25 | at Polly.Policy`1.Execute(Func`1 action)
26 | at GitVersion.Helpers.RetryAction`2.Execute(Func`1 operation) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Helpers\RetryAction.cs:line 42
27 | at GitVersion.Helpers.RetryAction`1.Execute(Action operation) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Helpers\RetryAction.cs:line 18
28 | at GitVersion.GitPreparer.NormalizeGitDirectory(Boolean noFetch, String currentBranchName, Boolean isDynamicRepository) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitPreparer.cs:line 185
29 | at GitVersion.GitPreparer.NormalizeGitDirectory(String targetBranch, Boolean isDynamicRepository) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitPreparer.cs:line 147
30 | at GitVersion.GitPreparer.PrepareInternal(Boolean normalizeGitDirectory, String currentBranch, Boolean shouldCleanUpRemotes) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitPreparer.cs:line 77
31 | at GitVersion.GitPreparer.Prepare() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitPreparer.cs:line 59
32 | at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 43
33 | at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 70
34 | INFO [05/25/21 10:02:15:60] Attempting to show the current git graph (please include in issue):
35 | INFO [05/25/21 10:02:15:60] Showing max of 100 commits
36 | INFO [05/25/21 10:02:15:71] * 1229b0a8c 23 seconds ago  (HEAD -&gt; feature/drone-ci, origin/feature/drone-ci)
```
## Steps to Reproduce
I've been able to reproduce the error on my local environment by adding the env var `DRONE=true`
```
docker run --rm -e DRONE=true  -e DRONE_BRANCH=master -v $(pwd):/repo gittools/gitversion /repo
```

## Your Environment
Drone server running on k8s cluster using bitbucket server as git source.

**Comment by asbjornu** [comment]
I can't seem to find out which Docker Image you are running here?

**Comment by pedroparraortega** [comment]
> I can't seem to find out which Docker Image you are running here?

i've tested with `gittools/gitversion` and  `gittools/gitversion:5.6.10-beta1-17-alpine.3.12-x64-3.1`

**Comment by mglochsen** [comment]
Might be caused by #2711

**Comment by pedroparraortega** [comment]
> Might be caused by #2711

i've tested it with a repo which only have master and no tags and it is happening the same issue
