### ISSUE TITLE
[Bug] Unexpected end of JSON input

### ISSUE THREAD

**Issue by sylvaingirardbe** [GitTools/GitVersion#2802]
**Describe the bug**
Since today our Ubuntu 20.04 build agents running version 5.6.11 of GitVersion.Tool are failing with Unexpected end of JSON input. A Windows agent running version 5.5.1 is working correctly.

## Expected Behavior
GitVersion completes successfully.

## Actual Behavior
Failing with this stack:
```
  ERROR [08/11/21 13:47:44:62] An unexpected error occurred:
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitVersion.GitObject..ctor(GitObject innerGitObject) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitObject.cs:line 12
INFO [08/11/21 13:47:43:98] Working directory: /azp/agent/_work/4/s
   at GitVersion.Commit..ctor(Commit innerCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 15
   at GitVersion.GitRepository.<>c__DisplayClass27_0.<FindMergeBase>b__0() in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 64
   at Polly.Policy`1.<>c__DisplayClass11_0.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy`1.Implementation(Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy`1.Execute(Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy`1.Execute(Func`1 action)
   at GitVersion.Helpers.RetryAction`2.Execute(Func`1 operation) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Helpers\RetryAction.cs:line 37
   at GitVersion.GitRepository.FindMergeBase(ICommit commit, ICommit otherCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 62
   at GitVersion.RepositoryStore.FindMergeBase(IBranch branch, IBranch otherBranch) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 48
   at GitVersion.RepositoryStore.<>c__DisplayClass29_0.<GetMergeCommitsForBranch>b__2(IBranch otherBranch) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 456
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.OrderedEnumerable`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitVersion.RepositoryStore.GetMergeCommitsForBranch(IBranch branch, Config configuration, IEnumerable`1 excludedBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 440
   at GitVersion.RepositoryStore.FindCommitBranchWasBranchedFrom(IBranch branch, Config configuration, IBranch[] excludedBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 321
   at GitVersion.Configuration.BranchConfigurationCalculator.InheritBranchConfiguration(IBranch targetBranch, BranchConfig branchConfiguration, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 81
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfiguration(IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 47
   at GitVersion.GitVersionContextFactory.Create(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionContextFactory.cs:line 40
   at GitVersion.GitVersionCoreModule.<>c__DisplayClass0_0.<RegisterTypes>b__1() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\GitVersionCoreModule.cs:line 38
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at GitVersion.VersionCalculation.NextVersionCalculator.get_context() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 17
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 32
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 52
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 70

```

This is the graph shown:
```
|\  
| * 72318e1cd 23 minutes ago  (bugfix/AL2-2682_AttachLinkedOrders)
|/  
*   2c056fe34 2 hours ago 
|\  
| * a526c864d 4 hours ago 
|/  
| * c19fb3c9f 6 hours ago  (origin/feature/AL2-2555_EndLevelCalc, feature/AL2-2555_EndLevelCalc)
| * 9938335e5 25 hours ago 
| * 320b12e2f 27 hours ago 
| * 04b10d285 29 hours ago 
| *   6869607f7 30 hours ago 
| |\  
| |/  
|/|   
* |   0be3d759b 30 hours ago 
|\ \  
| * | 48a1fbcd2 31 hours ago 
| * | 6f6c598c3 31 hours ago 
|/ /  
* |   ca81e4615 31 hours ago 
|\ \  
| * | d1dda06cb 2 days ago  (feature/AL2-2680_OpenTelemetry)
* | |   2286800cf 32 hours ago 
|\ \ \  
| * | | e4d3a5ed8 2 days ago 
| * | | 600fa3c25 2 days ago 
| * | | d9fd527e6 2 days ago 
| | | * ad4650afe 32 hours ago 
| | | *   f92ac198f 32 hours ago 
| | | |\  
| |_|_|/  
|/| | |   
* | | |   a6404ece6 2 days ago 
|\ \ \ \  
| * | | | 14f0d88c4 2 days ago 
|/ / / /  
* | | |   cc9201961 2 days ago 
|\ \ \ \  
| |/ / /  
|/| | |   
| * | | f5e9d0c25 2 days ago 
| * | | b7c1196dc 2 days ago 
| * | | 67d97fca8 5 days ago 
| * | | 11bd23b46 5 days ago 
| * | | 996ebd855 5 days ago 
| * | | e9bf78ea1 5 days ago 
| |/ /  
* | |   b4e93c384 2 days ago 
|\ \ \  
| |/ /  
|/| |   
| * | 84c5c4faa 5 days ago 
| * | be9542e9c 5 days ago 
| * | 302f5926e 6 days ago 
| * | 1166a4e03 6 days ago 
| * | 1023f4b69 6 days ago 
| * | bca2a54b8 6 days ago 
| * | 40f91ef77 6 days ago 
| * | 904b9f2cf 6 days ago 
| * | ec569337d 6 days ago 
|/ /  
* |   11e87a776 6 days ago 
|\ \  
| * | 83a26fdcd 6 days ago 
| * | 3f7ecd34a 6 days ago 
* | |   a97c66c5a 6 days ago 
|\ \ \  
| |/ /  
|/| |   
| * | 089358ef2 6 days ago 
| * | d4f3d79db 6 days ago 
* | |   216eabcc4 6 days ago 
|\ \ \  
| |/ /  
|/| |   
| * |   1c7259e5c 6 days ago 
| |\ \  
| |/ /  
|/| |   
* | |   dfac053af 6 days ago 
|\ \ \  
| * | | cabd2fced 6 days ago 
| * | | 2f0b858a9 6 days ago 
| * | | d6bdaa182 6 days ago 
|/ / /  
| * | 8f4a97c71 6 days ago  (bugfix/AL2-2653_Tank2Tank_SourceAndTarget)
| * | 2fe8fef68 6 days ago 
|/ /  
| * 09e4527a3 4 weeks ago 
| *   3bd8fe558 4 weeks ago 
| |\  
| * \   ffb0137ef 4 weeks ago 
| |\ \  
| * | | b1bf0a83c 5 weeks ago 
| * | | f091ea520 5 weeks ago 
| | | | * 0fc87ce03 7 hours ago  (origin/develop, develop)
| | | | * 462fb779f 7 hours ago 
| | | | * 173d66cb2 7 hours ago 
| | | | * 377c6aaa0 8 hours ago 
| | | | * c0c7c6ddb 8 hours ago 
| | | | * 9fe0bf487 8 hours ago 
| | | | * d4e9272b5 8 hours ago 
| | | | *   794767c58 5 months ago 
| | | | |\  
| | | | | * e61cd69b4 5 months ago 
| | | | |/| 
| | | | | *   08facb5d0 5 months ago 
| | | | | |\  
| | | | * | \   fd105b8a2 5 months ago 
| | | | |\ \ \  
| | | | | * | | b944e0deb 5 months ago 
| | | | |/ / /  
| | | | * | |   48e05a3be 5 months ago 
| | | | |\ \ \  
| | | | | * | | efde62cd5 5 months ago 
| | | | |/| | | 
| | | | | | |/  
| | | | | |/|   
| | | | | * |   6d1d2c4d5 5 months ago 
| | | | | |\ \  
| | | | | | * | 02dd2d07f 5 months ago 
| | | | | | * | 164245375 5 months ago 
| | | | | |/ /  
| | | | | * |   ce3f1a404 5 months ago 
| | | | | |\ \  
| | | | * | \ \   3b81ba115 5 months ago 
| | | | |\ \ \ \  
| | | | | |_|/ /  
| | | | |/| | /   
| | | | | | |/    
| | | | | |/|     
| | | | | * | 46ea616ee 5 months ago 
| | | | |/ /  
| | | | * |   d3bac7b6a 5 months ago 
| | | | |\ \  
| | | | | * | 8cf6f7a76 5 months ago 
| | | | | * | b7439d906 5 months ago 
| | | | | * | 380971b59 5 months ago 
| | | | |/ /  
| | | | * |   b4942b31e 5 months ago 
| | | | |\ \  
| | | | | |/  
| | | | |/|   
| | | | | * 0c3772d88 9 months ago 
| | | | | * 9cc042597 9 months ago 
| | | | | *   0a1e6e20a 9 months ago 
| | | | | |\  
| | | | | | * e5bd168d7 9 months ago 
| | | | | | * ab71bd8aa 9 months ago 
| | | | | | * b8e373272 9 months ago 
| | | | | | * 7eaa87ef2 9 months ago 
| | | | | | * d3b4c0743 9 months ago 
| | | | | | * 82a51d6be 9 months ago 
| | | | | | * ad1ddd387 9 months ago 
| | | | | | * 5cb517d13 9 months ago 
| | | | | | * b7fb89d74 9 months ago 
| | | | | | * 348e0bbaf 9 months ago 
| | | | | | * b9cb8b170 9 months ago 
| | | | | | *   99d37f464 9 months ago 
| | | | | | |\  
| | | | | | * | 59b369d50 9 months ago 
| | | | | * | | b3beaaf6a 9 months ago 
| | | | | | |/  
| | | | | |/|   
```

## Possible Fix
Using version 5.5.1 on Windows.

## Context
Determine the next version in our build pipeline.

## Your Environment

- Version Used: 5.6.11
- Operating System and version (Windows 10, Ubuntu 18.04): Ubuntu 20.04

**Comment by sylvaingirardbe** [comment]
It seems the issues was caused by accidentally pushing a develop branch from another repo into this repo (previous repo was renamed but the origin wasn't updated). Removing the branch and restarting the agents fixed the issue.
