### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by amballapavankumar** [GitTools/GitVersion#2833]
ERROR [09/02/21 6:43:58:88] An unexpected error occurred:
System.NullReferenceException: Object reference not set to an instance of an object.
INFO [09/02/21 6:43:57:63] Working directory: /azp/agent/_work/72/s
   at LibGit2Sharp.Core.Handles.ObjectHandle.op_Implicit(ObjectHandle handle)
   at LibGit2Sharp.Core.Proxy.git_commit_author(ObjectHandle obj)
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.LibGit2Sharp.Core.LazyGroup<T>.IEvaluator<TInput>.Evaluate(TInput input)
   at LibGit2Sharp.Core.LazyGroup`1.<Evaluate>b__6_0(T input)
   at LibGit2Sharp.Core.GitObjectLazyGroup.EvaluateInternal(Action`1 evaluator)
   at LibGit2Sharp.Core.LazyGroup`1.Evaluate()
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.Evaluate()
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.get_Value()
.
.
.
.
.
.
##[error]SyntaxError: Unexpected end of JSON input

This issue is happeninng intermittent. When we rerun which is working fine.

**Comment by asbjornu** [comment]
Do you have a publicly available repository where this behaviour is possible to reproduce?

**Comment by amballapavankumar** [comment]
This issue has been resolved after removing the shallow clone.
