### ISSUE TITLE
[Bug] SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by olie-chan** [GitTools/GitVersion#2858]
I was getting the following error with GitVersion 5.7 in my azure devops pipeline.

```
2021-09-22T09:41:49.5845481Z   INFO [09/22/21 9:41:49:55] Done writing 
2021-09-22T09:41:49.5872177Z ##[error]SyntaxError: Unexpected end of JSON input
2021-09-22T09:41:49.5884070Z    at GitVersion.Commit..ctor(Commit innerCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 15
2021-09-22T09:41:49.5884827Z    at GitVersion.GitRepository.<>c__DisplayClass27_0.<FindMergeBase>b__0() in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 64
2021-09-22T09:41:49.5885439Z    at Polly.Policy`1.<>c__DisplayClass11_0.<Execute>b__0(Context ctx, CancellationToken ct)
2021-09-22T09:41:49.5886258Z    at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
2021-09-22T09:41:49.5887101Z    at Polly.Retry.RetryPolicy`1.Implementation(Func`3 action, Context context, CancellationToken cancellationToken)
2021-09-22T09:41:49.5887583Z    at Polly.Policy`1.Execute(Func`3 action, Context context, CancellationToken cancellationToken)
2021-09-22T09:41:49.5887972Z    at Polly.Policy`1.Execute(Func`1 action)
2021-09-22T09:41:49.5888485Z    at GitVersion.Helpers.RetryAction`2.Execute(Func`1 operation) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Helpers\RetryAction.cs:line 37
2021-09-22T09:41:49.5889262Z    at GitVersion.GitRepository.FindMergeBase(ICommit commit, ICommit otherCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 62
2021-09-22T09:41:49.5890078Z    at GitVersion.RepositoryStore.FindMergeBase(ICommit commit, ICommit mainlineTip) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 488
2021-09-22T09:41:49.5891299Z    at GitVersion.VersionCalculation.MainlineVersionCalculator.AggregateMergeCommitIncrement(ICommit commit, List`1 directCommits, SemanticVersion mainlineVersion, IBranch mainline) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\MainlineVersionCalculator.cs:line 112
2021-09-22T09:41:49.5892439Z    at GitVersion.VersionCalculation.MainlineVersionCalculator.FindMainlineModeVersion(BaseVersion baseVersion) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\MainlineVersionCalculator.cs:line 66
2021-09-22T09:41:49.5893360Z    at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 63
2021-09-22T09:41:49.5894162Z    at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 52
2021-09-22T09:41:49.5894965Z    at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 70
```

And from what I can reverse engineer, it's because I didn't have version tags, so I managed to fix it by pushing up a default version tag of `0.1.0`.

Hopefully this helps the next person who might encounter this

**Comment by asbjornu** [comment]
Seems like this is a duplicate of #2690 and perhaps related to #2567.
