### ISSUE TITLE
Ignore tags matching a pattern/regex

### ISSUE THREAD

**Issue by Constantin07** [GitTools/GitVersion#2924]
## Detailed Description

I couldn't find in documentation if I can ignore some tags from calculation, by regex or pattern.

**Scenario**: Some historical tags have a timestamp in them, e.g. `1.0.11-develop-20211125143917`
and this makes GitVersion to fail miserably with error:

```
  ERROR [11/26/21 9:58:52:93] An unexpected error occurred:
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at GitVersion.SemanticVersionPreReleaseTag.Parse(String preReleaseTag)
   at GitVersion.SemanticVersion.TryParse(String version, String tagPrefixRegex, SemanticVersion& semanticVersion)
   at GitVersion.RepositoryStore.GetValidVersionTags(String tagPrefixRegex, Nullable`1 olderThan)
   at GitVersion.VersionCalculation.TaggedCommitVersionStrategy.GetTaggedVersions(IBranch currentBranch, Nullable`1 olderThan)
   at GitVersion.VersionCalculation.TaggedCommitVersionStrategy.GetVersions()
   at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersions(IVersionStrategy strategy)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersion()
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion()
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables()
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions)
  INFO [11/26/21 9:58:52:93] Attempting to show the current git graph (please include in issue):
  INFO [11/26/21 9:58:52:93] Showing max of 100 commits
```

## Context
At the moment the workaround is to remove all tags matching this pattern in pipeline but this is ugly.

## Possible Implementation
1. Add support for timestamp in tags so that it doesn't fail.
2. Add support to exclude some tags by regex/pattern

**Comment by Constantin07** [comment]
UPDATE: found a way to use `tag-prefix` for this purpose.
