### ISSUE TITLE
[Bug] merge-message-formats sample from docs gives error

### ISSUE THREAD

**Issue by sommmen** [GitTools/GitVersion#2986]
**Describe the bug**

Trying to add the sample for `merge-message-formats` fromt the docs gives an error.

Full config:

``` yaml
mode: Mainline
branches: 
  master:
    regex: ^master$|^main$
    increment: Patch
  feature:
    regex: ^[fF]eature?[/-]
    source-branches: ['master', 'feature']
    increment: Minor
ignore:
  sha: []
merge-message-formats:
    tfs: ^Merged (?:PR (?<PullRequestNumber>\d+)): Merge (?<SourceBranch>.+) to (?<TargetBranch>.+)
```

## Expected Behavior
No error.

## Actual Behavior

```
INFO [02/05/22 14:56:54:53] Working directory: C:\Repos\dotnet-api
INFO [02/05/22 14:56:54:54] Project root is: C:\Repos\dotnet-api\
INFO [02/05/22 14:56:54:54] DotGit directory is: C:\Repos\dotnet-api\.git
INFO [02/05/22 14:56:54:57] Begin: Loading version variables from disk cache
  INFO [02/05/22 14:56:54:57] Cache file C:\Repos\dotnet-api\.git\gitversion_cache\9B4D6BF4CE7033E9CF92DBD61CBFD4418F42157D.yml not found.
  INFO [02/05/22 14:56:54:57] End: Loading version variables from disk cache (Took: 0.46ms)
  ERROR [02/05/22 14:56:54:65] An unexpected error occurred:
YamlDotNet.Core.SemanticErrorException: (Line: 13, Col: 52, Idx: 291) - (Line: 13, Col: 52, Idx: 291): While scanning a plain scalar value, found invalid mapping.
   at YamlDotNet.Core.Parser.ParseNode(Boolean isBlock, Boolean isIndentlessSequence)
   at YamlDotNet.Core.Parser.ParseBlockMappingValue()
   at YamlDotNet.Core.Parser.StateMachine()
   at YamlDotNet.Core.Parser.MoveNext()
   at YamlDotNet.Core.ParserExtensions.TryConsume[T](IParser parser, T& event)
   at YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.DeserializeHelper(Type tKey, Type tValue, IParser parser, Func`3 nestedObjectDeserializer, IDictionary result)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at GitVersion.Configuration.ConfigSerializer.Read(TextReader reader) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\ConfigSerializer.cs:line 11
   at GitVersion.Configuration.ConfigFileLocator.ReadConfig(String workingDirectory) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\ConfigFileLocator.cs:line 48
   at GitVersion.Configuration.ConfigProvider.Provide(String workingDirectory, Config overrideConfig) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\ConfigProvider.cs:line 39
   at GitVersion.Configuration.ConfigProvider.Provide(Config overrideConfig) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\ConfigProvider.cs:line 35
   at GitVersion.GitVersionContextFactory.Create(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionContextFactory.cs:line 29
   at GitVersion.GitVersionCoreModule.<>c__DisplayClass0_0.<RegisterTypes>b__1() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\GitVersionCoreModule.cs:line 37
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at GitVersion.VersionCalculation.NextVersionCalculator.get_context() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 15
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 30
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 51
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 66
  INFO [02/05/22 14:56:54:65] Attempting to show the current git graph (please include in issue):
  INFO [02/05/22 14:56:54:65] Showing max of 100 commits
  INFO [02/05/22 14:56:54:71] *   42e5240 2 days ago  (HEAD -> master, origin/master, origin/HEAD)
|\
| * 49fe448 2 days ago
| * be9cd5c 2 days ago
* | 10ce675 2 days ago
|/
* 7803533 3 days ago
| * e0efd98 3 days ago  (feature/553_ProdStatsPartnerFilter)
| * 33ca1ba 3 days ago
| * 0e36b66 3 days ago
| * e997648 3 days ago
| * 32a24cc 3 days ago
| * 1c43660 4 days ago
| * 8764f78 4 days ago
|/
* 9cab429 4 days ago
* c18ba83 5 days ago
* 645bdb2 5 days ago
* 2ceb218 8 days ago
* 44e49d0 9 days ago
* ccdc0da 9 days ago
| *   2cbc050 9 days ago  (feature/547_FixupProdStats2)
| |\
| |/
|/|
* | f1d15ea 9 days ago
* | 136ae2a 9 days ago
| * 907ffed 9 days ago
| * 993690f 9 days ago
| * e5b647f 9 days ago
| * 07d68b5 9 days ago
| * 54d496c 10 days ago
| * 969d794 10 days ago
| * 984cc4d 10 days ago
| * 32f3186 10 days ago
| * 72a6e9f 10 days ago
| * c64584c 10 days ago
| *   697d36e 11 days ago
| |\
| |/
|/|
* | 86a3830 11 days ago
| * 3987a72 11 days ago
|/
* 0743243 11 days ago
* 3bd8fcf 11 days ago
| *-.   93dbb66 11 days ago  (refs/stash)
| |\ \
| | | * ce91b4c 11 days ago
| | * a6946d5 11 days ago
| |/
| * 89e0985 12 days ago
| * d83ff99 12 days ago
| *   7e4c344 12 days ago
| |\
| |/
|/|
* | ba3c5fb 2 weeks ago
* | 8d6b06a 2 weeks ago
| * 96f722e 2 weeks ago
|/
* 4e8c840 2 weeks ago
* 07a297d 2 weeks ago
* 3b097b2 2 weeks ago
* c34dd24 2 weeks ago
*   1bb792e 2 weeks ago
|\
| * 73235df 3 weeks ago
* | 68ddcd2 2 weeks ago
|/
* 4dcbbda 3 weeks ago
* 64d5321 3 weeks ago
* d060a1b 3 weeks ago
| * ebf1c91 3 weeks ago  (temp/StringTruncator)
| * 13fc9b9 4 weeks ago
| *   a79fb54 4 weeks ago
| |\
| |/
|/|
* | 9ee1f6e 4 weeks ago
* | 7a156fd 4 weeks ago
* | 07f7156 4 weeks ago
* | cfe5dc8 4 weeks ago
* | 5dad23d 4 weeks ago
* | 5afdb8b 4 weeks ago
| *   c7fd599 4 weeks ago
| |\
| |/
|/|
* | db723ad 4 weeks ago
* | 73a67bb 4 weeks ago
* | 669e567 4 weeks ago
* | 6e9af65 4 weeks ago
| * df7eb45 4 weeks ago
| * 0ae9187 4 weeks ago
| *   3d84905 4 weeks ago
| |\
| |/
|/|
* | 720d9ce 4 weeks ago
* |   6d3c8fe 4 weeks ago
|\ \
* | | 81e2591 4 weeks ago
| | * c95da3d 4 weeks ago
| | * 650b7f4 4 weeks ago
| |/
| * e809cc5 5 weeks ago
| * c3a55ec 5 weeks ago
|/
* 79dbd89 5 weeks ago
* 6e3d20e 6 weeks ago
* b193e40 6 weeks ago
* 8c93a4e 6 weeks ago
* 34211e5 7 weeks ago  (tag: 2021-12-20_2, origin/production)
* 926bdbf 7 weeks ago  (tag: 2021-12-20, origin/staging)
* 42c5c40 7 weeks ago
*   4562c67 7 weeks ago
|\
| * e2ad609 8 weeks ago
| * a83f088 8 weeks ago
| * c1325f5 8 weeks ago
* | a67daff 7 weeks ago
| | * 08e535e 6 weeks ago  (origin/feature/527_shipping_cost_overview)
| | * c8230b7 7 weeks ago
| | * 58eb27d 7 weeks ago
| |/
| * c30ab5c 9 weeks ago
|/
* d3c6dbb 9 weeks ago
*   099201c 9 weeks ago
|\
| *   90ae6db 10 weeks ago
| |\
| | * 3fa56fc 10 weeks ago
| |/
* / bc6bc28 9 weeks ago
|/


```

## Context

I'm fiddling with the config to adapt it to Azure devOps pipelines with the following flow:
I have one master branch. Fixes get applied directly to the master branch (patch++) whilst features are always applied via a feature branch (Minor++). Major versions are done manually by tagging the master branch.

Going full gitflow/githubflow is not accepted by colleagues who consistently use the master branch to apply hotfixes. I can't seem to get the config right for this setup though.

Whilst trying to do tis i noted that most PR merges of devops have the following message structure:
`^Merged PR (?<PullRequestNumber>\d+): ` so i was hoping to add that to `merge-message-formats`.

## Your Environment

- Version Used: Latest nuget tool
- Operating System and version (Windows 10, Ubuntu 18.04): Win11
- Link to your project: private
- Link to your CI build (if appropriate): private

**Comment by sommmen** [comment]
Single quoting the thing stops this:

`  tfs: '^Merged (?:PR (?<PullRequestNumber>\d+)): Merge (?<SourceBranch>.+) to (?<TargetBranch>.+)'`

**Comment by asbjornu** [comment]
It sounds like a good idea to quote that value, yes. Would you be up for submitting a PR fixing this in the documentation?

**Comment by sommmen** [comment]
> It sounds like a good idea to quote that value, yes. Would you be up for submitting a PR fixing this in the documentation?

I'll take a look (wish github had a remind me feature for this cause i hope i don't forget)
