### ISSUE TITLE
[Bug] LibGit2Sharp.NameConflictException: failed to make directory

### ISSUE THREAD

**Issue by MeikelLP** [GitTools/GitVersion#3015]
**Describe the bug**
I have the branch `hotfix/ibsd-7668` and GitVersion fails only on that branch which is a bummer.
Similar to #864 (?)

## Expected Behavior
Just works :)

## Actual Behavior
```
LibGit2Sharp.NameConflictException: failed to make directory 'D:/agentpool/_work/15/s/.git/logs/refs/heads/hotfix': directory exists
     at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 136
     at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 173
     at LibGit2Sharp.Core.Proxy.git_reference_ensure_log(RepositoryHandle repo, String refname) in /_/LibGit2Sharp/Core/Proxy.cs:line 2020
     at LibGit2Sharp.ReferenceCollection.EnsureHasLog(String canonicalName) in /_/LibGit2Sharp/ReferenceCollection.cs:line 852
     at LibGit2Sharp.ReferenceCollection.Add(String name, String canonicalRefNameOrObjectish, String logMessage, Boolean allowOverwrite) in /_/LibGit2Sharp/ReferenceCollection.cs:line 143
     at LibGit2Sharp.ReferenceCollection.Add(String name, String canonicalRefNameOrObjectish, Boolean allowOverwrite) in /_/LibGit2Sharp/ReferenceCollection.cs:line 167
     at GitVersion.ReferenceCollection.Add(String name, String canonicalRefNameOrObjectish, Boolean allowOverwrite) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\ReferenceCollection.cs:line 10
     at GitVersion.GitPreparer.CreateOrUpdateLocalBranchesFromRemoteTrackingOnes(String remoteName) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitPreparer.cs:line 339
     at GitVersion.GitPreparer.NormalizeGitDirectory(Boolean noFetch, String currentBranchName, Boolean isDynamicRepository) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitPreparer.cs:line 188
     at GitVersion.GitPreparer.NormalizeGitDirectory(String targetBranch, Boolean isDynamicRepository) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitPreparer.cs:line 144
     at GitVersion.GitPreparer.PrepareInternal(Boolean normalizeGitDirectory, String currentBranch, Boolean shouldCleanUpRemotes) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitPreparer.cs:line 76
     at GitVersion.GitPreparer.Prepare() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitPreparer.cs:line 57
     at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 51
     at GitVersion.GitVersionExecutor.RunGitVersi
```

## Possible Fix
Don't use `hotfix/` branches (?)

## Your Environment
- Version Used: 5.8.2
- Operating System and version (Windows 10, Ubuntu 18.04): Win Server 2016
- Link to your project:
- Link to your CI build (if appropriate):

**Comment by MeikelLP** [comment]
This issue occurs as long as the `hotfix/something` branch exists on the remote. All other branches will fail as well until that branch is deleted.

**Comment by asbjornu** [comment]
This seems like some Windows pathing peculiarities, the exception is thrown by LibGit2Sharp and I highly doubt there's anything we can do in GitVersion to circumvent this. Perhaps you have casing differences in your branches, so some are called `HotFix/*` and others `hotfix/*`?

**Comment by MeikelLP** [comment]
For everybody who's running into this issue in the future. We changed our pipeline to always build on Linux. We still have to deploy on our Windows machine due to security policies but the build (and GitVersion) runs on linux.

This is still a workaround. IMO GitVersion should handle paths differently depending on which OS/FS it's running on.

**Comment by asbjornu** [comment]
It's not up to GitVersion to handle paths as no paths are actually created by GitVersion. We rely on LibGit2Sharp to do it. We would have to write a lot of code around LibGit2 in order to detect these file system inconsistencies before handing control over to LibGit2Sharp. That is simply out of scope for GitVersion. 

Having the correct casing of files in the file system is just as important as having the correct casing of methods or variables you reference in C#. It is up to the developer to ensure this correctness, not up to GitVersion or the C# compiler. Closing as won't fix.
