### ISSUE TITLE
[Bug] NullReferenceException after git_commit_author

### ISSUE THREAD

**Issue by Invariel** [GitTools/GitVersion#3059]
**Describe the bug**
I'm not sure what I am doing wrong with my use of GitVersion through Git Actions, but including a GitVersion step results in this `NullReferenceException`.

## Expected Behavior
I would love an informative error message telling me what is missing, or for the exception to not be happening in the first place.

## Actual Behavior
```
INFO [03/29/22 13:57:10:85] Using latest commit on specified branch
  INFO [03/29/22 13:57:10:87] Begin: Attempting to inherit branch configuration from parent branch
  INFO [03/29/22 13:57:10:87] End: Attempting to inherit branch configuration from parent branch (Took: 5.30ms)
  ERROR [03/29/22 13:57:11:64] An unexpected error occurred:
System.NullReferenceException: Object reference not set to an instance of an object.
   at LibGit2Sharp.Core.Handles.ObjectHandle.op_Implicit(ObjectHandle handle) in /_/LibGit2Sharp/Core/Handles/Objects.cs:line 509
   at LibGit2Sharp.Core.Proxy.git_commit_author(ObjectHandle obj) in /_/LibGit2Sharp/Core/Proxy.cs:line 286
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.LibGit2Sharp.Core.LazyGroup<T>.IEvaluator<TInput>.Evaluate(TInput input) in /_/LibGit2Sharp/Core/LazyGroup.cs:line 88
   at LibGit2Sharp.Core.LazyGroup`1.<Evaluate>b__6_0(T input) in /_/LibGit2Sharp/Core/LazyGroup.cs:line 36
   at LibGit2Sharp.Core.GitObjectLazyGroup.EvaluateInternal(Action`1 evaluator) in /_/LibGit2Sharp/Core/GitObjectLazyGroup.cs:line 20
   at LibGit2Sharp.Core.LazyGroup`1.Evaluate() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 34
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.Evaluate() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 80
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.get_Value() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 73
   at LibGit2Sharp.Commit.get_Committer() in /_/LibGit2Sharp/Commit.cs:line 87
   at GitVersion.Commit..ctor(Commit innerCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 16
   at GitVersion.Commit.<>c.<.ctor>b__3_0(Commit parent) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 15
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at GitVersion.Configuration.BranchConfigurationCalculator.InheritBranchConfiguration(IBranch targetBranch, BranchConfig branchConfiguration, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 62
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfiguration(IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 44
   at GitVersion.GitVersionContextFactory.Create(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionContextFactory.cs:line 39
   at GitVersion.GitVersionCoreModule.<>c__DisplayClass0_0.<RegisterTypes>b__1() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\GitVersionCoreModule.cs:line 37
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at GitVersion.VersionCalculation.NextVersionCalculator.get_context() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 15
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 30
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 51
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 66
  INFO [03/29/22 13:57:11:65] Attempting to show the current git graph (please include in issue): 
  INFO [03/29/22 13:57:11:65] Showing max of 100 commits
  INFO [03/29/22 13:57:11:71] * 982cd91 2 minutes ago  (grafted, HEAD -> <project name>, <project name>)
```

## Possible Fix
N/A.

## Steps to Reproduce
I'm trying to build my project from a private repository, with private NuGet packages.  I have tried the default configuration (`useConfigFile: false`), and my own based on the default configuration (`useConfigFile: true`).

My Git Action looks like this:

```yaml
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        targetPath: <file path>
        configFilePath: <path to file>
        useConfigFile: false
        updateAssemblyInfo: true
        updateAssemblyInfoFilename: <path to file>
```

## Context
Because of the `NullReferenceException`, the Git Action fails and the build does not happen.

## Your Environment

- Version Used:
- Operating System and version Windows 10.
- Link to your project: Private repo.
- Link to your CI build (if appropriate): Git Action, with names removed:

```yaml
name: Project Name

on:
  workflow_dispatch:
    inputs:
      tag_for_release:
        required: true
        default: 'false'
      major_version:
        required: false
      dry_run:
        required: true
        default: 'false'

env:
  DOTNET_VERSION: '6.x' # The .NET SDK version to use
  GITVERSION_YAML_PATH: <path to file>
  CSPROJ: <path to file>

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Prepare Repository
      uses: actions/checkout@v2

    - name: Checkout GitHub Action Repo
      uses: actions/checkout@v2
      with:
        repository: <Private Repo link>
        ssh-key: ${{ secrets.SSH_KEY }}
        path: .github/actions

    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        source-url: <path to file>
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.ACTION_AUTH_TOKEN }}

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.8.0 ' # Was using 5.x, tried to see if a previous version fixed my issue, it did not.

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        targetPath: <path to file>
        configFilePath: <path to file>
        useConfigFile: false
        updateAssemblyInfo: true
        updateAssemblyInfoFilename: <path to file>

    - name: Build
      run: dotnet build ${{ env.CSPROJ }} --configuration Release

    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ steps.gitversion.outputs.fullSemVer }}',
            sha: context.sha
          })
```

Thank you in advance, even if you are unable to resolve my issue.

**Comment by asbjornu** [comment]
Why are you executing `actions/checkout@v2` three times? Either way, the last time you do it, you need to add `fetch-depth: 0` [as per the documentation](https://github.com/GitTools/actions/blob/main/docs/examples/github/gitversion/execute/usage-examples.md):

```yaml
  - uses: actions/checkout@v2
    with:
      fetch-depth: 0
```
