### ISSUE TITLE
[Bug] YamlDoNet failed on deserialize 

### ISSUE THREAD

**Issue by nicholas-chien** [GitTools/GitVersion#3090]
**Describe the bug**
got unexpected Exception when execute git version with configuration on Azure DevOps with GitTools 0.9.13 / GitVersion 5.10.1

```
2022-04-16T04:32:39.7947192Z YamlDotNet.Core.YamlException: (Line: 26, Col: 10, Idx: 845) - (Line: 26, Col: 10, Idx: 845): Exception during deserialization
2022-04-16T04:32:39.7948093Z  ---> System.InvalidOperationException: Failed to create an instance of type 'System.String'.
2022-04-16T04:32:39.7948918Z  ---> System.MissingMethodException: No parameterless constructor defined for type 'System.String'.
2022-04-16T04:32:39.7949611Z    at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
2022-04-16T04:32:39.7950381Z    at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
2022-04-16T04:32:39.7951076Z    at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
2022-04-16T04:32:39.7951595Z    at System.Activator.CreateInstance(Type type)
2022-04-16T04:32:39.7952102Z    at YamlDotNet.Serialization.ObjectFactories.DefaultObjectFactory.Create(Type type)
2022-04-16T04:32:39.7952760Z    --- End of inner exception stack trace ---
2022-04-16T04:32:39.7953248Z    at YamlDotNet.Serialization.ObjectFactories.DefaultObjectFactory.Create(Type type)
2022-04-16T04:32:39.7954122Z    at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
2022-04-16T04:32:39.7955201Z    at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
2022-04-16T04:32:39.7956092Z    --- End of inner exception stack trace ---
2022-04-16T04:32:39.7956820Z    at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
2022-04-16T04:32:39.7957941Z    at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
2022-04-16T04:32:39.7958938Z    at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
2022-04-16T04:32:39.7959906Z    at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
2022-04-16T04:32:39.7960992Z    at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
2022-04-16T04:32:39.7962048Z    at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
2022-04-16T04:32:39.7962977Z    at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
2022-04-16T04:32:39.7963890Z    at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.DeserializeHelper(Type tKey, Type tValue, IParser parser, Func`3 nestedObjectDeserializer, IDictionary result)
2022-04-16T04:32:39.7965192Z    at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
2022-04-16T04:32:39.7966284Z    at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
2022-04-16T04:32:39.7967345Z    at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
2022-04-16T04:32:39.7968285Z    at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
2022-04-16T04:32:39.7969240Z    at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
2022-04-16T04:32:39.7970336Z    at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
2022-04-16T04:32:39.7971379Z    at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
2022-04-16T04:32:39.7972259Z    at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
2022-04-16T04:32:39.7972822Z    at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
2022-04-16T04:32:39.7973354Z    at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
2022-04-16T04:32:39.7974140Z    at GitVersion.Configuration.ConfigSerializer.Read(TextReader reader) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\ConfigSerializer.cs:line 11
2022-04-16T04:32:39.7975159Z    at GitVersion.Configuration.ConfigFileLocator.ReadConfig(String workingDirectory) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\ConfigFileLocator.cs:line 49
2022-04-16T04:32:39.7976250Z    at GitVersion.Configuration.ConfigProvider.Provide(String workingDirectory, Config overrideConfig) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\ConfigProvider.cs:line 43
2022-04-16T04:32:39.7977319Z    at GitVersion.Configuration.ConfigProvider.Provide(Config overrideConfig) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\ConfigProvider.cs:line 36
2022-04-16T04:32:39.7978429Z    at GitVersion.GitVersionContextFactory.Create(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionContextFactory.cs:line 32
2022-04-16T04:32:39.7979531Z    at GitVersion.GitVersionCoreModule.<>c__DisplayClass0_0.<RegisterTypes>b__1() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\GitVersionCoreModule.cs:line 37
2022-04-16T04:32:39.7980245Z    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2022-04-16T04:32:39.7980832Z    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
2022-04-16T04:32:39.7981361Z    at System.Lazy`1.CreateValue()
2022-04-16T04:32:39.7981706Z    at System.Lazy`1.get_Value()
2022-04-16T04:32:39.7982413Z    at GitVersion.VersionCalculation.NextVersionCalculator.get_context() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 15
2022-04-16T04:32:39.7983471Z    at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 30
2022-04-16T04:32:39.7984491Z    at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 52
2022-04-16T04:32:39.7985524Z    at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 66
```

## Context
Here is my gitversion.yml file with pipeline

```
next-version: 1.0
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatchTag
assembly-informational-format: '{InformationalVersion}'
mode: ContinuousDelivery
increment: Inherit
continuous-delivery-fallback-tag: ci
tag-prefix: '[vV]'
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
commit-message-incrementing: Enabled
commit-date-format: 'yyyy-MM-dd'
merge-message-formats: {}
branches:
  develop:
    regex: ^develop?[/-]
    mode: ContinuousDelivery
    tag: {BranchName}-sd
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    source-branches: [ 'main' ]
    tracks-release-branches: true
    is-release-branch: false
    is-mainline: false
  main:
    regex: ^master$|^main$
    mode: ContinuousDelivery
    tag: main-qa
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    source-branches: [ 'develop' ]
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
  release:
    regex: ^release?[/-]
    mode: ContinuousDelivery
    tag: {BranchName}-ve
    increment: None
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    source-branches: [ 'main', 'production' ]
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
  production:
    regex: ^production?[/-]
    mode: ContinuousDelivery
    tag: production
    increment: None
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    source-branches: [ 'main', 'release' ]
    tracks-release-branches: false
    is-release-branch: true
    is-mainline: false
  pull-request:
    regex: ^(pull|pull\-requests|pr)[/-]
    mode: ContinuousDelivery
    tag: PullRequest
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
    track-merge-target: false
    source-branches: [ 'develop', 'main', 'release' ]
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
```

pipeline tasks:

```
        - task: gitversion/setup@0
          displayName: "Install GitVersion"
          inputs:
            versionSpec: "5.x"

        - task: gitversion/execute@0
          displayName: "Versioning"
          inputs:
            useConfigFile: true
            configFilePath: gitversion.yml
```

**Comment by asbjornu** [comment]
I recommend that you delete your `GitVersion.yml` file and only add the few keys you actually want to override. Having the entire default configuration is just a source of bugs and frustration as you now experience. If you go to [YAMLLint.com](http://www.yamllint.com/) and paste in your YAML file, you can see that it contains errors. Specifically, it seems that: 

```yaml
    tag: {BranchName}-sd
```

Should be quoted:


```yaml
    tag: '{BranchName}-sd'
```

**Comment by nicholas-chien** [comment]
> I recommend that you delete your `GitVersion.yml` file and only add the few keys you actually want to override. Having the entire default configuration is just a source of bugs and frustration as you now experience. If you go to [YAMLLint.com](http://www.yamllint.com/) and paste in your YAML file, you can see that it contains errors. Specifically, it seems that:
> 
> ```yaml
>     tag: {BranchName}-sd
> ```
> 
> Should be quoted:
> 
> ```yaml
>     tag: '{BranchName}-sd'
> ```

Thanks for @asbjornu kindly reply, after removing duplicated parts with default configuration file, and add quotes around tag name, the revised gitversion.yml has been worked again. Therefore I will close this issue and leave a path to others.

Here is my gitversion.yml after revised:

```
branches:
  develop:
    regex: ^develop?[/-]
    mode: ContinuousDelivery
    tag: 'sd.{BranchName}'
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    source-branches: [ 'main' ]
    tracks-release-branches: true
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 0
  main:
    regex: ^master$|^main$
    mode: ContinuousDelivery
    tag: 'qa.{BranchName}'
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    source-branches: [ 'develop' ]
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
    pre-release-weight: 30000
  release:
    regex: ^release?[/-]
    mode: ContinuousDelivery
    tag: 've.{BranchName}'
    increment: None
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    source-branches: [ 'main', 'production' ]
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  production:
    regex: ^production?[/-]
    mode: ContinuousDelivery
    tag: 'ol.{BranchName}'
    increment: None
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    source-branches: [ 'main', 'release' ]
    tracks-release-branches: false
    is-release-branch: true
    is-mainline: false
    pre-release-weight: 55000
  pull-request:
    regex: ^(pull|pull\-requests|pr)[/-]
    mode: ContinuousDelivery
    tag: ''
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
    track-merge-target: false
    source-branches: [ 'develop', 'main', 'release' ]
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
```
