### ISSUE TITLE
[Bug] Gitversion could not determine which branch to treat as the development branch

### ISSUE THREAD

**Issue by sanjivpurohit** [GitTools/GitVersion#3091]
**Describe the bug**
```
ERROR [04/18/22 16:49:40:48] An unexpected error occurred:
System.InvalidOperationException: Gitversion could not determine which branch to treat as the development branch (default is 'develop') nor release-able branch (default is 'main' or 'master'), either locally or remotely. Ensure the local clone and checkout match the requirements or considering using 'GitVersion Dynamic Repositories'
   at GitVersion.Configuration.BranchConfigurationCalculator.InheritBranchConfiguration(Int[32](https://github.com/Logitech/astro-leia/runs/6065381621?check_suite_focus=true#step:5:32) recursions, IBranch targetBranch, BranchConfig branchConfiguration, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 150
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfigurationInternal(Int32 recursions, IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 54
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfiguration(IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 28
   at GitVersion.GitVersionContextFactory.Create(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionContextFactory.cs:line 39
   at GitVersion.GitVersionCoreModule.<>c__DisplayClass0_0.<RegisterTypes>b__1() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\GitVersionCoreModule.cs:line [37](https://github.com/Logitech/astro-leia/runs/6065381621?check_suite_focus=true#step:5:37)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at GitVersion.VersionCalculation.NextVersionCalculator.get_context() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 15
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 30
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 52
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 66
```

## Expected Behavior
SemVer

## Actual Behavior
Unexpected error

## Your Environment

 Gitversion 5.10.1

- Version Used:
- Operating System and version (Windows 10, Ubuntu 18.04): Ubuntu 18.04 Gitversion 5.10.1
- Link to your project:
- Link to your CI build (if appropriate):

**Comment by asbjornu** [comment]
We would need more information to resolve this. My hunch is that the checkout is a detached `HEAD` or a shallow clone.

**Comment by sanjivpurohit** [comment]
The checkout was on a branch. The clone was a deep clone using checkout@v2 actions with fetch-depth set to 0.

**Comment by asbjornu** [comment]
Are you able to reproduce this in a public repository?

**Comment by sanjivpurohit** [comment]
I don't work much with public repository. The github repository contained Main and master branch but the default branch was master. I have now deleted the main branch and would test again. I would add more logs as I keep testing it.

**Comment by PaulFarry** [comment]
If you are running this inside Azure Devops, make sure that you have set the Pipeline to not shallow Fetch .

Edit Pipeline -> Elipsis(top right) -> Triggers -> YAML -> Get Sources 

![image](https://user-images.githubusercontent.com/81415/189006169-19242ebf-08ab-4424-8d7a-68432875f5b5.png)

This took me quite some time to figure out.

**Comment by pavelmateju** [comment]
This one sort it out  for us ( we are using azure repos / devops ) 

```
- stage: One
    variables:
    #preventing git shallow clone
    Agent.Source.Git.ShallowFetchDepth: 0    
    #. . rest of your pipeline
```



This prevents azure default checkout task from running a git shallow clone.

Other option is to set this in the azure DevOps UI on the pipeline triggers  (UNCHECK "Shallow fetch").

![image](https://user-images.githubusercontent.com/6265680/189184463-a2a97e1a-d57f-421a-9c6c-d355071b15cc.png)

**Comment by s-marrone** [comment]
Worked for us! Thanks @pavelmateju
