### ISSUE TITLE
[Bug] GitVersion task fails when run in a GitHub Actions workflow

### ISSUE THREAD

**Issue by ylatuya** [GitTools/GitVersion#3100]
**Describe the bug**
GitVersion task that generates gitversion.json fails only when run in a GitHub Actions workflow. The same task works correctly when run in a developer machine.

## Expected Behavior
gitversion.json is generated correctly

## Actual Behavior

When running `dotnet build` the task fails running the command:

```
     ERROR [04/26/22 12:01:13:29] An unexpected error occurred:
  System.NullReferenceException: Object reference not set to an instance of an object.
     at LibGit2Sharp.Core.Handles.ObjectHandle.op_Implicit(ObjectHandle handle) in /_/LibGit2Sharp/Core/Handles/Objects.cs:line 509
     at LibGit2Sharp.Core.Proxy.git_commit_author(ObjectHandle obj) in /_/LibGit2Sharp/Core/Proxy.cs:line 286
     at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.LibGit2Sharp.Core.LazyGroup<T>.IEvaluator<TInput>.Evaluate(TInput input) in /_/LibGit2Sharp/Core/LazyGroup.cs:line 88
     at LibGit2Sharp.Core.LazyGroup`1.<Evaluate>b__6_0(T input) in /_/LibGit2Sharp/Core/LazyGroup.cs:line 36
     at LibGit2Sharp.Core.GitObjectLazyGroup.EvaluateInternal(Action`1 evaluator) in /_/LibGit2Sharp/Core/GitObjectLazyGroup.cs:line 20
     at LibGit2Sharp.Core.LazyGroup`1.Evaluate() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 34
     at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.Evaluate() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 80
     at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.get_Value() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 73
     at LibGit2Sharp.Commit.get_Committer() in /_/LibGit2Sharp/Commit.cs:line 87
     at GitVersion.Commit..ctor(Commit innerCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 17
     at GitVersion.Commit.<>c.<.ctor>b__3_0(Commit parent) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 16
     at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
     at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
     at GitVersion.Configuration.BranchConfigurationCalculator.InheritBranchConfiguration(Int32 recursions, IBranch targetBranch, BranchConfig branchConfiguration, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 77
     at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfigurationInternal(Int32 recursions, IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 54
     at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfiguration(IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 28
     at GitVersion.GitVersionContextFactory.Create(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionContextFactory.cs:line 39
     at GitVersion.GitVersionCoreModule.<>c__DisplayClass0_0.<RegisterTypes>b__1() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\GitVersionCoreModule.cs:line 37
     at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
     at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
     at System.Lazy`1.CreateValue()
     at System.Lazy`1.get_Value()
     at GitVersion.VersionCalculation.NextVersionCalculator.get_context() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 15
     at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 30
     at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 52
     at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 66
    INFO [04/26/22 12:01:13:29] Attempting to show the current git graph (please include in issue): 
    INFO [04/26/22 12:01:13:29] Showing max of 100 commits
    INFO [04/26/22 12:01:13:35] * 97c6195 82 seconds ago  (grafted, HEAD -> pull/1/merge, pull/1/merge)
  
C:\Users\runneradmin\.nuget\packages\gitversion.msbuild\5.10.1\tools\GitVersion.MsBuild.targets(9,9): error MSB3073: The command "dotnet --roll-forward Major "C:\Users\runneradmin\.nuget\packages\gitversion.msbuild\5.10.1\tools\netcoreapp3.1/gitversion.dll" "D:\a\bug-gitversion-githubactions\bug-gitversion-githubactions" -output file -outputfile obj\gitversion.json" exited with code 1. [D:\a\bug-gitversion-githubactions\bug-gitversion-githubactions\bug-gitversion-githubactions.csproj]

Build FAILED.

C:\Users\runneradmin\.nuget\packages\gitversion.msbuild\5.10.1\tools\GitVersion.MsBuild.targets(9,9): error MSB3073: The command "dotnet --roll-forward Major "C:\Users\runneradmin\.nuget\packages\gitversion.msbuild\5.10.1\tools\netcoreapp3.1/gitversion.dll" "D:\a\bug-gitversion-githubactions\bug-gitversion-githubactions" -output file -outputfile obj\gitversion.json" exited with code 1. [D:\a\bug-gitversion-githubactions\bug-gitversion-githubactions\bug-gitversion-githubactions.csproj]
```

## Steps to Reproduce

1. Create a new project with dotnet new console
2. Add GitVersion.MsBuild Nuget to the project
3. Create a new GitHub Actions workflow that builds the projects
4. Create a new PR in the repo to trigger the workflow

I have created a repository to reproduce the error: https://github.com/ylatuya/bug-gitversion-githubactions/pull/1

## Your Environment
- Version Used: 5.10.1
- Operating System and version (Windows 10, Ubuntu 18.04):  windows-2022 from GitHub Actions
- Link to your project: https://github.com/ylatuya/bug-gitversion-githubactions
- Link to your CI build (if appropriate): https://github.com/ylatuya/bug-gitversion-githubactions/runs/6175145005?check_suite_focus=true

**Comment by ylatuya** [comment]
The issue is fixed using fetch-depth=0 as documented here: https://github.com/GitTools/actions/blob/main/docs/examples/github/gitversion/execute/usage-examples.md#execute-gitversion-action-gitversionexecute-usage-examples
