### ISSUE TITLE
TeamCity and status code 401

### ISSUE THREAD

**Issue by pkochubey** [GitTools/GitVersion#324]
Why be started manually getversion not occur download repository(everything works). And when you run out TeamCity accesses the repository?

```
Starting: C:\Windows\system32\cmd.exe /c gitversion.exe . /updateAssemblyInfo /output buildserver
[08:20:56]in directory: C:\BuildAgent\work\b82a712ae2d52dc7
[08:20:58]Working directory: C:\BuildAgent\work\b82a712ae2d52dc7
[08:20:58]Applicable build agent found: 'TeamCity'.
[08:20:58]One remote found (origin -> 'http://pkochubey@localhost:82/xmleditor.git').
[08:20:58]Fetching from remote 'origin' using the following refspecs: +refs/heads/*:refs/remotes/origin/*.
[08:20:59]An unexpected error occurred:
[08:20:59]LibGit2Sharp.LibGit2SharpException: Request failed with status code: 401
[08:20:59]   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
[08:20:59]   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteSafeHandle remote, Signature signature, String logMessage)
[08:20:59]   at LibGit2Sharp.Network.DoFetch(RemoteSafeHandle remoteHandle, FetchOptions options, Signature signature, String logMessage)
[08:20:59]   at LibGit2Sharp.Network.Fetch(Remote remote, FetchOptions options, Signature signature, String logMessage)
[08:20:59]   at GitVersion.GitHelper.NormalizeGitDirectory(String gitDirectory, Authentication authentication) in c:\BuildAgent\work\5e0d79a4e3943b17\GitVersionCore\BuildServers\GitHelper.cs:line 26
[08:20:59]   at GitVersion.Program.Main() in c:\BuildAgent\work\5e0d79a4e3943b17\GitVersionExe\Program.cs:line 60
```

**Comment by ddubau** [comment]
This is not very helpful, how do you get it to work for private repos?

**Comment by gep13** [comment]
>@ddubau said...
This is not very helpful, how do you get it to work for private repos?

As stated above, either change the identity of the TeamCity Build Agent to be a user who has access to the repository, or specify the username and password to use when executing the command.  More information can be found here:

https://github.com/ParticularLabs/GitVersion/wiki/Command-Line-Tool
