### ISSUE TITLE
[Bug] NullReferenceException when running GitVersion/execute ADO task

### ISSUE THREAD

**Issue by andyfurniss4** [GitTools/GitVersion#3292]
**Describe the bug**
When running the execute task in an Azure Devops pipeline, I am being shown the following exception in the logs:

```
...
INFO [11/16/22 10:22:58:18] Begin: Calculating base versions
    INFO [11/16/22 10:22:58:19] No branch configuration found for branch fix-nuget-versioning, falling back to default configuration
    INFO [11/16/22 10:22:58:19] Begin: Attempting to inherit branch configuration from parent branch
    INFO [11/16/22 10:22:58:20] End: Attempting to inherit branch configuration from parent branch (Took: 5.56ms)
  INFO [11/16/22 10:22:58:20] End: Calculating base versions (Took: 17.37ms)
  ERROR [11/16/22 10:22:58:21] An unexpected error occurred:
System.NullReferenceException: Object reference not set to an instance of an object.
   at LibGit2Sharp.Core.Handles.ObjectHandle.op_Implicit(ObjectHandle handle) in /_/LibGit2Sharp/Core/Handles/Objects.cs:line 509
   at LibGit2Sharp.Core.Proxy.git_commit_author(ObjectHandle obj) in /_/LibGit2Sharp/Core/Proxy.cs:line 289
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.LibGit2Sharp.Core.LazyGroup<T>.IEvaluator<TInput>.Evaluate(TInput input) in /_/LibGit2Sharp/Core/LazyGroup.cs:line 88
   at LibGit2Sharp.Core.LazyGroup`1.<Evaluate>b__6_0(T input) in /_/LibGit2Sharp/Core/LazyGroup.cs:line 36
   at LibGit2Sharp.Core.GitObjectLazyGroup.EvaluateInternal(Action`1 evaluator) in /_/LibGit2Sharp/Core/GitObjectLazyGroup.cs:line 20
   at LibGit2Sharp.Core.LazyGroup`1.Evaluate() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 34
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.Evaluate() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 80
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.get_Value() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 73
   at LibGit2Sharp.Commit.get_Committer() in /_/LibGit2Sharp/Commit.cs:line 87
   at GitVersion.Commit..ctor(Commit innerCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 17
   at GitVersion.Commit.<>c.<.ctor>b__3_0(Commit parent) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 16
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at GitVersion.Configuration.BranchConfigurationCalculator.InheritBranchConfiguration(Int32 recursions, IBranch targetBranch, BranchConfig branchConfiguration, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 77
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfigurationInternal(Int32 recursions, IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 54
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfiguration(IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 28
   at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersion()
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 60
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 52
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 66
```

My pipeline looks like this:

```
trigger: none

resources:
  pipelines:
    - pipeline: other-pipeline
      source: other-pipeline
      trigger:
        branches:
          include:
            - master
              
pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: gittools.gittools.setup-gitversion-task.gitversion/setup@0
    displayName: gitversion/setup
    inputs:
      versionSpec: 5.x

  - task: gittools.gittools.execute-gitversion-task.gitversion/execute@0
    displayName: gitversion/execute
    inputs:
      useConfigFile: true
      configFilePath: GitVersion.yml
```

I'm assuming this is something to do with my repo specifically since I have been using GitVersion successfully elsewhere, but the error does not make it clear what the issue is so I'm not really sure what to do about it.

- Version Used: 5.11.1
- Operating System and version: Ubuntu 20.04.5

**Comment by andyfurniss4** [comment]
Just discovered the string of existing closed issues for this (e.g. #3193 ). Have applied the same fix of setting `fetchDepth: 0`.

Closing.
