### ISSUE TITLE
[Bug] Issue with jenkins and gitversion in declarative pipeline

### ISSUE THREAD

**Issue by jacobnollette** [GitTools/GitVersion#3353]
Greetings,

Having an issue with GitVersion and jenkins - had a number of dumps from gitversion; it appears to be processing my githistory some, but not executing is proper actions (I think).

Here's a portion of my stage in jenkins pipeline
```
env.checkout_version_bump_sandbox = "*/master"

  checkout([$class: 'GitSCM', 
    branches: [[name: "${env.checkout_version_bump_sandbox}"]],
    extensions: [[$class: 'LocalBranch']],
    userRemoteConfigs: [[
      credentialsId: "${CFG.git.user}", 
      refspec: "+refs/heads/*:refs/remotes/origin/*",
      url: "${CFG.build_artifacts.version_bump_sandbox.repo}"
    ]]
  ])

  sh '''
    docker run --rm -v "$(pwd):/repo" gittools/gitversion:5.6.6 /repo
  '''
```

and here's the output
```
Cloning repository https://git.something.com/scm/dops/version-bump-sandbox.git
 > git init /buildp/jenkins/workspace/DevOpsTools/version-bump-sandbox # timeout=10
Fetching upstream changes from https://git.something.com/scm/dops/version-bump-sandbox.git
 > git --version # timeout=10
 > git --version # 'git version 2.39.1'
using GIT_ASKPASS to set credentials build.agent username and password for Bitbucket
 > git fetch --tags --force --progress -- https://git.something.com/scm/dops/version-bump-sandbox.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://git.something.com/scm/dops/version-bump-sandbox.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 592cbc26098e08a14f40f7b9552dd5c8e229de06 # timeout=10
 > git branch -a -v --no-abbrev # timeout=10
 > git checkout -b master 592cbc26098e08a14f40f7b9552dd5c8e229de06 # timeout=10
++ pwd
+ docker run --rm -v /buildp/jenkins/workspace/DevOpsTools/version-bump-sandbox:/repo gittools/gitversion:5.6.6 /repo
INFO [01/26/23 15:58:56:12] Working directory: /repo
INFO [01/26/23 15:58:56:14] Project root is: /repo/
INFO [01/26/23 15:58:56:14] DotGit directory is: /repo/.git
INFO [01/26/23 15:58:56:17] Begin: Loading version variables from disk cache
  INFO [01/26/23 15:58:56:17] Cache file /repo/.git/gitversion_cache/5297BA5DD2775F887EAB6D330DDAD95207D98313.yml not found.
  INFO [01/26/23 15:58:56:17] End: Loading version variables from disk cache (Took: 1.33ms)
  ERROR [01/26/23 15:58:56:24] An unexpected error occurred:
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitVersion.Configuration.ConfigFileLocator.<>c.<VerifyReadConfig>b__7_0(KeyValuePair`2 b) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\ConfigFileLocator.cs:line 52
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at GitVersion.Configuration.ConfigFileLocator.VerifyReadConfig(Config config) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\ConfigFileLocator.cs:line 52
   at GitVersion.Configuration.ConfigFileLocator.ReadConfig(String workingDirectory) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\ConfigFileLocator.cs:line 39
   at GitVersion.Configuration.ConfigProvider.Provide(String workingDirectory, Config overrideConfig) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\ConfigProvider.cs:line 42
   at GitVersion.Configuration.ConfigProvider.Provide(Config overrideConfig) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\ConfigProvider.cs:line 37
   at GitVersion.GitVersionContextFactory.Create(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionContextFactory.cs:line 30
   at GitVersion.GitVersionCoreModule.<>c__DisplayClass0_0.<RegisterTypes>b__3() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\GitVersionCoreModule.cs:line 61
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at GitVersion.VersionCalculation.NextVersionCalculator.get_context() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 17
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 32
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 52
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 61
  INFO [01/26/23 15:58:56:24] Attempting to show the current git graph (please include in issue): 
  INFO [01/26/23 15:58:56:24] Showing max of 100 commits
  INFO [01/26/23 15:58:56:27] * 592cbc2 18 seconds ago  (HEAD -> master, origin/master)
* 1134348 5 minutes ago  (tag: 0.0.1)
* bc4d9e5 11 minutes ago 
* 05a1ecf 13 minutes ago 
* 5ad72ba 18 minutes ago 
* b70c83a 19 minutes ago 
* ee1a6df 22 minutes ago 
* 8dd6e1d 24 minutes ago 
* fcf8d5c 33 minutes ago 
* 6cae15b 38 minutes ago 
* 4c9ecfa 40 minutes ago 
* 85041dd 17 hours ago 
* f3e9712 17 hours ago 
* e8fe215 17 hours ago 
* adf09c9 17 hours ago 
* 1e2e5db 17 hours ago 
* eab381a 20 hours ago 
* 358ed96 22 hours ago 
* 7d36f6a 23 hours ago 
* 9b98954 23 hours ago 
* 32bc507 23 hours ago 
* 7c2be79 23 hours ago 
* 46a901c 23 hours ago 
* 82a0eb7 24 hours ago 
* d1c509e 24 hours ago 
* 4b45279 24 hours ago 
* 543880c 2 days ago 
* 494a251 2 days ago 
* 775b97d 2 days ago 
* 41dd99a 2 days ago 
* 87086e1 2 days ago 
* d1bfc36 2 days ago 
* bcb451d 2 days ago 
* 78fa72c 2 days ago 
* 7c5bae1 2 days ago 
* b692697 2 days ago 
* 19383ee 2 days ago 
* 9cf2c7b 2 days ago 
* 16f5f17 2 days ago 
* 63b41e7 2 days ago 
* bc80da4 2 days ago 
* a5ddfc3 2 days ago 
* 4531a92 2 days ago 
* 9296487 2 days ago 
* 3a410ad 2 days ago 
```

## Expected Behavior
I'm not 100% sure, when I run it from my local mac, I have a more normal output, so I would like to start version bumping obviously

## Actual Behavior
Printing out a crash dump

## Possible Fix
I'm not sure, I did some work around my checkout command; it is paring the checkout branch with the local branch name, and checkout out all tags I believe...

## Steps to Reproduce
Included crash report and code sample above

## Context
Trying to version bump multiple staged deployments in jenkins mpl pipeline

## Your Environment
- Jenkins 2.332.4
- MPL Pipeline
- Self hosted bitbucket
- Redhat 7 runner
- Gitversion from docker, or downloaded binary show similar failures

**Comment by jacobnollette** [comment]
Looks like it may be from empty git commits
```
Object reference not set to an instance of an object.
```

**Comment by jacobnollette** [comment]
Apparently my gitversion.yml file was malformed; closing I suppose

**Comment by asbjornu** [comment]
This sounds like something we should provide a better error message for. Want to attack this with a  PR?
