### ISSUE TITLE
[Bug] AzureDevops gitversion task now failing due to missing lib.json

### ISSUE THREAD

**Issue by stevu236** [GitTools/GitVersion#3434]
**Describe the bug**
The Azure Devops task appears to have been updated, but the setup task is now failing with the following error: 

```
##[error]Error: Cannot find module '/azagent/_work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.0/lib.json'
    at webpackEmptyContext (/azagent/_work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.0/bundle.js:9818:10)
    at _loadLocStrings (/azagent/_work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.0/bundle.js:5821:143)
    at Object._setResourcePath [as setResourcePath] (/azagent/_work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.0/bundle.js:5876:23)
    at Object../node_modules/azure-pipelines-tool-lib/tool.js (/azagent/_work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.0/bundle.js:11453:4)
    at __webpack_require__ (/azagent/_work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.0/bundle.js:33565:42)
    at Module../src/agent/azure/build-agent.ts (/azagent/_work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.0/bundle.js:31568:87)
    at __webpack_require__ (/azagent/_work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.0/bundle.js:33565:42)
    at Module../src/core/ioc.ts (/azagent/_work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.0/bundle.js:31853:81)
    at __webpack_require__ (/azagent/_work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.0/bundle.js:33565:42)
    at Module../src/tasks/gitversion/main.ts (/azagent/_work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.0/bundle.js:31982:67)
/azagent/_work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.0/bundle.js:9820
	throw e;
	^
```

I have attempted clearing my build agent's _work directory to force a redownload of the task, however this does not fix the issue. 

## Expected Behavior
The task should successfully setup gitversion with no errors.

## Actual Behavior
The task errors out due to not being able to find a 'lib.json' file.

## Steps to Reproduce
Example pipeline YML: https://github.com/stevu236/gitver-bug-repro/blob/main/azure-pipelines.yml

1. In a devops git repository, create a new pipeline using the above yml.
2. Run a new pipeline build
3. The build will fail on gitversion/setup@0 and print the above error.

## Context
This bug causes all builds fail on Azure Devops which use this task, meaning I cannot release updates.

## Your Environment
- Version Used: Latest devops task version
- Operating System and version (Windows 10, Ubuntu 18.04): Ubuntu 20.04.5 LTS
- Link to your project: Private repository, cannot share due to NDA. Sample YML provided above is enough to repro.
- Link to your CI build (if appropriate): Private repository, cannot share due to NDA. Sample YML provided above is enough to repro.

**Comment by arturcic** [comment]
https://github.com/GitTools/actions/issues/815
