### ISSUE TITLE
[Bug]   gitversion/setup@0 no longer working

### ISSUE THREAD

**Issue by michelefa1988** [GitTools/GitVersion#3435]
Is there a problem with gitversion all of a sudden? 

Something which has been working for years stopped working this morning 

```
  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.11.1'
```
# Panic 
```
Starting: Install GitVersion
==============================================================================
Task         : Setup GitVersion Task
Description  : Easy Semantic Versioning (http://semver.org/) for projects using Git
Version      : 0.10.1
Author       : GitTools Contributors
Help         : See the [documentation](https://gitversion.net/docs/) for help
==============================================================================
##[error]Unhandled: Cannot find module '/home/vsts/work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.1/lib.json'
##[error]Error: Cannot find module '/home/vsts/work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.1/lib.json'
    at webpackEmptyContext (/home/vsts/work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.1/bundle.js:8325:10)
    at _loadLocStrings (/home/vsts/work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.1/bundle.js:4328:143)
    at Object._setResourcePath [as setResourcePath] (/home/vsts/work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.1/bundle.js:4383:23)
    at Object../node_modules/azure-pipelines-tool-lib/tool.js (/home/vsts/work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.1/bundle.js:8467:4)
    at __webpack_require__ (/home/vsts/work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.1/bundle.js:29140:42)
    at Object../src/agent/azure/build-agent.ts (/home/vsts/work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.1/bundle.js:27183:30)
    at __webpack_require__ (/home/vsts/work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.1/bundle.js:29140:42)
    at Object../src/core/ioc.ts (/home/vsts/work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.1/bundle.js:27475:23)
    at __webpack_require__ (/home/vsts/work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.1/bundle.js:29140:42)
    at Object../src/tasks/gitversion/main.ts (/home/vsts/work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.1/bundle.js:27663:31)
/home/vsts/work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.1/bundle.js:8327
	throw e;
	^

Error: Cannot find module '/home/vsts/work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.1/lib.json'
    at webpackEmptyContext (/home/vsts/work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.1/bundle.js:8325:10)
    at _loadLocStrings (/home/vsts/work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.1/bundle.js:4328:143)
    at Object._loc [as loc] (/home/vsts/work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.1/bundle.js:4414:26)
    at process.<anonymous> (/home/vsts/work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.1/bundle.js:5233:42)
    at process.emit (events.js:203:15)
    at process._fatalException (internal/bootstrap/node.js:497:27)
##[error]Exit code 7 returned from process: file name '/home/vsts/agents/2.217.2/externals/node10/bin/node', arguments '"/home/vsts/work/_tasks/gitversion/setup_a06c02ae-7b9a-4082-90dc-fe27b500e54f/0.10.1/bundle.js"'.
Finishing: Install GitVersion
```

**Comment by arturcic** [comment]
Duplicate https://github.com/GitTools/actions/issues/815
