### ISSUE TITLE
[Bug] System.NullReferenceException

### ISSUE THREAD

**Issue by InvertedLlama** [GitTools/GitVersion#3508]
**Describe the bug**
System.NullReferenceException when adding to new project

## Stack trace
```
INFO [05/16/23 15:16:50:69] Begin: Calculating base versions
    INFO [05/16/23 15:16:50:70] Begin: Attempting to inherit branch configuration from parent branch
    INFO [05/16/23 15:16:50:71] End: Attempting to inherit branch configuration from parent branch (Took: 10.30ms)
  INFO [05/16/23 15:16:50:71] End: Calculating base versions (Took: 17.29ms)
  ERROR [05/16/23 15:16:50:73] An unexpected error occurred:
System.NullReferenceException: Object reference not set to an instance of an object.
   at LibGit2Sharp.Core.Handles.ObjectHandle.op_Implicit(ObjectHandle handle) in /_/LibGit2Sharp/Core/Handles/Objects.cs:line 509
   at LibGit2Sharp.Core.Proxy.git_commit_author(ObjectHandle obj) in /_/LibGit2Sharp/Core/Proxy.cs:line 289
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.LibGit2Sharp.Core.LazyGroup<T>.IEvaluator<TInput>.Evaluate(TInput input) in /_/LibGit2Sharp/Core/LazyGroup.cs:line 88
   at LibGit2Sharp.Core.LazyGroup`1.<Evaluate>b__6_0(T input) in /_/LibGit2Sharp/Core/LazyGroup.cs:line 36
   at LibGit2Sharp.Core.GitObjectLazyGroup.EvaluateInternal(Action`1 evaluator) in /_/LibGit2Sharp/Core/GitObjectLazyGroup.cs:line 20
   at LibGit2Sharp.Core.LazyGroup`1.Evaluate() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 34
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.Evaluate() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 80
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.get_Value() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 73
   at LibGit2Sharp.Commit.get_Committer() in /_/LibGit2Sharp/Commit.cs:line 87
   at GitVersion.Commit..ctor(Commit innerCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 17
   at GitVersion.Commit.<>c.<.ctor>b__3_0(Commit parent) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 16
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at GitVersion.Configuration.BranchConfigurationCalculator.InheritBranchConfiguration(Int32 recursions, IBranch targetBranch, BranchConfig branchConfiguration, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 77
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfigurationInternal(Int32 recursions, IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 54
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfiguration(IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 28
   at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\BaseVersionCalculator.cs:line 37
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 56
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 52
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 66
  INFO [05/16/23 15:16:50:73] Attempting to show the current git graph (please include in issue): 
  INFO [05/16/23 15:16:50:73] Showing max of 100 commits
  INFO [05/16/23 15:16:50:79] * 5942535 3 minutes ago  (grafted, HEAD -> feature/SonarQubeVersionFix, origin/5942535b350d5307dd5274d8806c26f0354dd7a5, 5942535b350d5307dd5274d8806c26f0354dd7a5)
```

## Steps to Reproduce

Relevant parts of pipeline:
```
  - task: gitversion/setup@0
    displayName: Install GitVersion
    inputs:
      versionSpec: '5.x'

  - task: gitversion/execute@0
    displayName: Determine Version
    name: Version
    inputs:
      useConfigFile: true
      configFilePath: 'pipelines/GitVersion.yml'

```
GitVersion.yml
```
mode: Mainline 
branches:
    feature:
        tag: alpha
    develop:
        tag: rc
    main:
        tag: ''
    release:
        tag: ''
ignore:
  sha: []
merge-message-formats: {}
```

## Your Environment
Using Azure Devops tasks

- Version Used:
- 5.12.0

**Comment by arturcic** [comment]
Can you make sure you do not forget this step? https://github.com/GitTools/actions/blob/main/docs/examples/azure/gitversion/setup/usage-examples.md#usage-examples

steps:
  - checkout: self
    fetchDepth: 0

**Comment by arturcic** [comment]
I wonder why that section was skipped, and you are not the first one to skip it. Wonder how can we improve the docs so that we don't get this bugs opened again

**Comment by asbjornu** [comment]
We should probably catch this NRE and wrap it in a `WarningException` with more detail, @arturcic.

**Comment by arturcic** [comment]
@asbjornu we actually have this fixed in 6.x https://github.com/GitTools/GitVersion/pull/3479

**Comment by asbjornu** [comment]
True!
