### ISSUE TITLE
[Bug] Build not Calculated well on AzureDevops

### ISSUE THREAD

**Issue by michelefa1988** [GitTools/GitVersion#3700]
**Describe the bug**
When using Gitversion on Azure devops gitversion randomly fails to calculate the version number.  

Something I noticed are
- when running the same docker command locally, version is calculated well
- Issue happens randomly
- Creating a new branch, from the old branch seems to solve the issue, although then I sometimes get a version which includes --no-branch
- To me it looks like such issues have deteriorated on later versions of the gitversion. 

## Expected Behavior
Version number is always calculated correctly

## Actual Behavior
```
parse error: Invalid numeric literal at line 1, column 5
INFO [09/27/23 8:58:08:62] Applicable build agent found: 'LocalBuild'.
INFO [09/27/23 8:58:08:66] Working directory: /s
INFO [09/27/23 8:58:08:68] Project root is: /s/
INFO [09/27/23 8:58:08:68] DotGit directory is: /s/.git
INFO [09/27/23 8:58:08:68] Branch from build environment: 
INFO [09/27/23 8:58:08:71] Begin: Loading version variables from disk cache
  INFO [09/27/23 8:58:08:71] Cache file /s/.git/gitversion_cache/D3A1B405F5922E6CB54520D87664DD2B02691F11.yml not found.
  INFO [09/27/23 8:58:08:71] End: Loading version variables from disk cache (Took: 0.64ms)
  INFO [09/27/23 8:58:08:72] Using latest commit on specified branch
  INFO [09/27/23 8:58:08:81] Begin: Getting branches containing the commit 'bea4ddc'.
    INFO [09/27/23 8:58:08:81] Trying to find direct branches.
    INFO [09/27/23 8:58:08:81] No direct branches found, searching through all branches.
    INFO [09/27/23 8:58:08:81] Searching for commits reachable from 'origin/11835/xxxx-xxx'.
    INFO [09/27/23 8:58:08:96] The branch 'origin/11835/xxx-xxx' has no matching commits.
    INFO [09/27/23 8:58:08:96] Searching for commits reachable from 'origin/11835/xxxx-xxx-xxxx'.
    INFO [09/27/23 8:58:09:09] The branch 'origin/11835/xxx-xxxx' has no matching commits.
    INFO [09/27/23 8:58:09:09] Searching for commits reachable from 'origin/Z-204'.
    INFO [09/27/23 8:58:09:21] The branch 'origin/Z-204' has no matching commits.
    INFO [09/27/23 8:58:09:21] Searching for commits reachable from 'origin/Z'.

```

## Steps to Reproduce

```
    steps:
      # https://github.com/GitTools/GitVersion/issues/2393
    - checkout: self
      path: s
      fetchDepth: 0
  - task: Bash@3
    displayName: Gitversion
    name: StoreSemVer
    inputs:
      targetType: 'inline'
      script: |
        gitversion_version=$(docker run --rm -v $(pwd):/s gittools/gitversion:5.12.0-ubuntu.20.04-6.0 /s GitVersion.yml)
        SemverVersion=$(echo "$gitversion_version" | jq -r .SemVer)
        echo "$gitversion_version"
        echo "SemverVersion: $SemverVersion"
        echo "##vso[task.setvariable variable=Semver;isOutput=true;]$SemverVersion"
        echo "##vso[build.updatebuildnumber]$SemverVersion"

```

-->

## Your Environment
Azure Devops with self managed agent. Gitversion runs in docker container

- Version Used:
- Operating System and version (Windows 10, Ubuntu 18.04):
- Link to your project:
- Link to your CI build (if appropriate):

**Comment by HHobeck** [comment]
Hi there.

Could you please provide steps to reproduce and investigate in more detail in which circumstance this error happens? For me it makes no sense that on main branch sometimes (nondeterministic) a different branch were detected. The only reason I can think of is that you have multiple builds on the same time with the working directory. I'm using git-version for years with azure devops and have never seen this behavior.

Thank you very much.

**Comment by michelefa1988** [comment]
@HHobeck Issue still happens from time to time, although I still lack the steps to reproduce.

**Comment by michelefa1988** [comment]
So after a-lot of investigations I concluded the following 

# My Initial code

```
   - checkout: self
      path: s
      fetchDepth: 0
      clean: true

    - task: Bash@3
      name: StoreSemVer
      inputs:
        targetType: 'inline'
        script: |
          gitversion_version=$(docker run --rm -v $(pwd):/s gittools/gitversion:5.12.0-ubuntu.20.04-6.0 /s GitVersion.yml)
          SemverVersion=$(echo "$gitversion_version" | jq -r .SemVer)
          echo "##vso[build.updatebuildnumber]$SemverVersion"
```
# Conclusions

* Setting parameter `clean:true` does not work as expected. Not all the files are really cleaned + orphaned files still remain on the agent
* When cleaning the workspace with `worksspace.clean=true`, the gitversion cache was not deleted due to permissions error (permission denied error)
```
pipelineUser@agent:~/myagent/_work/1/s$ rm -r .git/
rm: descend into write-protected directory '.git/gitversion_cache'? y
rm: remove write-protected regular file '.git/gitversion_cache/DE8413FF01B8CE0E65FE900C4E27205A69445A94.yml'? y
rm: cannot remove '.git/gitversion_cache/DE8413FF01B8CE0E65FE900C4E27205A69445A94.yml': Permission denied
rm: remove write-protected regular file '.git/gitversion_cache/3F7503526FCADE96DA25A2D7DA3E6BAC30047146.yml'? y
rm: cannot remove '.git/gitversion_cache/3F7503526FCADE96DA25A2D7DA3E6BAC30047146.yml': Permission denied
```

* Master branches always seemed to build without issues
* When we ran a forced clean (e.g run gitversion of a fresh agent), it seemed that when we clone a repo, Azuredevops only checks-out out the current branch locally and master/main do not exist on the agent. Although the origin/master branch is visible the data is not locally there, therefore gitversion fails to calculate the version
```
pipelineUser@agent:~/myagent/_work/4/s$ git branch
* (HEAD detached at 34d25c731)
pipelineUser@agent:~/myagent/_work/4/s$ git branch --all
* (HEAD detached at 34d25c731)
  remotes/origin/feature/xxx-refactoring
  remotes/origin/feature/xxx-refactoring-backup
  remotes/origin/xxx-xxx-xxx

```
```
pipelineUser@agent:~/myagent/_work/5/s$ docker run --rm -v $(pwd):/s gittools/gitversion:5.12.0-ubuntu.20.04-6.0 /s .GitVersion.yml;
INFO [10/03/23 22:41:27:68] Applicable build agent found: 'LocalBuild'.
INFO [10/03/23 22:41:27:72] Working directory: /s
INFO [10/03/23 22:41:27:74] Project root is: /s/
INFO [10/03/23 22:41:27:74] DotGit directory is: /s/.git
INFO [10/03/23 22:41:27:74] Branch from build environment: 
INFO [10/03/23 22:41:27:78] Begin: Loading version variables from disk cache
  INFO [10/03/23 22:41:27:78] Cache file /s/.git/gitversion_cache/6B137FEE500D44A19307C3FE227682841E795CD5.yml not found.
  INFO [10/03/23 22:41:27:78] End: Loading version variables from disk cache (Took: 0.61ms)
  INFO [10/03/23 22:41:27:78] Using latest commit on specified branch
  INFO [10/03/23 22:41:28:03] Running against branch: feature/xxx-xxx-dev(4d036c9 xxxx)
  INFO [10/03/23 22:41:28:03] Begin: Calculating base versions
    INFO [10/03/23 22:41:28:05] Begin: Attempting to inherit branch configuration from parent branch
      INFO [10/03/23 22:41:28:06] Begin: Finding branch source of 'feature/xxx-xxx-dev-tested'
        
HIDDEN


        INFO [10/03/23 22:41:29:14] The branch 'origin/release/2023-07-11' has no matching commits.
      INFO [10/03/23 22:41:29:14] End: Getting branches containing the commit '4d036c9'. (Took: 1,060.51ms)
      INFO [10/03/23 22:41:29:14] Found possible parent branches: 
    INFO [10/03/23 22:41:29:14] End: Attempting to inherit branch configuration from parent branch (Took: 1,099.16ms)
  INFO [10/03/23 22:41:29:14] End: Calculating base versions (Took: 1,110.12ms)
  ERROR [10/03/23 22:41:29:16] An unexpected error occurred:
System.InvalidOperationException: Gitversion could not determine which branch to treat as the development branch (default is 'develop') nor release-able branch (default is 'main' or 'master'), either locally or remotely. Ensure the local clone and checkout match the requirements or considering using 'GitVersion Dynamic Repositories'
   at GitVersion.Configuration.BranchConfigurationCalculator.InheritBranchConfiguration(Int32 recursions, IBranch targetBranch, BranchConfig branchConfiguration, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 150
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfigurationInternal(Int32 recursions, IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 54
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfiguration(IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 28


```

# Fix/ Workaround
* The fix is manually delete the source folder
* After code is downloaded again I run git checkout master & git checkout main this makes master and main available locally. Following this the current branch is checked out again. Not sure if I am facing the same issue as https://github.com/GitTools/GitVersion/issues/2921


# Code: Workaround
```
- task: Bash@3
  displayName: Clean
  name: Clean
  inputs:
    targetType: 'inline'
    script: |
      rm -rfv  *
      sudo rm -rfv  .git/*
      rm -rfv  .gitmodules/*
      rm -rfv  .gitignore/*

- checkout: self
  path: s
  fetchDepth: 0
  clean: true


- task: Bash@3
  name: StoreSemVer
  inputs:
    targetType: 'inline'
    script: |
      currentBranch=$(echo $currentBranch | cut -d/ -f3-)

      git checkout master
      git checkout main
      git checkout $currentBranch

      gitversion_version=$(docker run --rm -v $(pwd):/s gittools/gitversion:5.12.0-ubuntu.20.04-6.0 /s GitVersion.yml)
      SemverVersion=$(echo "$gitversion_version" | jq -r .SemVer)
      echo "$gitversion_version"
      echo "SemverVersion: $SemverVersion"
      echo "##vso[task.setvariable variable=Semver;isOutput=true;]$SemverVersion"
      echo "##vso[build.updatebuildnumber]$SemverVersion"
  env:
    currentBranch: $(Build.SourceBranch)
```

**Comment by huw-dhcw** [comment]
Having had an issue only yesterday with a server build behaving differently to local - can I suggest explicitly setting your Working Folder on the script task:
workingDirectory: './'

**Comment by HHobeck** [comment]
Thank you very much sharing your findings in such detail and give us some workarounds. Everything you have documented seems to be build agent specific except https://github.com/GitTools/GitVersion/issues/2921. Do you have any other ideas to make git version more robust having this in mind? Anyway I would say to move this issue to the FAQ section.

**Comment by michelefa1988** [comment]
@HHobeck  If my investigations are correct, it would make sense that gitversion automatically uses the origin branch and not depends on the local one. This is the only thing which comes to mind for the time being. 

However I am still confused as to why this issue started happening - ive been using gitversion for many years. My guess it Azure updated something in the checkout step and it would b hidden somewhere deep in their documentation.
