### ISSUE TITLE
Auto fetch of master branch doesn't work with ssh

### ISSUE THREAD

**Issue by andreasohlund** [GitTools/GitVersion#38]
When a user does a fresh clone using SSH we can't auto fetch the master:

```

Error   1   Error occurred: GitFlowVersion.MissingBranchException: Could not fetch from 'git@github.com:Particular/PlatformInstaller.git' since LibGit2 does not support the transport. You have most likely cloned using SSH. If there is a remote branch named 'master' then fetch it manually, otherwise please create a local branch named 'master'. ---> LibGit2Sharp.LibGit2SharpException: An error was raised by libgit2. Category = Net (Error).
This transport isn't implemented. Sorry
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_connect(RemoteSafeHandle remote, GitDirection direction)
   at LibGit2Sharp.Network.Fetch(Remote remote, Nullable`1 tagFetchMode, ProgressHandler onProgress, CompletionHandler onCompletion, UpdateTipsHandler onUpdateTips, TransferProgressHandler onTransferProgress, Credentials credentials)
   at GitFlowVersion.LibGitExtensions.GetBranch(IRepository repository, String name) in c:\Code\Particular\GitFlowVersion\GitFlowVersion\LibGitExtensions.cs:line 126
   --- End of inner exception stack trace ---
   at GitFlowVersion.LibGitExtensions.GetBranch(IRepository repository, String name) in c:\Code\Particular\GitFlowVersion\GitFlowVersion\LibGitExtensions.cs:line 133
   at GitFlowVersion.VersionOnMasterFinder.<VersionsOnMaster>d__3.MoveNext() in c:\Code\Particular\GitFlowVersion\GitFlowVersion\VersionOnMasterFinder.cs:line 71
   at GitFlowVersion.VersionOnMasterFinder.Execute() in c:\Code\Particular\GitFlowVersion\GitFlowVersion\VersionOnMasterFinder.cs:line 37
   at GitFlowVersion.DevelopVersionFinder.GetSemanticVersion() in c:\Code\Particular\GitFlowVersion\GitFlowVersion\BranchFinders\DevelopVersionFinder.cs:line 36
   at GitFlowVersion.DevelopVersionFinder.FindVersion() in c:\Code\Particular\GitFlowVersion\GitFlowVersion\BranchFinders\DevelopVersionFinder.cs:line 13
   at GitFlowVersion.GitFlowVersionFinder.FindVersion() in c:\Code\Particular\GitFlowVersion\GitFlowVersion\GitFlowVersionFinder.cs:line 44
   at GitFlowVersion.VersionForRepositoryFinder.GetVersion(Repository repository) in c:\Code\Particular\GitFlowVersion\GitFlowVersion\VersionForDirectoryFinder.cs:line 18
   at GitFlowVersion.VersionCache.GetVersion(String gitDirectory) in c:\Code\Particular\GitFlowVersion\GitFlowVersion\VersionCache.cs:line 39
   at GitFlowVersionTask.UpdateAssemblyInfo.Execute() in c:\Code\Particular\GitFlowVersion\GitFlowVersionTask\UpdateAssemblyInfo.cs:line 57 PlatformInstaller.CustomActions


```

@nulltoken do you have any info on if/when this will be supported in LibGit2Sharp?

**Comment by efunkenbusch** [comment]
Is this seriously still not supported?  We don't use username/password in teamcity because our password expiration policy is draconic and it would require resetting passwords on hundreds of builds everytime they expire. 

Please implement this.

**Comment by asbjornu** [comment]
@efunkenbusch: For this to be fixed, GitVersion would need to build and bundle its own version of libgit2 as per libgit2/libgit2#2600. Since we're currently just using the official [LibGit2Sharp NuGet Package](https://www.nuget.org/packages/LibGit2Sharp), this is not an easy switch. [NuGet Packages that include SSH exist](https://www.nuget.org/packages/LibGit2Sharp-SSH/), but are not official and very out of date. If you have an idea for a sustainable and simple solution to this, we're open for pull requests.

**Comment by efunkenbusch** [comment]
@asbjornu - What about a branch that uses git command line instead?  If this issue is so insurmountable, that seems like the logical conclusion.

**Comment by asbjornu** [comment]
I believe that after upgrading to LibGit2Sharp version 0.26 in #1713, this problem should be fixed. Can you please try [the latest build](https://www.nuget.org/packages/GitVersionCore/5.0.0-beta4-1) and report back whether it fixes this problem or not? Please reopen this issue if the problem persists.
