### ISSUE TITLE
The type initializer for '<Module>' threw an exception (Attempted to read or write protected memory)

### ISSUE THREAD

**Issue by Philo** [GitTools/GitVersion#565]
I am receiving the following exception from GitVersion when executing GitVersion during a custom deployment command to an Azure Web App.  GitVersion is running against the 'master' branch.  Any thoughts on what could be causing this?

As the dump below shows I am trying to update a CommonAssemblyInfo.cs.

```
remote: Failed exitCode=-532462766, command="D:\home\site\repository\Production\lib\gitversion\gitversion.exe" /u
"D:\home\site\repository\Production\CommonAssemblyInfo.cs" /output json
remote: Unhandled Exception: System.TypeInitializationException: The type initializer for '<Module>' threw an exc
m.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other m
remote:    at Costura.AssemblyLoader.MoveFileEx(String lpExistingFileName, String lpNewFileName, Int32 dwFlags)
remote:    at Costura.AssemblyLoader.InternalPreloadUnmanagedLibraries(String tempBasePath, IEnumerable`1 libs, D
ums)
remote:    at Costura.AssemblyLoader.PreloadUnmanagedLibraries(String hash, String tempBasePath, IEnumerable`1 li
hecksums)
remote:    at Costura.AssemblyLoader.Attach()
remote:    at .cctor()
remote:    --- End of inner exception stack trace ---
```

**Comment by JakeGinnivan** [comment]
@SimonCropp @distantcam you guys seen this?

**Comment by SimonCropp** [comment]
i will fix this over the weekend
