### ISSUE TITLE
VSO task running GitVersion twice and claiming to find multiple branch configurations matching the branchName

### ISSUE THREAD

**Issue by labmonkey42** [GitTools/GitVersion#715]
About a week ago I had a practically empty repository in VSO apparently working properly with a CI build that included a GitVersion step using the TFS task custom step.  Today I added steps to this build which will package and publish my libraries and committed some code to make such a package.  When the CI build is triggered by the commit or by manually queuing the GitVersion step fails as illustrated below.

```
2015-11-13T00:54:32.9298227Z Executing the following commandline. (workingFolder = C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\default\tasks\GitVersion\3.3.1)
2015-11-13T00:54:32.9298227Z C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\default\tasks\GitVersion\3.3.1\GitVersion.exe "C:\a\1\s" /output buildserver /updateAssemblyInfo true /nofetch 
2015-11-13T00:54:32.9308228Z Error message highlight pattern: 
2015-11-13T00:54:32.9308228Z Warning message highlight pattern: 
2015-11-13T00:54:33.0038225Z INFO [11/13/15 0:54:32:98] Working directory: C:\a\1\s
2015-11-13T00:54:33.0058225Z INFO [11/13/15 0:54:32:99] Applicable build agent found: 'VsoAgent'.
2015-11-13T00:54:33.0058225Z INFO [11/13/15 0:54:33:00] Branch from build environment: refs/heads/feature/ModuleCore
2015-11-13T00:54:33.0898226Z INFO [11/13/15 0:54:33:08] One remote found (origin -> 'https://redacted.visualstudio.com/DefaultCollection/_git/redacted').
2015-11-13T00:54:33.0898226Z INFO [11/13/15 0:54:33:08] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
2015-11-13T00:54:33.1658390Z INFO [11/13/15 0:54:33:16] Creating local branch refs/heads/feature/ModuleCore
2015-11-13T00:54:33.2598216Z INFO [11/13/15 0:54:33:25] Creating local branch from remote tracking 'refs/remotes/origin/develop'.
2015-11-13T00:54:33.2728244Z INFO [11/13/15 0:54:33:27] Skipping update of 'refs/remotes/origin/feature/ModuleCore' as it already matches the remote ref.
2015-11-13T00:54:33.2748227Z INFO [11/13/15 0:54:33:27] Skipping update of 'refs/remotes/origin/master' as it already matches the remote ref.
2015-11-13T00:54:33.2758224Z INFO [11/13/15 0:54:33:27] HEAD points at branch 'refs/heads/feature/ModuleCore'.
2015-11-13T00:54:33.2758224Z INFO [11/13/15 0:54:33:27] Project root is: C:\a\1\s
2015-11-13T00:54:33.4178221Z INFO [11/13/15 0:54:33:41] Using latest commit on specified branch
2015-11-13T00:54:33.4258219Z ERROR [11/13/15 0:54:33:42] An unexpected error occurred:
2015-11-13T00:54:33.4258219Z System.Exception: Multiple branch configurations match the current branch branchName of 'feature/ModuleCore'. Matching configurations: 'feature(s)?[/-], features?[/-]'
2015-11-13T00:54:33.4268227Z    at GitVersion.BranchConfigurationCalculator.GetBranchConfiguration(Commit currentCommit, IRepository repository, Boolean onlyEvaluateTrackedBranches, Config config, Branch currentBranch, IList`1 excludedInheritBranches)
2015-11-13T00:54:33.4268227Z    at GitVersion.GitVersionContext.CalculateEffectiveConfiguration()
2015-11-13T00:54:33.4278224Z    at GitVersion.GitVersionContext..ctor(IRepository repository, Branch currentBranch, Config configuration, Boolean onlyEvaluateTrackedBranches, String commitId)
2015-11-13T00:54:33.4278224Z    at GitVersion.GitVersionContext..ctor(IRepository repository, Config configuration, Boolean isForTrackingBranchOnly, String commitId)
2015-11-13T00:54:33.4278224Z    at GitVersion.ExecuteCore.ExecuteGitVersion(IFileSystem fileSystem, String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId)
2015-11-13T00:54:33.4288227Z    at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
2015-11-13T00:54:33.4288227Z    at GitVersion.Program.VerifyArgumentsAndRun()
2015-11-13T00:54:33.4298217Z INFO [11/13/15 0:54:33:42] 
2015-11-13T00:54:33.4298217Z INFO [11/13/15 0:54:33:42] Here is the current git graph (please include in issue): 
2015-11-13T00:54:33.4298217Z INFO [11/13/15 0:54:33:42] Showing max of 100 commits
2015-11-13T00:54:36.9953484Z INFO [11/13/15 0:54:36:99] * ff93c5f 20 minutes ago  (HEAD, origin/feature/ModuleCore, feature/ModuleCore)
2015-11-13T00:54:36.9964367Z * 7db448d 2 hours ago 
2015-11-13T00:54:36.9973306Z * 4eeba92 6 days ago  (origin/develop, develop)
2015-11-13T00:54:36.9983151Z * 8545e45 7 days ago 
2015-11-13T00:54:36.9983151Z * 020d5d2 7 days ago 
2015-11-13T00:54:36.9983151Z * a95108b 7 days ago 
2015-11-13T00:54:36.9993150Z * 722b9d6 8 days ago 
2015-11-13T00:54:36.9993150Z * a223543 8 days ago 
2015-11-13T00:54:37.0003151Z * f40aebc 8 days ago 
2015-11-13T00:54:37.0013153Z *   beb6a66 12 days ago  (origin/master, master)
2015-11-13T00:54:37.0013153Z |\  
2015-11-13T00:54:37.0013153Z | * ebe089d 12 days ago 
2015-11-13T00:54:37.0023154Z |/  
2015-11-13T00:54:37.0023154Z * baf2f67 8 months ago 
2015-11-13T00:54:37.0023154Z INFO [11/13/15 0:54:32:98] Working directory: C:\a\1\s
2015-11-13T00:54:37.0033152Z INFO [11/13/15 0:54:32:99] Applicable build agent found: 'VsoAgent'.
2015-11-13T00:54:37.0033152Z INFO [11/13/15 0:54:33:00] Branch from build environment: refs/heads/feature/ModuleCore
2015-11-13T00:54:37.0043151Z INFO [11/13/15 0:54:33:08] One remote found (origin -> 'https://redacted.visualstudio.com/DefaultCollection/_git/redacted).
2015-11-13T00:54:37.0043151Z INFO [11/13/15 0:54:33:08] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
2015-11-13T00:54:37.0043151Z INFO [11/13/15 0:54:33:16] Creating local branch refs/heads/feature/ModuleCore
2015-11-13T00:54:37.0053152Z INFO [11/13/15 0:54:33:25] Creating local branch from remote tracking 'refs/remotes/origin/develop'.
2015-11-13T00:54:37.0053152Z INFO [11/13/15 0:54:33:27] Skipping update of 'refs/remotes/origin/feature/ModuleCore' as it already matches the remote ref.
2015-11-13T00:54:37.0063150Z INFO [11/13/15 0:54:33:27] Skipping update of 'refs/remotes/origin/master' as it already matches the remote ref.
2015-11-13T00:54:37.0063150Z INFO [11/13/15 0:54:33:27] HEAD points at branch 'refs/heads/feature/ModuleCore'.
2015-11-13T00:54:37.0063150Z INFO [11/13/15 0:54:33:27] Project root is: C:\a\1\s
2015-11-13T00:54:37.0073151Z INFO [11/13/15 0:54:33:41] Using latest commit on specified branch
2015-11-13T00:54:37.0073151Z ERROR [11/13/15 0:54:33:42] An unexpected error occurred:
2015-11-13T00:54:37.0083149Z System.Exception: Multiple branch configurations match the current branch branchName of 'feature/ModuleCore'. Matching configurations: 'feature(s)?[/-], features?[/-]'
2015-11-13T00:54:37.0083149Z    at GitVersion.BranchConfigurationCalculator.GetBranchConfiguration(Commit currentCommit, IRepository repository, Boolean onlyEvaluateTrackedBranches, Config config, Branch currentBranch, IList`1 excludedInheritBranches)
2015-11-13T00:54:37.0093152Z    at GitVersion.GitVersionContext.CalculateEffectiveConfiguration()
2015-11-13T00:54:37.0093152Z    at GitVersion.GitVersionContext..ctor(IRepository repository, Branch currentBranch, Config configuration, Boolean onlyEvaluateTrackedBranches, String commitId)
2015-11-13T00:54:37.0093152Z    at GitVersion.GitVersionContext..ctor(IRepository repository, Config configuration, Boolean isForTrackingBranchOnly, String commitId)
2015-11-13T00:54:37.0103148Z    at GitVersion.ExecuteCore.ExecuteGitVersion(IFileSystem fileSystem, String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId)
2015-11-13T00:54:37.0103148Z    at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
2015-11-13T00:54:37.0103148Z    at GitVersion.Program.VerifyArgumentsAndRun()
2015-11-13T00:54:37.0113151Z INFO [11/13/15 0:54:33:42] 
2015-11-13T00:54:37.0113151Z INFO [11/13/15 0:54:33:42] Here is the current git graph (please include in issue): 
2015-11-13T00:54:37.0123150Z INFO [11/13/15 0:54:33:42] Showing max of 100 commits
2015-11-13T00:54:37.0123150Z INFO [11/13/15 0:54:36:99] * ff93c5f 20 minutes ago  (HEAD, origin/feature/ModuleCore, feature/ModuleCore)
2015-11-13T00:54:37.0133223Z * 7db448d 2 hours ago 
2015-11-13T00:54:37.0133223Z * 4eeba92 6 days ago  (origin/develop, develop)
2015-11-13T00:54:37.0143210Z * 8545e45 7 days ago 
2015-11-13T00:54:37.0143210Z * 020d5d2 7 days ago 
2015-11-13T00:54:37.0153148Z * a95108b 7 days ago 
2015-11-13T00:54:37.0153148Z * 722b9d6 8 days ago 
2015-11-13T00:54:37.0163179Z * a223543 8 days ago 
2015-11-13T00:54:37.0173175Z * f40aebc 8 days ago 
2015-11-13T00:54:37.0173175Z *   beb6a66 12 days ago  (origin/master, master)
2015-11-13T00:54:37.0173175Z |\  
2015-11-13T00:54:37.0183164Z | * ebe089d 12 days ago 
2015-11-13T00:54:37.0183164Z |/  
2015-11-13T00:54:37.0193158Z * baf2f67 8 months ago 
```

The commit is a published feature branch and the CI build includes the develop and feature/* branches, so I'm not sure if this is some misconfiguration on my part or if there is something amiss in the TFS task.

Any assistance will be greatly appreciated!

**Comment by labmonkey42** [comment]
After some investigation it appears that my GitVersionConfig.yaml specified "feature(s)?[/-]:" and the default configuration specifies "features[/-]:".  I think this is related to #692 as, in this case, I do not see a way to tell ConfigurationProvider.Provide from either the command line or the TFS task to not apply the default feature branch configuration.  I have temporarily worked around this by changing my GitVersionConfig.yaml to explicitly specify "feature[/-]:" so that this feature branch will match only one branch configuration.

**Comment by JakeGinnivan** [comment]
Hey @labmonkey42 

Interesting issue, not sure how to resolve really. So your yaml file has a specification for feature but we have moved to feature(s). We kinda need a way to remove a default configuration via configuration. Did not think about this scenario. *sigh*

Did you want to try and come up with a solution, either in the form of a new issue which explains the problem properly and suggests some solutions or a pull request? Even a properly written up issue would be super handy because I can make as up for grabs and someone from the community can pick it up.

**Comment by labmonkey42** [comment]
Thanks @JakeGinnivan 

If I had known this would happen before I started creating feature branches with gitflow I would have left my GitVersionConfig set to specify "features[/-]" and configured gitflow to name feature branches accordingly.  However, I started some features in "feature/*" (I've been doing of PowerShell work which favors spelling nouns in the singular form) and so I changed GitVersionConfig to specify "feature(s)?[/-]".  I can imagine that some teams may not be very strict on plurality/naming conventions and may need to match branches with regex like this.

This seems like something that could be resolved programmatically by determining branch configuration collisions before adding default configurations and responding appropriately, but unfortunately I just don't even have enough time for my own projects right now and can't spare any time to work on a code solution.

The current situation is that I have "feature[/-]" in my GitVersionConfig and that is working for my current feature branches.  Once those features are completed I could change gitflow to "features/*" and GitVersionConfig to "features[/-]" but all that would really gain is to not have the default branch configuration added at all.  For the time being I will just stick with what I have.

I guess you could close this issue unless someone has a better idea.  Changing the default configurations to match plurality via regex (e.g. "feature(s)?[/-]", "hotfix(es)?[/-]", etc) might make this a non-issue but open the door for teams to diverge on branch naming.

At least if someone else runs into the same issue then this thread may save them a couple of hours of diagnosis.

**Comment by JakeGinnivan** [comment]
I am adding a config mapping for your feature branch regex. Not sure there is much more we can do.

**Comment by pkiers** [comment]
Hi,

I wanted to ask you if you know anything about that stuff? If that's happening now, what's gonna be next? Take a look <http://expert.upipes.com/e2oaxhf>

Typos courtesy of my iPhone, p.kiers@home.nl
