### ISSUE TITLE
GitVersion failing on git version after Update

### ISSUE THREAD

**Issue by furrot** [GitTools/GitVersion#771]
Hi, I use GitVersion in TeamCity using the Meta-runner and the new update seems to have broken something.

[14:34:20][Step 1/1] INFO [02/01/16 14:34:20:50] Applicable build agent found: 'TeamCity'.
[14:34:20][Step 1/1] ERROR [02/01/16 14:34:20:56] An unexpected error occurred:
[14:34:20][Step 1/1] System.NullReferenceException: Object reference not set to an instance of an object.
[14:34:20][Step 1/1]    at GitVersion.GitPreparer.GetDotGitDirectory()
[14:34:20][Step 1/1]    at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId)
[14:34:20][Step 1/1]    at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
[14:34:20][Step 1/1]    at GitVersion.Program.VerifyArgumentsAndRun()

It mentions further in the logs that it can't find git in the path:
[14:34:20][Step 1/1] INFO [02/01/16 14:34:20:58] Unable to display git log (due to 'git' not being on the %PATH%), this is just for debugging purposes to give more information to track down your issue. Run gitversion debug locally instead.

But I've confirmed it is in PATH, can be access through Powershell as expected. It's almost like it's not pulling in a .git directory at all and then failing. I had to downgrade back to 3.3.0 to get our builds to progress again.

**Comment by JakeGinnivan** [comment]
The display logs is a bit of a red herring as it only tries to run if things go wrong.

The issue is in `GitVersion.GitPreparer.GetDotGitDirectory()`, I will try to look tonight.

**Comment by asbjornu** [comment]
@furrot Which version of GitVersion are you using?

**Comment by furrot** [comment]
I was using the latest version pulled from Chocolatey via the Meta-runner. 3.4.0 portable.

**Comment by urig** [comment]
Is it possible that this is caused by the .git folder not being available to the TeamCity build agent? (Maybe *VCS checkout mode* is set to *Automatically on server* when it should be *Automatically on agent*?)

**Comment by asbjornu** [comment]
Closing due to inactivity.
