### ISSUE TITLE
unable to install Gitflow on visual studio

### ISSUE THREAD

**Issue by rikthefrog** [GitTools/GitVersion#787]
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at GitFlow.VS.GitFlowWrapper.Init(GitFlowRepoSettings settings)
   at GitFlowVS.Extension.ViewModels.InitModel.OnInitialize()

Error message installed git 64 bit verison of git that is working git flow is working from cygwin.

**Comment by pascalberger** [comment]
I think you got the wrong repository. This is about GitVersion (a tool to determine version information from a Git repository). For the GitFlow Visual Studio Extension you should report the issue at https://github.com/jakobehn/GitFlow.VS.
