### ISSUE TITLE
Running GitVersion on Kudu

### ISSUE THREAD

**Issue by devlead** [GitTools/GitVersion#810]
Running GitVersion in a restricted environment like i.e. Kudu (Azure web app deployment environment) results in a few issues

Your not allowed to set process priority so launching with `GitVersion.exe" /output json` results in
```
Unhandled Exception: System.ComponentModel.Win32Exception: Access is denied
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
   at GitVersion.Helpers.ProcessHelper.Start(ProcessStartInfo startInfo)
   at GitVersion.Helpers.ProcessHelper.Run(Action`1 output, Action`1 errorOutput, TextReader input, String exe, String args, String workingDirectory, KeyValuePair`2[] environmentalVariables)
   at GitVersion.LibGitExtensions.DumpGraph(String workingDirectory, Action`1 writer, Nullable`1 maxCommits)
   at GitVersion.Program.VerifyArgumentsAndRun()
   at GitVersion.Program.Main()
```
and exit code = `-532462766`
which seems to be releated to this
https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/Helpers/ProcessHelper.cs#L27

**Comment by devlead** [comment]
Interestingly running GitVersion with output build server on Kudu results in a hang
```
Executing: "D:/home/site/repository/tools/GitVersion.CommandLine/tools/GitVersion.exe" /output buildserver /updateassemblyinfo "src/SolutionInfo.cs"
INFO [03/20/16 21:28:13:28] Working directory: D:\home\site\repository
INFO [03/20/16 21:28:13:28] Applicable build agent found: 'AppVeyor'.
INFO [03/20/16 21:28:13:41] Project root is: D:\home\site\repository
INFO [03/20/16 21:28:13:53] Begin: Loading version variables from disk cache
  INFO [03/20/16 21:28:13:60] Cache file D:\home\site\repository\.git\gitversion_cache\9C48E0884E183D9B574A5E778160C8BFB90AD534.yml not found.
INFO [03/20/16 21:28:13:60] End: Loading version variables from disk cache (Took: 62.50ms)
INFO [03/20/16 21:28:13:60] Branch from build environment: 
INFO [03/20/16 21:28:13:63] One remote found (origin -> 'https://github.com/devlead/cake').
INFO [03/20/16 21:28:13:64] Adding refspec: +refs/heads/*:refs/remotes/origin/*
```
Checking process handle has that to git objects i.e.
`D:\home\site\repository\.git\objects\pack\pack-771ce3c8dc85268157793cf6822c570334dab529.pack`

and it has a couple of threads idling
![image](https://cloud.githubusercontent.com/assets/1647294/13907345/67553fe6-eeec-11e5-92c6-258afb505809.png)

Currently running free site which is 32bit don't know if that could be the issue.

**Comment by gep13** [comment]
This doesn't seem right to me:

```
INFO [03/20/16 21:28:13:28] Applicable build agent found: 'AppVeyor'.
```

I think there is a bug in there...

**Comment by devlead** [comment]
@gep13 oh that was a error on my hand... set an environment while testing (should probably not hang anyways though).

Without that env var it doesn't hang but still fail, but similar error as on local:
```
D:\home\site\repository>"D:/home/site/repository/tools/GitVersion.CommandLine/tools/GitVersion.exe" /output buildserver /updateassemblyinfo "src/SolutionInfo.cs"
INFO [03/20/16 21:43:16:05] Working directory: D:\home\site\repository
INFO [03/20/16 21:43:16:13] Project root is: D:\home\site\repository
INFO [03/20/16 21:43:16:24] Begin: Loading version variables from disk cache
  INFO [03/20/16 21:43:16:30] Cache file D:\home\site\repository\.git\gitversion_cache\664A5FED1B320F78ED179DFA018104BB1EF46986.yml not found.
INFO [03/20/16 21:43:16:30] End: Loading version variables from disk cache (Took: 62.50ms)
INFO [03/20/16 21:43:16:47] Using latest commit on specified branch
INFO [03/20/16 21:43:16:66] Begin: Attempting to inherit branch configuration from parent branch
  INFO [03/20/16 21:43:16:80] Begin: Finding branch source
  INFO [03/20/16 21:43:16:86] End: Finding branch source (Took: 62.50ms)
  INFO [03/20/16 21:43:16:86] Found possible parent branches: 
INFO [03/20/16 21:43:16:91] End: Attempting to inherit branch configuration from parent branch (Took: 250.00ms)
ERROR [03/20/16 21:43:16:91] An unexpected error occurred:
System.InvalidOperationException: Could not find a 'develop' or 'master' branch, neither locally nor remotely.
   at GitVersion.BranchConfigurationCalculator.InheritBranchConfiguration(Boolean onlyEvaluateTrackedBranches, IRepository repository, Commit currentCommit, Branch currentBranch, KeyValuePair`2 keyValuePair, BranchConfig branchConfiguration, Config config, IList`1 excludedInheritBranches)
   at GitVersion.BranchConfigurationCalculator.GetBranchConfiguration(Commit currentCommit, IRepository repository, Boolean onlyEvaluateTrackedBranches, Config config, Branch currentBranch, IList`1 excludedInheritBranches)
   at GitVersion.GitVersionContext.CalculateEffectiveConfiguration()
   at GitVersion.GitVersionContext..ctor(IRepository repository, Branch currentBranch, Config configuration, Boolean onlyEvaluateTrackedBranches, String commitId)
   at GitVersion.GitVersionContext..ctor(IRepository repository, Config configuration, Boolean isForTrackingBranchOnly, String commitId)
   at GitVersion.ExecuteCore.ExecuteInternal(String targetBranch, String commitId, IRepository repo, GitPreparer gitPreparer, String projectRoot, IBuildServer buildServer)
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId)
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
INFO [03/20/16 21:43:16:91] 
INFO [03/20/16 21:43:16:91] Here is the current git graph (please include in issue): 
INFO [03/20/16 21:43:16:91] Showing max of 100 commits


D:\home\site\repository>Unhandled Exception: System.ComponentModel.Win32Exception: Access is denied
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
   at GitVersion.Helpers.ProcessHelper.Start(ProcessStartInfo startInfo)
   at GitVersion.Helpers.ProcessHelper.Run(Action`1 output, Action`1 errorOutput, TextReader input, String exe, String args, String workingDirectory, KeyValuePair`2[] environmentalVariables)
   at GitVersion.LibGitExtensions.DumpGraph(String workingDirectory, Action`1 writer, Nullable`1 maxCommits)
   at GitVersion.Program.VerifyArgumentsAndRun()
   at GitVersion.Program.Main()```

**Comment by gep13** [comment]
Ok, that helps to know that.  The only thing that would cause that output is from here:

```
        public override bool CanApplyToCurrentContext()
        {
            return !string.IsNullOrEmpty(Environment.GetEnvironmentVariable("APPVEYOR"));
        }
```

The issue with regard to the not finding branches is likely due to the way that Kudu is shallow cloning the repo for building.  We would likely need to add support for Kudu as a BuildServer, so that the branch normalisation process can be executed.

**Comment by devlead** [comment]
Checking the kudu source code they're indeed doing a shallow clone
```csharp
            string fetchCommand = @"fetch {0} --progress";
            if (this.IsEmpty() && _settings.AllowShallowClones())
            {
                // If it's the initial fetch and the setting allows it, we do a shallow fetch so that we omit all the history, keeping
                // our repo small. In subsequent fetches, we can't use the --depth flag as that would further
                // trim the repo, preventing us from redeploying old deployments
                fetchCommand += " --depth 1";
            }
```
https://github.com/projectkudu/kudu/blob/master/Kudu.Core/SourceControl/Git/GitExeRepository.cs#L274-L281

There seems to be a `SCM_USE_SHALLOW_CLONE` setting though, I'll try to set that one to see what happens.

**Comment by gep13** [comment]
@devlead I suspect you will still run into the same, latter, issue.  But at least you will have all the branch information available in order to correctly asset the Semantic Version :-D

**Comment by devlead** [comment]
Yeah full clone resulted in same issues.

**Comment by devlead** [comment]
I clone & built version on Kudu, commented out the [process.PriorityClass = ProcessPriorityClass.Idle;](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/Helpers/ProcessHelper.cs#L27) line.

```
PS D:\home\site\repository> D:\home\test\GitVersion\src\GitVersionExe\bin\Debug\GitVersion.exe /output json
```
and got output without exception
```json
{
  "Major":0,
  "Minor":11,
  "Patch":0,
  "PreReleaseTag":"kudu.1",
  "PreReleaseTagWithDash":"-kudu.1",
  "PreReleaseLabel":"kudu",
  "PreReleaseNumber":1,
  "BuildMetaData":17,
  "BuildMetaDataPadded":"0017",
  "FullBuildMetaData":"17.Branch.feature/kudu.Sha.666fa85c39f97506682e0d4a4e995a9bc8f18483",
  "MajorMinorPatch":"0.11.0",
  "SemVer":"0.11.0-kudu.1",
  "LegacySemVer":"0.11.0-kudu1",
  "LegacySemVerPadded":"0.11.0-kudu0001",
  "AssemblySemVer":"0.11.0.0",
  "FullSemVer":"0.11.0-kudu.1+17",
  "InformationalVersion":"0.11.0-kudu.1+17.Branch.feature/kudu.Sha.666fa85c39f97506682e0d4a4e995a9bc8f18483",
  "BranchName":"feature/kudu",
  "Sha":"666fa85c39f97506682e0d4a4e995a9bc8f18483",
  "NuGetVersionV2":"0.11.0-kudu0001",
  "NuGetVersion":"0.11.0-kudu0001",
  "CommitsSinceVersionSource":17,
  "CommitsSinceVersionSourcePadded":"0017",
  "CommitDate":"2016-03-20"
}
```

and ` /output buildserver` worked too
```
PS D:\home\site\repository> D:\home\test\GitVersion\src\GitVersionExe\bin\Debug\GitVersion.exe /output buildserver
INFO [03/20/16 23:12:27:79] Working directory: D:\home\site\repository
INFO [03/20/16 23:12:28:01] Project root is: D:\home\site\repository
INFO [03/20/16 23:12:28:10] Begin: Loading version variables from disk cache
  INFO [03/20/16 23:12:28:18] Cache file D:\home\site\repository\.git\gitversion_cache\305FB85518FA976C66D9E8E34BAE3C7F298710D0.yml not found.
INFO [03/20/16 23:12:28:18] End: Loading version variables from disk cache (Took: 78.13ms)
INFO [03/20/16 23:12:28:40] Using latest commit on specified branch
INFO [03/20/16 23:12:28:40] Begin: Attempting to inherit branch configuration from parent branch
  INFO [03/20/16 23:12:28:57] Begin: Finding branch source
    INFO [03/20/16 23:12:28:63] Begin: Found merge base of 666fa85c39f97506682e0d4a4e995a9bc8f18483 against develop
    INFO [03/20/16 23:12:28:66] End: Found merge base of 666fa85c39f97506682e0d4a4e995a9bc8f18483 against develop (Took: 31.25ms)
  INFO [03/20/16 23:12:28:68] End: Finding branch source (Took: 109.37ms)
  INFO [03/20/16 23:12:28:70] Found possible parent branches: develop
INFO [03/20/16 23:12:28:70] End: Attempting to inherit branch configuration from parent branch (Took: 296.86ms)
INFO [03/20/16 23:12:28:90] Running against branch: feature/kudu (666fa85c39f97506682e0d4a4e995a9bc8f18483)
INFO [03/20/16 23:12:28:91] Begin: Calculating base versions
  INFO [03/20/16 23:12:29:74] Fallback base version: 0.1.0 with commit count source 15464e294d37c105c0afefe2aefdd437da6bc18f
  INFO [03/20/16 23:12:30:87] Git tag 'v0.1.24': 0.1.24 with commit count source 696448ae4f611c2647e047ee4a3e29d6466fd0e5
  INFO [03/20/16 23:12:30:90] Git tag 'v0.1.23': 0.1.23 with commit count source e2826ea56bb01c8c1b7a427c1f32a06d7385b963
  INFO [03/20/16 23:12:30:91] Git tag 'v0.1.22': 0.1.22 with commit count source b05d5920f3cb5aceec88f8b106874a830c182d82
  INFO [03/20/16 23:12:30:91] Git tag 'v0.1.21': 0.1.21 with commit count source 7589a7e5f4bf2d6d19250461c0a5424c2733e039
  INFO [03/20/16 23:12:30:93] Git tag 'v0.1.20': 0.1.20 with commit count source a8b45aed54e412b67e2813920ff24ccf46bddfcf
  INFO [03/20/16 23:12:30:95] Git tag 'v0.1.19': 0.1.19 with commit count source c76352becb66f2e95401cc65d40701b662e026f5
  INFO [03/20/16 23:12:30:96] Git tag 'v0.1.18': 0.1.18 with commit count source 8a9f53463d122aed69207e94b69b44a4d554c7f9
  INFO [03/20/16 23:12:30:98] Git tag 'v0.1.17': 0.1.17 with commit count source 7086796b948d7200dc6debc55eea5f6a2f5486fb
  INFO [03/20/16 23:12:30:99] Git tag 'v0.1.16': 0.1.16 with commit count source d6e5a56a117c8a81ec836b627a01203bb435e6a3
  INFO [03/20/16 23:12:31:02] Git tag 'v0.1.15': 0.1.15 with commit count source cae2b270a756461ed79af387728e26584d070ac3
  INFO [03/20/16 23:12:31:04] Git tag 'v0.1.14': 0.1.14 with commit count source 894cc1574187ba82c0d9cceb9496cd1a0ba048c7
  INFO [03/20/16 23:12:31:05] Git tag 'v0.1.13': 0.1.13 with commit count source 9e8805d75196f7e364f88ea2164ad1b29aa6d4d6
  INFO [03/20/16 23:12:31:07] Git tag 'v0.1.12': 0.1.12 with commit count source a35b6f8e67df8b123077cb94e6089cd30ca52f6c
  INFO [03/20/16 23:12:31:09] Git tag 'v0.1.11': 0.1.11 with commit count source 280f5feb5a3f3ae29ffa861a691660e3f249bd78
  INFO [03/20/16 23:12:31:10] Git tag 'v0.1.10': 0.1.10 with commit count source e81bb903141ebb0ea9b1c9f8f4d65e236596b391
  INFO [03/20/16 23:12:31:12] Git tag 'v0.1.9': 0.1.9 with commit count source 9a9653e3d41d087fd85424434eaedea747fd9b47
  INFO [03/20/16 23:12:31:15] Git tag 'v0.1.8': 0.1.8 with commit count source d2180d1294d9a936354b33b873ea48b29c1dd233
  INFO [03/20/16 23:12:31:16] Git tag 'v0.1.7': 0.1.7 with commit count source 7446ea4bb30f7e5d0b93b12fc79923f1da8c3a65
  INFO [03/20/16 23:12:31:18] Git tag 'v0.1.6': 0.1.6 with commit count source 848594f03a0a3b0b261103415682cdc3974be22a
  INFO [03/20/16 23:12:31:20] Git tag 'v0.1.5': 0.1.5 with commit count source 9d5b9eb1b3b3efc1a43299fbc070e9007f650b2b
  INFO [03/20/16 23:12:31:21] Git tag 'v0.1.4': 0.1.4 with commit count source fd84df79d9730affdfbbe7cff4e20681613e6826
  INFO [03/20/16 23:12:31:23] Git tag 'v0.1.2': 0.1.2 with commit count source e3c697b1a18b84e1da1de6afebe43f8e723c4929
  INFO [03/20/16 23:12:31:24] Git tag 'v0.1.1': 0.1.1 with commit count source 88ba79c5e0f28517b7f7bce4dd2dfb94c2cd240d
  INFO [03/20/16 23:12:32:06] Merge message 'Merge branch 'release/0.10.0' into develop': 0.10.0 with commit count source b34d41cd23221fd787a3b102b4757bb805d1a7ae
  INFO [03/20/16 23:12:32:07] Merge message 'Merge branch 'release/0.8.0' into develop': 0.8.0 with commit count source 529be613f17eee100fc3c5e5e20a87cf3df0a559
  INFO [03/20/16 23:12:32:09] Merge message 'Merge branch 'release/0.7.0' into develop': 0.7.0 with commit count source a2f27c10c024f4c93dec2ddba3ce19ad585f7e76
  INFO [03/20/16 23:12:32:10] Merge message 'Merge branch 'hotfix/0.6.4' into develop

Conflicts:
	ReleaseNotes.md
	src/Cake.Core/IO/ProcessRunner.cs
	src/SolutionInfo.cs': 0.6.4 with commit count source c6459a98f146294c7fb74fe2fe962ccf4b0faa5c
  INFO [03/20/16 23:12:32:12] Merge message 'Merge pull request #489 from devlead/f/v0.6.1bump

Update version & copyright': 0.6.1 with commit count source 643b581ceeffa5e40b4a3a0487ede9da55f4cfeb
  INFO [03/20/16 23:12:32:12] Merge message 'Merge pull request #483 from devlead/f/v0.6.0

Bumped version to 0.6.0': 0.6.0 with commit count source fb7f6722e14fe36671e05fab1c139a5d9407001e
  INFO [03/20/16 23:12:32:15] Base version used: Merge message 'Merge branch 'release/0.10.0' into develop': 0.10.0 with commit count source b34d41cd23221fd787a3b102b4757bb805d1a7ae
INFO [03/20/16 23:12:32:15] End: Calculating base versions (Took: 3,235.70ms)
INFO [03/20/16 23:12:32:17] Using branch name to calculate version tag
INFO [03/20/16 23:12:33:01] 17 commits found between b34d41cd23221fd787a3b102b4757bb805d1a7ae and 666fa85c39f97506682e0d4a4e995a9bc8f18483
INFO [03/20/16 23:12:33:06] Begin: Creating dictionary
INFO [03/20/16 23:12:33:07] End: Creating dictionary (Took: 15.63ms)
INFO [03/20/16 23:12:33:07] Begin: Storing version variables to cache file D:\home\site\repository\.git\gitversion_cache\305FB85518FA976C66D9E8E34BAE3C7F298710D0.yml
INFO [03/20/16 23:12:33:12] End: Storing version variables to cache file D:\home\site\repository\.git\gitversion_cache\305FB85518FA976C66D9E8E34BAE3C7F298710D0.yml (Took: 46.87ms)
PS D:\home\site\repository> $LASTEXITCODE
0

**Comment by gep13** [comment]
@devlead did you also have to change the shallow clone settings to get it to work correctly?

@JakeGinnivan do you know why the priority is being set on that Process?

**Comment by devlead** [comment]
@gep13 would have to setup a new site to confirm. I changed deep clone before I compiled a custom version of GitVersion.

**Comment by JakeGinnivan** [comment]
@gep13 no idea, removing it

**Comment by JakeGinnivan** [comment]
Though the process crash is a red herring. We only execute that when there is an unhandled exception elsewhere.

**Comment by gep13** [comment]
@devlead any chance you can test out the latest develop branch version of GitVersion again?  See if there are any other issues?

**Comment by gep13** [comment]
>@JakeGinnivan said...
@gep13 no idea, removing it

Cool, thanks!

**Comment by devlead** [comment]
@gep13 Sure, I'll try to revisit tomorrow, is it on MyGet or should I build from source?

**Comment by gep13** [comment]
@devlead good question!  No, we don't have a MyGet Feed for GitVersion currently.  But you can find the most recent package as an artifact in the AppVeyor Build here:

https://ci.appveyor.com/project/GitTools/gitversion/build/3.4.1-PullRequest.832+121.build.652/artifacts

**Comment by devlead** [comment]
@gep13 I no longer get that exception and get what looks to be correct version :+1: 
```json
{
  "Major":0,
  "Minor":11,
  "Patch":0,
  "PreReleaseTag":"kudu.1",
  "PreReleaseTagWithDash":"-kudu.1",
  "PreReleaseLabel":"kudu",
  "PreReleaseNumber":1,
  "BuildMetaData":1060,
  "BuildMetaDataPadded":1060,
  "FullBuildMetaData":"1060.Branch.feature/kudu.Sha.8b419abda581c894d6172c13af989b92b293bb70",
  "MajorMinorPatch":"0.11.0",
  "SemVer":"0.11.0-kudu.1",
  "LegacySemVer":"0.11.0-kudu1",
  "LegacySemVerPadded":"0.11.0-kudu0001",
  "AssemblySemVer":"0.11.0.0",
  "FullSemVer":"0.11.0-kudu.1+1060",
  "InformationalVersion":"0.11.0-kudu.1+1060.Branch.feature/kudu.Sha.8b419abda581c894d6172c13af989b92b293bb70",
  "BranchName":"feature/kudu",
  "Sha":"8b419abda581c894d6172c13af989b92b293bb70",
  "NuGetVersionV2":"0.11.0-kudu0001",
  "NuGetVersion":"0.11.0-kudu0001",
  "CommitsSinceVersionSource":1060,
  "CommitsSinceVersionSourcePadded":1060,
  "CommitDate":"2016-04-19"
}
```

**Comment by gep13** [comment]
@devlead cool! Thanks for letting us know! :+1:

**Comment by asbjornu** [comment]
@devlead Can this be closed?

**Comment by devlead** [comment]
@asbjornu yes :+1:
