### ISSUE TITLE
error on git merge

### ISSUE THREAD

**Issue by profestate** [GitTools/GitVersion#812]
Does anybody know what can case this issue. while i try just to exec gitversion.exe on a git repo folder i got error like below. the hash (f3e804c6baea1bd0d856254026f1d85d69a9bcce) witch case the error is the merge commit hash. i see no restriction on getversion about merges. 

PS F:\Jenkins\workspace\x> GitVersion.exe
INFO [03/25/16 3:17:41:64] Working directory: F:\Jenkins\workspace\x
INFO [03/25/16 3:17:41:67] Project root is: F:\Jenkins\workspace\x
INFO [03/25/16 3:17:41:71] Begin: Loading version variables from disk cache
  INFO [03/25/16 3:17:41:73] Cache file F:\Jenkins\workspace\x\.git\gitversion_cache\2E0DEC4AC6ECC52DD4CC
EE48D79A2F50EA7E3A2F.yml not found.
INFO [03/25/16 3:17:41:73] End: Loading version variables from disk cache (Took: 15.62ms)
INFO [03/25/16 3:17:41:75] Using latest commit on specified branch
INFO [03/25/16 3:17:41:76] Running against branch: master (7cb18e93f33adf1a31f7abfd2a466e4686c4ae83)
INFO [03/25/16 3:17:41:76] Begin: Calculating base versions
INFO [03/25/16 3:17:41:78] End: Calculating base versions (Took: 15.60ms)
ERROR [03/25/16 3:17:41:78] An unexpected error occurred:
LibGit2Sharp.NotFoundException: Object not found - failed to find pack entry (f3e804c6baea1bd0d856254026f1d85d69a9bcce)
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_revwalk_next(RevWalkerSafeHandle walker)
   at LibGit2Sharp.CommitLog.CommitEnumerator.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at GitVersion.VersionCalculation.FallbackBaseVersionStrategy.<GetVersions>d__0.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersion(GitVersionContext context)
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion(GitVersionContext context)
   at GitVersion.GitVersionFinder.FindVersion(GitVersionContext context)
   at GitVersion.ExecuteCore.ExecuteInternal(String targetBranch, String commitId, IRepository repo, GitPreparer gitPrep
arer, String projectRoot, IBuildServer buildServer)
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authen
tication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId)
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
INFO [03/25/16 3:17:41:78]
INFO [03/25/16 3:17:41:78] Here is the current git graph (please include in issue):
INFO [03/25/16 3:17:41:78] Showing max of 100 commits
INFO [03/25/16 3:17:41:81] * e678d73 10 days ago  (grafted, origin/develop, develop)
* 71e99dd 10 days ago  (grafted, origin/dp/prep, dp/prep)
* 7cb18e9 3 weeks ago  (grafted, HEAD -> master, origin/master, show, origin/DA/BP-v2.0, list)
* 1084065 7 weeks ago  (grafted, origin/TestLSBranch, TestLSBranch)
* 1b82acc 9 weeks ago  (grafted, origin/DA/v2.0-C, DA/v2.0-C)
* be34437 9 weeks ago  (grafted, origin/DA/Training, DA/Training)
* 72270b6 8 months ago  (grafted, origin/DA/v1.1, DA/v1.1)
* e63b305 10 months ago  (grafted, origin/DA/v1.2, DA/v1.2)
* 57c3040 1 year, 2 months ago  (grafted, origin/DA/v1.0, DA/v1.0)
* 312cf8f 2 years, 9 months ago  (grafted, origin/DA/branches/Gate-Test, DA/branches/Gate-
Test)

very appreciate any help and suggestion on this.

**Comment by profestate** [comment]
have no idea why i got exactly this error but the issue was with shallow clone repo.
