### ISSUE TITLE
VSO GitVersion breaks MSBuild

### ISSUE THREAD

**Issue by justdeserves** [GitTools/GitVersion#842]
The latest release of the vNext GitVersion task causes an error during the MSBuild process. Error CS0579: Duplicate 'AssemblyVersion' attribute & Error CS0579: Duplicate 'AssemblyVersion' attribute.

On removing the task from the build pipeline the code successfully compiles. I have not selected the option to 'Update AssemblyInfo files'

Is there a work around?

**Comment by JakeGinnivan** [comment]
I think this is related to https://github.com/GitTools/GitVersion/pull/714 as @csmager had a similar issue.

Can you grab the versions at https://ci.appveyor.com/project/GitTools/gitversion/build/3.5.1-AssemblyInfoFix.1+1.build.673/artifacts and see if this is still a problem.

I reverted the above PR to see if it helps. Am heading to bed now so would be great if you could test and get back to me. If that works I will release a patch tomorrow morning

**Comment by pascalberger** [comment]
Maybe this is related to #846 (In the current version the "Update AssemblyInfo files" option doesn't make a difference, the files always will be updated)

**Comment by JakeGinnivan** [comment]
There are two issues here, the fact that the checkbox doesn't work means you cannot work around the other breaking change. 

@justdeserves if you are able to check that branch I linked above (use the command line to check) and see if it fixes the underlying issue too.

**Comment by justdeserves** [comment]
@JakeGinnivan I implemented the fix above this morning , but came across this:
2016-04-27T09:38:26.6977193Z ##[error]Unhandled Exception: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'git2-381caf5': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
2016-04-27T09:38:26.6977193Z ##[error]   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
2016-04-27T09:38:26.6987194Z ##[error]   at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor()
2016-04-27T09:38:26.6997212Z ##[error]   at LibGit2Sharp.Core.NativeMethods..cctor()
2016-04-27T09:38:26.6997212Z ##[error]   --- End of inner exception stack trace ---
2016-04-27T09:38:26.7007194Z ##[error]   at LibGit2Sharp.Core.NativeMethods.RemoveHandle()
2016-04-27T09:38:26.7007194Z ##[error]   at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject.Finalize()
2016-04-27T09:38:33.9241157Z ##[error]Unexpected exit code -532462766 returned from tool GitVersion.exe

**Comment by JakeGinnivan** [comment]
@justdeserves that should be fixed, how are you building/running GitVersion.exe?

**Comment by justdeserves** [comment]
@JakeGinnivan I'm using the GitVersion.exe that is bundled in with the 
GitVersionTfsBuildTask_3.5.1-assemblyinfofix0001.zip

**Comment by JakeGinnivan** [comment]
Ah, that is broken for that branch.

Use the GitVersion.exe in https://ci.appveyor.com/api/buildjobs/b6io43o3wx1vntf9/artifacts/GitVersion_3.5.1-assemblyinfofix0001.zip

3.5.0 build vnext was broken =(

**Comment by justdeserves** [comment]
I've run through a few builds - it appears to be sorted and not raising the problem anymore. Ty for your assistant.

**Comment by JakeGinnivan** [comment]
Ok sweet, will close
