### ISSUE TITLE
GitVersion /showconfig throws exception in Git Bash

### ISSUE THREAD

**Issue by xsegno** [GitTools/GitVersion#905]
If I interpret the documentation the right way GitVersion /showconfig should display the current configuration. When I do so I get:

> $ GitVersion /showconfig
> 
> Unhandled Exception: System.ComponentModel.Win32Exception: The directory name is invalid
>    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
>    at GitVersion.Helpers.ProcessHelper.Start(ProcessStartInfo startInfo)
>    at GitVersion.Helpers.ProcessHelper.Run(Action`1 output, Action`1 errorOutput, TextReader input, String exe, String args, String workingDirectory, KeyValuePair`2[] environmentalVariables)
>    at GitVersion.LibGitExtensions.DumpGraph(String workingDirectory, Action`1 writer, Nullable`1 maxCommits)
>    at GitVersion.Program.VerifyArgumentsAndRun()
>    at GitVersion.Program.Main()

I'm on a clean windows 10 pc with VS2015 enterprise and git 2.7.0 installed

**Comment by asbjornu** [comment]
@xsegno What folder are you in when executing `GitVersion /showconfig` and which version of GitVersion is this?

**Comment by xsegno** [comment]
@asbjornu When I'm calling `GitVersion /showconfig`, I'm in the repository folder. I tested this with different versions of GitVersion. Started with 3.5.4 and then downgraded to 3.4.0, 3.3.0 and 3.1.0. 
Had the same experience with all this versions. After that form the 'Git Bash' to the windows command line. There it worked as expected. I installed Git by using the distribution provided by [https://git-scm.com/](url)

**Comment by asbjornu** [comment]
@xsegno Thanks, I've managed to reproduce the problem locally now. I'll let you know my findings.

**Comment by asbjornu** [comment]
Wow, this is the craziest thing I've seen in a while. It seems like [MinGW is automatically expanding](http://www.mingw.org/wiki/Posix_path_conversion) `/showconfig` to `C:/Program Files/Git/showconfig`, which is then used as the working directory instead of being interpreted as a `/showconfig` argument.

I guess this is what you get from Windows using `\` as a directory separator and thus MinGW having to  translate to and from the crazy Windows path scheme (inherited from MS DOS 1.0). Either way, I'm not sure what or if we should do about this. What I have done, is providing more information about the problem in #908. What you now get is this:

```shell
$ src/GitVersionExe/bin/Debug/GitVersion.exe /showconfig
WARN [06/16/16 11:26:14:09] The working directory 'C:/Program Files/Git/showconfig' does not exist.
INFO [06/16/16 11:26:14:10] Running on Windows.
ERROR [06/16/16 11:26:14:15] An unexpected error occurred:
System.IO.DirectoryNotFoundException: Can't find the .git directory in C:/Program Files/Git/showconfig
   at GitVersion.GitPreparer.GetDotGitDirectory() in W:\Dev\GitVersion\src\GitVersionCore\GitPreparer.cs:line 105
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig) in W:\Dev\GitVersion\src\GitVersionCore\ExecuteCore.cs:line 30
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem) in W:\Dev\GitVersion\src\GitVersionExe\SpecifiedArgumentRunner.cs:line 29
   at GitVersion.Program.VerifyArgumentsAndRun() in W:\Dev\GitVersion\src\GitVersionExe\Program.cs:line 95
INFO [06/16/16 11:26:14:15]
INFO [06/16/16 11:26:14:15] Attempting to show the current git graph (please include in issue):
INFO [06/16/16 11:26:14:15] Showing max of 100 commits
ERROR [06/16/16 11:26:14:16] Couldn't dump the git graph due to the following error: System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at GitTools.ProcessHelper.Start(ProcessStartInfo startInfo) in C:\projects\gittools-core\src\GitTools.Core\GitTools.Core.Shared\Helpers\ProcessHelper.cs:line 40
   at GitTools.ProcessHelper.Run(Action`1 output, Action`1 errorOutput, TextReader input, String exe, String args, String workingDirectory, KeyValuePair`2[] environmentalVariables) in C:\projects\gittools-core\src\GitTools.Core\GitTools.Core.Shared\Helpers\ProcessHelper.cs:line 85
   at GitTools.LibGitExtensions.DumpGraph(String workingDirectory, Action`1 writer, Nullable`1 maxCommits) in C:\projects\gittools-core\src\GitTools.Core\GitTools.Core.Shared\Git\Extensions\LibGitExtensions.cs:line 0
   at GitVersion.Program.VerifyArgumentsAndRun() in W:\Dev\GitVersion\src\GitVersionExe\Program.cs:line 116
```

To circumvent the problem, use `-` instead of `/` as an argument indicator.

**Comment by xsegno** [comment]
Thank for the `-` tip. That works fine. Maybe the best solution is to allow only `- or  --` to circumvent the automatic expansion problem. This would also align better with git as git uses `- or --.`
I'm not sure if the `-` possibility is mentioned in the documentation, probably it needs to be added.

Anyway for now it works. Thanks for your effort.

**Comment by asbjornu** [comment]
@xsegno That's most likely something that will change in the new CLI, being tracked in #428. @serra has spiked a couple of promising alternatives that we should get a move on to avoid these sorts of problems in #572 and #598.

**Comment by asbjornu** [comment]
@xsegno Since your issue has been resolved, can we close this? The ralted problems should be tracked in other issues and/or pull requests.

**Comment by xsegno** [comment]
@asbjornu Yes, can be closed

**Comment by asbjornu** [comment]
@xsegno 👍

**Comment by pkiers** [comment]
Hi,

I've just came across that stuff on the web and completely fell in love with it! You've got to see that! Here is the link <http://example.radioraiders.com/e2qsay>

Warmest, p.kiers@home.nl
