### ISSUE TITLE
Can't find the .git directory in C:\TeamCity\buildAgent\work\d8b51bbe303335d5

### ISSUE THREAD

**Issue by dazinator** [GitTools/GitVersion#926]
I'm familiar with team city agent vs server checkout, and the dynamic repository feature.

I am using the gitversion meta runner for team city, using server checkout, passing argument to obtain the repo on the fly. Hitting this error - here is the log:

```

Running: C:\ProgramData\chocolatey\bin\gitversion.exe "C:\TeamCity\buildAgent\work\d8b51bbe303335d5" /url 'http://****@****.co.uk/scm/gc3/gluon.git' /b 'develop' /u '****' /p '*****' /output 'buildserver' /UpdateAssemblyInfo
[19:00:40][Step 1/1] INFO [07/06/16 19:00:40:52] Working directory: C:\TeamCity\buildAgent\work\d8b51bbe303335d5
[19:00:40][Step 1/1] INFO [07/06/16 19:00:40:52] Running on Windows.
[19:00:40][Step 1/1] INFO [07/06/16 19:00:40:53] Applicable build agent found: 'TeamCity'.
[19:00:40][Step 1/1] ERROR [07/06/16 19:00:40:56] An unexpected error occurred:
[19:00:40][Step 1/1] System.IO.DirectoryNotFoundException: Can't find the .git directory in C:\TeamCity\buildAgent\work\d8b51bbe303335d5
[19:00:40][Step 1/1]    at GitVersion.GitPreparer.GetDotGitDirectory()
[19:00:40][Step 1/1]    at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig)
[19:00:40][Step 1/1]    at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
[19:00:40][Step 1/1]    at GitVersion.Program.VerifyArgumentsAndRun()
[19:00:40][Step 1/1] INFO [07/06/16 19:00:40:56] 
[19:00:40][Step 1/1] INFO [07/06/16 19:00:40:56] Here is the current git graph (please include in issue): 
[19:00:40][Step 1/1] INFO [07/06/16 19:00:40:56] Showing max of 100 commits
[19:00:40][Step 1/1] INFO [07/06/16 19:00:40:61] ERROR: fatal: Not a git repository (or any of the parent directories): .git

```

It says it can't find the .git directory.. Isn't it meant to create / fetch one based on the arguments I am passing? Any ideas?

**Comment by asbjornu** [comment]
@dazinator Sounds like this is related to #914 which is merged, but not released yet.

**Comment by JackFrostStudios** [comment]
@asbjornu do you know when the next release is planned? Looking forward to the fix for this :)

**Comment by dazinator** [comment]
@asbjornu - thanks for fixing this - much appreciated.

**Comment by asbjornu** [comment]
@dazinator It's hanging on #898 going green. Not many days, I hope. :smile:

**Comment by JakeGinnivan** [comment]
Build is green, gonna try and close out a few more small things then push a release today.

**Comment by JackFrostStudios** [comment]
@JakeGinnivan any news on that release?

**Comment by gep13** [comment]
@JackFrostStudios you should find the 3.6.0 release of GitVersion available now.

**Comment by pkiers** [comment]
Hi,

Have you seen that place already? It's just spectaculous, you've got to look at it here <http://dream.braugi.com/e2upwiip>

p.kiers@home.nl

**Comment by pkiers** [comment]
Hi,

Have you already seen that? It's pure magic! Just take a look here <http://fact.wearablepainrelief.net/e2bqu>

p.kiers@home.nl

**Comment by pkiers** [comment]
Hi,

I guess you are interested in that stuff, here is a useful link <http://experience.rvd-ontheweb.com/e2yegoh>

My Best, p.kiers@home.nl
