### ISSUE TITLE
Dynamic Repositories not working in 3.6.1

### ISSUE THREAD

**Issue by rubenmamo** [GitTools/GitVersion#981]
When using dynamic repositories in 3.6.1 I'm getting the following in the log:
```
2016-07-27 09:07:34		INFO [07/27/16 9:07:34:72] Working directory: C:\BuildAgent\work\c59d12a8890150e5
2016-07-27 09:07:34		INFO [07/27/16 9:07:34:74] IsDynamicGitRepository: False
2016-07-27 09:07:34		ERROR [07/27/16 9:07:34:77] An unexpected error occurred:
System.IO.DirectoryNotFoundException: Can't find the .git directory in C:\BuildAgent\work\c59d12a8890150e5
   at GitVersion.GitPreparer.GetDotGitDirectory()
   at GitVersion.GitPreparer.GetProjectRootDirectory()
   at GitVersion.ConfigurationProvider.Verify(GitPreparer gitPreparer, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
```

I traced this down to the configuration verification code as it is creating a new instance of GitPreparer and using without calling Initialise.

@asbjornu @JakeGinnivan , the GitPreparer class seems to be causing a number of recurring issues when changes are done since it seems to not be obvious that Initialise needs to be called in order for it to function correctly. Can we change the class so that if you try to use any of it's methods without calling the Initialise method first it throws an exception? This would cause tests to fail whenever GitPreparer is used incorrectly and hence avoid the recurrence of similar issues.

I'm happy to do the change in GitPreparer myself if you agree this is a good way forward

**Comment by rubenmamo** [comment]
Closed as duplicate of #953
